<?php

namespace Database\Seeders;

use App\Models\AcademicProgram;
use App\Models\Faculty;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AcademicProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programsByFaculty = [
            'faculty-of-sharia-and-law' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس الشريعة الإسلامية',
                        'en' => 'Bachelor of Islamic Sharia',
                        'fr' => 'Licence en Charia Islamique',
                        'es' => 'Licenciatura en Sharia Islámica',
                        'zh' => '伊斯兰教法学士',
                        'ru' => 'Бакалавриат исламского шариата',
                        'ur' => 'بیچلر آف اسلامی شریعہ',
                    ],
                    'description' => [
                        'ar' => 'برنامج شامل يدرس أصول الفقه الإسلامي والشريعة الإسلامية ومقاصدها، مع التركيز على تطبيقات الشريعة في العصر الحديث والقضايا المعاصرة.',
                        'en' => 'A comprehensive program studying the foundations of Islamic jurisprudence and Sharia law and its objectives, with focus on modern applications and contemporary issues.',
                        'fr' => 'Un programme complet étudiant les fondements de la jurisprudence islamique et du droit de la Charia et ses objectifs, avec un accent sur les applications modernes.',
                        'es' => 'Un programa integral que estudia los fundamentos de la jurisprudencia islámica y la ley Sharia y sus objetivos, con enfoque en aplicaciones modernas.',
                        'zh' => '全面研究伊斯兰法学基础和伊斯兰教法及其目标的课程，重点关注现代应用和当代问题。',
                        'ru' => 'Комплексная программа по изучению основ исламской юриспруденции и шариатского права и его целей с акцентом на современные применения.',
                        'ur' => 'اسلامی فقہ اور شریعت کے اصولوں اور اس کے مقاصد کا جامع مطالعہ، جدید اطلاقات اور معاصر مسائل پر توجہ کے ساتھ۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => 140,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة (الأزهرية أو ما يعادلها) بتقدير جيد على الأقل. إجادة اللغة العربية ومعرفة أساسية بالعلوم الإسلامية.',
                        'en' => 'High school diploma (Al-Azhar or equivalent) with at least a good grade. Proficiency in Arabic and basic knowledge of Islamic sciences.',
                        'fr' => 'Diplôme d\'études secondaires (Al-Azhar ou équivalent) avec au moins une bonne note. Maîtrise de l\'arabe et connaissances de base en sciences islamiques.',
                        'es' => 'Diploma de secundaria (Al-Azhar o equivalente) con al menos buena calificación. Dominio del árabe y conocimientos básicos de ciencias islámicas.',
                        'zh' => '高中毕业证书（艾资哈尔或同等学历），成绩至少良好。精通阿拉伯语并具备伊斯兰科学基础知识。',
                        'ru' => 'Аттестат о среднем образовании (Аль-Азхар или эквивалент) с хорошими оценками. Владение арабским языком и базовые знания исламских наук.',
                        'ur' => 'ہائی اسکول ڈپلومہ (الازہر یا مساوی) کم از کم اچھے درجے کے ساتھ۔ عربی زبان میں مہارت اور اسلامی علوم کا بنیادی علم۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'القضاء الشرعي، المحاماة، الإفتاء، التدريس الجامعي، الاستشارات القانونية الشرعية، العمل في المؤسسات الدينية والأوقاف.',
                        'en' => 'Sharia judiciary, legal practice, issuing fatwas, university teaching, Sharia legal consulting, work in religious institutions and endowments.',
                        'fr' => 'Magistrature de la Charia, pratique juridique, émission de fatwas, enseignement universitaire, conseil juridique de la Charia.',
                        'es' => 'Judicatura Sharia, práctica legal, emisión de fatwas, enseñanza universitaria, consultoría legal Sharia.',
                        'zh' => '伊斯兰教法司法、法律实务、发布法特瓦、大学教学、伊斯兰法律咨询、宗教机构和宗教基金工作。',
                        'ru' => 'Шариатское судопроизводство, юридическая практика, издание фетв, преподавание, консультирование по шариатскому праву.',
                        'ur' => 'شرعی عدالت، قانونی پریکٹس، فتویٰ جاری کرنا، جامعاتی تدریس، شرعی قانونی مشاورت، دینی اداروں اور اوقاف میں کام۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'ماجستير الفقه المقارن',
                        'en' => 'Master of Comparative Jurisprudence',
                        'fr' => 'Master en Jurisprudence Comparée',
                        'es' => 'Maestría en Jurisprudencia Comparada',
                        'zh' => '比较法学硕士',
                        'ru' => 'Магистратура сравнительного правоведения',
                        'ur' => 'ماسٹر آف تقابلی فقہ',
                    ],
                    'description' => [
                        'ar' => 'دراسة معمقة للفقه المقارن بين المذاهب الإسلامية الأربعة مع التركيز على مناهج الاستنباط والاجتهاد وتطبيقاتها المعاصرة.',
                        'en' => 'An in-depth study of comparative jurisprudence across the four Islamic schools of thought, focusing on methods of deduction, ijtihad, and their contemporary applications.',
                        'fr' => 'Une étude approfondie de la jurisprudence comparée des quatre écoles islamiques, axée sur les méthodes de déduction et d\'ijtihad.',
                        'es' => 'Un estudio profundo de la jurisprudencia comparada de las cuatro escuelas islámicas, enfocado en métodos de deducción e ijtihad.',
                        'zh' => '深入研究四大伊斯兰法学派之间的比较法学，重点关注推理方法、伊智提哈德及其当代应用。',
                        'ru' => 'Углублённое изучение сравнительного правоведения четырёх исламских школ с акцентом на методы вывода и иджтихад.',
                        'ur' => 'چاروں اسلامی مکاتب فکر کے درمیان تقابلی فقہ کا گہرائی سے مطالعہ، استنباط اور اجتہاد کے طریقوں پر توجہ۔',
                    ],
                    'degree_level' => 'master',
                    'duration' => '2 years',
                    'credit_hours' => 36,
                    'requirements' => [
                        'ar' => 'بكالوريوس في الشريعة الإسلامية أو القانون بتقدير جيد جداً. اجتياز اختبار القبول ومقابلة شخصية.',
                        'en' => 'Bachelor\'s degree in Islamic Sharia or Law with a very good grade. Passing the admission test and personal interview.',
                        'fr' => 'Licence en Charia islamique ou en Droit avec mention très bien. Réussite du test d\'admission et entretien.',
                        'es' => 'Licenciatura en Sharia Islámica o Derecho con muy buena calificación. Aprobar el examen de admisión y entrevista.',
                        'zh' => '伊斯兰教法或法律学士学位，成绩优良。通过入学考试和面试。',
                        'ru' => 'Степень бакалавра исламского шариата или права с отличными оценками. Сдача вступительного экзамена и собеседование.',
                        'ur' => 'اسلامی شریعت یا قانون میں بیچلر ڈگری بہت اچھے درجے کے ساتھ۔ داخلہ ٹیسٹ اور ذاتی انٹرویو پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس الجامعي، البحث العلمي، القضاء الشرعي الأعلى، الاستشارات الفقهية المتخصصة، العمل في مجامع الفقه الإسلامي.',
                        'en' => 'University teaching, academic research, senior Sharia judiciary, specialized jurisprudential consulting, work in Islamic jurisprudence councils.',
                        'fr' => 'Enseignement universitaire, recherche académique, magistrature supérieure de la Charia, conseil juridique spécialisé.',
                        'es' => 'Enseñanza universitaria, investigación académica, judicatura superior Sharia, consultoría jurisprudencial especializada.',
                        'zh' => '大学教学、学术研究、高级伊斯兰教法司法、专业法学咨询、伊斯兰法学委员会工作。',
                        'ru' => 'Преподавание, научные исследования, высшее шариатское судопроизводство, специализированные консультации.',
                        'ur' => 'جامعاتی تدریس، علمی تحقیق، اعلیٰ شرعی عدالت، ماہرانہ فقہی مشاورت، اسلامی فقہ اکیڈمیوں میں کام۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'دكتوراه في الفقه الإسلامي',
                        'en' => 'Doctorate in Islamic Jurisprudence',
                        'fr' => 'Doctorat en Jurisprudence Islamique',
                        'es' => 'Doctorado en Jurisprudencia Islámica',
                        'zh' => '伊斯兰法学博士',
                        'ru' => 'Докторантура исламского правоведения',
                        'ur' => 'ڈاکٹریٹ ان اسلامک فقہ',
                    ],
                    'description' => [
                        'ar' => 'برنامج بحثي متقدم في الفقه الإسلامي يهدف إلى إعداد علماء متخصصين قادرين على الاجتهاد والإفتاء ومعالجة القضايا الفقهية المعاصرة.',
                        'en' => 'An advanced research program in Islamic jurisprudence aimed at preparing specialized scholars capable of ijtihad, issuing fatwas, and addressing contemporary jurisprudential issues.',
                        'fr' => 'Un programme de recherche avancé en jurisprudence islamique visant à préparer des savants spécialisés capables d\'ijtihad et de traiter les questions contemporaines.',
                        'es' => 'Un programa de investigación avanzado en jurisprudencia islámica dirigido a preparar académicos especializados capaces de ijtihad.',
                        'zh' => '伊斯兰法学高级研究项目，旨在培养能够进行伊智提哈德、发布法特瓦并处理当代法学问题的专业学者。',
                        'ru' => 'Передовая исследовательская программа по исламскому правоведению для подготовки специалистов, способных к иджтихаду.',
                        'ur' => 'اسلامی فقہ میں اعلیٰ تحقیقی پروگرام جو ماہرین تیار کرنے کے لیے ہے جو اجتہاد، فتویٰ اور معاصر فقہی مسائل حل کر سکیں۔',
                    ],
                    'degree_level' => 'doctorate',
                    'duration' => '3 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'ماجستير في الفقه الإسلامي أو الشريعة بتقدير جيد جداً. تقديم مقترح بحثي واجتياز اختبار الكفاءة.',
                        'en' => 'Master\'s degree in Islamic Jurisprudence or Sharia with a very good grade. Submission of a research proposal and passing the proficiency exam.',
                        'fr' => 'Master en jurisprudence islamique ou en Charia avec mention très bien. Soumission d\'une proposition de recherche.',
                        'es' => 'Maestría en Jurisprudencia Islámica o Sharia con muy buena calificación. Presentación de propuesta de investigación.',
                        'zh' => '伊斯兰法学或教法硕士学位，成绩优良。提交研究计划书并通过能力考试。',
                        'ru' => 'Степень магистра исламского правоведения или шариата с отличными оценками. Представление исследовательского предложения.',
                        'ur' => 'اسلامی فقہ یا شریعت میں ماسٹر ڈگری بہت اچھے درجے کے ساتھ۔ تحقیقی تجویز اور قابلیت کا امتحان پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'الأستاذية الجامعية، رئاسة أقسام الفقه، العضوية في مجامع الفقه الدولية، الإفتاء الرسمي، قيادة المؤسسات الدينية.',
                        'en' => 'University professorship, heading jurisprudence departments, membership in international fiqh councils, official fatwa issuance, leading religious institutions.',
                        'fr' => 'Professorat universitaire, direction de départements, membre de conseils internationaux de fiqh, émission officielle de fatwas.',
                        'es' => 'Profesorado universitario, dirección de departamentos, membresía en consejos internacionales de fiqh, emisión oficial de fatwas.',
                        'zh' => '大学教授职位、法学系主任、国际伊斯兰法学委员会成员、官方法特瓦发布、领导宗教机构。',
                        'ru' => 'Профессура, руководство кафедрами, членство в международных советах фикха, официальное издание фетв.',
                        'ur' => 'جامعاتی پروفیسرشپ، فقہ کے شعبوں کی سربراہی، بین الاقوامی فقہ کونسلوں کی رکنیت، سرکاری فتویٰ جاری کرنا۔',
                    ],
                ],
            ],
            'faculty-of-theology' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس أصول الدين',
                        'en' => 'Bachelor of Islamic Theology',
                        'fr' => 'Licence en Théologie Islamique',
                        'es' => 'Licenciatura en Teología Islámica',
                        'zh' => '伊斯兰神学学士',
                        'ru' => 'Бакалавриат исламского богословия',
                        'ur' => 'بیچلر آف اسلامی علم الکلام',
                    ],
                    'description' => [
                        'ar' => 'برنامج يقدم دراسة متكاملة في أصول الدين الإسلامي شاملاً العقيدة والتفسير والحديث والدعوة والفلسفة الإسلامية.',
                        'en' => 'A program offering integrated study in Islamic theology including creed, exegesis, hadith, da\'wa, and Islamic philosophy.',
                        'fr' => 'Un programme offrant une étude intégrée de la théologie islamique incluant le credo, l\'exégèse, le hadith et la philosophie islamique.',
                        'es' => 'Un programa que ofrece estudio integrado en teología islámica incluyendo credo, exégesis, hadiz y filosofía islámica.',
                        'zh' => '提供伊斯兰神学综合研究的课程，包括信条、经注、圣训、宣教和伊斯兰哲学。',
                        'ru' => 'Программа комплексного изучения исламского богословия, включая акыду, тафсир, хадисы, дааву и исламскую философию.',
                        'ur' => 'اسلامی علم الکلام کا مربوط مطالعہ بشمول عقیدہ، تفسیر، حدیث، دعوت اور اسلامی فلسفہ۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => 136,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية الأزهرية أو ما يعادلها. حفظ أجزاء من القرآن الكريم. اجتياز اختبار القبول.',
                        'en' => 'Al-Azhar secondary certificate or equivalent. Memorization of portions of the Holy Quran. Passing the admission test.',
                        'fr' => 'Certificat secondaire d\'Al-Azhar ou équivalent. Mémorisation de portions du Saint Coran. Réussite du test d\'admission.',
                        'es' => 'Certificado secundario de Al-Azhar o equivalente. Memorización de porciones del Sagrado Corán. Aprobar el examen de admisión.',
                        'zh' => '艾资哈尔中学证书或同等学历。背诵《古兰经》部分章节。通过入学考试。',
                        'ru' => 'Аттестат Аль-Азхара или эквивалент. Заучивание частей Священного Корана. Сдача вступительного экзамена.',
                        'ur' => 'الازہر ثانوی سرٹیفکیٹ یا مساوی۔ قرآن کریم کے اجزاء کا حفظ۔ داخلہ ٹیسٹ پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس في المعاهد الدينية، الإمامة والخطابة، الدعوة والإرشاد، العمل في المراكز الإسلامية، البحث العلمي الديني.',
                        'en' => 'Teaching in religious institutes, leading prayers and sermons, da\'wa and guidance, working in Islamic centers, religious academic research.',
                        'fr' => 'Enseignement dans les instituts religieux, direction de prières, da\'wa et orientation, travail dans les centres islamiques.',
                        'es' => 'Enseñanza en institutos religiosos, dirección de oraciones, da\'wa y orientación, trabajo en centros islámicos.',
                        'zh' => '在宗教学院教学、领拜和布道、宣教和指导、在伊斯兰中心工作、宗教学术研究。',
                        'ru' => 'Преподавание в религиозных институтах, руководство молитвами, даава, работа в исламских центрах, научные исследования.',
                        'ur' => 'دینی اداروں میں تدریس، امامت و خطبات، دعوت و ارشاد، اسلامی مراکز میں کام، دینی علمی تحقیق۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'ماجستير الدراسات القرآنية',
                        'en' => 'Master of Quranic Studies',
                        'fr' => 'Master en Études Coraniques',
                        'es' => 'Maestría en Estudios Coránicos',
                        'zh' => '古兰经研究硕士',
                        'ru' => 'Магистратура коранических исследований',
                        'ur' => 'ماسٹر آف قرآنی علوم',
                    ],
                    'description' => [
                        'ar' => 'برنامج متقدم في علوم القرآن والتفسير يتناول مناهج المفسرين والإعجاز القرآني والدراسات الاستشراقية للقرآن.',
                        'en' => 'An advanced program in Quranic sciences and exegesis covering exegetical methodologies, Quranic inimitability, and orientalist studies of the Quran.',
                        'fr' => 'Un programme avancé en sciences coraniques et exégèse couvrant les méthodologies exégétiques et l\'inimitabilité coranique.',
                        'es' => 'Un programa avanzado en ciencias coránicas y exégesis que cubre metodologías exegéticas e inimitabilidad coránica.',
                        'zh' => '古兰经科学和经注高级课程，涵盖经注方法论、古兰经的奇迹性和东方学对古兰经的研究。',
                        'ru' => 'Продвинутая программа по кораническим наукам и тафсиру, охватывающая методологии толкования и неподражаемость Корана.',
                        'ur' => 'قرآنی علوم اور تفسیر میں اعلیٰ پروگرام جو مفسرین کے مناہج، اعجاز القرآن اور مستشرقین کے مطالعات کا احاطہ کرتا ہے۔',
                    ],
                    'degree_level' => 'master',
                    'duration' => '2 years',
                    'credit_hours' => 30,
                    'requirements' => [
                        'ar' => 'بكالوريوس في أصول الدين أو العلوم الإسلامية بتقدير جيد جداً. حفظ القرآن الكريم كاملاً يُعد ميزة إضافية.',
                        'en' => 'Bachelor\'s degree in Theology or Islamic Sciences with a very good grade. Full memorization of the Holy Quran is an added advantage.',
                        'fr' => 'Licence en théologie ou sciences islamiques avec mention très bien. La mémorisation complète du Coran est un avantage.',
                        'es' => 'Licenciatura en Teología o Ciencias Islámicas con muy buena calificación. La memorización completa del Corán es una ventaja.',
                        'zh' => '神学或伊斯兰科学学士学位，成绩优良。完整背诵《古兰经》为加分项。',
                        'ru' => 'Степень бакалавра богословия или исламских наук с отличными оценками. Полное заучивание Корана является преимуществом.',
                        'ur' => 'علم الکلام یا اسلامی علوم میں بیچلر ڈگری بہت اچھے درجے کے ساتھ۔ قرآن کریم کا مکمل حفظ اضافی فائدہ ہے۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس الجامعي في كليات أصول الدين، البحث العلمي المتخصص، تأليف الكتب والمراجع القرآنية، الإشراف على حلقات تحفيظ القرآن.',
                        'en' => 'University teaching in theology faculties, specialized research, authoring Quranic references, supervising Quran memorization circles.',
                        'fr' => 'Enseignement universitaire, recherche spécialisée, rédaction de références coraniques, supervision de cercles de mémorisation.',
                        'es' => 'Enseñanza universitaria, investigación especializada, autoría de referencias coránicas, supervisión de círculos de memorización.',
                        'zh' => '在神学院大学教学、专业研究、撰写古兰经参考文献、监督古兰经背诵圈。',
                        'ru' => 'Преподавание на богословских факультетах, специализированные исследования, написание коранических трудов.',
                        'ur' => 'اصول الدین کے کلیات میں جامعاتی تدریس، ماہرانہ تحقیق، قرآنی مراجع کی تصنیف، حفظ قرآن حلقوں کی نگرانی۔',
                    ],
                ],
            ],
            'faculty-of-arabic-language' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس اللغة العربية وآدابها',
                        'en' => 'Bachelor of Arabic Language and Literature',
                        'fr' => 'Licence en Langue et Littérature Arabes',
                        'es' => 'Licenciatura en Lengua y Literatura Árabe',
                        'zh' => '阿拉伯语言文学学士',
                        'ru' => 'Бакалавриат арабского языка и литературы',
                        'ur' => 'بیچلر آف عربی زبان و ادب',
                    ],
                    'description' => [
                        'ar' => 'برنامج شامل يدرس اللغة العربية نحواً وصرفاً وبلاغة، مع دراسة الأدب العربي عبر العصور من الجاهلية إلى العصر الحديث.',
                        'en' => 'A comprehensive program studying Arabic grammar, morphology, and rhetoric, along with Arabic literature from pre-Islamic era to modern times.',
                        'fr' => 'Un programme complet étudiant la grammaire arabe, la morphologie et la rhétorique, ainsi que la littérature arabe à travers les âges.',
                        'es' => 'Un programa integral que estudia gramática árabe, morfología y retórica, junto con literatura árabe desde la era preislámica hasta la modernidad.',
                        'zh' => '全面研究阿拉伯语语法、词法和修辞的课程，以及从前伊斯兰时期到现代的阿拉伯文学。',
                        'ru' => 'Комплексная программа изучения арабской грамматики, морфологии и риторики, а также арабской литературы от доисламской эпохи до современности.',
                        'ur' => 'عربی زبان کی گرامر، صرف اور بلاغت کا جامع مطالعہ، نیز جاہلیت سے عصر حاضر تک عربی ادب کا مطالعہ۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => 138,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة أو الأزهرية. مستوى جيد في اللغة العربية. اجتياز اختبار القبول اللغوي.',
                        'en' => 'General or Al-Azhar secondary certificate. Good level of Arabic language. Passing the linguistic admission test.',
                        'fr' => 'Certificat secondaire général ou d\'Al-Azhar. Bon niveau en langue arabe. Réussite du test d\'admission linguistique.',
                        'es' => 'Certificado secundario general o de Al-Azhar. Buen nivel de árabe. Aprobar el examen de admisión lingüístico.',
                        'zh' => '普通或艾资哈尔中学证书。良好的阿拉伯语水平。通过语言入学考试。',
                        'ru' => 'Общий или азхарский аттестат. Хороший уровень арабского языка. Сдача лингвистического вступительного экзамена.',
                        'ur' => 'عام یا الازہر ثانوی سرٹیفکیٹ۔ عربی زبان کی اچھی سطح۔ لسانی داخلہ ٹیسٹ پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'تدريس اللغة العربية، الترجمة، الصحافة والإعلام، تحقيق المخطوطات، العمل في المجامع اللغوية، الكتابة والتأليف.',
                        'en' => 'Teaching Arabic language, translation, journalism and media, manuscript editing, working in linguistic academies, writing and authorship.',
                        'fr' => 'Enseignement de la langue arabe, traduction, journalisme, édition de manuscrits, travail dans les académies linguistiques.',
                        'es' => 'Enseñanza del árabe, traducción, periodismo, edición de manuscritos, trabajo en academias lingüísticas, escritura.',
                        'zh' => '阿拉伯语教学、翻译、新闻媒体、手稿编辑、语言学院工作、写作和著述。',
                        'ru' => 'Преподавание арабского языка, перевод, журналистика, редактирование рукописей, работа в лингвистических академиях.',
                        'ur' => 'عربی زبان کی تدریس، ترجمہ، صحافت اور میڈیا، مخطوطات کی تحقیق، لسانی مجمعوں میں کام، تصنیف و تالیف۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'ماجستير اللسانيات العربية',
                        'en' => 'Master of Arabic Linguistics',
                        'fr' => 'Master en Linguistique Arabe',
                        'es' => 'Maestría en Lingüística Árabe',
                        'zh' => '阿拉伯语语言学硕士',
                        'ru' => 'Магистратура арабской лингвистики',
                        'ur' => 'ماسٹر آف عربی لسانیات',
                    ],
                    'description' => [
                        'ar' => 'دراسة متقدمة في علوم اللسانيات العربية تشمل النحو التحويلي والدلالة والأصوات اللغوية والمعجمية الحديثة.',
                        'en' => 'Advanced study in Arabic linguistics including transformational grammar, semantics, phonology, and modern lexicography.',
                        'fr' => 'Étude avancée en linguistique arabe incluant la grammaire transformationnelle, la sémantique, la phonologie et la lexicographie moderne.',
                        'es' => 'Estudio avanzado en lingüística árabe incluyendo gramática transformacional, semántica, fonología y lexicografía moderna.',
                        'zh' => '阿拉伯语语言学高级研究，包括转换语法、语义学、音韵学和现代词典学。',
                        'ru' => 'Углублённое изучение арабской лингвистики, включая трансформационную грамматику, семантику, фонологию и лексикографию.',
                        'ur' => 'عربی لسانیات میں اعلیٰ مطالعہ بشمول تحویلی گرامر، علم المعانی، صوتیات اور جدید لغت نویسی۔',
                    ],
                    'degree_level' => 'master',
                    'duration' => '2 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'بكالوريوس في اللغة العربية بتقدير جيد جداً. القدرة على البحث العلمي. اجتياز المقابلة الشخصية.',
                        'en' => 'Bachelor\'s degree in Arabic Language with a very good grade. Research capability. Passing the personal interview.',
                        'fr' => 'Licence en langue arabe avec mention très bien. Capacité de recherche. Réussite de l\'entretien personnel.',
                        'es' => 'Licenciatura en Lengua Árabe con muy buena calificación. Capacidad investigadora. Aprobar la entrevista personal.',
                        'zh' => '阿拉伯语学士学位，成绩优良。具备研究能力。通过个人面试。',
                        'ru' => 'Степень бакалавра арабского языка с отличными оценками. Исследовательские способности. Прохождение собеседования.',
                        'ur' => 'عربی زبان میں بیچلر ڈگری بہت اچھے درجے کے ساتھ۔ تحقیقی صلاحیت۔ ذاتی انٹرویو پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس الجامعي، البحث اللغوي المتقدم، العمل في مجامع اللغة العربية، تطوير المناهج اللغوية، اللسانيات الحاسوبية.',
                        'en' => 'University teaching, advanced linguistic research, working in Arabic language academies, curriculum development, computational linguistics.',
                        'fr' => 'Enseignement universitaire, recherche linguistique avancée, académies de langue arabe, développement de curricula, linguistique computationnelle.',
                        'es' => 'Enseñanza universitaria, investigación lingüística avanzada, academias de lengua árabe, desarrollo curricular, lingüística computacional.',
                        'zh' => '大学教学、高级语言学研究、阿拉伯语学院工作、课程开发、计算语言学。',
                        'ru' => 'Преподавание, продвинутые лингвистические исследования, работа в академиях арабского языка, разработка учебных программ.',
                        'ur' => 'جامعاتی تدریس، اعلیٰ لسانی تحقیق، عربی زبان اکیڈمیوں میں کام، نصابی ترقی، کمپیوٹیشنل لسانیات۔',
                    ],
                ],
            ],
            'faculty-of-medicine' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس الطب والجراحة',
                        'en' => 'Bachelor of Medicine and Surgery',
                        'fr' => 'Licence en Médecine et Chirurgie',
                        'es' => 'Licenciatura en Medicina y Cirugía',
                        'zh' => '医学与外科学士',
                        'ru' => 'Бакалавриат медицины и хирургии',
                        'ur' => 'بیچلر آف میڈیسن اینڈ سرجری',
                    ],
                    'description' => [
                        'ar' => 'برنامج طبي متكامل يعد الأطباء لممارسة الطب العام والجراحة، يشمل العلوم الأساسية والسريرية والتدريب العملي في المستشفيات الجامعية.',
                        'en' => 'An integrated medical program preparing physicians for general medicine and surgery, covering basic and clinical sciences with practical training in university hospitals.',
                        'fr' => 'Un programme médical intégré préparant les médecins à la médecine générale et à la chirurgie, avec formation pratique dans les hôpitaux universitaires.',
                        'es' => 'Un programa médico integrado que prepara médicos para medicina general y cirugía, con formación práctica en hospitales universitarios.',
                        'zh' => '综合医学课程，培养从事普通医学和外科的医生，涵盖基础和临床科学以及大学附属医院的实践培训。',
                        'ru' => 'Интегрированная медицинская программа подготовки врачей общей практики и хирургов с практикой в университетских больницах.',
                        'ur' => 'عام طب اور جراحی کے لیے ڈاکٹروں کو تیار کرنے والا مربوط طبی پروگرام، بنیادی اور طبی علوم اور جامعاتی ہسپتالوں میں عملی تربیت۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '6 years',
                    'credit_hours' => 280,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم بمجموع لا يقل عن 90%. اجتياز اختبارات القدرات والمقابلة الشخصية. اللياقة الطبية الكاملة.',
                        'en' => 'High school diploma in sciences with a minimum of 90%. Passing aptitude tests and personal interview. Full medical fitness.',
                        'fr' => 'Diplôme de secondaire en sciences avec un minimum de 90%. Réussite des tests d\'aptitude et de l\'entretien. Aptitude médicale complète.',
                        'es' => 'Diploma de secundaria en ciencias con mínimo 90%. Aprobar pruebas de aptitud y entrevista. Aptitud médica completa.',
                        'zh' => '理科高中毕业证书，总分不低于90%。通过能力测试和面试。完全的医学健康。',
                        'ru' => 'Аттестат по естественным наукам с минимальным баллом 90%. Сдача тестов и собеседование. Полная медицинская пригодность.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ کم از کم 90% کے ساتھ۔ قابلیت ٹیسٹ اور ذاتی انٹرویو پاس کرنا۔ مکمل طبی فٹنس۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'الطب العام، التخصص في فروع الطب المختلفة، العمل في المستشفيات والمراكز الطبية، البحث الطبي، الصحة العامة.',
                        'en' => 'General practice, specialization in various medical fields, working in hospitals and medical centers, medical research, public health.',
                        'fr' => 'Pratique générale, spécialisation dans divers domaines médicaux, travail dans les hôpitaux, recherche médicale, santé publique.',
                        'es' => 'Práctica general, especialización en diversos campos médicos, trabajo en hospitales, investigación médica, salud pública.',
                        'zh' => '全科医学、各医学领域专科化、在医院和医疗中心工作、医学研究、公共卫生。',
                        'ru' => 'Общая практика, специализация, работа в больницах и медицинских центрах, медицинские исследования, общественное здоровье.',
                        'ur' => 'جنرل پریکٹس، مختلف طبی شعبوں میں تخصص، ہسپتالوں اور طبی مراکز میں کام، طبی تحقیق، عوامی صحت۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'ماجستير الطب الباطني',
                        'en' => 'Master of Internal Medicine',
                        'fr' => 'Master en Médecine Interne',
                        'es' => 'Maestría en Medicina Interna',
                        'zh' => '内科学硕士',
                        'ru' => 'Магистратура внутренней медицины',
                        'ur' => 'ماسٹر آف انٹرنل میڈیسن',
                    ],
                    'description' => [
                        'ar' => 'برنامج تخصصي متقدم في الطب الباطني يشمل تشخيص وعلاج الأمراض الداخلية مع التدريب السريري المكثف.',
                        'en' => 'An advanced specialization program in internal medicine covering diagnosis and treatment of internal diseases with intensive clinical training.',
                        'fr' => 'Un programme de spécialisation avancé en médecine interne couvrant le diagnostic et le traitement des maladies internes.',
                        'es' => 'Un programa de especialización avanzado en medicina interna que cubre diagnóstico y tratamiento de enfermedades internas.',
                        'zh' => '内科高级专业课程，涵盖内科疾病的诊断和治疗以及密集的临床培训。',
                        'ru' => 'Продвинутая программа специализации по внутренней медицине с интенсивной клинической подготовкой.',
                        'ur' => 'باطنی طب میں اعلیٰ تخصصی پروگرام جو اندرونی بیماریوں کی تشخیص اور علاج کا احاطہ کرتا ہے۔',
                    ],
                    'degree_level' => 'master',
                    'duration' => '3 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'بكالوريوس الطب والجراحة. سنة امتياز كاملة. الحصول على ترخيص مزاولة المهنة.',
                        'en' => 'Bachelor of Medicine and Surgery. Completed internship year. Medical practice license obtained.',
                        'fr' => 'Licence en médecine et chirurgie. Année d\'internat complétée. Licence de pratique médicale obtenue.',
                        'es' => 'Licenciatura en Medicina y Cirugía. Año de internado completado. Licencia de práctica médica obtenida.',
                        'zh' => '医学与外科学士学位。完成实习年。获得医疗执业许可证。',
                        'ru' => 'Степень бакалавра медицины и хирургии. Завершённая интернатура. Полученная лицензия на практику.',
                        'ur' => 'بیچلر آف میڈیسن اینڈ سرجری۔ مکمل انٹرنشپ سال۔ طبی پریکٹس لائسنس حاصل کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'استشاري طب باطني، التدريس الجامعي الطبي، البحث السريري، إدارة الأقسام الطبية، الممارسة الطبية التخصصية.',
                        'en' => 'Internal medicine consultant, medical university teaching, clinical research, managing medical departments, specialized medical practice.',
                        'fr' => 'Consultant en médecine interne, enseignement médical universitaire, recherche clinique, gestion de départements médicaux.',
                        'es' => 'Consultor de medicina interna, enseñanza médica universitaria, investigación clínica, gestión de departamentos médicos.',
                        'zh' => '内科顾问、医科大学教学、临床研究、管理医疗科室、专科医疗实践。',
                        'ru' => 'Консультант по внутренней медицине, преподавание, клинические исследования, управление медицинскими отделениями.',
                        'ur' => 'باطنی طب کے مشیر، طبی جامعاتی تدریس، طبی تحقیق، طبی شعبوں کا انتظام، تخصصی طبی پریکٹس۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'دكتوراه في الجراحة',
                        'en' => 'Doctorate in Surgery',
                        'fr' => 'Doctorat en Chirurgie',
                        'es' => 'Doctorado en Cirugía',
                        'zh' => '外科博士',
                        'ru' => 'Докторантура хирургии',
                        'ur' => 'ڈاکٹریٹ ان سرجری',
                    ],
                    'description' => [
                        'ar' => 'برنامج بحثي وسريري متقدم في الجراحة العامة والتخصصية يهدف لإعداد جراحين على أعلى مستوى من الكفاءة والبحث العلمي.',
                        'en' => 'An advanced research and clinical program in general and specialized surgery aimed at preparing surgeons at the highest level of competence and scientific research.',
                        'fr' => 'Un programme avancé de recherche et de clinique en chirurgie générale et spécialisée visant à préparer des chirurgiens de haut niveau.',
                        'es' => 'Un programa avanzado de investigación y clínica en cirugía general y especializada dirigido a preparar cirujanos de alto nivel.',
                        'zh' => '普通和专科外科高级研究和临床课程，旨在培养最高水平的外科医生和科学研究人才。',
                        'ru' => 'Продвинутая исследовательская и клиническая программа по общей и специализированной хирургии.',
                        'ur' => 'عام اور تخصصی جراحی میں اعلیٰ تحقیقی اور طبی پروگرام جو اعلیٰ ترین سطح کے سرجن تیار کرنے کے لیے ہے۔',
                    ],
                    'degree_level' => 'doctorate',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'ماجستير في الجراحة العامة. خبرة سريرية لا تقل عن سنتين. نشر بحث علمي محكم. اجتياز اختبار الكفاءة.',
                        'en' => 'Master\'s in General Surgery. Minimum two years of clinical experience. Published peer-reviewed research. Passing the proficiency exam.',
                        'fr' => 'Master en chirurgie générale. Minimum deux ans d\'expérience clinique. Recherche publiée. Réussite de l\'examen de compétence.',
                        'es' => 'Maestría en Cirugía General. Mínimo dos años de experiencia clínica. Investigación publicada. Aprobar el examen de competencia.',
                        'zh' => '普通外科硕士学位。至少两年临床经验。发表同行评审研究。通过能力考试。',
                        'ru' => 'Магистратура по общей хирургии. Минимум два года клинического опыта. Опубликованное рецензированное исследование.',
                        'ur' => 'جنرل سرجری میں ماسٹرز۔ کم از کم دو سال کا طبی تجربہ۔ شائع شدہ تحقیق۔ قابلیت کا امتحان پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'أستاذ جراحة جامعي، استشاري جراحة متقدمة، رئاسة أقسام الجراحة، البحث الجراحي المتقدم، الممارسة الجراحية التخصصية.',
                        'en' => 'University surgery professor, advanced surgery consultant, heading surgery departments, advanced surgical research, specialized surgical practice.',
                        'fr' => 'Professeur de chirurgie universitaire, consultant en chirurgie avancée, direction de départements chirurgicaux, recherche chirurgicale.',
                        'es' => 'Profesor universitario de cirugía, consultor de cirugía avanzada, dirección de departamentos quirúrgicos, investigación quirúrgica.',
                        'zh' => '大学外科教授、高级外科顾问、外科科室主任、高级外科研究、专科外科实践。',
                        'ru' => 'Профессор хирургии, консультант по передовой хирургии, руководство хирургическими отделениями, исследования.',
                        'ur' => 'جامعاتی سرجری پروفیسر، اعلیٰ سرجری مشیر، سرجری کے شعبوں کی سربراہی، اعلیٰ جراحی تحقیق۔',
                    ],
                ],
            ],
            'faculty-of-engineering' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس الهندسة المدنية',
                        'en' => 'Bachelor of Civil Engineering',
                        'fr' => 'Licence en Génie Civil',
                        'es' => 'Licenciatura en Ingeniería Civil',
                        'zh' => '土木工程学士',
                        'ru' => 'Бакалавриат гражданского строительства',
                        'ur' => 'بیچلر آف سول انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'برنامج هندسي يؤهل الطلاب لتصميم وتنفيذ وإدارة المشاريع الإنشائية والبنية التحتية بما يتوافق مع المعايير الدولية.',
                        'en' => 'An engineering program qualifying students to design, execute, and manage construction and infrastructure projects in accordance with international standards.',
                        'fr' => 'Un programme d\'ingénierie qualifiant les étudiants pour concevoir, exécuter et gérer des projets de construction conformément aux normes internationales.',
                        'es' => 'Un programa de ingeniería que califica a los estudiantes para diseñar, ejecutar y gestionar proyectos de construcción según estándares internacionales.',
                        'zh' => '工程课程，使学生具备按照国际标准设计、执行和管理建筑和基础设施项目的资格。',
                        'ru' => 'Инженерная программа, готовящая студентов к проектированию и управлению строительными проектами по международным стандартам.',
                        'ur' => 'انجینئرنگ پروگرام جو طلباء کو بین الاقوامی معیارات کے مطابق تعمیراتی منصوبوں کی ڈیزائن، تعمیل اور انتظام کے قابل بناتا ہے۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '5 years',
                    'credit_hours' => 170,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة الرياضيات بمجموع لا يقل عن 85%. اجتياز اختبار القدرات الهندسية.',
                        'en' => 'High school diploma in mathematics track with a minimum of 85%. Passing engineering aptitude tests.',
                        'fr' => 'Diplôme de secondaire en mathématiques avec un minimum de 85%. Réussite des tests d\'aptitude en ingénierie.',
                        'es' => 'Diploma de secundaria en matemáticas con mínimo 85%. Aprobar pruebas de aptitud en ingeniería.',
                        'zh' => '数学方向高中毕业证书，总分不低于85%。通过工程能力测试。',
                        'ru' => 'Аттестат по математике с минимальным баллом 85%. Сдача инженерных тестов.',
                        'ur' => 'ریاضی شعبے میں ہائی اسکول ڈپلومہ کم از کم 85% کے ساتھ۔ انجینئرنگ قابلیت ٹیسٹ پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'شركات المقاولات والبناء، الاستشارات الهندسية، إدارة المشاريع، التصميم الإنشائي، العمل الحكومي في البنية التحتية.',
                        'en' => 'Construction companies, engineering consulting, project management, structural design, government infrastructure work.',
                        'fr' => 'Entreprises de construction, conseil en ingénierie, gestion de projets, conception structurelle, travaux d\'infrastructure.',
                        'es' => 'Empresas de construcción, consultoría de ingeniería, gestión de proyectos, diseño estructural, trabajo de infraestructura.',
                        'zh' => '建筑公司、工程咨询、项目管理、结构设计、政府基础设施工作。',
                        'ru' => 'Строительные компании, инженерный консалтинг, управление проектами, структурное проектирование.',
                        'ur' => 'تعمیراتی کمپنیاں، انجینئرنگ مشاورت، پراجیکٹ مینجمنٹ، ساختی ڈیزائن، حکومتی بنیادی ڈھانچے کا کام۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'بكالوريوس هندسة الحاسبات',
                        'en' => 'Bachelor of Computer Engineering',
                        'fr' => 'Licence en Génie Informatique',
                        'es' => 'Licenciatura en Ingeniería Informática',
                        'zh' => '计算机工程学士',
                        'ru' => 'Бакалавриат компьютерной инженерии',
                        'ur' => 'بیچلر آف کمپیوٹر انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'برنامج يجمع بين هندسة الحاسبات وعلوم البرمجيات، يشمل تصميم الأنظمة الرقمية والشبكات والذكاء الاصطناعي.',
                        'en' => 'A program combining computer hardware engineering and software sciences, covering digital systems design, networks, and artificial intelligence.',
                        'fr' => 'Un programme combinant ingénierie matérielle et sciences logicielles, couvrant la conception de systèmes numériques, les réseaux et l\'IA.',
                        'es' => 'Un programa que combina ingeniería de hardware y ciencias de software, cubriendo diseño de sistemas digitales, redes e inteligencia artificial.',
                        'zh' => '结合计算机硬件工程和软件科学的课程，涵盖数字系统设计、网络和人工智能。',
                        'ru' => 'Программа, сочетающая компьютерную инженерию и программирование, охватывающая проектирование цифровых систем, сети и ИИ.',
                        'ur' => 'کمپیوٹر ہارڈویئر انجینئرنگ اور سافٹ ویئر سائنسز کو ملانے والا پروگرام، ڈیجیٹل سسٹم ڈیزائن، نیٹ ورکس اور مصنوعی ذہانت۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '5 years',
                    'credit_hours' => 168,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة الرياضيات بمجموع لا يقل عن 85%. مهارات أساسية في الحاسب الآلي.',
                        'en' => 'High school diploma in mathematics track with a minimum of 85%. Basic computer skills.',
                        'fr' => 'Diplôme de secondaire en mathématiques avec un minimum de 85%. Compétences informatiques de base.',
                        'es' => 'Diploma de secundaria en matemáticas con mínimo 85%. Habilidades informáticas básicas.',
                        'zh' => '数学方向高中毕业证书，总分不低于85%。基本计算机技能。',
                        'ru' => 'Аттестат по математике с минимальным баллом 85%. Базовые компьютерные навыки.',
                        'ur' => 'ریاضی شعبے میں ہائی اسکول ڈپلومہ کم از کم 85% کے ساتھ۔ بنیادی کمپیوٹر مہارتیں۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'تطوير البرمجيات، هندسة الأنظمة، أمن المعلومات، الذكاء الاصطناعي، إدارة الشبكات، ريادة الأعمال التقنية.',
                        'en' => 'Software development, systems engineering, information security, artificial intelligence, network administration, tech entrepreneurship.',
                        'fr' => 'Développement logiciel, ingénierie des systèmes, sécurité informatique, intelligence artificielle, administration réseau.',
                        'es' => 'Desarrollo de software, ingeniería de sistemas, seguridad informática, inteligencia artificial, administración de redes.',
                        'zh' => '软件开发、系统工程、信息安全、人工智能、网络管理、科技创业。',
                        'ru' => 'Разработка ПО, системная инженерия, информационная безопасность, ИИ, сетевое администрирование, технологическое предпринимательство.',
                        'ur' => 'سافٹ ویئر ڈویلپمنٹ، سسٹمز انجینئرنگ، انفارمیشن سیکیورٹی، مصنوعی ذہانت، نیٹ ورک ایڈمنسٹریشن، ٹیک کاروبار۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'ماجستير الهندسة الإنشائية',
                        'en' => 'Master of Structural Engineering',
                        'fr' => 'Master en Génie Structurel',
                        'es' => 'Maestría en Ingeniería Estructural',
                        'zh' => '结构工程硕士',
                        'ru' => 'Магистратура строительной инженерии',
                        'ur' => 'ماسٹر آف سٹرکچرل انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'برنامج متقدم في التحليل والتصميم الإنشائي للمباني والجسور والمنشآت الخاصة باستخدام أحدث التقنيات والبرمجيات.',
                        'en' => 'An advanced program in structural analysis and design of buildings, bridges, and special structures using the latest technologies and software.',
                        'fr' => 'Un programme avancé en analyse et conception structurelle de bâtiments, ponts et structures spéciales avec les technologies les plus récentes.',
                        'es' => 'Un programa avanzado en análisis y diseño estructural de edificios, puentes y estructuras especiales con las últimas tecnologías.',
                        'zh' => '建筑、桥梁和特殊结构的结构分析与设计高级课程，使用最新技术和软件。',
                        'ru' => 'Продвинутая программа по структурному анализу и проектированию зданий, мостов с использованием новейших технологий.',
                        'ur' => 'عمارتوں، پلوں اور خصوصی ڈھانچوں کے ساختی تجزیے اور ڈیزائن میں اعلیٰ پروگرام جدید ترین ٹیکنالوجیز کے ساتھ۔',
                    ],
                    'degree_level' => 'master',
                    'duration' => '2 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'بكالوريوس الهندسة المدنية بتقدير جيد جداً. خبرة عملية سنة على الأقل مفضلة.',
                        'en' => 'Bachelor of Civil Engineering with a very good grade. At least one year of practical experience preferred.',
                        'fr' => 'Licence en génie civil avec mention très bien. Au moins un an d\'expérience pratique souhaité.',
                        'es' => 'Licenciatura en Ingeniería Civil con muy buena calificación. Al menos un año de experiencia práctica preferido.',
                        'zh' => '土木工程学士学位，成绩优良。至少一年实践经验优先。',
                        'ru' => 'Степень бакалавра гражданского строительства с отличными оценками. Предпочтителен опыт работы.',
                        'ur' => 'سول انجینئرنگ میں بیچلر ڈگری بہت اچھے درجے کے ساتھ۔ کم از کم ایک سال عملی تجربہ ترجیحی۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'استشاري إنشائي، تصميم المنشآت الكبرى، التدريس الجامعي، البحث في مواد البناء المتقدمة، إدارة المشاريع الكبرى.',
                        'en' => 'Structural consultant, major structure design, university teaching, research in advanced building materials, major project management.',
                        'fr' => 'Consultant structurel, conception de grandes structures, enseignement universitaire, recherche en matériaux de construction avancés.',
                        'es' => 'Consultor estructural, diseño de grandes estructuras, enseñanza universitaria, investigación en materiales de construcción avanzados.',
                        'zh' => '结构顾问、大型结构设计、大学教学、先进建筑材料研究、大型项目管理。',
                        'ru' => 'Консультант по конструкциям, проектирование крупных объектов, преподавание, исследования строительных материалов.',
                        'ur' => 'ساختی مشیر، بڑے ڈھانچوں کا ڈیزائن، جامعاتی تدریس، جدید تعمیراتی مواد میں تحقیق، بڑے پراجیکٹس کا انتظام۔',
                    ],
                ],
            ],
            'faculty-of-science' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس الفيزياء',
                        'en' => 'Bachelor of Physics',
                        'fr' => 'Licence en Physique',
                        'es' => 'Licenciatura en Física',
                        'zh' => '物理学学士',
                        'ru' => 'Бакалавриат физики',
                        'ur' => 'بیچلر آف فزکس',
                    ],
                    'description' => [
                        'ar' => 'برنامج يقدم دراسة شاملة في الفيزياء النظرية والتطبيقية شاملاً الميكانيكا والكهرومغناطيسية وفيزياء الكم والفيزياء النووية.',
                        'en' => 'A program offering comprehensive study in theoretical and applied physics including mechanics, electromagnetism, quantum physics, and nuclear physics.',
                        'fr' => 'Un programme offrant une étude complète en physique théorique et appliquée incluant la mécanique, l\'électromagnétisme et la physique quantique.',
                        'es' => 'Un programa que ofrece estudio integral en física teórica y aplicada incluyendo mecánica, electromagnetismo y física cuántica.',
                        'zh' => '提供理论和应用物理学综合研究的课程，包括力学、电磁学、量子物理和核物理。',
                        'ru' => 'Программа комплексного изучения теоретической и прикладной физики, включая механику, электромагнетизм и квантовую физику.',
                        'ur' => 'نظری اور عملی فزکس کا جامع مطالعہ بشمول میکانکس، برقی مقناطیسیت، کوانٹم فزکس اور نیوکلیئر فزکس۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => 140,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم بتقدير جيد. درجات عالية في الفيزياء والرياضيات.',
                        'en' => 'High school diploma in sciences with a good grade. High marks in physics and mathematics.',
                        'fr' => 'Diplôme de secondaire en sciences avec une bonne note. Notes élevées en physique et mathématiques.',
                        'es' => 'Diploma de secundaria en ciencias con buena calificación. Altas calificaciones en física y matemáticas.',
                        'zh' => '理科高中毕业证书，成绩良好。物理和数学成绩优异。',
                        'ru' => 'Аттестат по естественным наукам с хорошими оценками. Высокие баллы по физике и математике.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ اچھے درجے کے ساتھ۔ فزکس اور ریاضی میں اعلیٰ نمبرات۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس، البحث العلمي، العمل في المختبرات، الطاقة النووية، الاتصالات، تكنولوجيا الليزر، الأرصاد الجوية.',
                        'en' => 'Teaching, scientific research, laboratory work, nuclear energy, telecommunications, laser technology, meteorology.',
                        'fr' => 'Enseignement, recherche scientifique, travail en laboratoire, énergie nucléaire, télécommunications, technologie laser.',
                        'es' => 'Enseñanza, investigación científica, trabajo de laboratorio, energía nuclear, telecomunicaciones, tecnología láser.',
                        'zh' => '教学、科学研究、实验室工作、核能、电信、激光技术、气象学。',
                        'ru' => 'Преподавание, научные исследования, лабораторная работа, ядерная энергетика, телекоммуникации, лазерные технологии.',
                        'ur' => 'تدریس، سائنسی تحقیق، لیبارٹری کام، ایٹمی توانائی، مواصلات، لیزر ٹیکنالوجی، موسمیات۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'بكالوريوس الكيمياء',
                        'en' => 'Bachelor of Chemistry',
                        'fr' => 'Licence en Chimie',
                        'es' => 'Licenciatura en Química',
                        'zh' => '化学学士',
                        'ru' => 'Бакалавриат химии',
                        'ur' => 'بیچلر آف کیمسٹری',
                    ],
                    'description' => [
                        'ar' => 'برنامج يدرس الكيمياء العضوية وغير العضوية والتحليلية والفيزيائية مع التطبيقات الصناعية والبيئية.',
                        'en' => 'A program studying organic, inorganic, analytical, and physical chemistry with industrial and environmental applications.',
                        'fr' => 'Un programme étudiant la chimie organique, inorganique, analytique et physique avec des applications industrielles et environnementales.',
                        'es' => 'Un programa que estudia química orgánica, inorgánica, analítica y física con aplicaciones industriales y ambientales.',
                        'zh' => '研究有机化学、无机化学、分析化学和物理化学及其工业和环境应用的课程。',
                        'ru' => 'Программа изучения органической, неорганической, аналитической и физической химии с промышленными и экологическими применениями.',
                        'ur' => 'نامیاتی، غیر نامیاتی، تجزیاتی اور طبیعی کیمیا کا مطالعہ صنعتی اور ماحولیاتی اطلاقات کے ساتھ۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم. درجات جيدة في الكيمياء والرياضيات.',
                        'en' => 'High school diploma in sciences. Good marks in chemistry and mathematics.',
                        'fr' => 'Diplôme de secondaire en sciences. Bonnes notes en chimie et mathématiques.',
                        'es' => 'Diploma de secundaria en ciencias. Buenas calificaciones en química y matemáticas.',
                        'zh' => '理科高中毕业证书。化学和数学成绩良好。',
                        'ru' => 'Аттестат по естественным наукам. Хорошие оценки по химии и математике.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ۔ کیمسٹری اور ریاضی میں اچھے نمبرات۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'الصناعات الكيميائية، مراقبة الجودة، البحث العلمي، صناعة الأدوية، حماية البيئة، التدريس.',
                        'en' => 'Chemical industries, quality control, scientific research, pharmaceutical industry, environmental protection, teaching.',
                        'fr' => 'Industries chimiques, contrôle qualité, recherche scientifique, industrie pharmaceutique, protection environnementale, enseignement.',
                        'es' => 'Industrias químicas, control de calidad, investigación científica, industria farmacéutica, protección ambiental, enseñanza.',
                        'zh' => '化学工业、质量控制、科学研究、制药业、环境保护、教学。',
                        'ru' => 'Химическая промышленность, контроль качества, научные исследования, фармацевтика, охрана окружающей среды, преподавание.',
                        'ur' => 'کیمیائی صنعتیں، کوالٹی کنٹرول، سائنسی تحقیق، دوا سازی، ماحولیاتی تحفظ، تدریس۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'بكالوريوس الرياضيات',
                        'en' => 'Bachelor of Mathematics',
                        'fr' => 'Licence en Mathématiques',
                        'es' => 'Licenciatura en Matemáticas',
                        'zh' => '数学学士',
                        'ru' => 'Бакалавриат математики',
                        'ur' => 'بیچلر آف ریاضی',
                    ],
                    'description' => [
                        'ar' => 'برنامج يقدم دراسة معمقة في الرياضيات البحتة والتطبيقية شاملاً الجبر والتحليل والإحصاء والرياضيات الحاسوبية.',
                        'en' => 'A program offering in-depth study in pure and applied mathematics including algebra, analysis, statistics, and computational mathematics.',
                        'fr' => 'Un programme offrant une étude approfondie en mathématiques pures et appliquées incluant l\'algèbre, l\'analyse et les statistiques.',
                        'es' => 'Un programa que ofrece estudio profundo en matemáticas puras y aplicadas incluyendo álgebra, análisis y estadísticas.',
                        'zh' => '提供纯数学和应用数学深入研究的课程，包括代数、分析、统计学和计算数学。',
                        'ru' => 'Программа углублённого изучения чистой и прикладной математики, включая алгебру, анализ, статистику и вычислительную математику.',
                        'ur' => 'خالص اور عملی ریاضی کا گہرائی سے مطالعہ بشمول الجبرا، تجزیہ، شماریات اور کمپیوٹیشنل ریاضی۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة الرياضيات أو العلوم. درجات عالية في الرياضيات.',
                        'en' => 'High school diploma in mathematics or sciences track. High marks in mathematics.',
                        'fr' => 'Diplôme de secondaire en mathématiques ou sciences. Notes élevées en mathématiques.',
                        'es' => 'Diploma de secundaria en matemáticas o ciencias. Altas calificaciones en matemáticas.',
                        'zh' => '数学或理科方向高中毕业证书。数学成绩优异。',
                        'ru' => 'Аттестат по математике или естественным наукам. Высокие баллы по математике.',
                        'ur' => 'ریاضی یا سائنس شعبے میں ہائی اسکول ڈپلومہ۔ ریاضی میں اعلیٰ نمبرات۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس، البحث العلمي، تحليل البيانات، القطاع المالي والمصرفي، التأمين، البرمجة والذكاء الاصطناعي.',
                        'en' => 'Teaching, scientific research, data analysis, financial and banking sector, insurance, programming and artificial intelligence.',
                        'fr' => 'Enseignement, recherche, analyse de données, secteur financier et bancaire, assurance, programmation et IA.',
                        'es' => 'Enseñanza, investigación, análisis de datos, sector financiero y bancario, seguros, programación e IA.',
                        'zh' => '教学、科学研究、数据分析、金融银行业、保险、编程和人工智能。',
                        'ru' => 'Преподавание, исследования, анализ данных, финансовый и банковский сектор, страхование, программирование и ИИ.',
                        'ur' => 'تدریس، سائنسی تحقیق، ڈیٹا تجزیہ، مالیاتی اور بینکنگ شعبہ، انشورنس، پروگرامنگ اور مصنوعی ذہانت۔',
                    ],
                ],
            ],
            'faculty-of-commerce' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس المحاسبة',
                        'en' => 'Bachelor of Accounting',
                        'fr' => 'Licence en Comptabilité',
                        'es' => 'Licenciatura en Contabilidad',
                        'zh' => '会计学学士',
                        'ru' => 'Бакалавриат бухгалтерского учёта',
                        'ur' => 'بیچلر آف اکاؤنٹنگ',
                    ],
                    'description' => [
                        'ar' => 'برنامج يعد متخصصين في المحاسبة المالية والإدارية والمراجعة والضرائب مع دراسة المعايير المحاسبية الدولية.',
                        'en' => 'A program preparing specialists in financial and managerial accounting, auditing, and taxation with study of international accounting standards.',
                        'fr' => 'Un programme préparant des spécialistes en comptabilité financière et de gestion, audit et fiscalité selon les normes internationales.',
                        'es' => 'Un programa que prepara especialistas en contabilidad financiera y gerencial, auditoría e impuestos con estándares internacionales.',
                        'zh' => '培养财务会计、管理会计、审计和税务专家的课程，研究国际会计准则。',
                        'ru' => 'Программа подготовки специалистов по финансовому и управленческому учёту, аудиту и налогообложению по международным стандартам.',
                        'ur' => 'مالیاتی اور انتظامی اکاؤنٹنگ، آڈیٹنگ اور ٹیکسیشن میں ماہرین تیار کرنے والا پروگرام بین الاقوامی معیارات کے ساتھ۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => 136,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة أو ما يعادلها. اجتياز اختبار القبول.',
                        'en' => 'High school diploma or equivalent. Passing the admission test.',
                        'fr' => 'Diplôme de secondaire ou équivalent. Réussite du test d\'admission.',
                        'es' => 'Diploma de secundaria o equivalente. Aprobar el examen de admisión.',
                        'zh' => '高中毕业证书或同等学历。通过入学考试。',
                        'ru' => 'Аттестат о среднем образовании или эквивалент. Сдача вступительного экзамена.',
                        'ur' => 'ہائی اسکول ڈپلومہ یا مساوی۔ داخلہ ٹیسٹ پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'المحاسبة في الشركات، المراجعة والتدقيق، الاستشارات المالية، البنوك، هيئات الضرائب، التدريس.',
                        'en' => 'Corporate accounting, auditing, financial consulting, banking, tax authorities, teaching.',
                        'fr' => 'Comptabilité d\'entreprise, audit, conseil financier, banque, autorités fiscales, enseignement.',
                        'es' => 'Contabilidad corporativa, auditoría, consultoría financiera, banca, autoridades fiscales, enseñanza.',
                        'zh' => '企业会计、审计、财务咨询、银行业、税务机关、教学。',
                        'ru' => 'Корпоративный учёт, аудит, финансовый консалтинг, банковское дело, налоговые органы, преподавание.',
                        'ur' => 'کارپوریٹ اکاؤنٹنگ، آڈیٹنگ، مالیاتی مشاورت، بینکنگ، ٹیکس ادارے، تدریس۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'بكالوريوس إدارة الأعمال',
                        'en' => 'Bachelor of Business Administration',
                        'fr' => 'Licence en Administration des Affaires',
                        'es' => 'Licenciatura en Administración de Empresas',
                        'zh' => '工商管理学士',
                        'ru' => 'Бакалавриат делового администрирования',
                        'ur' => 'بیچلر آف بزنس ایڈمنسٹریشن',
                    ],
                    'description' => [
                        'ar' => 'برنامج شامل في إدارة الأعمال يغطي الإدارة الاستراتيجية والتسويق والموارد البشرية وإدارة العمليات والتمويل.',
                        'en' => 'A comprehensive business administration program covering strategic management, marketing, human resources, operations management, and finance.',
                        'fr' => 'Un programme complet en administration des affaires couvrant la gestion stratégique, le marketing, les ressources humaines et la finance.',
                        'es' => 'Un programa integral en administración de empresas que cubre gestión estratégica, marketing, recursos humanos y finanzas.',
                        'zh' => '全面的工商管理课程，涵盖战略管理、市场营销、人力资源、运营管理和财务。',
                        'ru' => 'Комплексная программа делового администрирования, охватывающая стратегическое управление, маркетинг, HR и финансы.',
                        'ur' => 'بزنس ایڈمنسٹریشن کا جامع پروگرام جو اسٹریٹجک مینجمنٹ، مارکیٹنگ، ہیومن ریسورسز اور فنانس کا احاطہ کرتا ہے۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة أو ما يعادلها. مستوى مقبول في اللغة الإنجليزية.',
                        'en' => 'High school diploma or equivalent. Acceptable level of English language.',
                        'fr' => 'Diplôme de secondaire ou équivalent. Niveau acceptable en anglais.',
                        'es' => 'Diploma de secundaria o equivalente. Nivel aceptable de inglés.',
                        'zh' => '高中毕业证书或同等学历。英语水平达标。',
                        'ru' => 'Аттестат или эквивалент. Приемлемый уровень английского языка.',
                        'ur' => 'ہائی اسکول ڈپلومہ یا مساوی۔ انگریزی زبان کی قابل قبول سطح۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'إدارة الشركات، التسويق، الموارد البشرية، ريادة الأعمال، الاستشارات الإدارية، المشاريع الصغيرة والمتوسطة.',
                        'en' => 'Corporate management, marketing, human resources, entrepreneurship, management consulting, SME businesses.',
                        'fr' => 'Gestion d\'entreprise, marketing, ressources humaines, entrepreneuriat, conseil en gestion, PME.',
                        'es' => 'Gestión corporativa, marketing, recursos humanos, emprendimiento, consultoría de gestión, PyMEs.',
                        'zh' => '企业管理、市场营销、人力资源、创业、管理咨询、中小企业。',
                        'ru' => 'Корпоративное управление, маркетинг, HR, предпринимательство, управленческий консалтинг, МСП.',
                        'ur' => 'کارپوریٹ مینجمنٹ، مارکیٹنگ، ہیومن ریسورسز، کاروبار، انتظامی مشاورت، چھوٹے اور درمیانے کاروبار۔',
                    ],
                ],
            ],
            'faculty-of-education' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس التربية - دراسات إسلامية',
                        'en' => 'Bachelor of Education - Islamic Studies',
                        'fr' => 'Licence en Éducation - Études Islamiques',
                        'es' => 'Licenciatura en Educación - Estudios Islámicos',
                        'zh' => '教育学学士 - 伊斯兰研究',
                        'ru' => 'Бакалавриат педагогики - исламские исследования',
                        'ur' => 'بیچلر آف ایجوکیشن - اسلامی علوم',
                    ],
                    'description' => [
                        'ar' => 'برنامج يجمع بين العلوم الإسلامية وعلوم التربية لإعداد معلمين متخصصين في تدريس المواد الإسلامية في المدارس.',
                        'en' => 'A program combining Islamic sciences and educational sciences to prepare specialized teachers for teaching Islamic subjects in schools.',
                        'fr' => 'Un programme combinant sciences islamiques et sciences de l\'éducation pour préparer des enseignants spécialisés en matières islamiques.',
                        'es' => 'Un programa que combina ciencias islámicas y ciencias educativas para preparar maestros especializados en materias islámicas.',
                        'zh' => '结合伊斯兰科学和教育科学的课程，培养学校伊斯兰学科的专业教师。',
                        'ru' => 'Программа, сочетающая исламские и педагогические науки для подготовки учителей исламских предметов.',
                        'ur' => 'اسلامی علوم اور تعلیمی علوم کو ملانے والا پروگرام جو اسکولوں میں اسلامی مضامین کے ماہر اساتذہ تیار کرتا ہے۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية الأزهرية أو العامة. رغبة حقيقية في مهنة التعليم. اجتياز المقابلة الشخصية.',
                        'en' => 'Al-Azhar or general secondary certificate. Genuine desire for teaching profession. Passing the personal interview.',
                        'fr' => 'Certificat secondaire d\'Al-Azhar ou général. Désir sincère pour la profession enseignante. Réussite de l\'entretien.',
                        'es' => 'Certificado secundario de Al-Azhar o general. Deseo genuino por la profesión docente. Aprobar la entrevista.',
                        'zh' => '艾资哈尔或普通中学证书。对教学职业的真诚愿望。通过个人面试。',
                        'ru' => 'Аттестат Аль-Азхара или общий. Искреннее стремление к педагогической профессии. Прохождение собеседования.',
                        'ur' => 'الازہر یا عام ثانوی سرٹیفکیٹ۔ تدریسی پیشے کی حقیقی خواہش۔ ذاتی انٹرویو پاس کرنا۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس في المدارس الأزهرية والعامة، الإشراف التربوي، تطوير المناهج الدينية، التوجيه والإرشاد التربوي.',
                        'en' => 'Teaching in Al-Azhar and public schools, educational supervision, religious curriculum development, educational guidance and counseling.',
                        'fr' => 'Enseignement dans les écoles d\'Al-Azhar et publiques, supervision éducative, développement de curricula religieux.',
                        'es' => 'Enseñanza en escuelas de Al-Azhar y públicas, supervisión educativa, desarrollo de currículos religiosos.',
                        'zh' => '在艾资哈尔和公立学校教学、教育督导、宗教课程开发、教育指导和咨询。',
                        'ru' => 'Преподавание в школах Аль-Азхара и государственных школах, педагогический надзор, разработка религиозных программ.',
                        'ur' => 'الازہر اور سرکاری اسکولوں میں تدریس، تعلیمی نگرانی، دینی نصاب کی ترقی، تعلیمی رہنمائی۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'بكالوريوس التربية - العلوم',
                        'en' => 'Bachelor of Education - Sciences',
                        'fr' => 'Licence en Éducation - Sciences',
                        'es' => 'Licenciatura en Educación - Ciencias',
                        'zh' => '教育学学士 - 科学',
                        'ru' => 'Бакалавриат педагогики - естественные науки',
                        'ur' => 'بیچلر آف ایجوکیشن - سائنسز',
                    ],
                    'description' => [
                        'ar' => 'برنامج يجمع بين العلوم الطبيعية وعلوم التربية لإعداد معلمين مؤهلين لتدريس العلوم في المراحل المختلفة.',
                        'en' => 'A program combining natural sciences and educational sciences to prepare qualified teachers for teaching sciences at various levels.',
                        'fr' => 'Un programme combinant sciences naturelles et sciences de l\'éducation pour préparer des enseignants qualifiés en sciences.',
                        'es' => 'Un programa que combina ciencias naturales y ciencias educativas para preparar maestros calificados en ciencias.',
                        'zh' => '结合自然科学和教育科学的课程，培养各级科学学科的合格教师。',
                        'ru' => 'Программа, сочетающая естественные и педагогические науки для подготовки квалифицированных учителей.',
                        'ur' => 'قدرتی علوم اور تعلیمی علوم کو ملانے والا پروگرام جو مختلف سطحوں پر سائنس کے اہل اساتذہ تیار کرتا ہے۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '4 years',
                    'credit_hours' => null,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم. رغبة في مهنة التعليم.',
                        'en' => 'High school diploma in sciences track. Desire for teaching profession.',
                        'fr' => 'Diplôme de secondaire en sciences. Désir pour la profession enseignante.',
                        'es' => 'Diploma de secundaria en ciencias. Deseo por la profesión docente.',
                        'zh' => '理科高中毕业证书。对教学职业的愿望。',
                        'ru' => 'Аттестат по естественным наукам. Стремление к педагогической профессии.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ۔ تدریسی پیشے کی خواہش۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'تدريس العلوم في المدارس، الإشراف التربوي، تطوير مناهج العلوم، إدارة المختبرات المدرسية.',
                        'en' => 'Teaching sciences in schools, educational supervision, science curriculum development, school laboratory management.',
                        'fr' => 'Enseignement des sciences dans les écoles, supervision éducative, développement de curricula scientifiques.',
                        'es' => 'Enseñanza de ciencias en escuelas, supervisión educativa, desarrollo de currículos científicos.',
                        'zh' => '在学校教授科学、教育督导、科学课程开发、学校实验室管理。',
                        'ru' => 'Преподавание наук в школах, педагогический надзор, разработка научных программ, управление школьными лабораториями.',
                        'ur' => 'اسکولوں میں سائنس کی تدریس، تعلیمی نگرانی، سائنس نصاب کی ترقی، اسکول لیبارٹریوں کا انتظام۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'دبلوم التربية',
                        'en' => 'Diploma of Education',
                        'fr' => 'Diplôme d\'Éducation',
                        'es' => 'Diploma de Educación',
                        'zh' => '教育文凭',
                        'ru' => 'Диплом педагогического образования',
                        'ur' => 'ڈپلومہ آف ایجوکیشن',
                    ],
                    'description' => [
                        'ar' => 'برنامج مهني يؤهل خريجي الكليات غير التربوية للعمل في مجال التدريس من خلال دراسة أساسيات التربية وطرق التدريس.',
                        'en' => 'A professional program qualifying non-education faculty graduates for teaching through studying educational foundations and teaching methods.',
                        'fr' => 'Un programme professionnel qualifiant les diplômés non-éducatifs pour l\'enseignement à travers les fondements éducatifs et les méthodes pédagogiques.',
                        'es' => 'Un programa profesional que califica a graduados no educativos para la enseñanza a través de fundamentos educativos y métodos de enseñanza.',
                        'zh' => '专业课程，通过学习教育基础和教学方法，使非教育学院毕业生获得教学资格。',
                        'ru' => 'Профессиональная программа для выпускников непедагогических факультетов для получения квалификации учителя.',
                        'ur' => 'پیشہ ورانہ پروگرام جو غیر تعلیمی کلیات کے فارغ التحصیل افراد کو تعلیمی بنیادوں اور تدریسی طریقوں کے ذریعے تدریس کے قابل بناتا ہے۔',
                    ],
                    'degree_level' => 'diploma',
                    'duration' => '1 year',
                    'credit_hours' => 30,
                    'requirements' => [
                        'ar' => 'بكالوريوس في أي تخصص بتقدير مقبول على الأقل. الرغبة في العمل بمهنة التعليم.',
                        'en' => 'Bachelor\'s degree in any discipline with at least a passing grade. Desire to work in the teaching profession.',
                        'fr' => 'Licence dans toute discipline avec au moins la moyenne. Désir de travailler dans l\'enseignement.',
                        'es' => 'Licenciatura en cualquier disciplina con al menos calificación aprobatoria. Deseo de trabajar en la enseñanza.',
                        'zh' => '任何专业学士学位，至少及格。有从事教学职业的愿望。',
                        'ru' => 'Степень бакалавра любой специальности с проходным баллом. Желание работать учителем.',
                        'ur' => 'کسی بھی مضمون میں بیچلر ڈگری کم از کم پاس درجے کے ساتھ۔ تدریسی پیشے میں کام کرنے کی خواہش۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'التدريس في المدارس الحكومية والخاصة، التأهيل المهني للمعلمين، العمل في مراكز التدريب التربوي.',
                        'en' => 'Teaching in public and private schools, professional teacher qualification, working in educational training centers.',
                        'fr' => 'Enseignement dans les écoles publiques et privées, qualification professionnelle des enseignants, centres de formation.',
                        'es' => 'Enseñanza en escuelas públicas y privadas, cualificación profesional docente, centros de formación educativa.',
                        'zh' => '在公立和私立学校教学、教师专业资格、在教育培训中心工作。',
                        'ru' => 'Преподавание в государственных и частных школах, профессиональная квалификация учителей, образовательные центры.',
                        'ur' => 'سرکاری اور نجی اسکولوں میں تدریس، پیشہ ورانہ اساتذہ کی اہلیت، تعلیمی تربیتی مراکز میں کام۔',
                    ],
                ],
            ],
            'faculty-of-pharmacy' => [
                [
                    'name' => [
                        'ar' => 'دكتور صيدلة',
                        'en' => 'Doctor of Pharmacy',
                        'fr' => 'Docteur en Pharmacie',
                        'es' => 'Doctor en Farmacia',
                        'zh' => '药学博士',
                        'ru' => 'Доктор фармации',
                        'ur' => 'ڈاکٹر آف فارمیسی',
                    ],
                    'description' => [
                        'ar' => 'برنامج مهني متكامل يعد صيادلة مؤهلين في العلوم الصيدلانية والصيدلة السريرية وتصنيع الأدوية والرقابة الدوائية.',
                        'en' => 'An integrated professional program preparing qualified pharmacists in pharmaceutical sciences, clinical pharmacy, drug manufacturing, and pharmaceutical regulation.',
                        'fr' => 'Un programme professionnel intégré préparant des pharmaciens qualifiés en sciences pharmaceutiques et pharmacie clinique.',
                        'es' => 'Un programa profesional integrado que prepara farmacéuticos calificados en ciencias farmacéuticas y farmacia clínica.',
                        'zh' => '综合专业课程，培养药学科学、临床药学、药物制造和药品监管方面的合格药剂师。',
                        'ru' => 'Интегрированная профессиональная программа подготовки фармацевтов в области фармацевтических наук и клинической фармации.',
                        'ur' => 'مربوط پیشہ ورانہ پروگرام جو دوائی سائنسز، طبی فارمیسی، ادویات کی تیاری اور دوائی نگرانی میں اہل فارماسسٹ تیار کرتا ہے۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '6 years',
                    'credit_hours' => 240,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم بمجموع لا يقل عن 88%. اجتياز اختبارات القبول. اللياقة الطبية.',
                        'en' => 'High school diploma in sciences with a minimum of 88%. Passing admission tests. Medical fitness.',
                        'fr' => 'Diplôme de secondaire en sciences avec un minimum de 88%. Réussite des tests d\'admission. Aptitude médicale.',
                        'es' => 'Diploma de secundaria en ciencias con mínimo 88%. Aprobar exámenes de admisión. Aptitud médica.',
                        'zh' => '理科高中毕业证书，总分不低于88%。通过入学考试。医学健康。',
                        'ru' => 'Аттестат по естественным наукам с минимальным баллом 88%. Сдача вступительных экзаменов. Медицинская пригодность.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ کم از کم 88% کے ساتھ۔ داخلہ ٹیسٹ پاس کرنا۔ طبی فٹنس۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'الصيدليات العامة والمستشفيات، صناعة الأدوية، الرقابة الدوائية، البحث الصيدلاني، الصيدلة السريرية، التسويق الدوائي.',
                        'en' => 'Community and hospital pharmacies, pharmaceutical industry, drug regulation, pharmaceutical research, clinical pharmacy, pharmaceutical marketing.',
                        'fr' => 'Pharmacies communautaires et hospitalières, industrie pharmaceutique, réglementation des médicaments, recherche pharmaceutique.',
                        'es' => 'Farmacias comunitarias y hospitalarias, industria farmacéutica, regulación de medicamentos, investigación farmacéutica.',
                        'zh' => '社区和医院药房、制药业、药品监管、药学研究、临床药学、药品营销。',
                        'ru' => 'Аптеки и больничные фармации, фармацевтическая промышленность, регулирование лекарств, фармацевтические исследования.',
                        'ur' => 'کمیونٹی اور ہسپتال فارمیسیاں، ادویاتی صنعت، ادویاتی نگرانی، دوائی تحقیق، طبی فارمیسی، دوائی مارکیٹنگ۔',
                    ],
                ],
            ],
            'faculty-of-dentistry' => [
                [
                    'name' => [
                        'ar' => 'بكالوريوس طب الأسنان',
                        'en' => 'Bachelor of Dental Medicine',
                        'fr' => 'Licence en Médecine Dentaire',
                        'es' => 'Licenciatura en Medicina Dental',
                        'zh' => '口腔医学学士',
                        'ru' => 'Бакалавриат стоматологии',
                        'ur' => 'بیچلر آف ڈینٹل میڈیسن',
                    ],
                    'description' => [
                        'ar' => 'برنامج طبي متكامل في طب وجراحة الفم والأسنان يشمل العلوم الأساسية والسريرية والتدريب العملي في العيادات الجامعية.',
                        'en' => 'An integrated medical program in oral and dental medicine and surgery covering basic and clinical sciences with practical training in university clinics.',
                        'fr' => 'Un programme médical intégré en médecine bucco-dentaire et chirurgie avec formation pratique dans les cliniques universitaires.',
                        'es' => 'Un programa médico integrado en medicina oral y dental y cirugía con formación práctica en clínicas universitarias.',
                        'zh' => '口腔医学和外科综合医学课程，涵盖基础和临床科学以及大学诊所的实践培训。',
                        'ru' => 'Интегрированная медицинская программа по стоматологии и челюстно-лицевой хирургии с практикой в университетских клиниках.',
                        'ur' => 'زبانی اور دندان کی طب اور جراحی میں مربوط طبی پروگرام، بنیادی اور طبی علوم اور جامعاتی کلینکس میں عملی تربیت۔',
                    ],
                    'degree_level' => 'bachelor',
                    'duration' => '5 years',
                    'credit_hours' => 220,
                    'requirements' => [
                        'ar' => 'شهادة الثانوية العامة شعبة العلوم بمجموع لا يقل عن 88%. اجتياز اختبارات القدرات والمقابلة. اللياقة الطبية الكاملة.',
                        'en' => 'High school diploma in sciences with a minimum of 88%. Passing aptitude tests and interview. Full medical fitness.',
                        'fr' => 'Diplôme de secondaire en sciences avec un minimum de 88%. Réussite des tests d\'aptitude et de l\'entretien. Aptitude médicale.',
                        'es' => 'Diploma de secundaria en ciencias con mínimo 88%. Aprobar pruebas de aptitud y entrevista. Aptitud médica completa.',
                        'zh' => '理科高中毕业证书，总分不低于88%。通过能力测试和面试。完全的医学健康。',
                        'ru' => 'Аттестат по естественным наукам с минимальным баллом 88%. Сдача тестов и собеседование. Полная медицинская пригодность.',
                        'ur' => 'سائنس شعبے میں ہائی اسکول ڈپلومہ کم از کم 88% کے ساتھ۔ قابلیت ٹیسٹ اور انٹرویو پاس کرنا۔ مکمل طبی فٹنس۔',
                    ],
                    'career_prospects' => [
                        'ar' => 'طب الأسنان العام، التخصص في فروع طب الأسنان، العيادات الخاصة، المستشفيات، البحث العلمي، التدريس الجامعي.',
                        'en' => 'General dentistry, specialization in dental fields, private clinics, hospitals, scientific research, university teaching.',
                        'fr' => 'Dentisterie générale, spécialisation dentaire, cliniques privées, hôpitaux, recherche scientifique, enseignement universitaire.',
                        'es' => 'Odontología general, especialización dental, clínicas privadas, hospitales, investigación científica, enseñanza universitaria.',
                        'zh' => '普通牙科、牙科专科化、私人诊所、医院、科学研究、大学教学。',
                        'ru' => 'Общая стоматология, специализация, частные клиники, больницы, научные исследования, преподавание.',
                        'ur' => 'عام دندان سازی، دندان کے شعبوں میں تخصص، نجی کلینکس، ہسپتال، سائنسی تحقیق، جامعاتی تدریس۔',
                    ],
                ],
            ],
        ];

        $order = 1;
        foreach ($programsByFaculty as $facultySlug => $programs) {
            $faculty = Faculty::where('slug', $facultySlug)->first();
            if (! $faculty) {
                continue;
            }

            foreach ($programs as $programData) {
                $program = new AcademicProgram();
                $program->slug = Str::slug($programData['name']['en']);
                $program->name = $programData['name'];
                $program->description = $programData['description'];
                $program->degree_level = $programData['degree_level'];
                $program->duration = $programData['duration'];
                $program->credit_hours = $programData['credit_hours'];
                $program->requirements = $programData['requirements'];
                $program->career_prospects = $programData['career_prospects'];
                $program->faculty_id = $faculty->id;
                $program->department_id = null;
                $program->order = $order++;
                $program->is_published = true;
                $program->save();
            }
        }
    }
}
