<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Faculty;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departmentsByFaculty = [
            'faculty-of-theology' => [
                [
                    'name' => [
                        'ar' => 'قسم العقيدة والفلسفة',
                        'en' => 'Department of Creed and Philosophy',
                        'fr' => 'Departement de Credo et Philosophie',
                        'es' => 'Departamento de Credo y Filosofia',
                        'zh' => '信条与哲学系',
                        'ru' => 'Кафедра вероубеждения и философии',
                        'ur' => 'شعبہ عقیدہ و فلسفہ',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم دراسة العقيدة الإسلامية والفلسفة الإسلامية والمقارنة بين المذاهب الكلامية والفلسفية.',
                        'en' => 'The department covers Islamic creed, Islamic philosophy, and comparative study of theological and philosophical schools.',
                        'fr' => 'Le departement couvre le credo islamique, la philosophie islamique et l\'etude comparative des ecoles theologiques et philosophiques.',
                        'es' => 'El departamento cubre el credo islamico, la filosofia islamica y el estudio comparativo de las escuelas teologicas y filosoficas.',
                        'zh' => '该系涵盖伊斯兰信条、伊斯兰哲学以及神学和哲学学派的比较研究。',
                        'ru' => 'Кафедра охватывает исламское вероубеждение, исламскую философию и сравнительное изучение богословских и философских школ.',
                        'ur' => 'یہ شعبہ اسلامی عقیدہ، اسلامی فلسفہ اور کلامی و فلسفیانہ مکاتب فکر کے تقابلی مطالعہ پر مشتمل ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم التفسير وعلوم القرآن',
                        'en' => 'Department of Exegesis and Quranic Sciences',
                        'fr' => 'Departement d\'Exegese et Sciences Coraniques',
                        'es' => 'Departamento de Exegesis y Ciencias Coranicas',
                        'zh' => '古兰经注释与古兰经科学系',
                        'ru' => 'Кафедра тафсира и коранических наук',
                        'ur' => 'شعبہ تفسیر و علوم القرآن',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بدراسة تفسير القرآن الكريم وعلومه من أسباب النزول والناسخ والمنسوخ وإعجاز القرآن.',
                        'en' => 'The department specializes in Quranic exegesis and its sciences including revelation contexts, abrogation, and Quranic inimitability.',
                        'fr' => 'Le departement se specialise dans l\'exegese coranique et ses sciences, y compris les contextes de revelation et l\'inimitabilite coranique.',
                        'es' => 'El departamento se especializa en la exegesis coranica y sus ciencias, incluidos los contextos de revelacion y la inimitabilidad coranica.',
                        'zh' => '该系专攻古兰经注释及其相关科学，包括降示背景、废止与被废止以及古兰经的奇迹性。',
                        'ru' => 'Кафедра специализируется на толковании Корана и его науках, включая причины ниспослания, отмену и неподражаемость Корана.',
                        'ur' => 'یہ شعبہ تفسیر قرآن اور اس کے علوم بشمول اسباب نزول، ناسخ و منسوخ اور اعجاز القرآن میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الحديث وعلومه',
                        'en' => 'Department of Hadith and Its Sciences',
                        'fr' => 'Departement du Hadith et Ses Sciences',
                        'es' => 'Departamento de Hadiz y Sus Ciencias',
                        'zh' => '圣训及其科学系',
                        'ru' => 'Кафедра хадисоведения',
                        'ur' => 'شعبہ حدیث و علوم حدیث',
                    ],
                    'description' => [
                        'ar' => 'يهتم القسم بدراسة الحديث النبوي الشريف ومصطلح الحديث وعلم الرجال والجرح والتعديل.',
                        'en' => 'The department focuses on Prophetic Hadith studies, hadith terminology, narrator evaluation, and authentication sciences.',
                        'fr' => 'Le departement se concentre sur les etudes du Hadith prophetique, la terminologie du hadith et les sciences d\'authentification.',
                        'es' => 'El departamento se centra en los estudios del Hadiz profetico, la terminologia del hadiz y las ciencias de autenticacion.',
                        'zh' => '该系专注于先知圣训研究、圣训术语、传述人评价及鉴定科学。',
                        'ru' => 'Кафедра занимается изучением пророческих хадисов, терминологии хадисов, оценки передатчиков и наук аутентификации.',
                        'ur' => 'یہ شعبہ حدیث نبوی، مصطلح الحدیث، علم رجال اور جرح و تعدیل کے مطالعہ پر مرکوز ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الدعوة والثقافة الإسلامية',
                        'en' => 'Department of Da\'wa and Islamic Culture',
                        'fr' => 'Departement de Da\'wa et Culture Islamique',
                        'es' => 'Departamento de Da\'wa y Cultura Islamica',
                        'zh' => '宣教与伊斯兰文化系',
                        'ru' => 'Кафедра призыва и исламской культуры',
                        'ur' => 'شعبہ دعوت و اسلامی ثقافت',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بدراسة أساليب الدعوة الإسلامية والثقافة الإسلامية ومقارنة الأديان والمذاهب المعاصرة.',
                        'en' => 'The department studies Islamic preaching methodologies, Islamic culture, comparative religion, and contemporary ideologies.',
                        'fr' => 'Le departement etudie les methodologies de predication islamique, la culture islamique et la religion comparee.',
                        'es' => 'El departamento estudia las metodologias de predicacion islamica, la cultura islamica y la religion comparada.',
                        'zh' => '该系研究伊斯兰宣教方法、伊斯兰文化、比较宗教学和当代思潮。',
                        'ru' => 'Кафедра изучает методологии исламского призыва, исламскую культуру, сравнительное религиоведение и современные идеологии.',
                        'ur' => 'یہ شعبہ اسلامی دعوت کے اسالیب، اسلامی ثقافت، مقارنۃ الادیان اور عصری مکاتب فکر کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-sharia-and-law' => [
                [
                    'name' => [
                        'ar' => 'قسم الفقه الإسلامي',
                        'en' => 'Department of Islamic Jurisprudence',
                        'fr' => 'Departement de Jurisprudence Islamique',
                        'es' => 'Departamento de Jurisprudencia Islamica',
                        'zh' => '伊斯兰教法学系',
                        'ru' => 'Кафедра исламской юриспруденции',
                        'ur' => 'شعبہ فقہ اسلامی',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم دراسة الفقه الإسلامي المقارن والمعاملات المالية والأحوال الشخصية وفقه النوازل المعاصرة.',
                        'en' => 'The department covers comparative Islamic jurisprudence, financial transactions, personal status law, and contemporary legal issues.',
                        'fr' => 'Le departement couvre la jurisprudence islamique comparee, les transactions financieres et le droit du statut personnel.',
                        'es' => 'El departamento cubre la jurisprudencia islamica comparada, las transacciones financieras y el derecho de estatus personal.',
                        'zh' => '该系涵盖比较伊斯兰教法学、金融交易、个人身份法和当代法律问题。',
                        'ru' => 'Кафедра охватывает сравнительную исламскую юриспруденцию, финансовые операции и семейное право.',
                        'ur' => 'یہ شعبہ تقابلی فقہ اسلامی، مالی معاملات، احوال شخصیہ اور عصری فقہی مسائل کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم أصول الفقه',
                        'en' => 'Department of Principles of Jurisprudence',
                        'fr' => 'Departement des Principes de Jurisprudence',
                        'es' => 'Departamento de Principios de Jurisprudencia',
                        'zh' => '教法原理系',
                        'ru' => 'Кафедра основ юриспруденции',
                        'ur' => 'شعبہ اصول فقہ',
                    ],
                    'description' => [
                        'ar' => 'يختص بدراسة القواعد الأصولية والمنهجية التي يبنى عليها استنباط الأحكام الشرعية من مصادرها.',
                        'en' => 'Specializes in the foundational rules and methodology for deriving legal rulings from their sources.',
                        'fr' => 'Se specialise dans les regles fondamentales et la methodologie pour deriver les decisions juridiques de leurs sources.',
                        'es' => 'Se especializa en las reglas fundamentales y la metodologia para derivar decisiones juridicas de sus fuentes.',
                        'zh' => '专注于从法律渊源推导法律裁决的基础规则和方法论。',
                        'ru' => 'Специализируется на фундаментальных правилах и методологии извлечения правовых решений из их источников.',
                        'ur' => 'شرعی مصادر سے احکام کے استنباط کے لیے اصولی قواعد اور منہجیت میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم القانون العام',
                        'en' => 'Department of Public Law',
                        'fr' => 'Departement de Droit Public',
                        'es' => 'Departamento de Derecho Publico',
                        'zh' => '公法系',
                        'ru' => 'Кафедра публичного права',
                        'ur' => 'شعبہ قانون عامہ',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم فروع القانون العام من دستوري وإداري وجنائي ودولي عام مع الربط بالشريعة الإسلامية.',
                        'en' => 'Studies branches of public law including constitutional, administrative, criminal, and international law linked with Islamic Sharia.',
                        'fr' => 'Etudie les branches du droit public, y compris le droit constitutionnel, administratif, penal et international lie a la charia islamique.',
                        'es' => 'Estudia las ramas del derecho publico, incluido el derecho constitucional, administrativo, penal e internacional vinculado con la Sharia islamica.',
                        'zh' => '研究公法各分支，包括宪法、行政法、刑法和与伊斯兰教法相关的国际法。',
                        'ru' => 'Изучает отрасли публичного права, включая конституционное, административное, уголовное и международное право в связи с исламским шариатом.',
                        'ur' => 'آئینی، انتظامی، فوجداری اور بین الاقوامی قانون سمیت قانون عامہ کی شاخوں کا اسلامی شریعت سے ربط کے ساتھ مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم القانون الخاص',
                        'en' => 'Department of Private Law',
                        'fr' => 'Departement de Droit Prive',
                        'es' => 'Departamento de Derecho Privado',
                        'zh' => '私法系',
                        'ru' => 'Кафедра частного права',
                        'ur' => 'شعبہ قانون خاص',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم دراسة القانون المدني والتجاري والمرافعات وقانون العمل مع مقارنتها بأحكام الفقه الإسلامي.',
                        'en' => 'Covers civil law, commercial law, procedural law, and labor law with comparison to Islamic jurisprudence.',
                        'fr' => 'Couvre le droit civil, commercial, procedural et du travail avec comparaison a la jurisprudence islamique.',
                        'es' => 'Cubre el derecho civil, comercial, procesal y laboral con comparacion a la jurisprudencia islamica.',
                        'zh' => '涵盖民法、商法、诉讼法和劳动法，并与伊斯兰教法学进行比较。',
                        'ru' => 'Охватывает гражданское, коммерческое, процессуальное и трудовое право с сравнением с исламской юриспруденцией.',
                        'ur' => 'مدنی، تجارتی، مرافعاتی اور قانون کار کا فقہ اسلامی سے تقابل کے ساتھ مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-arabic-language' => [
                [
                    'name' => [
                        'ar' => 'قسم النحو والصرف والعروض',
                        'en' => 'Department of Grammar, Morphology and Prosody',
                        'fr' => 'Departement de Grammaire, Morphologie et Prosodie',
                        'es' => 'Departamento de Gramatica, Morfologia y Prosodia',
                        'zh' => '语法、词法与韵律系',
                        'ru' => 'Кафедра грамматики, морфологии и просодии',
                        'ur' => 'شعبہ نحو، صرف و عروض',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بدراسة قواعد النحو العربي والصرف والعروض والقافية وتطبيقاتها على النصوص الأدبية.',
                        'en' => 'Focuses on Arabic grammar rules, morphology, prosody and rhyme with applications to literary texts.',
                        'fr' => 'Se concentre sur les regles de grammaire arabe, la morphologie, la prosodie et la rime avec des applications aux textes litteraires.',
                        'es' => 'Se centra en las reglas de la gramatica arabe, la morfologia, la prosodia y la rima con aplicaciones a los textos literarios.',
                        'zh' => '专注于阿拉伯语语法规则、词法、韵律和押韵及其在文学文本中的应用。',
                        'ru' => 'Изучает правила арабской грамматики, морфологии, просодии и рифмы с применением к литературным текстам.',
                        'ur' => 'عربی قواعد نحو، صرف، عروض و قافیہ اور ادبی متون پر ان کے اطلاقات کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم البلاغة والنقد الأدبي',
                        'en' => 'Department of Rhetoric and Literary Criticism',
                        'fr' => 'Departement de Rhetorique et Critique Litteraire',
                        'es' => 'Departamento de Retorica y Critica Literaria',
                        'zh' => '修辞学与文学批评系',
                        'ru' => 'Кафедра риторики и литературной критики',
                        'ur' => 'شعبہ بلاغت و ادبی تنقید',
                    ],
                    'description' => [
                        'ar' => 'يختص بدراسة علوم البلاغة الثلاثة (المعاني والبيان والبديع) والنقد الأدبي القديم والحديث.',
                        'en' => 'Specializes in the three branches of rhetoric (meanings, expression, embellishment) and classical and modern literary criticism.',
                        'fr' => 'Se specialise dans les trois branches de la rhetorique et la critique litteraire classique et moderne.',
                        'es' => 'Se especializa en las tres ramas de la retorica y la critica literaria clasica y moderna.',
                        'zh' => '专攻修辞学三科（含义学、修辞学、修饰学）以及古典和现代文学批评。',
                        'ru' => 'Специализируется на трёх разделах риторики и классической и современной литературной критике.',
                        'ur' => 'بلاغت کی تین شاخوں (معانی، بیان، بدیع) اور قدیم و جدید ادبی تنقید میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الأدب والنصوص',
                        'en' => 'Department of Literature and Texts',
                        'fr' => 'Departement de Litterature et Textes',
                        'es' => 'Departamento de Literatura y Textos',
                        'zh' => '文学与文本系',
                        'ru' => 'Кафедра литературы и текстов',
                        'ur' => 'شعبہ ادب و نصوص',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم الأدب العربي عبر العصور من الجاهلي إلى الحديث مع تحليل النصوص الأدبية الكبرى.',
                        'en' => 'Studies Arabic literature across eras from pre-Islamic to modern with analysis of major literary texts.',
                        'fr' => 'Etudie la litterature arabe a travers les epoques, du pre-islamique au moderne, avec analyse des textes litteraires majeurs.',
                        'es' => 'Estudia la literatura arabe a traves de las epocas, desde la preislamica hasta la moderna, con analisis de los principales textos literarios.',
                        'zh' => '研究从前伊斯兰时期到现代各时期的阿拉伯文学及主要文学文本分析。',
                        'ru' => 'Изучает арабскую литературу от доисламского периода до современности с анализом крупных литературных текстов.',
                        'ur' => 'جاہلی دور سے جدید دور تک عربی ادب کا مطالعہ اور بڑے ادبی متون کا تجزیہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم علم اللغة',
                        'en' => 'Department of Linguistics',
                        'fr' => 'Departement de Linguistique',
                        'es' => 'Departamento de Linguistica',
                        'zh' => '语言学系',
                        'ru' => 'Кафедра лингвистики',
                        'ur' => 'شعبہ علم اللسان',
                    ],
                    'description' => [
                        'ar' => 'يهتم القسم بدراسة علم اللغة العام والتطبيقي وفقه اللغة العربية وعلم الأصوات والدلالة.',
                        'en' => 'Focuses on general and applied linguistics, Arabic philology, phonetics, and semantics.',
                        'fr' => 'Se concentre sur la linguistique generale et appliquee, la philologie arabe, la phonetique et la semantique.',
                        'es' => 'Se centra en la linguistica general y aplicada, la filologia arabe, la fonetica y la semantica.',
                        'zh' => '专注于普通语言学和应用语言学、阿拉伯语文学、语音学和语义学。',
                        'ru' => 'Изучает общую и прикладную лингвистику, арабскую филологию, фонетику и семантику.',
                        'ur' => 'عمومی و اطلاقی لسانیات، عربی فقہ اللغہ، صوتیات اور علم الدلالہ کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-medicine' => [
                [
                    'name' => [
                        'ar' => 'قسم التشريح',
                        'en' => 'Department of Anatomy',
                        'fr' => 'Departement d\'Anatomie',
                        'es' => 'Departamento de Anatomia',
                        'zh' => '解剖学系',
                        'ru' => 'Кафедра анатомии',
                        'ur' => 'شعبہ تشریح الابدان',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم التشريح البشري والأنسجة وعلم الأجنة باستخدام أحدث التقنيات التعليمية.',
                        'en' => 'Studies human anatomy, histology, and embryology using the latest educational technologies.',
                        'fr' => 'Etudie l\'anatomie humaine, l\'histologie et l\'embryologie en utilisant les dernieres technologies educatives.',
                        'es' => 'Estudia la anatomia humana, la histologia y la embriologia utilizando las ultimas tecnologias educativas.',
                        'zh' => '使用最新教育技术研究人体解剖学、组织学和胚胎学。',
                        'ru' => 'Изучает анатомию человека, гистологию и эмбриологию с использованием новейших образовательных технологий.',
                        'ur' => 'جدید ترین تعلیمی ٹیکنالوجیز کا استعمال کرتے ہوئے انسانی تشریح، علم الانسجہ اور علم الاجنہ کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الباطنة العامة',
                        'en' => 'Department of Internal Medicine',
                        'fr' => 'Departement de Medecine Interne',
                        'es' => 'Departamento de Medicina Interna',
                        'zh' => '内科系',
                        'ru' => 'Кафедра внутренних болезней',
                        'ur' => 'شعبہ امراض باطنیہ',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بتشخيص وعلاج الأمراض الباطنية وتدريب الأطباء على أحدث أساليب الطب الباطني.',
                        'en' => 'Covers diagnosis and treatment of internal diseases and trains physicians in the latest internal medicine practices.',
                        'fr' => 'Couvre le diagnostic et le traitement des maladies internes et forme les medecins aux pratiques les plus recentes.',
                        'es' => 'Cubre el diagnostico y tratamiento de enfermedades internas y capacita medicos en las practicas mas recientes.',
                        'zh' => '涵盖内科疾病的诊断和治疗，培训医生掌握最新的内科医学实践。',
                        'ru' => 'Охватывает диагностику и лечение внутренних болезней и обучает врачей новейшим методам внутренней медицины.',
                        'ur' => 'باطنی امراض کی تشخیص و علاج اور ڈاکٹروں کو جدید ترین طبی طریقوں کی تربیت فراہم کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الجراحة العامة',
                        'en' => 'Department of General Surgery',
                        'fr' => 'Departement de Chirurgie Generale',
                        'es' => 'Departamento de Cirugia General',
                        'zh' => '普通外科系',
                        'ru' => 'Кафедра общей хирургии',
                        'ur' => 'شعبہ جراحت عامہ',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بتدريس الجراحة العامة وجراحة الطوارئ والجراحة بالمناظير والتدريب العملي في المستشفيات الجامعية.',
                        'en' => 'Specializes in general surgery, emergency surgery, laparoscopic surgery, and clinical training at university hospitals.',
                        'fr' => 'Se specialise dans la chirurgie generale, la chirurgie d\'urgence, la chirurgie laparoscopique et la formation clinique.',
                        'es' => 'Se especializa en cirugia general, cirugia de emergencia, cirugia laparoscopica y formacion clinica.',
                        'zh' => '专攻普通外科、急诊外科、腹腔镜外科和大学医院临床培训。',
                        'ru' => 'Специализируется на общей хирургии, неотложной хирургии, лапароскопической хирургии и клинической подготовке.',
                        'ur' => 'عمومی جراحی، ایمرجنسی جراحی، لیپروسکوپک جراحی اور یونیورسٹی ہسپتالوں میں عملی تربیت میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم طب الأطفال',
                        'en' => 'Department of Pediatrics',
                        'fr' => 'Departement de Pediatrie',
                        'es' => 'Departamento de Pediatria',
                        'zh' => '儿科系',
                        'ru' => 'Кафедра педиатрии',
                        'ur' => 'شعبہ امراض اطفال',
                    ],
                    'description' => [
                        'ar' => 'يهتم القسم بصحة الأطفال وأمراضهم وطب حديثي الولادة والتغذية والنمو والتطور.',
                        'en' => 'Focuses on child health, pediatric diseases, neonatology, nutrition, growth and development.',
                        'fr' => 'Se concentre sur la sante des enfants, les maladies pediatriques, la neonatologie, la nutrition, la croissance et le developpement.',
                        'es' => 'Se centra en la salud infantil, las enfermedades pediatricas, la neonatologia, la nutricion, el crecimiento y el desarrollo.',
                        'zh' => '专注于儿童健康、儿科疾病、新生儿学、营养、生长和发育。',
                        'ru' => 'Изучает здоровье детей, педиатрические заболевания, неонатологию, питание, рост и развитие.',
                        'ur' => 'بچوں کی صحت، اطفال کے امراض، نوزائیدگی کا طب، غذائیت اور نشوونما پر توجہ مرکوز کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم النساء والتوليد',
                        'en' => 'Department of Obstetrics and Gynecology',
                        'fr' => 'Departement d\'Obstetrique et Gynecologie',
                        'es' => 'Departamento de Obstetricia y Ginecologia',
                        'zh' => '妇产科系',
                        'ru' => 'Кафедра акушерства и гинекологии',
                        'ur' => 'شعبہ امراض نسواں و زچگی',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم صحة المرأة وأمراض النساء والتوليد وطب الخصوبة والإنجاب.',
                        'en' => 'Covers women\'s health, gynecological diseases, obstetrics, fertility medicine, and reproductive health.',
                        'fr' => 'Couvre la sante des femmes, les maladies gynecologiques, l\'obstetrique et la medecine de la fertilite.',
                        'es' => 'Cubre la salud de la mujer, las enfermedades ginecologicas, la obstetricia y la medicina de la fertilidad.',
                        'zh' => '涵盖妇女健康、妇科疾病、产科学、生育医学和生殖健康。',
                        'ru' => 'Охватывает здоровье женщин, гинекологические заболевания, акушерство и репродуктивную медицину.',
                        'ur' => 'خواتین کی صحت، امراض نسواں، زچگی، طب تولید اور تولیدی صحت کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-engineering' => [
                [
                    'name' => [
                        'ar' => 'قسم الهندسة المدنية',
                        'en' => 'Department of Civil Engineering',
                        'fr' => 'Departement de Genie Civil',
                        'es' => 'Departamento de Ingenieria Civil',
                        'zh' => '土木工程系',
                        'ru' => 'Кафедра гражданского строительства',
                        'ur' => 'شعبہ سول انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم دراسة الإنشاءات والهندسة الهيكلية والمائية والجيوتقنية والبنية التحتية.',
                        'en' => 'Covers structural, hydraulic, geotechnical engineering, and infrastructure studies.',
                        'fr' => 'Couvre l\'ingenierie structurelle, hydraulique, geotechnique et les etudes d\'infrastructure.',
                        'es' => 'Cubre la ingenieria estructural, hidraulica, geotecnica y los estudios de infraestructura.',
                        'zh' => '涵盖结构工程、水利工程、岩土工程和基础设施研究。',
                        'ru' => 'Охватывает структурную, гидравлическую, геотехническую инженерию и инфраструктурные исследования.',
                        'ur' => 'ساختیاتی، ہائیڈرالک، جیوٹیکنیکل انجینئرنگ اور بنیادی ڈھانچے کے مطالعات کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الهندسة الكهربائية',
                        'en' => 'Department of Electrical Engineering',
                        'fr' => 'Departement de Genie Electrique',
                        'es' => 'Departamento de Ingenieria Electrica',
                        'zh' => '电气工程系',
                        'ru' => 'Кафедра электротехники',
                        'ur' => 'شعبہ برقی انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم هندسة القوى الكهربائية والإلكترونيات والاتصالات والتحكم الآلي.',
                        'en' => 'Studies electrical power engineering, electronics, telecommunications, and automatic control.',
                        'fr' => 'Etudie l\'ingenierie de l\'energie electrique, l\'electronique, les telecommunications et le controle automatique.',
                        'es' => 'Estudia la ingenieria de potencia electrica, la electronica, las telecomunicaciones y el control automatico.',
                        'zh' => '研究电力工程、电子学、电信和自动控制。',
                        'ru' => 'Изучает электроэнергетику, электронику, телекоммуникации и автоматическое управление.',
                        'ur' => 'برقی طاقت کی انجینئرنگ، الیکٹرانکس، ٹیلی مواصلات اور خودکار کنٹرول کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الهندسة الميكانيكية',
                        'en' => 'Department of Mechanical Engineering',
                        'fr' => 'Departement de Genie Mecanique',
                        'es' => 'Departamento de Ingenieria Mecanica',
                        'zh' => '机械工程系',
                        'ru' => 'Кафедра машиностроения',
                        'ur' => 'شعبہ مکینیکل انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'يشمل القسم دراسة الديناميكا الحرارية وميكانيكا الموائع والتصميم الميكانيكي وهندسة الإنتاج.',
                        'en' => 'Covers thermodynamics, fluid mechanics, mechanical design, and production engineering.',
                        'fr' => 'Couvre la thermodynamique, la mecanique des fluides, la conception mecanique et l\'ingenierie de production.',
                        'es' => 'Cubre la termodinamica, la mecanica de fluidos, el diseno mecanico y la ingenieria de produccion.',
                        'zh' => '涵盖热力学、流体力学、机械设计和生产工程。',
                        'ru' => 'Охватывает термодинамику, механику жидкостей, механическое проектирование и производственную инженерию.',
                        'ur' => 'حرحرکیات، سیالی میکانکس، مکینیکل ڈیزائن اور پیداواری انجینئرنگ کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم هندسة الحاسبات والنظم',
                        'en' => 'Department of Computer and Systems Engineering',
                        'fr' => 'Departement d\'Ingenierie Informatique et Systemes',
                        'es' => 'Departamento de Ingenieria de Computadores y Sistemas',
                        'zh' => '计算机与系统工程系',
                        'ru' => 'Кафедра компьютерной и системной инженерии',
                        'ur' => 'شعبہ کمپیوٹر اینڈ سسٹمز انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بهندسة الحاسبات وأنظمة التشغيل والشبكات والذكاء الاصطناعي وهندسة البرمجيات.',
                        'en' => 'Specializes in computer engineering, operating systems, networks, artificial intelligence, and software engineering.',
                        'fr' => 'Se specialise dans l\'ingenierie informatique, les systemes d\'exploitation, les reseaux, l\'intelligence artificielle et l\'ingenierie logicielle.',
                        'es' => 'Se especializa en ingenieria informatica, sistemas operativos, redes, inteligencia artificial e ingenieria de software.',
                        'zh' => '专攻计算机工程、操作系统、网络、人工智能和软件工程。',
                        'ru' => 'Специализируется на компьютерной инженерии, операционных системах, сетях, искусственном интеллекте и программной инженерии.',
                        'ur' => 'کمپیوٹر انجینئرنگ، آپریٹنگ سسٹمز، نیٹ ورکس، مصنوعی ذہانت اور سافٹ ویئر انجینئرنگ میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الهندسة المعمارية',
                        'en' => 'Department of Architectural Engineering',
                        'fr' => 'Departement d\'Architecture',
                        'es' => 'Departamento de Ingenieria Arquitectonica',
                        'zh' => '建筑工程系',
                        'ru' => 'Кафедра архитектурной инженерии',
                        'ur' => 'شعبہ تعمیراتی انجینئرنگ',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم التصميم المعماري والتخطيط العمراني والعمارة الإسلامية والتصميم المستدام.',
                        'en' => 'Studies architectural design, urban planning, Islamic architecture, and sustainable design.',
                        'fr' => 'Etudie la conception architecturale, l\'urbanisme, l\'architecture islamique et la conception durable.',
                        'es' => 'Estudia el diseno arquitectonico, la planificacion urbana, la arquitectura islamica y el diseno sostenible.',
                        'zh' => '研究建筑设计、城市规划、伊斯兰建筑和可持续设计。',
                        'ru' => 'Изучает архитектурное проектирование, градостроительство, исламскую архитектуру и устойчивый дизайн.',
                        'ur' => 'تعمیراتی ڈیزائن، شہری منصوبہ بندی، اسلامی فنِ تعمیر اور پائیدار ڈیزائن کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-science' => [
                [
                    'name' => [
                        'ar' => 'قسم الرياضيات',
                        'en' => 'Department of Mathematics',
                        'fr' => 'Departement de Mathematiques',
                        'es' => 'Departamento de Matematicas',
                        'zh' => '数学系',
                        'ru' => 'Кафедра математики',
                        'ur' => 'شعبہ ریاضیات',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم الرياضيات البحتة والتطبيقية والإحصاء وعلوم الحاسوب الرياضية.',
                        'en' => 'Covers pure and applied mathematics, statistics, and computational mathematics.',
                        'fr' => 'Couvre les mathematiques pures et appliquees, les statistiques et les mathematiques computationnelles.',
                        'es' => 'Cubre las matematicas puras y aplicadas, la estadistica y las matematicas computacionales.',
                        'zh' => '涵盖纯数学和应用数学、统计学和计算数学。',
                        'ru' => 'Охватывает чистую и прикладную математику, статистику и вычислительную математику.',
                        'ur' => 'خالص و اطلاقی ریاضیات، شماریات اور حسابیاتی ریاضیات کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الفيزياء',
                        'en' => 'Department of Physics',
                        'fr' => 'Departement de Physique',
                        'es' => 'Departamento de Fisica',
                        'zh' => '物理系',
                        'ru' => 'Кафедра физики',
                        'ur' => 'شعبہ طبیعیات',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم الفيزياء النظرية والتجريبية والفيزياء النووية والليزر وفيزياء المواد.',
                        'en' => 'Studies theoretical and experimental physics, nuclear physics, laser physics, and materials science.',
                        'fr' => 'Etudie la physique theorique et experimentale, la physique nucleaire, la physique des lasers et la science des materiaux.',
                        'es' => 'Estudia la fisica teorica y experimental, la fisica nuclear, la fisica de laseres y la ciencia de materiales.',
                        'zh' => '研究理论物理和实验物理、核物理、激光物理和材料科学。',
                        'ru' => 'Изучает теоретическую и экспериментальную физику, ядерную физику, лазерную физику и материаловедение.',
                        'ur' => 'نظری و تجرباتی طبیعیات، نیوکلیائی طبیعیات، لیزر طبیعیات اور مادی سائنس کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الكيمياء',
                        'en' => 'Department of Chemistry',
                        'fr' => 'Departement de Chimie',
                        'es' => 'Departamento de Quimica',
                        'zh' => '化学系',
                        'ru' => 'Кафедра химии',
                        'ur' => 'شعبہ کیمیا',
                    ],
                    'description' => [
                        'ar' => 'يشمل القسم الكيمياء العضوية وغير العضوية والفيزيائية والتحليلية والكيمياء الحيوية.',
                        'en' => 'Covers organic, inorganic, physical, analytical, and biochemistry.',
                        'fr' => 'Couvre la chimie organique, inorganique, physique, analytique et la biochimie.',
                        'es' => 'Cubre la quimica organica, inorganica, fisica, analitica y la bioquimica.',
                        'zh' => '涵盖有机化学、无机化学、物理化学、分析化学和生物化学。',
                        'ru' => 'Охватывает органическую, неорганическую, физическую, аналитическую и биохимию.',
                        'ur' => 'نامیاتی، غیر نامیاتی، طبیعی، تجزیاتی اور حیاتی کیمیا کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم علم الأحياء',
                        'en' => 'Department of Biology',
                        'fr' => 'Departement de Biologie',
                        'es' => 'Departamento de Biologia',
                        'zh' => '生物学系',
                        'ru' => 'Кафедра биологии',
                        'ur' => 'شعبہ حیاتیات',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بدراسة علم الحيوان والنبات والأحياء الدقيقة والوراثة والبيولوجيا الجزيئية.',
                        'en' => 'Studies zoology, botany, microbiology, genetics, and molecular biology.',
                        'fr' => 'Etudie la zoologie, la botanique, la microbiologie, la genetique et la biologie moleculaire.',
                        'es' => 'Estudia la zoologia, la botanica, la microbiologia, la genetica y la biologia molecular.',
                        'zh' => '研究动物学、植物学、微生物学、遗传学和分子生物学。',
                        'ru' => 'Изучает зоологию, ботанику, микробиологию, генетику и молекулярную биологию.',
                        'ur' => 'حیوانیات، نباتیات، خردحیاتیات، جینیات اور سالماتی حیاتیات کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الجيولوجيا',
                        'en' => 'Department of Geology',
                        'fr' => 'Departement de Geologie',
                        'es' => 'Departamento de Geologia',
                        'zh' => '地质学系',
                        'ru' => 'Кафедра геологии',
                        'ur' => 'شعبہ ارضیات',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم علوم الأرض والمعادن والصخور والجيولوجيا البيئية والتطبيقية.',
                        'en' => 'Studies earth sciences, mineralogy, petrology, environmental and applied geology.',
                        'fr' => 'Etudie les sciences de la terre, la mineralogie, la petrologie et la geologie environnementale et appliquee.',
                        'es' => 'Estudia las ciencias de la tierra, la mineralogia, la petrologia y la geologia ambiental y aplicada.',
                        'zh' => '研究地球科学、矿物学、岩石学、环境地质学和应用地质学。',
                        'ru' => 'Изучает науки о Земле, минералогию, петрологию, экологическую и прикладную геологию.',
                        'ur' => 'ارضی علوم، معدنیات، چٹانیات، ماحولیاتی اور اطلاقی ارضیات کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-commerce' => [
                [
                    'name' => [
                        'ar' => 'قسم المحاسبة',
                        'en' => 'Department of Accounting',
                        'fr' => 'Departement de Comptabilite',
                        'es' => 'Departamento de Contabilidad',
                        'zh' => '会计系',
                        'ru' => 'Кафедра бухгалтерского учёта',
                        'ur' => 'شعبہ محاسبہ',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم المحاسبة المالية والإدارية والتكاليف والمراجعة والمحاسبة الحكومية.',
                        'en' => 'Covers financial, managerial, and cost accounting, auditing, and governmental accounting.',
                        'fr' => 'Couvre la comptabilite financiere, manageriale et des couts, l\'audit et la comptabilite gouvernementale.',
                        'es' => 'Cubre la contabilidad financiera, gerencial y de costos, la auditoria y la contabilidad gubernamental.',
                        'zh' => '涵盖财务会计、管理会计、成本会计、审计和政府会计。',
                        'ru' => 'Охватывает финансовый, управленческий учёт и учёт затрат, аудит и государственный учёт.',
                        'ur' => 'مالی، انتظامی اور لاگت محاسبہ، آڈیٹنگ اور حکومتی محاسبہ کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم إدارة الأعمال',
                        'en' => 'Department of Business Administration',
                        'fr' => 'Departement d\'Administration des Affaires',
                        'es' => 'Departamento de Administracion de Empresas',
                        'zh' => '工商管理系',
                        'ru' => 'Кафедра делового администрирования',
                        'ur' => 'شعبہ انتظامِ کاروبار',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم الإدارة العامة والتسويق والموارد البشرية والإدارة الاستراتيجية وريادة الأعمال.',
                        'en' => 'Studies management, marketing, human resources, strategic management, and entrepreneurship.',
                        'fr' => 'Etudie la gestion, le marketing, les ressources humaines, la gestion strategique et l\'entrepreneuriat.',
                        'es' => 'Estudia la gestion, el marketing, los recursos humanos, la gestion estrategica y el emprendimiento.',
                        'zh' => '研究管理学、市场营销、人力资源、战略管理和创业。',
                        'ru' => 'Изучает менеджмент, маркетинг, управление персоналом, стратегический менеджмент и предпринимательство.',
                        'ur' => 'انتظام، مارکیٹنگ، انسانی وسائل، اسٹریٹیجک انتظام اور کاروباری جدت کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الاقتصاد',
                        'en' => 'Department of Economics',
                        'fr' => 'Departement d\'Economie',
                        'es' => 'Departamento de Economia',
                        'zh' => '经济学系',
                        'ru' => 'Кафедра экономики',
                        'ur' => 'شعبہ اقتصادیات',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم الاقتصاد الجزئي والكلي والاقتصاد الإسلامي والتنمية الاقتصادية والاقتصاد الدولي.',
                        'en' => 'Covers micro and macroeconomics, Islamic economics, economic development, and international economics.',
                        'fr' => 'Couvre la micro et macroeconomie, l\'economie islamique, le developpement economique et l\'economie internationale.',
                        'es' => 'Cubre la micro y macroeconomia, la economia islamica, el desarrollo economico y la economia internacional.',
                        'zh' => '涵盖微观经济学和宏观经济学、伊斯兰经济学、经济发展和国际经济学。',
                        'ru' => 'Охватывает микро- и макроэкономику, исламскую экономику, экономическое развитие и международную экономику.',
                        'ur' => 'خرد و کلاں معاشیات، اسلامی معاشیات، اقتصادی ترقی اور بین الاقوامی معاشیات کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الإحصاء والتأمين',
                        'en' => 'Department of Statistics and Insurance',
                        'fr' => 'Departement de Statistiques et Assurance',
                        'es' => 'Departamento de Estadistica y Seguros',
                        'zh' => '统计与保险系',
                        'ru' => 'Кафедра статистики и страхования',
                        'ur' => 'شعبہ شماریات و بیمہ',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بالإحصاء التطبيقي والرياضي وعلوم التأمين والعلوم الاكتوارية.',
                        'en' => 'Specializes in applied and mathematical statistics, insurance sciences, and actuarial studies.',
                        'fr' => 'Se specialise dans les statistiques appliquees et mathematiques, les sciences de l\'assurance et les etudes actuarielles.',
                        'es' => 'Se especializa en estadistica aplicada y matematica, ciencias del seguro y estudios actuariales.',
                        'zh' => '专攻应用统计学和数理统计学、保险科学和精算研究。',
                        'ru' => 'Специализируется на прикладной и математической статистике, страховых науках и актуарных исследованиях.',
                        'ur' => 'اطلاقی و ریاضیاتی شماریات، بیمہ علوم اور ایکچوریل مطالعات میں مہارت رکھتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-islamic-studies' => [
                [
                    'name' => [
                        'ar' => 'قسم الفقه وأصوله',
                        'en' => 'Department of Jurisprudence and Its Principles',
                        'fr' => 'Departement de Jurisprudence et Ses Principes',
                        'es' => 'Departamento de Jurisprudencia y Sus Principios',
                        'zh' => '教法学及其原理系',
                        'ru' => 'Кафедра юриспруденции и её основ',
                        'ur' => 'شعبہ فقہ و اصول فقہ',
                    ],
                    'description' => [
                        'ar' => 'يجمع القسم بين دراسة الفقه الإسلامي بمذاهبه المختلفة وأصول الفقه ومناهج الاجتهاد.',
                        'en' => 'Combines the study of Islamic jurisprudence across its schools with the principles and methodologies of legal reasoning.',
                        'fr' => 'Combine l\'etude de la jurisprudence islamique a travers ses ecoles avec les principes et methodologies du raisonnement juridique.',
                        'es' => 'Combina el estudio de la jurisprudencia islamica a traves de sus escuelas con los principios y metodologias del razonamiento juridico.',
                        'zh' => '将伊斯兰教法学各学派的研究与法律推理的原理和方法论相结合。',
                        'ru' => 'Сочетает изучение исламской юриспруденции через её школы с принципами и методологиями правового мышления.',
                        'ur' => 'فقہ اسلامی کے مختلف مذاہب کے مطالعہ کو اصول فقہ اور اجتہادی مناہج سے جوڑتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم التفسير والحديث',
                        'en' => 'Department of Exegesis and Hadith',
                        'fr' => 'Departement d\'Exegese et Hadith',
                        'es' => 'Departamento de Exegesis y Hadiz',
                        'zh' => '古兰经注释与圣训系',
                        'ru' => 'Кафедра тафсира и хадисов',
                        'ur' => 'شعبہ تفسیر و حدیث',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم تفسير القرآن الكريم وعلوم الحديث النبوي بمنهج تكاملي يجمع بين العلمين.',
                        'en' => 'Studies Quranic exegesis and Prophetic Hadith sciences through an integrated approach combining both disciplines.',
                        'fr' => 'Etudie l\'exegese coranique et les sciences du Hadith prophetique a travers une approche integree combinant les deux disciplines.',
                        'es' => 'Estudia la exegesis coranica y las ciencias del Hadiz profetico a traves de un enfoque integrado que combina ambas disciplinas.',
                        'zh' => '通过综合方法研究古兰经注释和先知圣训科学，将两门学科相结合。',
                        'ru' => 'Изучает толкование Корана и хадисоведение через интегрированный подход, объединяющий обе дисциплины.',
                        'ur' => 'دونوں علوم کو جوڑنے والے تکاملی منہج کے ذریعے تفسیر قرآن اور علوم حدیث کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم العقيدة والدعوة',
                        'en' => 'Department of Creed and Da\'wa',
                        'fr' => 'Departement de Credo et Da\'wa',
                        'es' => 'Departamento de Credo y Da\'wa',
                        'zh' => '信条与宣教系',
                        'ru' => 'Кафедра вероубеждения и призыва',
                        'ur' => 'شعبہ عقیدہ و دعوت',
                    ],
                    'description' => [
                        'ar' => 'يجمع القسم بين دراسة العقيدة الإسلامية وأساليب الدعوة المعاصرة ومقارنة الأديان.',
                        'en' => 'Combines Islamic creed studies with contemporary preaching methodologies and comparative religion.',
                        'fr' => 'Combine les etudes du credo islamique avec les methodologies de predication contemporaines et la religion comparee.',
                        'es' => 'Combina los estudios del credo islamico con las metodologias de predicacion contemporaneas y la religion comparada.',
                        'zh' => '将伊斯兰信条研究与当代宣教方法论和比较宗教学相结合。',
                        'ru' => 'Сочетает изучение исламского вероубеждения с современными методологиями призыва и сравнительным религиоведением.',
                        'ur' => 'اسلامی عقیدے کے مطالعہ کو عصری دعوتی اسالیب اور مقارنۃ الادیان سے جوڑتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-islamic-dawa' => [
                [
                    'name' => [
                        'ar' => 'قسم الدعوة والإعلام',
                        'en' => 'Department of Da\'wa and Media',
                        'fr' => 'Departement de Da\'wa et Medias',
                        'es' => 'Departamento de Da\'wa y Medios',
                        'zh' => '宣教与媒体系',
                        'ru' => 'Кафедра призыва и СМИ',
                        'ur' => 'شعبہ دعوت و ذرائع ابلاغ',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم أساليب الدعوة الإسلامية الحديثة واستخدام وسائل الإعلام والتقنيات الرقمية في نشر الرسالة الإسلامية.',
                        'en' => 'Studies modern Islamic preaching methods and the use of media and digital technologies in spreading the Islamic message.',
                        'fr' => 'Etudie les methodes modernes de predication islamique et l\'utilisation des medias et technologies numeriques.',
                        'es' => 'Estudia los metodos modernos de predicacion islamica y el uso de medios y tecnologias digitales.',
                        'zh' => '研究现代伊斯兰宣教方法以及利用媒体和数字技术传播伊斯兰信息。',
                        'ru' => 'Изучает современные методы исламского призыва и использование СМИ и цифровых технологий.',
                        'ur' => 'جدید اسلامی دعوتی طریقوں اور اسلامی پیغام کی ترویج میں ذرائع ابلاغ و ڈیجیٹل ٹیکنالوجیز کے استعمال کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الأديان والمذاهب',
                        'en' => 'Department of Religions and Sects',
                        'fr' => 'Departement des Religions et Sectes',
                        'es' => 'Departamento de Religiones y Sectas',
                        'zh' => '宗教与教派系',
                        'ru' => 'Кафедра религий и сект',
                        'ur' => 'شعبہ ادیان و مذاہب',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بالدراسة المقارنة للأديان السماوية والمذاهب الفكرية المعاصرة والحوار بين الأديان.',
                        'en' => 'Specializes in comparative study of Abrahamic religions, contemporary ideological movements, and interfaith dialogue.',
                        'fr' => 'Se specialise dans l\'etude comparative des religions abrahamiques, des mouvements ideologiques contemporains et du dialogue interreligieux.',
                        'es' => 'Se especializa en el estudio comparativo de las religiones abrahamicas, los movimientos ideologicos contemporaneos y el dialogo interreligioso.',
                        'zh' => '专攻亚伯拉罕诸宗教的比较研究、当代意识形态运动和宗教间对话。',
                        'ru' => 'Специализируется на сравнительном изучении авраамических религий, современных идеологических движений и межрелигиозном диалоге.',
                        'ur' => 'ابراہیمی ادیان کے تقابلی مطالعہ، عصری نظریاتی تحریکوں اور بین المذاہب مکالمے میں مہارت رکھتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-education' => [
                [
                    'name' => [
                        'ar' => 'قسم المناهج وطرق التدريس',
                        'en' => 'Department of Curricula and Teaching Methods',
                        'fr' => 'Departement des Programmes et Methodes d\'Enseignement',
                        'es' => 'Departamento de Curriculos y Metodos de Ensenanza',
                        'zh' => '课程与教学方法系',
                        'ru' => 'Кафедра учебных программ и методов преподавания',
                        'ur' => 'شعبہ نصاب و طریقہ تدریس',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بتطوير المناهج الدراسية وأساليب التدريس الحديثة وتقنيات التعليم والتقويم التربوي.',
                        'en' => 'Focuses on curriculum development, modern teaching methods, educational technology, and pedagogical assessment.',
                        'fr' => 'Se concentre sur le developpement des programmes, les methodes d\'enseignement modernes et la technologie educative.',
                        'es' => 'Se centra en el desarrollo curricular, los metodos de ensenanza modernos y la tecnologia educativa.',
                        'zh' => '专注于课程开发、现代教学方法、教育技术和教学评估。',
                        'ru' => 'Изучает разработку учебных программ, современные методы преподавания, образовательные технологии и педагогическую оценку.',
                        'ur' => 'نصاب کی ترقی، جدید طریقہ تدریس، تعلیمی ٹیکنالوجی اور تربیتی تقویم پر توجہ مرکوز کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم علم النفس التربوي',
                        'en' => 'Department of Educational Psychology',
                        'fr' => 'Departement de Psychologie de l\'Education',
                        'es' => 'Departamento de Psicologia Educativa',
                        'zh' => '教育心理学系',
                        'ru' => 'Кафедра педагогической психологии',
                        'ur' => 'شعبہ تعلیمی نفسیات',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم نظريات التعلم والنمو النفسي والقياس النفسي والتوجيه والإرشاد التربوي.',
                        'en' => 'Studies learning theories, psychological development, psychometrics, and educational guidance and counseling.',
                        'fr' => 'Etudie les theories de l\'apprentissage, le developpement psychologique, la psychometrie et l\'orientation educative.',
                        'es' => 'Estudia las teorias del aprendizaje, el desarrollo psicologico, la psicometria y la orientacion educativa.',
                        'zh' => '研究学习理论、心理发展、心理测量学和教育指导与咨询。',
                        'ru' => 'Изучает теории обучения, психологическое развитие, психометрию и образовательное консультирование.',
                        'ur' => 'نظریات تعلم، نفسیاتی نشوونما، نفسی پیمائش اور تعلیمی رہنمائی و مشاورت کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم أصول التربية',
                        'en' => 'Department of Foundations of Education',
                        'fr' => 'Departement des Fondements de l\'Education',
                        'es' => 'Departamento de Fundamentos de la Educacion',
                        'zh' => '教育基础系',
                        'ru' => 'Кафедра основ педагогики',
                        'ur' => 'شعبہ اصول تعلیم',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم الأسس الفلسفية والاجتماعية والتاريخية للتربية وسياسات التعليم والتربية المقارنة.',
                        'en' => 'Covers philosophical, social, and historical foundations of education, educational policies, and comparative education.',
                        'fr' => 'Couvre les fondements philosophiques, sociaux et historiques de l\'education, les politiques educatives et l\'education comparee.',
                        'es' => 'Cubre los fundamentos filosoficos, sociales e historicos de la educacion, las politicas educativas y la educacion comparada.',
                        'zh' => '涵盖教育的哲学、社会和历史基础、教育政策和比较教育学。',
                        'ru' => 'Охватывает философские, социальные и исторические основы образования, образовательную политику и сравнительную педагогику.',
                        'ur' => 'تعلیم کی فلسفیانہ، سماجی اور تاریخی بنیادوں، تعلیمی پالیسیوں اور تقابلی تعلیم کا احاطہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-pharmacy' => [
                [
                    'name' => [
                        'ar' => 'قسم الكيمياء الصيدلية',
                        'en' => 'Department of Pharmaceutical Chemistry',
                        'fr' => 'Departement de Chimie Pharmaceutique',
                        'es' => 'Departamento de Quimica Farmaceutica',
                        'zh' => '药物化学系',
                        'ru' => 'Кафедра фармацевтической химии',
                        'ur' => 'شعبہ دوائی کیمیا',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بتصميم وتحليل المركبات الدوائية والكيمياء العضوية الطبية وتطوير الأدوية.',
                        'en' => 'Specializes in drug compound design and analysis, medicinal organic chemistry, and drug development.',
                        'fr' => 'Se specialise dans la conception et l\'analyse de composes medicamenteux, la chimie organique medicinale et le developpement de medicaments.',
                        'es' => 'Se especializa en el diseno y analisis de compuestos farmaceuticos, la quimica organica medicinal y el desarrollo de farmacos.',
                        'zh' => '专攻药物化合物设计与分析、药用有机化学和药物开发。',
                        'ru' => 'Специализируется на проектировании и анализе лекарственных соединений, медицинской органической химии и разработке лекарств.',
                        'ur' => 'دوائی مرکبات کے ڈیزائن و تجزیہ، طبی نامیاتی کیمیا اور ادویات کی ترقی میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الصيدلانيات',
                        'en' => 'Department of Pharmaceutics',
                        'fr' => 'Departement de Pharmaceutique',
                        'es' => 'Departamento de Farmaceutica',
                        'zh' => '药剂学系',
                        'ru' => 'Кафедра фармацевтики',
                        'ur' => 'شعبہ صیدلانیات',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم تصنيع الأشكال الصيدلانية والتكنولوجيا الصيدلانية والصيدلة الصناعية.',
                        'en' => 'Studies pharmaceutical dosage form manufacturing, pharmaceutical technology, and industrial pharmacy.',
                        'fr' => 'Etudie la fabrication de formes pharmaceutiques, la technologie pharmaceutique et la pharmacie industrielle.',
                        'es' => 'Estudia la fabricacion de formas farmaceuticas, la tecnologia farmaceutica y la farmacia industrial.',
                        'zh' => '研究药物剂型制造、制药技术和工业药学。',
                        'ru' => 'Изучает производство лекарственных форм, фармацевтическую технологию и промышленную фармацию.',
                        'ur' => 'دوائی اشکال کی تیاری، دوائی ٹیکنالوجی اور صنعتی صیدلانیات کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم العقاقير',
                        'en' => 'Department of Pharmacognosy',
                        'fr' => 'Departement de Pharmacognosie',
                        'es' => 'Departamento de Farmacognosia',
                        'zh' => '生药学系',
                        'ru' => 'Кафедра фармакогнозии',
                        'ur' => 'شعبہ عقاقیر',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بدراسة الأدوية المشتقة من مصادر طبيعية نباتية وحيوانية ومعدنية.',
                        'en' => 'Studies drugs derived from natural plant, animal, and mineral sources.',
                        'fr' => 'Etudie les medicaments derives de sources naturelles vegetales, animales et minerales.',
                        'es' => 'Estudia los farmacos derivados de fuentes naturales vegetales, animales y minerales.',
                        'zh' => '研究来源于天然植物、动物和矿物的药物。',
                        'ru' => 'Изучает лекарства, полученные из природных растительных, животных и минеральных источников.',
                        'ur' => 'قدرتی نباتاتی، حیوانی اور معدنی ذرائع سے حاصل ہونے والی ادویات کا مطالعہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم الأدوية والسموم',
                        'en' => 'Department of Pharmacology and Toxicology',
                        'fr' => 'Departement de Pharmacologie et Toxicologie',
                        'es' => 'Departamento de Farmacologia y Toxicologia',
                        'zh' => '药理学与毒理学系',
                        'ru' => 'Кафедра фармакологии и токсикологии',
                        'ur' => 'شعبہ ادویات و سمیات',
                    ],
                    'description' => [
                        'ar' => 'يدرس القسم تأثير الأدوية على الجسم وعلم السموم والتداخلات الدوائية والأمان الدوائي.',
                        'en' => 'Studies drug effects on the body, toxicology, drug interactions, and pharmacovigilance.',
                        'fr' => 'Etudie les effets des medicaments sur le corps, la toxicologie, les interactions medicamenteuses et la pharmacovigilance.',
                        'es' => 'Estudia los efectos de los farmacos en el cuerpo, la toxicologia, las interacciones medicamentosas y la farmacovigilancia.',
                        'zh' => '研究药物对人体的作用、毒理学、药物相互作用和药物安全监测。',
                        'ru' => 'Изучает действие лекарств на организм, токсикологию, лекарственные взаимодействия и фармаконадзор.',
                        'ur' => 'ادویات کے جسم پر اثرات، سمیات، دوائی تعاملات اور ادویاتی حفاظت کا مطالعہ کرتا ہے۔',
                    ],
                ],
            ],
            'faculty-of-dentistry' => [
                [
                    'name' => [
                        'ar' => 'قسم طب الفم والأسنان',
                        'en' => 'Department of Oral Medicine',
                        'fr' => 'Departement de Medecine Buccale',
                        'es' => 'Departamento de Medicina Oral',
                        'zh' => '口腔医学系',
                        'ru' => 'Кафедра стоматологии',
                        'ur' => 'شعبہ امراض دہن و دندان',
                    ],
                    'description' => [
                        'ar' => 'يختص القسم بتشخيص وعلاج أمراض الفم والأسنان واللثة والأغشية المخاطية.',
                        'en' => 'Specializes in diagnosis and treatment of oral, dental, gum, and mucosal diseases.',
                        'fr' => 'Se specialise dans le diagnostic et le traitement des maladies buccales, dentaires et gingivales.',
                        'es' => 'Se especializa en el diagnostico y tratamiento de enfermedades orales, dentales y gingivales.',
                        'zh' => '专攻口腔、牙齿、牙龈和黏膜疾病的诊断和治疗。',
                        'ru' => 'Специализируется на диагностике и лечении заболеваний полости рта, зубов и дёсен.',
                        'ur' => 'دہن، دانتوں، مسوڑھوں اور مخاطی جھلیوں کے امراض کی تشخیص و علاج میں مہارت رکھتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم جراحة الفم والوجه والفكين',
                        'en' => 'Department of Oral and Maxillofacial Surgery',
                        'fr' => 'Departement de Chirurgie Buccale et Maxillo-faciale',
                        'es' => 'Departamento de Cirugia Oral y Maxilofacial',
                        'zh' => '口腔颌面外科系',
                        'ru' => 'Кафедра челюстно-лицевой хирургии',
                        'ur' => 'شعبہ جراحت دہن و فکین',
                    ],
                    'description' => [
                        'ar' => 'يعنى القسم بجراحات الفم والوجه والفكين بما في ذلك خلع الأسنان الجراحي وزراعة الأسنان وإصابات الوجه.',
                        'en' => 'Covers oral and maxillofacial surgeries including surgical extractions, dental implants, and facial trauma.',
                        'fr' => 'Couvre les chirurgies buccales et maxillo-faciales, y compris les extractions chirurgicales, les implants et les traumatismes faciaux.',
                        'es' => 'Cubre las cirugias orales y maxilofaciales, incluyendo extracciones quirurgicas, implantes dentales y traumatismos faciales.',
                        'zh' => '涵盖口腔颌面外科手术，包括外科拔牙、种植牙和面部创伤。',
                        'ru' => 'Охватывает челюстно-лицевую хирургию, включая хирургические удаления, зубные имплантаты и лицевые травмы.',
                        'ur' => 'جراحی اخراج، دانتوں کی پیوند کاری اور چہرے کی چوٹوں سمیت دہن و فکین کی جراحیوں کا احاطہ کرتا ہے۔',
                    ],
                ],
                [
                    'name' => [
                        'ar' => 'قسم التقويم',
                        'en' => 'Department of Orthodontics',
                        'fr' => 'Departement d\'Orthodontie',
                        'es' => 'Departamento de Ortodoncia',
                        'zh' => '正畸科',
                        'ru' => 'Кафедра ортодонтии',
                        'ur' => 'شعبہ تقویم الاسنان',
                    ],
                    'description' => [
                        'ar' => 'يتناول القسم تشخيص وعلاج سوء إطباق الأسنان وتشوهات الفكين باستخدام أحدث التقنيات التقويمية.',
                        'en' => 'Covers diagnosis and treatment of dental malocclusion and jaw deformities using the latest orthodontic techniques.',
                        'fr' => 'Couvre le diagnostic et le traitement des malocclusions dentaires et des deformites de la machoire avec les techniques orthodontiques les plus recentes.',
                        'es' => 'Cubre el diagnostico y tratamiento de la maloclusion dental y las deformidades mandibulares con las tecnicas ortodonticas mas recientes.',
                        'zh' => '使用最新的正畸技术涵盖牙齿咬合不正和颌骨畸形的诊断和治疗。',
                        'ru' => 'Охватывает диагностику и лечение зубочелюстных аномалий и деформаций челюстей с использованием новейших ортодонтических методов.',
                        'ur' => 'جدید ترین آرتھوڈونٹک تکنیکوں کا استعمال کرتے ہوئے دانتوں کی خرابی اور جبڑے کی بد شکلی کی تشخیص و علاج کا احاطہ کرتا ہے۔',
                    ],
                ],
            ],
        ];

        $order = 1;
        foreach ($departmentsByFaculty as $facultySlug => $departments) {
            $faculty = Faculty::where('slug', $facultySlug)->first();
            if (! $faculty) {
                continue;
            }

            foreach ($departments as $deptData) {
                $dept = new Department();
                $dept->slug = \Illuminate\Support\Str::slug($deptData['name']['en']);
                $dept->name = $deptData['name'];
                $dept->description = $deptData['description'] ?? null;
                $dept->faculty_id = $faculty->id;
                $dept->order = $order++;
                $dept->is_published = true;
                $dept->save();
            }
        }
    }
}
