<?php

namespace Database\Seeders;

use App\Models\Faculty;
use Illuminate\Database\Seeder;

class FacultySeeder extends Seeder
{
    public function run(): void
    {
        $faculties = [
            [
                'slug' => 'faculty-of-sharia-and-law',
                'name' => [
                    'ar' => 'كلية الشريعة والقانون',
                    'en' => 'Faculty of Sharia and Law',
                    'fr' => 'Faculte de la Charia et du Droit',
                    'es' => 'Facultad de Sharia y Derecho',
                    'zh' => '伊斯兰法与法律学院',
                    'ru' => 'Факультет шариата и права',
                    'ur' => 'شریعہ اور قانون کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1930,
                'description' => [
                    'ar' => 'كلية الشريعة والقانون من الكليات المؤسسة لجامعة الأزهر، تأسست عام 1930م وتجمع بين دراسة الفقه الإسلامي بمذاهبه المختلفة والقانون الوضعي المعاصر. لها فروع في القاهرة وطنطا ودمياط وأسيوط. تخرج الكلية قضاة ومحامين ومفتين قادرين على الربط بين الشريعة الإسلامية والأنظمة القانونية الحديثة.',
                    'en' => 'The Faculty of Sharia and Law is one of Al-Azhar University\'s founding faculties, established in 1930. It combines the study of Islamic jurisprudence across various schools of thought with contemporary positive law. With branches in Cairo, Tanta, Damietta, and Assiut, the faculty graduates judges, lawyers, and muftis capable of bridging Islamic Sharia and modern legal systems.',
                    'fr' => 'La Faculte de la Charia et du Droit est l\'une des facultes fondatrices de l\'Universite d\'Al-Azhar, creee en 1930. Elle combine l\'etude de la jurisprudence islamique avec le droit positif contemporain, formant des juges, avocats et muftis.',
                    'es' => 'La Facultad de Sharia y Derecho es una de las facultades fundadoras de la Universidad de Al-Azhar, establecida en 1930. Combina el estudio de la jurisprudencia islamica con el derecho positivo contemporaneo.',
                    'zh' => '伊斯兰法与法律学院是艾资哈尔大学的创始学院之一，成立于1930年。该学院将伊斯兰教法学与现代法律相结合，培养法官、律师和教法顾问。',
                    'ru' => 'Факультет шариата и права является одним из основателей университета Аль-Азхар, основан в 1930 году. Он сочетает изучение исламского правоведения с современным позитивным правом.',
                    'ur' => 'شریعہ اور قانون کی فیکلٹی الازہر یونیورسٹی کی بانی فیکلٹیوں میں سے ایک ہے، جو 1930 میں قائم ہوئی۔ یہ اسلامی فقہ اور جدید قانون کی تعلیم کو یکجا کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نحرص في كلية الشريعة والقانون على تأهيل خريجين يجمعون بين الفقه الإسلامي العميق والمعرفة القانونية المعاصرة لخدمة المجتمع.',
                    'en' => 'At the Faculty of Sharia and Law, we are dedicated to qualifying graduates who combine deep Islamic jurisprudence with contemporary legal knowledge to serve society.',
                    'fr' => 'Nous nous engageons a former des diplomes combinant jurisprudence islamique et connaissances juridiques contemporaines.',
                    'es' => 'Nos dedicamos a formar graduados que combinen la jurisprudencia islamica con el conocimiento juridico contemporaneo.',
                    'zh' => '我们致力于培养兼具伊斯兰教法和现代法律知识的毕业生，为社会服务。',
                    'ru' => 'Мы стремимся готовить выпускников, сочетающих глубокое знание исламского права с современными юридическими знаниями.',
                    'ur' => 'ہم ایسے فارغ التحصیل افراد تیار کرنے کے لیے پرعزم ہیں جو اسلامی فقہ اور جدید قانونی علم کو یکجا کریں۔',
                ],
                'is_published' => true,
                'order' => 1,
            ],
            [
                'slug' => 'faculty-of-theology',
                'name' => [
                    'ar' => 'كلية أصول الدين',
                    'en' => 'Faculty of Theology (Usul al-Din)',
                    'fr' => 'Faculte de Theologie',
                    'es' => 'Facultad de Teologia',
                    'zh' => '宗教原理学院',
                    'ru' => 'Факультет теологии',
                    'ur' => 'اصول الدین کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1930,
                'description' => [
                    'ar' => 'تعد كلية أصول الدين من أعرق كليات جامعة الأزهر، تأسست عام 1930م وتختص بدراسة العقيدة الإسلامية والفلسفة الإسلامية والتفسير والحديث والدعوة. لها فروع في القاهرة وطنطا والمنصورة والزقازيق والمنوفية وأسيوط. تهدف إلى إعداد علماء متخصصين في أصول الدين.',
                    'en' => 'The Faculty of Theology is one of the oldest faculties at Al-Azhar University, established in 1930. It specializes in Islamic creed, Islamic philosophy, Quranic exegesis, Hadith, and Da\'wa. With branches in Cairo, Tanta, Mansoura, Zagazig, Menoufia, and Assiut, it aims to prepare specialized scholars in theology.',
                    'fr' => 'La Faculte de Theologie est l\'une des plus anciennes facultes de l\'Universite d\'Al-Azhar, fondee en 1930. Elle se specialise dans la croyance islamique, la philosophie, l\'exegese coranique et le hadith.',
                    'es' => 'La Facultad de Teologia es una de las mas antiguas de la Universidad de Al-Azhar, fundada en 1930. Se especializa en credo islamico, filosofia islamica, exegesis coranica y hadiz.',
                    'zh' => '宗教原理学院是艾资哈尔大学最古老的学院之一，成立于1930年。专攻伊斯兰信条、伊斯兰哲学、古兰经注释和圣训学。',
                    'ru' => 'Факультет теологии — один из старейших в университете Аль-Азхар, основан в 1930 году. Специализируется на исламском вероучении, философии, тафсире и хадисоведении.',
                    'ur' => 'اصول الدین کی فیکلٹی الازہر یونیورسٹی کی قدیم ترین فیکلٹیوں میں سے ایک ہے، جو 1930 میں قائم ہوئی۔ اسلامی عقیدہ، فلسفہ، تفسیر اور حدیث میں مہارت رکھتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نسعى في كلية أصول الدين إلى تخريج علماء يحملون رسالة الوسطية والاعتدال، ويدافعون عن صحيح الإسلام بالعلم والمعرفة.',
                    'en' => 'At the Faculty of Theology, we strive to graduate scholars who carry the message of moderation and defend authentic Islam through knowledge and scholarship.',
                    'fr' => 'Nous formons des erudits porteurs du message de moderation et defenseurs de l\'islam authentique par le savoir.',
                    'es' => 'Formamos eruditos portadores del mensaje de moderacion y defensores del islam autentico a traves del conocimiento.',
                    'zh' => '我们培养承载中正温和信息的学者，以知识和学术捍卫真正的伊斯兰教。',
                    'ru' => 'Мы готовим учёных, несущих послание умеренности и защищающих подлинный ислам знанием.',
                    'ur' => 'ہم ایسے علماء تیار کرتے ہیں جو اعتدال کا پیغام لے کر چلیں اور علم و معرفت سے صحیح اسلام کا دفاع کریں۔',
                ],
                'is_published' => true,
                'order' => 2,
            ],
            [
                'slug' => 'faculty-of-arabic-language',
                'name' => [
                    'ar' => 'كلية اللغة العربية',
                    'en' => 'Faculty of Arabic Language',
                    'fr' => 'Faculte de Langue Arabe',
                    'es' => 'Facultad de Lengua Arabe',
                    'zh' => '阿拉伯语学院',
                    'ru' => 'Факультет арабского языка',
                    'ur' => 'عربی زبان کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1930,
                'description' => [
                    'ar' => 'كلية اللغة العربية من الكليات الثلاث المؤسسة لجامعة الأزهر عام 1930م. تختص بدراسة النحو والصرف والبلاغة والأدب العربي والنقد الأدبي. لها فروع في القاهرة والمنوفية والمنصورة والزقازيق وجرجا وأسيوط وإيتاي البارود. تعد المرجع الأول في العالم الإسلامي للحفاظ على اللغة العربية.',
                    'en' => 'The Faculty of Arabic Language is one of the three founding faculties of Al-Azhar University in 1930. It specializes in grammar, morphology, rhetoric, Arabic literature, and literary criticism. With branches across seven governorates, it is the foremost reference in the Islamic world for preserving the Arabic language.',
                    'fr' => 'La Faculte de Langue Arabe est l\'une des trois facultes fondatrices en 1930. Elle se specialise dans la grammaire, la rhetorique et la litterature arabe.',
                    'es' => 'La Facultad de Lengua Arabe es una de las tres facultades fundadoras en 1930. Se especializa en gramatica, retorica y literatura arabe.',
                    'zh' => '阿拉伯语学院是1930年艾资哈尔大学三个创始学院之一。专攻语法、修辞和阿拉伯文学。',
                    'ru' => 'Факультет арабского языка — один из трёх основателей университета в 1930 году. Специализируется на грамматике, риторике и арабской литературе.',
                    'ur' => 'عربی زبان کی فیکلٹی 1930 میں الازہر یونیورسٹی کی تین بانی فیکلٹیوں میں سے ایک ہے۔ نحو، بلاغت اور عربی ادب میں مہارت رکھتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'اللغة العربية هي لغة القرآن الكريم، ونحن في هذه الكلية العريقة نعمل على الحفاظ عليها وتطوير مناهج تعليمها لتواكب العصر.',
                    'en' => 'Arabic is the language of the Holy Quran, and at this prestigious faculty we work to preserve it and develop its teaching methodologies to keep pace with the times.',
                    'fr' => 'L\'arabe est la langue du Saint Coran, et nous travaillons a la preserver et developper ses methodes d\'enseignement.',
                    'es' => 'El arabe es la lengua del Sagrado Coran, y trabajamos para preservarla y desarrollar sus metodologias de ensenanza.',
                    'zh' => '阿拉伯语是《古兰经》的语言，我们致力于保护它并发展其教学方法。',
                    'ru' => 'Арабский — язык Священного Корана, и мы работаем над его сохранением и развитием методик преподавания.',
                    'ur' => 'عربی قرآن مجید کی زبان ہے، اور ہم اس کے تحفظ اور تدریسی طریقہ کار کی ترقی کے لیے کام کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 3,
            ],
            [
                'slug' => 'faculty-of-islamic-dawa',
                'name' => [
                    'ar' => 'كلية الدعوة الإسلامية',
                    'en' => 'Faculty of Islamic Da\'wa',
                    'fr' => 'Faculte de la Predication Islamique',
                    'es' => 'Facultad de Predicacion Islamica',
                    'zh' => '伊斯兰宣教学院',
                    'ru' => 'Факультет исламского призыва',
                    'ur' => 'اسلامی دعوت کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1978,
                'description' => [
                    'ar' => 'تأسست كلية الدعوة الإسلامية عام 1978م بالقاهرة لإعداد دعاة متميزين قادرين على نشر رسالة الإسلام الصحيحة بأساليب عصرية. تدرس الكلية فنون الخطابة والإعلام الإسلامي وعلم النفس الدعوي والأديان المقارنة.',
                    'en' => 'The Faculty of Islamic Da\'wa was established in 1978 in Cairo to prepare distinguished preachers capable of spreading the true message of Islam through modern methods. The faculty teaches rhetoric, Islamic media, psychology of preaching, and comparative religion.',
                    'fr' => 'La Faculte de la Predication Islamique a ete fondee en 1978 au Caire pour former des predicateurs distingues capables de diffuser le message de l\'islam.',
                    'es' => 'La Facultad de Predicacion Islamica fue fundada en 1978 en El Cairo para formar predicadores capaces de difundir el mensaje del islam.',
                    'zh' => '伊斯兰宣教学院于1978年在开罗成立，培养能够以现代方式传播伊斯兰真正信息的杰出传教士。',
                    'ru' => 'Факультет исламского призыва был основан в 1978 году в Каире для подготовки проповедников, способных распространять истинное послание ислама.',
                    'ur' => 'اسلامی دعوت کی فیکلٹی 1978 میں قاہرہ میں قائم ہوئی تاکہ جدید طریقوں سے اسلام کا صحیح پیغام پھیلانے والے داعی تیار کیے جائیں۔',
                ],
                'dean_message' => [
                    'ar' => 'نعد دعاة يحملون رسالة الإسلام الوسطي إلى العالم بلغة العصر وأساليبه الحديثة.',
                    'en' => 'We prepare preachers who carry the message of moderate Islam to the world using contemporary language and modern methods.',
                    'fr' => 'Nous formons des predicateurs porteurs du message de l\'islam modere dans le monde.',
                    'es' => 'Formamos predicadores que llevan el mensaje del islam moderado al mundo.',
                    'zh' => '我们培养以当代语言和现代方式向世界传递温和伊斯兰信息的传教士。',
                    'ru' => 'Мы готовим проповедников, несущих послание умеренного ислама миру.',
                    'ur' => 'ہم ایسے داعی تیار کرتے ہیں جو جدید زبان اور طریقوں سے معتدل اسلام کا پیغام دنیا تک پہنچائیں۔',
                ],
                'is_published' => true,
                'order' => 4,
            ],
            [
                'slug' => 'faculty-of-medicine',
                'name' => [
                    'ar' => 'كلية الطب',
                    'en' => 'Faculty of Medicine',
                    'fr' => 'Faculte de Medecine',
                    'es' => 'Facultad de Medicina',
                    'zh' => '医学院',
                    'ru' => 'Медицинский факультет',
                    'ur' => 'طب کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'أنشئت كلية الطب بجامعة الأزهر عام 1961م ضمن القانون رقم 103 لتطوير الأزهر. لها فروع في القاهرة (بنين وبنات) ودمياط وأسيوط. تقدم الكلية برنامجاً طبياً متكاملاً يجمع بين العلوم الطبية الحديثة والقيم الإسلامية والأخلاق الطبية. تضم مستشفيات جامعية تخدم ملايين المرضى سنوياً.',
                    'en' => 'The Faculty of Medicine was established in 1961 under Law No. 103 for Al-Azhar\'s modernization. With branches in Cairo (boys and girls), Damietta, and Assiut, it offers a comprehensive medical program combining modern medical sciences with Islamic values and medical ethics, and includes university hospitals serving millions annually.',
                    'fr' => 'La Faculte de Medecine a ete creee en 1961 dans le cadre de la loi 103 de modernisation. Elle offre un programme medical complet alliant sciences medicales modernes et valeurs islamiques.',
                    'es' => 'La Facultad de Medicina fue establecida en 1961 bajo la Ley 103 de modernizacion. Ofrece un programa medico integral que combina ciencias medicas modernas con valores islamicos.',
                    'zh' => '医学院于1961年根据第103号现代化法令成立。提供将现代医学与伊斯兰价值观和医学伦理相结合的综合医学课程。',
                    'ru' => 'Медицинский факультет был основан в 1961 году по Закону № 103 о модернизации. Предлагает комплексную медицинскую программу, сочетающую современные медицинские науки с исламскими ценностями.',
                    'ur' => 'طب کی فیکلٹی 1961 میں قانون نمبر 103 کے تحت قائم ہوئی۔ جدید طبی علوم اور اسلامی اقدار کو یکجا کرنے والا جامع طبی پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نسعى لتخريج أطباء يجمعون بين التميز العلمي والالتزام بالأخلاق الطبية الإسلامية لخدمة المجتمع والإنسانية.',
                    'en' => 'We strive to graduate physicians who combine scientific excellence with commitment to Islamic medical ethics to serve society and humanity.',
                    'fr' => 'Nous formons des medecins alliant excellence scientifique et ethique medicale islamique.',
                    'es' => 'Formamos medicos que combinan la excelencia cientifica con la etica medica islamica.',
                    'zh' => '我们培养兼具科学卓越与伊斯兰医学伦理的医生，服务社会和人类。',
                    'ru' => 'Мы готовим врачей, сочетающих научное мастерство с исламской медицинской этикой.',
                    'ur' => 'ہم ایسے ڈاکٹر تیار کرتے ہیں جو سائنسی فضیلت اور اسلامی طبی اخلاقیات کو یکجا کریں۔',
                ],
                'is_published' => true,
                'order' => 5,
            ],
            [
                'slug' => 'faculty-of-dentistry',
                'name' => [
                    'ar' => 'كلية طب الأسنان',
                    'en' => 'Faculty of Dentistry',
                    'fr' => 'Faculte de Medecine Dentaire',
                    'es' => 'Facultad de Odontologia',
                    'zh' => '牙科学院',
                    'ru' => 'Стоматологический факультет',
                    'ur' => 'دندان سازی کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1974,
                'description' => [
                    'ar' => 'كلية طب الأسنان بجامعة الأزهر تأسست عام 1974م ولها فروع في القاهرة (بنين وبنات) وأسيوط. تقدم برنامجاً متكاملاً في طب وجراحة الفم والأسنان وتضم عيادات ومختبرات حديثة لتدريب الطلاب.',
                    'en' => 'The Faculty of Dentistry at Al-Azhar University was established in 1974 with branches in Cairo (boys and girls) and Assiut. It offers a comprehensive program in oral medicine and dental surgery with modern clinics and laboratories.',
                    'fr' => 'La Faculte de Medecine Dentaire a ete fondee en 1974 et offre un programme complet en medecine buccale et chirurgie dentaire.',
                    'es' => 'La Facultad de Odontologia fue fundada en 1974 y ofrece un programa integral en medicina oral y cirugia dental.',
                    'zh' => '牙科学院成立于1974年，提供口腔医学和牙科外科的综合课程。',
                    'ru' => 'Стоматологический факультет был основан в 1974 году и предлагает комплексную программу по стоматологии и челюстно-лицевой хирургии.',
                    'ur' => 'دندان سازی کی فیکلٹی 1974 میں قائم ہوئی اور زبانی طب اور دندان سازی کا جامع پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نسعى لتخريج أطباء أسنان متميزين يقدمون أفضل الخدمات العلاجية للمجتمع.',
                    'en' => 'We strive to graduate distinguished dentists who provide the best therapeutic services to the community.',
                    'fr' => 'Nous formons des dentistes d\'excellence pour servir la communaute.',
                    'es' => 'Formamos dentistas distinguidos que brindan los mejores servicios a la comunidad.',
                    'zh' => '我们培养为社区提供最佳治疗服务的优秀牙医。',
                    'ru' => 'Мы готовим выдающихся стоматологов для служения обществу.',
                    'ur' => 'ہم معاشرے کو بہترین علاج کی خدمات فراہم کرنے والے ممتاز دندان ساز تیار کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 6,
            ],
            [
                'slug' => 'faculty-of-pharmacy',
                'name' => [
                    'ar' => 'كلية الصيدلة',
                    'en' => 'Faculty of Pharmacy',
                    'fr' => 'Faculte de Pharmacie',
                    'es' => 'Facultad de Farmacia',
                    'zh' => '药学院',
                    'ru' => 'Фармацевтический факультет',
                    'ur' => 'فارمیسی کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1974,
                'description' => [
                    'ar' => 'تأسست كلية الصيدلة بجامعة الأزهر عام 1974م ولها فروع في القاهرة (بنين وبنات) وأسيوط. تقدم برنامجاً أكاديمياً متكاملاً في العلوم الصيدلانية يشمل الكيمياء الصيدلية والصيدلانيات والعقاقير والأدوية والسموم.',
                    'en' => 'The Faculty of Pharmacy was established in 1974 with branches in Cairo (boys and girls) and Assiut. It offers a comprehensive academic program in pharmaceutical sciences including pharmaceutical chemistry, pharmaceutics, pharmacognosy, and pharmacology.',
                    'fr' => 'La Faculte de Pharmacie a ete fondee en 1974 et offre un programme complet en sciences pharmaceutiques.',
                    'es' => 'La Facultad de Farmacia fue fundada en 1974 y ofrece un programa integral en ciencias farmaceuticas.',
                    'zh' => '药学院成立于1974年，提供药物化学、药剂学、生药学和药理学的综合课程。',
                    'ru' => 'Фармацевтический факультет был основан в 1974 году и предлагает комплексную программу по фармацевтическим наукам.',
                    'ur' => 'فارمیسی کی فیکلٹی 1974 میں قائم ہوئی اور دوائی سازی کے علوم کا جامع پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نلتزم بتخريج صيادلة أكفاء يساهمون في تطوير الصناعة الدوائية وتحسين الرعاية الصحية.',
                    'en' => 'We are committed to graduating competent pharmacists who contribute to pharmaceutical industry development and healthcare improvement.',
                    'fr' => 'Nous formons des pharmaciens competents contribuant au developpement de l\'industrie pharmaceutique.',
                    'es' => 'Formamos farmaceuticos competentes que contribuyen al desarrollo de la industria farmaceutica.',
                    'zh' => '我们致力于培养为制药工业发展和医疗保健改善做出贡献的合格药剂师。',
                    'ru' => 'Мы готовим компетентных фармацевтов, вносящих вклад в развитие фармацевтической отрасли.',
                    'ur' => 'ہم فارماسیوٹیکل صنعت کی ترقی میں حصہ ڈالنے والے قابل فارماسسٹ تیار کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 7,
            ],
            [
                'slug' => 'faculty-of-engineering',
                'name' => [
                    'ar' => 'كلية الهندسة',
                    'en' => 'Faculty of Engineering',
                    'fr' => 'Faculte d\'Ingenierie',
                    'es' => 'Facultad de Ingenieria',
                    'zh' => '工程学院',
                    'ru' => 'Инженерный факультет',
                    'ur' => 'انجینئرنگ کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'تأسست كلية الهندسة بجامعة الأزهر عام 1961م ضمن القانون 103 ولها فروع في القاهرة وقنا. تضم أقساماً في الهندسة المدنية والمعمارية والكهربائية والميكانيكية وهندسة الحاسبات. صُنفت في تصنيف THE 2025 في المرتبة 501-600 عالمياً.',
                    'en' => 'The Faculty of Engineering was established in 1961 under Law 103 with branches in Cairo and Qena. It includes departments of civil, architectural, electrical, mechanical, and computer engineering. Ranked 501-600 globally in the THE World University Rankings 2025.',
                    'fr' => 'La Faculte d\'Ingenierie a ete fondee en 1961 et comprend des departements de genie civil, electrique, mecanique et informatique. Classee 501-600 mondial par THE 2025.',
                    'es' => 'La Facultad de Ingenieria fue fundada en 1961 e incluye departamentos de ingenieria civil, electrica, mecanica e informatica. Clasificada 501-600 mundialmente por THE 2025.',
                    'zh' => '工程学院成立于1961年，设有土木、建筑、电气、机械和计算机工程系。2025年THE世界大学排名501-600。',
                    'ru' => 'Инженерный факультет основан в 1961 году и включает кафедры гражданского, электрического, механического и компьютерного инжиниринга. Рейтинг THE 2025: 501-600.',
                    'ur' => 'انجینئرنگ کی فیکلٹی 1961 میں قائم ہوئی اور سول، برقی، مکینیکل اور کمپیوٹر انجینئرنگ کے شعبے شامل ہیں۔ THE 2025 میں 501-600 عالمی درجہ بندی۔',
                ],
                'dean_message' => [
                    'ar' => 'نعمل على تأهيل مهندسين قادرين على مواجهة تحديات العصر التقنية مع التمسك بالقيم الأخلاقية والمهنية.',
                    'en' => 'We work to qualify engineers capable of facing modern technological challenges while upholding ethical and professional values.',
                    'fr' => 'Nous formons des ingenieurs capables de relever les defis technologiques modernes tout en respectant les valeurs ethiques.',
                    'es' => 'Formamos ingenieros capaces de enfrentar los desafios tecnologicos modernos manteniendo los valores eticos.',
                    'zh' => '我们培养能够应对现代技术挑战同时坚持道德和专业价值观的工程师。',
                    'ru' => 'Мы готовим инженеров, способных решать современные технологические задачи, соблюдая этические ценности.',
                    'ur' => 'ہم اخلاقی اقدار کو برقرار رکھتے ہوئے جدید تکنیکی چیلنجوں کا مقابلہ کرنے والے انجینئر تیار کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 8,
            ],
            [
                'slug' => 'faculty-of-science',
                'name' => [
                    'ar' => 'كلية العلوم',
                    'en' => 'Faculty of Science',
                    'fr' => 'Faculte des Sciences',
                    'es' => 'Facultad de Ciencias',
                    'zh' => '理学院',
                    'ru' => 'Факультет наук',
                    'ur' => 'سائنس کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'كلية العلوم بجامعة الأزهر تأسست عام 1961م ولها فروع في القاهرة وأسيوط. تشمل أقسام الرياضيات والفيزياء والكيمياء والأحياء والجيولوجيا. تسهم في البحث العلمي والابتكار وتخريج باحثين متميزين.',
                    'en' => 'The Faculty of Science was established in 1961 with branches in Cairo and Assiut. It includes departments of Mathematics, Physics, Chemistry, Biology, and Geology, contributing to scientific research, innovation, and graduating distinguished researchers.',
                    'fr' => 'La Faculte des Sciences a ete fondee en 1961 et comprend les departements de mathematiques, physique, chimie, biologie et geologie.',
                    'es' => 'La Facultad de Ciencias fue fundada en 1961 e incluye departamentos de matematicas, fisica, quimica, biologia y geologia.',
                    'zh' => '理学院成立于1961年，设有数学、物理、化学、生物和地质系。',
                    'ru' => 'Факультет наук основан в 1961 году и включает кафедры математики, физики, химии, биологии и геологии.',
                    'ur' => 'سائنس کی فیکلٹی 1961 میں قائم ہوئی اور ریاضی، طبیعیات، کیمیا، حیاتیات اور ارضیات کے شعبے شامل ہیں۔',
                ],
                'dean_message' => [
                    'ar' => 'نؤمن بأن العلم الحقيقي يقود إلى معرفة الله، ونسعى لتحقيق التميز في البحث العلمي وخدمة المجتمع.',
                    'en' => 'We believe that true science leads to knowing God, and we strive to achieve excellence in scientific research and community service.',
                    'fr' => 'Nous croyons que la vraie science mene a la connaissance de Dieu et nous visons l\'excellence en recherche scientifique.',
                    'es' => 'Creemos que la verdadera ciencia conduce al conocimiento de Dios y buscamos la excelencia en la investigacion cientifica.',
                    'zh' => '我们相信真正的科学引导人认识真主，我们追求科学研究和社会服务的卓越。',
                    'ru' => 'Мы верим, что истинная наука ведёт к познанию Бога, и стремимся к совершенству в научных исследованиях.',
                    'ur' => 'ہمارا ایمان ہے کہ حقیقی سائنس اللہ کی معرفت کی طرف لے جاتی ہے، اور ہم سائنسی تحقیق میں فضیلت حاصل کرنے کی کوشش کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 9,
            ],
            [
                'slug' => 'faculty-of-commerce',
                'name' => [
                    'ar' => 'كلية التجارة',
                    'en' => 'Faculty of Commerce',
                    'fr' => 'Faculte de Commerce',
                    'es' => 'Facultad de Comercio',
                    'zh' => '商学院',
                    'ru' => 'Коммерческий факультет',
                    'ur' => 'تجارت کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'تأسست كلية التجارة بجامعة الأزهر عام 1961م ولها فروع متعددة. تقدم برامج في المحاسبة وإدارة الأعمال والاقتصاد والإحصاء. تتميز بدمج مبادئ الاقتصاد الإسلامي والمعاملات المالية الإسلامية في مناهجها.',
                    'en' => 'The Faculty of Commerce was established in 1961 with multiple branches, offering programs in accounting, business administration, economics, and statistics. It is distinguished by integrating Islamic economics and Islamic financial transactions into its curricula.',
                    'fr' => 'La Faculte de Commerce a ete fondee en 1961 et propose des programmes en comptabilite, gestion, economie et statistiques, integrant l\'economie islamique.',
                    'es' => 'La Facultad de Comercio fue fundada en 1961 y ofrece programas en contabilidad, administracion de empresas, economia y estadistica, integrando la economia islamica.',
                    'zh' => '商学院成立于1961年，提供会计、工商管理、经济和统计课程，并将伊斯兰经济学纳入课程体系。',
                    'ru' => 'Коммерческий факультет основан в 1961 году и предлагает программы по бухгалтерскому учёту, менеджменту, экономике и статистике с интеграцией исламской экономики.',
                    'ur' => 'تجارت کی فیکلٹی 1961 میں قائم ہوئی اور اکاؤنٹنگ، بزنس ایڈمنسٹریشن، اقتصادیات اور شماریات کے پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نعد خريجين متميزين في مجالات المال والأعمال يجمعون بين الكفاءة المهنية والالتزام بأحكام المعاملات الإسلامية.',
                    'en' => 'We prepare distinguished graduates in finance and business who combine professional competence with adherence to Islamic transaction principles.',
                    'fr' => 'Nous formons des diplomes d\'excellence en finance et commerce, alliant competence professionnelle et principes islamiques.',
                    'es' => 'Formamos graduados distinguidos en finanzas y negocios que combinan competencia profesional con principios islamicos.',
                    'zh' => '我们培养兼具专业能力和伊斯兰交易原则的杰出金融和商业毕业生。',
                    'ru' => 'Мы готовим выпускников в области финансов и бизнеса, сочетающих профессионализм с исламскими принципами.',
                    'ur' => 'ہم مالیات اور کاروبار میں ایسے ممتاز فارغ التحصیل تیار کرتے ہیں جو پیشہ ورانہ قابلیت اور اسلامی اصولوں کو یکجا کریں۔',
                ],
                'is_published' => true,
                'order' => 10,
            ],
            [
                'slug' => 'faculty-of-education',
                'name' => [
                    'ar' => 'كلية التربية',
                    'en' => 'Faculty of Education',
                    'fr' => 'Faculte d\'Education',
                    'es' => 'Facultad de Educacion',
                    'zh' => '教育学院',
                    'ru' => 'Педагогический факультет',
                    'ur' => 'تعلیم کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'تأسست كلية التربية بجامعة الأزهر عام 1961م ولها فروع في القاهرة وأسيوط. تجمع بين العلوم التربوية الحديثة والقيم الإسلامية في إعداد المعلم الأزهري المتميز.',
                    'en' => 'The Faculty of Education was established in 1961 with branches in Cairo and Assiut. It combines modern educational sciences with Islamic values in preparing the distinguished Azhari teacher.',
                    'fr' => 'La Faculte d\'Education a ete fondee en 1961 et combine les sciences educatives modernes avec les valeurs islamiques.',
                    'es' => 'La Facultad de Educacion fue fundada en 1961 y combina las ciencias educativas modernas con los valores islamicos.',
                    'zh' => '教育学院成立于1961年，将现代教育科学与伊斯兰价值观相结合。',
                    'ru' => 'Педагогический факультет основан в 1961 году и сочетает современные образовательные науки с исламскими ценностями.',
                    'ur' => 'تعلیم کی فیکلٹی 1961 میں قائم ہوئی اور جدید تعلیمی علوم کو اسلامی اقدار کے ساتھ جوڑتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'التعليم رسالة سامية، ونحن نعد معلمين يجمعون بين الكفاءة التربوية والقدوة الحسنة.',
                    'en' => 'Education is a noble mission, and we prepare teachers who combine educational competence with being role models.',
                    'fr' => 'L\'education est une noble mission, et nous formons des enseignants exemplaires et competents.',
                    'es' => 'La educacion es una noble mision, y formamos maestros que combinan competencia con ser modelos a seguir.',
                    'zh' => '教育是崇高的使命，我们培养兼具教育能力和榜样作用的教师。',
                    'ru' => 'Образование — благородная миссия, и мы готовим учителей, сочетающих компетентность с примерным поведением.',
                    'ur' => 'تعلیم ایک عظیم مشن ہے، اور ہم ایسے اساتذہ تیار کرتے ہیں جو تعلیمی قابلیت اور نمونہ عمل کو یکجا کریں۔',
                ],
                'is_published' => true,
                'order' => 11,
            ],
            [
                'slug' => 'faculty-of-languages-and-translation',
                'name' => [
                    'ar' => 'كلية اللغات والترجمة',
                    'en' => 'Faculty of Languages and Translation',
                    'fr' => 'Faculte des Langues et de la Traduction',
                    'es' => 'Facultad de Lenguas y Traduccion',
                    'zh' => '语言与翻译学院',
                    'ru' => 'Факультет языков и перевода',
                    'ur' => 'زبانوں اور ترجمے کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1970,
                'description' => [
                    'ar' => 'كلية اللغات والترجمة بجامعة الأزهر بالقاهرة تأسست لتدريس اللغات الأجنبية بما في ذلك الإنجليزية والفرنسية وغيرها، مع التركيز على الترجمة الإسلامية وترجمة المصادر الشرعية.',
                    'en' => 'The Faculty of Languages and Translation in Cairo was established to teach foreign languages including English, French, and others, with focus on Islamic translation and translating Islamic sources.',
                    'fr' => 'La Faculte des Langues et de la Traduction enseigne les langues etrangeres avec un accent sur la traduction islamique.',
                    'es' => 'La Facultad de Lenguas y Traduccion ensena idiomas extranjeros con enfasis en la traduccion islamica.',
                    'zh' => '语言与翻译学院教授外语，重点关注伊斯兰翻译和伊斯兰文献翻译。',
                    'ru' => 'Факультет языков и перевода обучает иностранным языкам с акцентом на исламский перевод.',
                    'ur' => 'زبانوں اور ترجمے کی فیکلٹی غیر ملکی زبانیں پڑھاتی ہے اور اسلامی ترجمے پر خصوصی توجہ دیتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نسعى لبناء جسور التواصل بين الثقافات من خلال تأهيل مترجمين أكفاء قادرين على نقل رسالة الأزهر الوسطية إلى العالم.',
                    'en' => 'We strive to build bridges of communication between cultures by qualifying competent translators capable of conveying Al-Azhar\'s moderate message to the world.',
                    'fr' => 'Nous construisons des ponts entre les cultures en formant des traducteurs competents.',
                    'es' => 'Construimos puentes entre culturas formando traductores competentes.',
                    'zh' => '我们通过培养合格的翻译人才在文化之间架起沟通的桥梁。',
                    'ru' => 'Мы строим мосты между культурами, готовя компетентных переводчиков.',
                    'ur' => 'ہم قابل مترجمین تیار کر کے ثقافتوں کے درمیان رابطے کے پل تعمیر کرتے ہیں۔',
                ],
                'is_published' => true,
                'order' => 12,
            ],
            [
                'slug' => 'faculty-of-islamic-studies',
                'name' => [
                    'ar' => 'كلية الدراسات الإسلامية والعربية',
                    'en' => 'Faculty of Islamic and Arabic Studies',
                    'fr' => 'Faculte des Etudes Islamiques et Arabes',
                    'es' => 'Facultad de Estudios Islamicos y Arabes',
                    'zh' => '伊斯兰与阿拉伯研究学院',
                    'ru' => 'Факультет исламских и арабских исследований',
                    'ur' => 'اسلامی اور عربی مطالعات کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1961,
                'description' => [
                    'ar' => 'كلية الدراسات الإسلامية والعربية من الكليات الشرعية المتميزة في جامعة الأزهر ولها فروع متعددة في القاهرة ومحافظات مصر. تقدم دراسات شاملة في العلوم الإسلامية تشمل الفقه وأصوله والتفسير والحديث والعقيدة والدعوة.',
                    'en' => 'The Faculty of Islamic and Arabic Studies is a distinguished Islamic faculty at Al-Azhar University with multiple branches across Cairo and Egypt\'s governorates. It offers comprehensive studies in Islamic sciences including jurisprudence, exegesis, hadith, creed, and da\'wa.',
                    'fr' => 'La Faculte des Etudes Islamiques et Arabes offre des etudes completes en sciences islamiques incluant la jurisprudence, l\'exegese et le hadith.',
                    'es' => 'La Facultad de Estudios Islamicos y Arabes ofrece estudios integrales en ciencias islamicas incluyendo jurisprudencia, exegesis y hadiz.',
                    'zh' => '伊斯兰与阿拉伯研究学院提供全面的伊斯兰科学研究，包括教法、注释和圣训。',
                    'ru' => 'Факультет исламских и арабских исследований предлагает комплексное изучение исламских наук.',
                    'ur' => 'اسلامی اور عربی مطالعات کی فیکلٹی اسلامی علوم کا جامع مطالعہ پیش کرتی ہے جس میں فقہ، تفسیر اور حدیث شامل ہیں۔',
                ],
                'dean_message' => [
                    'ar' => 'نسعى لتقديم رؤية إسلامية شاملة ومعتدلة تجمع بين التراث العلمي الأصيل ومتطلبات العصر الحديث.',
                    'en' => 'We strive to present a comprehensive and moderate Islamic vision that bridges authentic scholarly heritage with the demands of the modern era.',
                    'fr' => 'Nous presentons une vision islamique moderee alliant patrimoine savant et exigences modernes.',
                    'es' => 'Presentamos una vision islamica moderada que combina el patrimonio academico con las exigencias modernas.',
                    'zh' => '我们呈现一种全面温和的伊斯兰愿景，将正统学术遗产与现代需求相结合。',
                    'ru' => 'Мы представляем умеренное исламское видение, сочетающее научное наследие с современными требованиями.',
                    'ur' => 'ہم ایک جامع اور معتدل اسلامی نظریہ پیش کرتے ہیں جو اصل علمی ورثے اور جدید دور کے تقاضوں کو جوڑتا ہے۔',
                ],
                'is_published' => true,
                'order' => 13,
            ],
            [
                'slug' => 'faculty-of-mass-communication',
                'name' => [
                    'ar' => 'كلية الإعلام',
                    'en' => 'Faculty of Mass Communication',
                    'fr' => 'Faculte des Medias',
                    'es' => 'Facultad de Comunicacion',
                    'zh' => '传媒学院',
                    'ru' => 'Факультет массовых коммуникаций',
                    'ur' => 'ذرائع ابلاغ کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 2003,
                'description' => [
                    'ar' => 'كلية الإعلام بجامعة الأزهر تأسست عام 2003م بالقاهرة لمواكبة التطور في مجال الإعلام والاتصال. تقدم برامج في الصحافة والإذاعة والتلفزيون والعلاقات العامة والإعلان، مع التركيز على الإعلام الإسلامي المسؤول.',
                    'en' => 'The Faculty of Mass Communication was established in 2003 in Cairo to keep pace with developments in media and communication. It offers programs in journalism, broadcasting, public relations, and advertising, with a focus on responsible Islamic media.',
                    'fr' => 'La Faculte des Medias a ete fondee en 2003 et propose des programmes en journalisme, radiodiffusion et relations publiques.',
                    'es' => 'La Facultad de Comunicacion fue fundada en 2003 y ofrece programas en periodismo, radiodifusion y relaciones publicas.',
                    'zh' => '传媒学院成立于2003年，提供新闻、广播、公共关系和广告课程。',
                    'ru' => 'Факультет массовых коммуникаций основан в 2003 году и предлагает программы по журналистике, вещанию и связям с общественностью.',
                    'ur' => 'ذرائع ابلاغ کی فیکلٹی 2003 میں قائم ہوئی اور صحافت، نشریات اور تعلقات عامہ کے پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نعد إعلاميين يحملون رسالة الأزهر الوسطية ويواجهون التحديات الإعلامية المعاصرة بمهنية وأخلاق.',
                    'en' => 'We prepare media professionals who carry Al-Azhar\'s moderate message and face contemporary media challenges with professionalism and ethics.',
                    'fr' => 'Nous formons des professionnels des medias porteurs du message modere d\'Al-Azhar.',
                    'es' => 'Formamos profesionales de medios portadores del mensaje moderado de Al-Azhar.',
                    'zh' => '我们培养传递艾资哈尔温和信息的媒体专业人才。',
                    'ru' => 'Мы готовим медиа-профессионалов, несущих умеренное послание Аль-Азхара.',
                    'ur' => 'ہم ایسے میڈیا پروفیشنلز تیار کرتے ہیں جو الازہر کا معتدل پیغام لے کر چلیں۔',
                ],
                'is_published' => true,
                'order' => 14,
            ],
            [
                'slug' => 'faculty-of-nursing',
                'name' => [
                    'ar' => 'كلية التمريض',
                    'en' => 'Faculty of Nursing',
                    'fr' => 'Faculte des Sciences Infirmieres',
                    'es' => 'Facultad de Enfermeria',
                    'zh' => '护理学院',
                    'ru' => 'Факультет сестринского дела',
                    'ur' => 'نرسنگ کی فیکلٹی',
                ],
                'type' => 'faculty',
                'established_year' => 1994,
                'description' => [
                    'ar' => 'كلية التمريض بجامعة الأزهر بالقاهرة (فرع البنات) تقدم برامج متكاملة في التمريض العام والتخصصي. تهدف إلى إعداد ممرضات مؤهلات قادرات على تقديم رعاية صحية متميزة وفق القيم الإسلامية.',
                    'en' => 'The Faculty of Nursing at Al-Azhar University in Cairo (girls\' branch) offers comprehensive programs in general and specialized nursing, aiming to prepare qualified nurses capable of providing distinguished healthcare aligned with Islamic values.',
                    'fr' => 'La Faculte des Sciences Infirmieres offre des programmes complets en soins infirmiers generaux et specialises.',
                    'es' => 'La Facultad de Enfermeria ofrece programas integrales en enfermeria general y especializada.',
                    'zh' => '护理学院提供综合护理和专科护理课程。',
                    'ru' => 'Факультет сестринского дела предлагает комплексные программы общего и специализированного сестринского ухода.',
                    'ur' => 'نرسنگ کی فیکلٹی عمومی اور خصوصی نرسنگ کے جامع پروگرام پیش کرتی ہے۔',
                ],
                'dean_message' => [
                    'ar' => 'نلتزم بتخريج ممرضات يجمعن بين الكفاءة المهنية العالية والرحمة والأخلاق الإسلامية في رعاية المرضى.',
                    'en' => 'We are committed to graduating nurses who combine high professional competence with compassion and Islamic ethics in patient care.',
                    'fr' => 'Nous formons des infirmieres alliant competence, compassion et ethique islamique.',
                    'es' => 'Formamos enfermeras que combinan competencia, compasion y etica islamica.',
                    'zh' => '我们培养兼具高专业能力、同情心和伊斯兰伦理的护士。',
                    'ru' => 'Мы готовим медсестёр, сочетающих профессионализм с состраданием и исламской этикой.',
                    'ur' => 'ہم ایسی نرسیں تیار کرتی ہیں جو اعلیٰ پیشہ ورانہ قابلیت، رحمدلی اور اسلامی اخلاقیات کو یکجا کریں۔',
                ],
                'is_published' => true,
                'order' => 15,
            ],
        ];

        foreach ($faculties as $data) {
            $faculty = new Faculty();
            $faculty->slug = $data['slug'];
            $faculty->name = $data['name'];
            $faculty->description = $data['description'];
            $faculty->dean_message = $data['dean_message'];
            $faculty->type = $data['type'];
            $faculty->established_year = $data['established_year'];
            $faculty->is_published = $data['is_published'];
            $faculty->order = $data['order'];
            $faculty->save();
        }
    }
}
