<?php

namespace Database\Seeders;

use App\Models\Faculty;
use App\Models\LibraryItem;
use Illuminate\Database\Seeder;

class LibrarySeeder extends Seeder
{
    public function run(): void
    {
        $shariaFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Sharia and Law')->first();
        $theologyFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Theology')->first();
        $arabicFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Arabic Language')->first();
        $scienceFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Science')->first();
        $islamicStudies = Faculty::whereJsonContains('name->en', 'Faculty of Islamic Studies')->first();
        $engineeringFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Engineering')->first();
        $medicineFaculty = Faculty::whereJsonContains('name->en', 'Faculty of Medicine')->first();

        $items = [
            // === MANUSCRIPTS (4) ===
            [
                'slug' => 'kufic-quran-codex',
                'title' => [
                    'ar' => 'مخطوط مصحف كوفي من القرن الرابع الهجري',
                    'en' => 'Kufic Quran Codex from the 4th Century AH',
                    'fr' => 'Codex coranique coufique du IVe siecle de l\'Hegire',
                    'es' => 'Codice coranico cufico del siglo IV de la Hegira',
                    'zh' => '伊斯兰历四世纪库法体古兰经手抄本',
                    'ru' => 'Куфический список Корана IV века хиджры',
                    'ur' => 'چوتھی صدی ہجری کا کوفی قرآنی مخطوطہ',
                ],
                'subtitle' => [
                    'ar' => 'من أقدم المصاحف المحفوظة في مكتبة الأزهر',
                    'en' => 'One of the oldest Quran copies preserved in Al-Azhar Library',
                    'fr' => 'L\'une des plus anciennes copies du Coran conservees a la bibliotheque d\'Al-Azhar',
                    'es' => 'Una de las copias mas antiguas del Coran conservadas en la biblioteca de Al-Azhar',
                    'zh' => '艾资哈尔图书馆保存的最古老的古兰经之一',
                    'ru' => 'Одна из древнейших копий Корана, хранящихся в библиотеке Аль-Азхара',
                    'ur' => 'الازہر لائبریری میں محفوظ قرآن کی قدیم ترین نسخوں میں سے ایک',
                ],
                'description' => [
                    'ar' => 'مصحف نادر مكتوب بالخط الكوفي على رق الغزال، يعود إلى القرن الرابع الهجري (العاشر الميلادي). يتميز بزخارفه الذهبية وعلامات التشكيل المبكرة. يُعد من أهم المقتنيات في مكتبة الأزهر التي أُسست حوالي عام 1005م.',
                    'en' => 'A rare Quran manuscript written in Kufic script on gazelle parchment, dating to the 4th century AH (10th century CE). Distinguished by its gold illumination and early vocalization marks. It is among the most important holdings of Al-Azhar Library, established around 1005 CE.',
                    'fr' => 'Un rare manuscrit coranique ecrit en ecriture coufique sur parchemin de gazelle, datant du IVe siecle de l\'Hegire (Xe siecle). Remarquable par ses enluminures dorees et ses signes diacritiques anciens. Il est parmi les pieces les plus importantes de la bibliotheque d\'Al-Azhar, fondee vers 1005.',
                    'es' => 'Un raro manuscrito coranico escrito en escritura cufica sobre pergamino de gacela, que data del siglo IV de la Hegira (siglo X). Se distingue por sus iluminaciones doradas y sus marcas de vocalizacion tempranas. Es una de las piezas mas importantes de la biblioteca de Al-Azhar, fundada alrededor de 1005.',
                    'zh' => '一部罕见的古兰经手稿，以库法体书写在瞪羚皮纸上，可追溯到伊斯兰历四世纪（公元十世纪）。以其金色装饰和早期元音标记而著称。这是约于1005年建立的艾资哈尔图书馆最重要的藏品之一。',
                    'ru' => 'Редкая рукопись Корана, написанная куфическим письмом на пергаменте из кожи газели, датируемая IV веком хиджры (X век н.э.). Отличается золотым орнаментом и ранними диакритическими знаками. Является одним из важнейших экспонатов библиотеки Аль-Азхара, основанной около 1005 года.',
                    'ur' => 'غزال کے چرم پر کوفی خط میں لکھا گیا ایک نادر قرآنی مخطوطہ، جو چوتھی صدی ہجری (دسویں صدی عیسوی) سے تعلق رکھتا ہے۔ اپنی سنہری آرائش اور ابتدائی اعراب کی علامات کی وجہ سے ممتاز ہے۔ یہ تقریباً 1005ء میں قائم ہونے والی الازہر لائبریری کے اہم ترین ذخائر میں سے ایک ہے۔',
                ],
                'abstract' => [
                    'ar' => 'مصحف مكتوب بالخط الكوفي على الرق يعود للقرن الرابع الهجري، يمثل نموذجاً للمصاحف المبكرة بزخارفها الذهبية.',
                    'en' => 'A Quran codex in Kufic script on parchment from the 4th century AH, representing an example of early Qurans with gold ornamentation.',
                    'fr' => 'Un codex coranique en ecriture coufique sur parchemin du IVe siecle de l\'Hegire, representant un exemple des premiers Corans avec ornementation doree.',
                    'es' => 'Un codice coranico en escritura cufica sobre pergamino del siglo IV de la Hegira, que representa un ejemplo de los primeros Coranes con ornamentacion dorada.',
                    'zh' => '伊斯兰历四世纪的羊皮纸库法体古兰经抄本，是早期古兰经金饰装帧的典范。',
                    'ru' => 'Список Корана куфическим письмом на пергаменте IV века хиджры, представляющий образец ранних Коранов с золотым орнаментом.',
                    'ur' => 'چوتھی صدی ہجری کا چرمی مخطوطے پر کوفی خط میں لکھا قرآن، سنہری آرائش والے ابتدائی قرآنی نسخوں کا نمونہ۔',
                ],
                'type' => 'manuscript',
                'authors' => ['غير معروف - مكتبة الأزهر'],
                'subjects' => ['القرآن الكريم', 'المخطوطات الإسلامية', 'الخط الكوفي'],
                'language' => 'ar',
                'era' => 'fatimid',
                'page_count' => 210,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(6),
                'faculty_id' => $theologyFaculty?->id,
            ],
            [
                'slug' => 'muqaddimah-ibn-khaldun',
                'title' => [
                    'ar' => 'مخطوط المقدمة لابن خلدون',
                    'en' => 'Muqaddimah Manuscript by Ibn Khaldun',
                    'fr' => 'Manuscrit de la Muqaddima d\'Ibn Khaldoun',
                    'es' => 'Manuscrito de la Muqaddima de Ibn Jaldun',
                    'zh' => '伊本·赫勒敦《绪论》手稿',
                    'ru' => 'Рукопись «Мукаддимы» Ибн Хальдуна',
                    'ur' => 'ابن خلدون کی مقدمہ کا مخطوطہ',
                ],
                'subtitle' => [
                    'ar' => 'مقدمة في علم العمران البشري',
                    'en' => 'Prolegomenon to the Science of Human Civilization',
                    'fr' => 'Prolegomenes a la science de la civilisation humaine',
                    'es' => 'Prolegomeno a la ciencia de la civilizacion humana',
                    'zh' => '人类文明科学绪论',
                    'ru' => 'Введение в науку о человеческой цивилизации',
                    'ur' => 'علم العمران البشری کا مقدمہ',
                ],
                'description' => [
                    'ar' => 'مخطوط نادر من "المقدمة" للعلامة عبد الرحمن بن خلدون (1332-1406م)، الذي درس في الأزهر. يُعد أول مؤلف في علم الاجتماع والعمران البشري. يحلل ابن خلدون طبيعة المجتمعات والدول وأسباب قيامها وسقوطها، ويضع نظريات في الاقتصاد والتعليم والسياسة.',
                    'en' => 'A rare manuscript of the "Muqaddimah" by the scholar Abd al-Rahman ibn Khaldun (1332-1406 CE), who studied at Al-Azhar. Considered the first work on sociology and human civilization. Ibn Khaldun analyzes the nature of societies and states, the causes of their rise and fall, and develops theories on economics, education, and politics.',
                    'fr' => 'Un rare manuscrit de la "Muqaddima" du savant Abd al-Rahman ibn Khaldoun (1332-1406), qui etudia a Al-Azhar. Considere comme le premier ouvrage de sociologie et de civilisation humaine. Ibn Khaldoun analyse la nature des societes et des Etats, les causes de leur essor et de leur declin.',
                    'es' => 'Un raro manuscrito de la "Muqaddima" del erudito Abd al-Rahman ibn Jaldun (1332-1406), quien estudio en Al-Azhar. Considerado la primera obra sobre sociologia y civilizacion humana. Ibn Jaldun analiza la naturaleza de las sociedades y los estados, las causas de su auge y caida.',
                    'zh' => '学者阿卜杜拉赫曼·伊本·赫勒敦（1332-1406年）的珍贵《绪论》手稿，他曾在艾资哈尔学习。被认为是社会学和人类文明的第一部著作。伊本·赫勒敦分析了社会和国家的本质及其兴衰原因，并提出了经济、教育和政治理论。',
                    'ru' => 'Редкая рукопись «Мукаддимы» учёного Абд ар-Рахмана ибн Хальдуна (1332-1406), учившегося в Аль-Азхаре. Считается первой работой по социологии и человеческой цивилизации. Ибн Хальдун анализирует природу обществ и государств, причины их расцвета и упадка.',
                    'ur' => 'عالم عبد الرحمٰن ابن خلدون (1332-1406ء) کی "مقدمہ" کا نادر مخطوطہ، جنہوں نے الازہر میں تعلیم حاصل کی۔ یہ سماجیات اور عمرانیات کی پہلی تصنیف مانی جاتی ہے۔ ابن خلدون معاشروں اور ریاستوں کی نوعیت، ان کے عروج و زوال کے اسباب کا تجزیہ کرتے ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة تحليلية في طبيعة العمران والدول ومراحل تطورها وأسباب انهيارها مع نظريات في العصبية والاقتصاد.',
                    'en' => 'An analytical study of civilization, states, stages of development, and causes of decline, with theories on social solidarity and economics.',
                    'fr' => 'Une etude analytique de la civilisation, des Etats, des etapes de developpement et des causes de declin, avec des theories sur la solidarite sociale et l\'economie.',
                    'es' => 'Un estudio analitico de la civilizacion, los estados, las etapas de desarrollo y las causas del declive, con teorias sobre la solidaridad social y la economia.',
                    'zh' => '对文明、国家、发展阶段和衰落原因的分析研究，以及关于社会团结和经济的理论。',
                    'ru' => 'Аналитическое исследование цивилизации, государств, этапов развития и причин упадка с теориями социальной солидарности и экономики.',
                    'ur' => 'تہذیب، ریاستوں، ترقی کے مراحل اور زوال کے اسباب کا تجزیاتی مطالعہ، عصبیت اور معاشیات کے نظریات کے ساتھ۔',
                ],
                'type' => 'manuscript',
                'authors' => ['عبد الرحمن بن محمد بن خلدون'],
                'subjects' => ['علم الاجتماع', 'التاريخ', 'الفلسفة', 'العمران'],
                'language' => 'ar',
                'era' => 'mamluk',
                'page_count' => 890,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(10),
                'faculty_id' => $islamicStudies?->id,
            ],
            [
                'slug' => 'canon-of-medicine-avicenna',
                'title' => [
                    'ar' => 'مخطوط القانون في الطب لابن سينا',
                    'en' => 'The Canon of Medicine Manuscript by Avicenna',
                    'fr' => 'Manuscrit du Canon de la Medecine d\'Avicenne',
                    'es' => 'Manuscrito del Canon de Medicina de Avicena',
                    'zh' => '伊本·西那《医典》手稿',
                    'ru' => 'Рукопись «Канона врачебной науки» Авиценны',
                    'ur' => 'ابن سینا کی القانون فی الطب کا مخطوطہ',
                ],
                'subtitle' => [
                    'ar' => 'الموسوعة الطبية التي ظلت مرجعاً لخمسة قرون',
                    'en' => 'The medical encyclopedia that remained a reference for five centuries',
                    'fr' => 'L\'encyclopedie medicale qui est restee une reference pendant cinq siecles',
                    'es' => 'La enciclopedia medica que fue referencia durante cinco siglos',
                    'zh' => '持续五个世纪的医学权威百科全书',
                    'ru' => 'Медицинская энциклопедия, остававшаяся справочником в течение пяти веков',
                    'ur' => 'طبی دائرۃ المعارف جو پانچ صدیوں تک مرجع رہی',
                ],
                'description' => [
                    'ar' => 'مخطوط من كتاب "القانون في الطب" للحكيم أبو علي الحسين بن سينا (980-1037م)، الموسوعة الطبية الأشهر في التاريخ الإسلامي. يتناول التشريح وأمراض الأعضاء والأدوية المفردة والمركبة والأمراض العامة. ظل مرجعاً أساسياً في التعليم الطبي بأوروبا حتى القرن السابع عشر.',
                    'en' => 'A manuscript of "The Canon of Medicine" by the physician Abu Ali al-Husayn ibn Sina (Avicenna, 980-1037 CE), the most famous medical encyclopedia in Islamic history. It covers anatomy, organ diseases, simple and compound medicines, and general diseases. It remained a primary reference in European medical education until the 17th century.',
                    'fr' => 'Un manuscrit du "Canon de la Medecine" du medecin Abu Ali al-Husayn ibn Sina (Avicenne, 980-1037). L\'encyclopedie medicale la plus celebre de l\'histoire islamique. Il couvre l\'anatomie, les maladies des organes, les medicaments simples et composes. Il est reste une reference principale dans l\'enseignement medical europeen jusqu\'au XVIIe siecle.',
                    'es' => 'Un manuscrito del "Canon de Medicina" del medico Abu Ali al-Husayn ibn Sina (Avicena, 980-1037). La enciclopedia medica mas famosa de la historia islamica. Cubre anatomia, enfermedades de organos, medicamentos simples y compuestos. Permanecio como referencia principal en la educacion medica europea hasta el siglo XVII.',
                    'zh' => '医学家阿布·阿里·侯赛因·伊本·西那（阿维森纳，980-1037年）《医典》手稿，伊斯兰历史上最著名的医学百科全书。涵盖解剖学、器官疾病、单方和复方药物以及一般疾病。直到17世纪仍是欧洲医学教育的主要参考书。',
                    'ru' => 'Рукопись «Канона врачебной науки» медика Абу Али аль-Хусейна ибн Сины (Авиценна, 980-1037). Самая знаменитая медицинская энциклопедия в исламской истории. Охватывает анатомию, болезни органов, простые и составные лекарства. Оставалась основным справочником в европейском медицинском образовании до XVII века.',
                    'ur' => 'طبیب ابو علی الحسین ابن سینا (980-1037ء) کی "القانون فی الطب" کا مخطوطہ، اسلامی تاریخ کا سب سے مشہور طبی دائرۃ المعارف۔ اس میں تشریح، اعضاء کے امراض، مفرد و مرکب ادویات اور عمومی امراض شامل ہیں۔ سترہویں صدی تک یورپی طبی تعلیم میں بنیادی مرجع رہی۔',
                ],
                'abstract' => [
                    'ar' => 'موسوعة طبية شاملة في خمسة كتب تغطي المبادئ العامة للطب والأدوية المفردة وأمراض الأعضاء والأمراض العامة والأدوية المركبة.',
                    'en' => 'A comprehensive medical encyclopedia in five books covering general principles of medicine, simple drugs, organ-specific diseases, general diseases, and compound medicines.',
                    'fr' => 'Une encyclopedie medicale complete en cinq livres couvrant les principes generaux de la medecine, les medicaments simples, les maladies specifiques aux organes, les maladies generales et les medicaments composes.',
                    'es' => 'Una enciclopedia medica integral en cinco libros que cubre los principios generales de la medicina, los medicamentos simples, las enfermedades especificas de los organos, las enfermedades generales y los medicamentos compuestos.',
                    'zh' => '五卷综合医学百科全书，涵盖医学总论、单方药物、器官疾病、一般疾病和复方药物。',
                    'ru' => 'Всеобъемлющая медицинская энциклопедия в пяти книгах, охватывающая общие принципы медицины, простые лекарства, заболевания органов, общие заболевания и составные лекарства.',
                    'ur' => 'پانچ کتابوں پر مشتمل جامع طبی دائرۃ المعارف جو طب کے عمومی اصول، مفرد ادویات، اعضاء کے امراض، عمومی امراض اور مرکب ادویات کا احاطہ کرتی ہے۔',
                ],
                'type' => 'manuscript',
                'authors' => ['أبو علي الحسين بن عبد الله بن سينا'],
                'subjects' => ['الطب', 'الصيدلة', 'التشريح', 'التراث الطبي الإسلامي'],
                'language' => 'ar',
                'era' => 'mamluk',
                'page_count' => 1650,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(8),
                'faculty_id' => $medicineFaculty?->id,
            ],
            [
                'slug' => 'al-risala-al-shafii',
                'title' => [
                    'ar' => 'مخطوط الرسالة للإمام الشافعي',
                    'en' => 'Al-Risala Manuscript by Imam Al-Shafi\'i',
                    'fr' => 'Manuscrit d\'Al-Risala de l\'Imam Al-Chafi\'i',
                    'es' => 'Manuscrito de Al-Risala del Imam Al-Shafi\'i',
                    'zh' => '伊玛目沙斐仪《书信集》手稿',
                    'ru' => 'Рукопись «Ар-Рисала» имама аш-Шафии',
                    'ur' => 'امام شافعی کی الرسالہ کا مخطوطہ',
                ],
                'subtitle' => [
                    'ar' => 'أول كتاب في أصول الفقه الإسلامي',
                    'en' => 'The First Book on Islamic Legal Theory',
                    'fr' => 'Le premier livre sur la theorie juridique islamique',
                    'es' => 'El primer libro sobre la teoria juridica islamica',
                    'zh' => '伊斯兰法学理论的第一部著作',
                    'ru' => 'Первая книга по теории исламского права',
                    'ur' => 'اسلامی اصول فقہ کی پہلی کتاب',
                ],
                'description' => [
                    'ar' => 'مخطوط نادر من كتاب "الرسالة" للإمام محمد بن إدريس الشافعي (150-204هـ)، وهو أول مؤلف في علم أصول الفقه الإسلامي. يضع الإمام الشافعي القواعد والأصول التي يُبنى عليها الاستنباط الفقهي من القرآن والسنة والإجماع والقياس.',
                    'en' => 'A rare manuscript of "Al-Risala" by Imam Muhammad ibn Idris al-Shafi\'i (767-820 CE), the first work on Islamic legal theory (usul al-fiqh). Imam al-Shafi\'i establishes the principles and foundations for deriving legal rulings from the Quran, Sunnah, consensus, and analogical reasoning.',
                    'fr' => 'Un rare manuscrit de "Al-Risala" de l\'Imam Muhammad ibn Idris al-Chafi\'i (767-820), le premier ouvrage sur la theorie juridique islamique (usul al-fiqh). L\'Imam al-Chafi\'i etablit les principes et fondements pour deriver les decisions juridiques du Coran, de la Sunna, du consensus et du raisonnement analogique.',
                    'es' => 'Un raro manuscrito de "Al-Risala" del Imam Muhammad ibn Idris al-Shafi\'i (767-820), la primera obra sobre la teoria juridica islamica (usul al-fiqh). El Imam al-Shafi\'i establece los principios y fundamentos para derivar decisiones juridicas del Coran, la Sunna, el consenso y el razonamiento analogico.',
                    'zh' => '伊玛目穆罕默德·本·伊德里斯·沙斐仪（767-820年）的珍贵《书信集》手稿，是伊斯兰法学理论（教法原理学）的第一部著作。沙斐仪伊玛目确立了从古兰经、圣训、公议和类比推理中推导法律裁决的原则和基础。',
                    'ru' => 'Редкая рукопись «Ар-Рисала» имама Мухаммада ибн Идриса аш-Шафии (767-820), первый труд по теории исламского права (усуль аль-фикх). Имам аш-Шафии устанавливает принципы и основы для извлечения правовых решений из Корана, Сунны, иджмы и кыяса.',
                    'ur' => 'امام محمد بن ادریس الشافعی (767-820ء) کی "الرسالہ" کا نادر مخطوطہ، اسلامی اصول فقہ پر پہلی تصنیف۔ امام شافعی قرآن، سنت، اجماع اور قیاس سے فقہی احکام کے استنباط کے اصول و قواعد مقرر کرتے ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'يتناول الكتاب أصول الاستنباط الفقهي ومنهجية فهم النصوص الشرعية وترتيب الأدلة والجمع بين المتعارض منها.',
                    'en' => 'The book addresses the foundations of legal derivation, methodology for understanding religious texts, ordering of evidence, and reconciliation of apparently conflicting texts.',
                    'fr' => 'Le livre aborde les fondements de la derivation juridique, la methodologie de comprehension des textes religieux, l\'ordonnancement des preuves et la reconciliation des textes apparemment contradictoires.',
                    'es' => 'El libro aborda los fundamentos de la derivacion juridica, la metodologia para comprender los textos religiosos, el ordenamiento de las pruebas y la reconciliacion de textos aparentemente contradictorios.',
                    'zh' => '本书探讨法律推导的基础、理解宗教文本的方法论、证据的排序以及表面矛盾文本的调和。',
                    'ru' => 'Книга рассматривает основы правового вывода, методологию понимания религиозных текстов, упорядочение доказательств и примирение внешне противоречивых текстов.',
                    'ur' => 'کتاب فقہی استنباط کے اصول، شرعی نصوص کو سمجھنے کا منہج، ادلے کی ترتیب اور متعارض نصوص کے درمیان تطبیق پر بحث کرتی ہے۔',
                ],
                'type' => 'manuscript',
                'authors' => ['الإمام محمد بن إدريس الشافعي'],
                'subjects' => ['أصول الفقه', 'الفقه الإسلامي', 'علم المنهج'],
                'language' => 'ar',
                'era' => 'fatimid',
                'page_count' => 320,
                'access_level' => 'registered',
                'is_published' => true,
                'published_at' => now()->subMonths(12),
                'faculty_id' => $shariaFaculty?->id,
            ],

            // === BOOKS (3) ===
            [
                'slug' => 'history-of-al-azhar-thousand-years',
                'title' => [
                    'ar' => 'تاريخ الأزهر في ألف عام',
                    'en' => 'History of Al-Azhar in a Thousand Years',
                    'fr' => 'Histoire d\'Al-Azhar en mille ans',
                    'es' => 'Historia de Al-Azhar en mil anos',
                    'zh' => '艾资哈尔千年史',
                    'ru' => 'История Аль-Азхара за тысячу лет',
                    'ur' => 'الازہر کی ہزار سالہ تاریخ',
                ],
                'subtitle' => [
                    'ar' => 'رحلة عبر القرون من 972 إلى اليوم',
                    'en' => 'A Journey Through Centuries from 972 to Today',
                    'fr' => 'Un voyage a travers les siecles de 972 a aujourd\'hui',
                    'es' => 'Un viaje a traves de los siglos desde 972 hasta hoy',
                    'zh' => '从972年至今的世纪之旅',
                    'ru' => 'Путешествие сквозь века с 972 года до наших дней',
                    'ur' => '972ء سے آج تک صدیوں کا سفر',
                ],
                'description' => [
                    'ar' => 'كتاب توثيقي شامل يروي تاريخ الأزهر الشريف منذ تأسيسه عام 972م بأمر الخليفة المعز لدين الله الفاطمي وحتى العصر الحديث. يتناول المراحل التاريخية المختلفة: الفاطمية والأيوبية والمملوكية والعثمانية والحديثة، والتحولات الكبرى في بنيته التعليمية والإدارية ودوره في الحياة الثقافية والسياسية.',
                    'en' => 'A comprehensive documentary book narrating the history of Al-Azhar from its founding in 972 CE by order of the Fatimid Caliph Al-Mu\'izz li-Din Allah to the modern era. It covers the various historical phases: Fatimid, Ayyubid, Mamluk, Ottoman, and modern, and the major transformations in its educational and administrative structure and its role in cultural and political life.',
                    'fr' => 'Un livre documentaire complet racontant l\'histoire d\'Al-Azhar depuis sa fondation en 972 par ordre du calife fatimide Al-Mu\'izz li-Din Allah jusqu\'a l\'ere moderne. Il couvre les differentes phases historiques et les transformations majeures de sa structure educative et administrative.',
                    'es' => 'Un libro documental completo que narra la historia de Al-Azhar desde su fundacion en 972 por orden del califa fatimi Al-Mu\'izz li-Din Allah hasta la era moderna. Cubre las diferentes fases historicas y las principales transformaciones en su estructura educativa y administrativa.',
                    'zh' => '一部全面的纪录性著作，讲述了艾资哈尔自972年法蒂玛王朝哈里发穆伊兹下令建立至现代的历史。涵盖法蒂玛、阿尤布、马穆鲁克、奥斯曼和现代等各个历史阶段，以及其教育和行政结构的重大变革及其在文化和政治生活中的角色。',
                    'ru' => 'Всеобъемлющая документальная книга, повествующая об истории Аль-Азхара от его основания в 972 году по приказу фатимидского халифа Аль-Муизза ли-Дин Аллаха до наших дней. Охватывает различные исторические этапы: фатимидский, айюбидский, мамлюкский, османский и современный, и крупные преобразования.',
                    'ur' => 'ایک جامع تاریخی کتاب جو 972ء میں فاطمی خلیفہ المعز لدین اللہ کے حکم سے الازہر کی بنیاد سے لے کر جدید دور تک کی تاریخ بیان کرتی ہے۔ فاطمی، ایوبی، مملوک، عثمانی اور جدید ادوار اور تعلیمی و انتظامی ڈھانچے میں بڑی تبدیلیوں کا احاطہ کرتی ہے۔',
                ],
                'abstract' => [
                    'ar' => 'توثيق تاريخي شامل لمسيرة الأزهر عبر العصور الفاطمية والمملوكية والعثمانية والحديثة.',
                    'en' => 'Comprehensive historical documentation of Al-Azhar\'s journey through the Fatimid, Mamluk, Ottoman, and modern eras.',
                    'fr' => 'Documentation historique complete du parcours d\'Al-Azhar a travers les eres fatimide, mamelouke, ottomane et moderne.',
                    'es' => 'Documentacion historica completa del recorrido de Al-Azhar a traves de las eras fatimi, mameluca, otomana y moderna.',
                    'zh' => '艾资哈尔在法蒂玛、马穆鲁克、奥斯曼和现代各时期历程的全面历史记录。',
                    'ru' => 'Всестороннее историческое документирование пути Аль-Азхара через фатимидскую, мамлюкскую, османскую и современную эпохи.',
                    'ur' => 'فاطمی، مملوک، عثمانی اور جدید ادوار میں الازہر کے سفر کی جامع تاریخی دستاویز۔',
                ],
                'type' => 'book',
                'authors' => ['د. عبد العظيم رمضان'],
                'subjects' => ['تاريخ الأزهر', 'تاريخ مصر', 'التعليم الإسلامي'],
                'publisher' => 'الهيئة المصرية العامة للكتاب',
                'publication_year' => 1994,
                'language' => 'ar',
                'page_count' => 720,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(2),
                'faculty_id' => null,
            ],
            [
                'slug' => 'islamic-jurisprudence-and-evidence',
                'title' => [
                    'ar' => 'الفقه الإسلامي وأدلته',
                    'en' => 'Islamic Jurisprudence and Its Evidence',
                    'fr' => 'La jurisprudence islamique et ses preuves',
                    'es' => 'La jurisprudencia islamica y sus pruebas',
                    'zh' => '伊斯兰教法学及其证据',
                    'ru' => 'Исламская юриспруденция и её доказательства',
                    'ur' => 'فقہ اسلامی اور اس کے دلائل',
                ],
                'subtitle' => [
                    'ar' => 'الشامل للأدلة الشرعية والمذاهب الفقهية',
                    'en' => 'Comprehensive Guide to Legal Evidence and Jurisprudential Schools',
                    'fr' => 'Guide complet des preuves juridiques et des ecoles de jurisprudence',
                    'es' => 'Guia completa de las pruebas juridicas y las escuelas de jurisprudencia',
                    'zh' => '法律证据和教法学派综合指南',
                    'ru' => 'Полное руководство по правовым доказательствам и юридическим школам',
                    'ur' => 'شرعی دلائل اور فقہی مذاہب کا جامع رہنما',
                ],
                'description' => [
                    'ar' => 'موسوعة فقهية شاملة للدكتور وهبة الزحيلي تتناول أحكام الفقه الإسلامي مع أدلتها من الكتاب والسنة والإجماع والقياس، مع عرض آراء المذاهب الفقهية الأربعة والترجيح بينها.',
                    'en' => 'A comprehensive jurisprudential encyclopedia by Dr. Wahba al-Zuhayli covering Islamic jurisprudence rulings with evidence from the Quran, Sunnah, consensus, and analogy, presenting the views of the four schools with comparative analysis.',
                    'fr' => 'Une encyclopedie juridique complete du Dr. Wahba al-Zuhayli couvrant les decisions de jurisprudence islamique avec des preuves du Coran, de la Sunna, du consensus et de l\'analogie, presentant les vues des quatre ecoles.',
                    'es' => 'Una enciclopedia juridica completa del Dr. Wahba al-Zuhayli que cubre las decisiones de la jurisprudencia islamica con pruebas del Coran, la Sunna, el consenso y la analogia, presentando las opiniones de las cuatro escuelas.',
                    'zh' => '瓦赫巴·祖海利博士的综合教法学百科全书，以古兰经、圣训、公议和类比为证据阐述伊斯兰教法裁决，并呈现四大学派的观点及比较分析。',
                    'ru' => 'Всеобъемлющая юридическая энциклопедия доктора Вахбы аз-Зухайли, охватывающая решения исламской юриспруденции с доказательствами из Корана, Сунны, иджмы и кыяса, представляя взгляды четырёх школ.',
                    'ur' => 'ڈاکٹر وہبہ الزحیلی کا جامع فقہی دائرۃ المعارف جو قرآن، سنت، اجماع اور قیاس سے دلائل کے ساتھ فقہ اسلامی کے احکام کا احاطہ کرتا ہے، چاروں فقہی مذاہب کی آراء اور ان کے درمیان ترجیح کے ساتھ۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة مقارنة للفقه الإسلامي تشمل جميع أبواب الفقه مع الأدلة والترجيح بين المذاهب.',
                    'en' => 'A comparative study of Islamic jurisprudence covering all chapters with evidence and comparative analysis across schools.',
                    'fr' => 'Une etude comparative de la jurisprudence islamique couvrant tous les chapitres avec des preuves et une analyse comparative entre les ecoles.',
                    'es' => 'Un estudio comparativo de la jurisprudencia islamica que cubre todos los capitulos con pruebas y analisis comparativo entre las escuelas.',
                    'zh' => '伊斯兰教法学的比较研究，涵盖所有章节，附有证据和各学派的比较分析。',
                    'ru' => 'Сравнительное исследование исламской юриспруденции, охватывающее все главы с доказательствами и сравнительным анализом школ.',
                    'ur' => 'فقہ اسلامی کا تقابلی مطالعہ جو تمام ابواب فقہ کو دلائل اور مذاہب کے درمیان ترجیح کے ساتھ شامل کرتا ہے۔',
                ],
                'type' => 'book',
                'authors' => ['د. وهبة الزحيلي'],
                'subjects' => ['الفقه الإسلامي', 'الفقه المقارن'],
                'publisher' => 'دار الفكر',
                'publication_year' => 1985,
                'language' => 'ar',
                'page_count' => 3200,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(3),
                'faculty_id' => $shariaFaculty?->id,
            ],
            [
                'slug' => 'al-nahw-al-wafi',
                'title' => [
                    'ar' => 'النحو الوافي',
                    'en' => 'Comprehensive Arabic Grammar',
                    'fr' => 'Grammaire arabe complete',
                    'es' => 'Gramatica arabe completa',
                    'zh' => '完备阿拉伯语语法',
                    'ru' => 'Полная арабская грамматика',
                    'ur' => 'جامع عربی قواعد',
                ],
                'subtitle' => [
                    'ar' => 'مع ربطه بالأساليب الرفيعة والحياة اللغوية المتجددة',
                    'en' => 'Linked with Elevated Styles and Renewed Linguistic Life',
                    'fr' => 'Lie aux styles eleves et a la vie linguistique renouvelee',
                    'es' => 'Vinculado con estilos elevados y vida linguistica renovada',
                    'zh' => '与高雅文体和语言生活革新相结合',
                    'ru' => 'Связанная с высокими стилями и обновлённой языковой жизнью',
                    'ur' => 'رفیع اسالیب اور متجدد لسانی زندگی سے مربوط',
                ],
                'description' => [
                    'ar' => 'موسوعة نحوية شاملة للدكتور عباس حسن تتناول قواعد النحو العربي بأسلوب واضح ومنهجي. يعد هذا الكتاب من أهم المراجع في النحو العربي ويُدرَّس في كليات اللغة العربية بالأزهر والجامعات العربية.',
                    'en' => 'A comprehensive grammar encyclopedia by Dr. Abbas Hasan covering Arabic grammar rules in a clear and systematic manner. This book is among the most important references in Arabic grammar and is taught at Arabic language faculties at Al-Azhar and Arab universities.',
                    'fr' => 'Une encyclopedie grammaticale complete du Dr. Abbas Hasan couvrant les regles de grammaire arabe de maniere claire et systematique. Ce livre est l\'une des references les plus importantes en grammaire arabe, enseigne dans les facultes d\'Al-Azhar et des universites arabes.',
                    'es' => 'Una enciclopedia gramatical completa del Dr. Abbas Hasan que cubre las reglas de la gramatica arabe de manera clara y sistematica. Este libro es una de las referencias mas importantes en la gramatica arabe, ensenado en Al-Azhar y universidades arabes.',
                    'zh' => '阿巴斯·哈桑博士的综合语法百科全书，以清晰系统的方式涵盖阿拉伯语语法规则。这本书是阿拉伯语语法最重要的参考书之一，在艾资哈尔和阿拉伯大学的阿拉伯语学院中教授。',
                    'ru' => 'Всеобъемлющая грамматическая энциклопедия доктора Аббаса Хасана, охватывающая правила арабской грамматики ясным и систематическим образом. Одна из важнейших работ по арабской грамматике, изучаемая в Аль-Азхаре и арабских университетах.',
                    'ur' => 'ڈاکٹر عباس حسن کا جامع نحوی دائرۃ المعارف جو واضح اور منہجی انداز میں عربی قواعد نحو کا احاطہ کرتا ہے۔ یہ عربی نحو میں اہم ترین مراجع میں سے ہے اور الازہر اور عربی جامعات میں پڑھایا جاتا ہے۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة شاملة لقواعد النحو العربي مع التطبيقات والشواهد من القرآن والشعر والنثر.',
                    'en' => 'A comprehensive study of Arabic grammar rules with applications and examples from the Quran, poetry, and prose.',
                    'fr' => 'Une etude complete des regles de grammaire arabe avec des applications et des exemples du Coran, de la poesie et de la prose.',
                    'es' => 'Un estudio completo de las reglas de la gramatica arabe con aplicaciones y ejemplos del Coran, la poesia y la prosa.',
                    'zh' => '阿拉伯语语法规则的全面研究，附有古兰经、诗歌和散文中的应用和例证。',
                    'ru' => 'Всестороннее исследование правил арабской грамматики с примерами из Корана, поэзии и прозы.',
                    'ur' => 'قرآن، شاعری اور نثر سے شواہد اور تطبیقات کے ساتھ عربی قواعد نحو کا جامع مطالعہ۔',
                ],
                'type' => 'book',
                'authors' => ['د. عباس حسن'],
                'subjects' => ['النحو العربي', 'اللغة العربية'],
                'publisher' => 'دار المعارف',
                'publication_year' => 1975,
                'language' => 'ar',
                'page_count' => 2200,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(5),
                'faculty_id' => $arabicFaculty?->id,
            ],

            // === THESES (2) ===
            [
                'slug' => 'maqasid-approach-islamic-jurisprudence',
                'title' => [
                    'ar' => 'المنهج المقاصدي في الفقه الإسلامي: دراسة تأصيلية تطبيقية',
                    'en' => 'The Maqasid Approach in Islamic Jurisprudence: A Foundational Applied Study',
                    'fr' => 'L\'approche des Maqasid dans la jurisprudence islamique : etude fondamentale appliquee',
                    'es' => 'El enfoque de los Maqasid en la jurisprudencia islamica: un estudio fundamental aplicado',
                    'zh' => '伊斯兰教法学中的目的论方法：基础应用研究',
                    'ru' => 'Подход макасид в исламской юриспруденции: фундаментальное прикладное исследование',
                    'ur' => 'فقہ اسلامی میں مقاصدی منہج: ایک تاصیلی و تطبیقی مطالعہ',
                ],
                'subtitle' => [
                    'ar' => 'رسالة دكتوراه',
                    'en' => 'PhD Dissertation',
                    'fr' => 'These de doctorat',
                    'es' => 'Tesis doctoral',
                    'zh' => '博士论文',
                    'ru' => 'Докторская диссертация',
                    'ur' => 'پی ایچ ڈی مقالہ',
                ],
                'description' => [
                    'ar' => 'رسالة دكتوراه تتناول المنهج المقاصدي في الفقه الإسلامي وكيفية توظيف مقاصد الشريعة في استنباط الأحكام الفقهية المعاصرة. تقدم الرسالة إطاراً نظرياً وتطبيقياً لفهم العلاقة بين المقاصد والأحكام الجزئية.',
                    'en' => 'A PhD dissertation examining the maqasid approach in Islamic jurisprudence and how to employ the objectives of Sharia in deriving contemporary jurisprudential rulings. The dissertation provides a theoretical and applied framework for understanding the relationship between objectives and specific rulings.',
                    'fr' => 'Une these de doctorat examinant l\'approche des maqasid dans la jurisprudence islamique et comment employer les objectifs de la charia dans la derivation des decisions juridiques contemporaines.',
                    'es' => 'Una tesis doctoral que examina el enfoque de los maqasid en la jurisprudencia islamica y como emplear los objetivos de la Sharia en la derivacion de decisiones juridicas contemporaneas.',
                    'zh' => '一篇博士论文，研究伊斯兰教法学中的目的论方法以及如何运用伊斯兰法的目标来推导当代法律裁决。',
                    'ru' => 'Докторская диссертация, исследующая подход макасид в исламской юриспруденции и применение целей шариата в выведении современных правовых решений.',
                    'ur' => 'ایک پی ایچ ڈی مقالہ جو فقہ اسلامی میں مقاصدی منہج اور عصری فقہی احکام کے استنباط میں مقاصد شریعت کے توظیف کا جائزہ لیتا ہے۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة تأصيلية تطبيقية في المنهج المقاصدي تهدف إلى بناء منهج متكامل لتوظيف المقاصد في الاجتهاد الفقهي المعاصر.',
                    'en' => 'A foundational applied study aimed at building an integrated methodology for employing objectives in contemporary jurisprudential reasoning.',
                    'fr' => 'Une etude fondamentale appliquee visant a construire une methodologie integree pour employer les objectifs dans le raisonnement juridique contemporain.',
                    'es' => 'Un estudio fundamental aplicado destinado a construir una metodologia integrada para emplear los objetivos en el razonamiento juridico contemporaneo.',
                    'zh' => '一项旨在建立运用目标进行当代法律推理的综合方法论的基础应用研究。',
                    'ru' => 'Фундаментальное прикладное исследование, направленное на создание комплексной методологии применения целей в современном правовом мышлении.',
                    'ur' => 'ایک تاصیلی و تطبیقی مطالعہ جس کا مقصد عصری فقہی اجتہاد میں مقاصد کے توظیف کے لیے مکمل منہج کی تعمیر ہے۔',
                ],
                'type' => 'thesis',
                'authors' => ['د. عبد الرحمن محمد السيد'],
                'subjects' => ['مقاصد الشريعة', 'الفقه الإسلامي', 'الاجتهاد'],
                'publisher' => 'جامعة الأزهر',
                'publication_year' => 2022,
                'language' => 'ar',
                'page_count' => 450,
                'access_level' => 'registered',
                'is_published' => true,
                'published_at' => now()->subMonths(7),
                'faculty_id' => $shariaFaculty?->id,
            ],
            [
                'slug' => 'interfaith-dialogue-contemporary-thought',
                'title' => [
                    'ar' => 'الحوار بين الأديان في الفكر الإسلامي المعاصر',
                    'en' => 'Interfaith Dialogue in Contemporary Islamic Thought',
                    'fr' => 'Le dialogue interreligieux dans la pensee islamique contemporaine',
                    'es' => 'El dialogo interreligioso en el pensamiento islamico contemporaneo',
                    'zh' => '当代伊斯兰思想中的宗教间对话',
                    'ru' => 'Межрелигиозный диалог в современной исламской мысли',
                    'ur' => 'عصری اسلامی فکر میں بین المذاہب مکالمہ',
                ],
                'subtitle' => [
                    'ar' => 'رسالة دكتوراه',
                    'en' => 'PhD Dissertation',
                    'fr' => 'These de doctorat',
                    'es' => 'Tesis doctoral',
                    'zh' => '博士论文',
                    'ru' => 'Докторская диссертация',
                    'ur' => 'پی ایچ ڈی مقالہ',
                ],
                'description' => [
                    'ar' => 'رسالة دكتوراه تبحث في أسس الحوار بين الأديان من منظور إسلامي، وتستعرض جهود العلماء المسلمين المعاصرين في هذا المجال. تتناول الرسالة التجربة الأزهرية في الحوار مع الفاتيكان والكنائس المسيحية، بما في ذلك بيت العائلة المصرية.',
                    'en' => 'A PhD dissertation examining the foundations of interfaith dialogue from an Islamic perspective, reviewing the efforts of contemporary Muslim scholars. It covers Al-Azhar\'s experience in dialogue with the Vatican and Christian churches, including the Egyptian Family House initiative.',
                    'fr' => 'Une these de doctorat examinant les fondements du dialogue interreligieux d\'un point de vue islamique, passant en revue les efforts des savants musulmans contemporains. Elle couvre l\'experience d\'Al-Azhar dans le dialogue avec le Vatican et les eglises chretiennes.',
                    'es' => 'Una tesis doctoral que examina los fundamentos del dialogo interreligioso desde una perspectiva islamica, revisando los esfuerzos de los eruditos musulmanes contemporaneos. Cubre la experiencia de Al-Azhar en el dialogo con el Vaticano y las iglesias cristianas.',
                    'zh' => '一篇博士论文，从伊斯兰视角审视宗教间对话的基础，回顾当代穆斯林学者的努力。涵盖艾资哈尔与梵蒂冈和基督教教会对话的经验，包括埃及家庭之家倡议。',
                    'ru' => 'Докторская диссертация, исследующая основы межрелигиозного диалога с исламской точки зрения, обзор усилий современных мусульманских учёных. Охватывает опыт Аль-Азхара в диалоге с Ватиканом и христианскими церквями.',
                    'ur' => 'ایک پی ایچ ڈی مقالہ جو اسلامی نقطہ نظر سے بین المذاہب مکالمے کی بنیادوں کا جائزہ لیتا ہے اور عصری مسلمان علماء کی کاوشوں کا جائزہ لیتا ہے۔ ویٹیکن اور مسیحی کلیساؤں کے ساتھ الازہر کے مکالمے کے تجربے کا احاطہ کرتا ہے۔',
                ],
                'abstract' => [
                    'ar' => 'بحث في أسس الحوار بين الأديان إسلامياً مع دراسة تطبيقية لتجربة الأزهر في الحوار مع الآخر.',
                    'en' => 'Research on the foundations of interfaith dialogue from an Islamic perspective with an applied study of Al-Azhar\'s experience.',
                    'fr' => 'Recherche sur les fondements du dialogue interreligieux d\'une perspective islamique avec une etude appliquee de l\'experience d\'Al-Azhar.',
                    'es' => 'Investigacion sobre los fundamentos del dialogo interreligioso desde una perspectiva islamica con un estudio aplicado de la experiencia de Al-Azhar.',
                    'zh' => '从伊斯兰视角研究宗教间对话的基础，并对艾资哈尔的经验进行应用研究。',
                    'ru' => 'Исследование основ межрелигиозного диалога с исламской точки зрения с прикладным изучением опыта Аль-Азхара.',
                    'ur' => 'اسلامی نقطہ نظر سے بین المذاہب مکالمے کی بنیادوں پر تحقیق اور الازہر کے تجربے کا عملی مطالعہ۔',
                ],
                'type' => 'thesis',
                'authors' => ['د. محمود عبد الله النجار'],
                'subjects' => ['حوار الأديان', 'الفكر الإسلامي', 'الدراسات المقارنة'],
                'publisher' => 'جامعة الأزهر',
                'publication_year' => 2021,
                'language' => 'ar',
                'page_count' => 520,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(11),
                'faculty_id' => $islamicStudies?->id,
            ],

            // === RESEARCH PAPERS (2) ===
            [
                'slug' => 'ai-in-islamic-education',
                'title' => [
                    'ar' => 'الذكاء الاصطناعي في خدمة التعليم الإسلامي',
                    'en' => 'Artificial Intelligence in Service of Islamic Education',
                    'fr' => 'L\'intelligence artificielle au service de l\'education islamique',
                    'es' => 'La inteligencia artificial al servicio de la educacion islamica',
                    'zh' => '人工智能服务于伊斯兰教育',
                    'ru' => 'Искусственный интеллект на службе исламского образования',
                    'ur' => 'اسلامی تعلیم کی خدمت میں مصنوعی ذہانت',
                ],
                'subtitle' => [
                    'ar' => 'بحث علمي محكّم',
                    'en' => 'Peer-Reviewed Research Paper',
                    'fr' => 'Article de recherche evalue par les pairs',
                    'es' => 'Articulo de investigacion revisado por pares',
                    'zh' => '同行评审研究论文',
                    'ru' => 'Рецензируемая научная статья',
                    'ur' => 'ہم مرتبہ جائزہ شدہ تحقیقی مقالہ',
                ],
                'description' => [
                    'ar' => 'بحث علمي يستكشف تطبيقات الذكاء الاصطناعي في مجال التعليم الإسلامي، بما في ذلك تحليل النصوص العربية القديمة وأتمتة استخراج الأحكام الفقهية والتعلم التكيفي للطلاب. يقترح إطاراً عملياً لدمج تقنيات الذكاء الاصطناعي في المناهج الأزهرية.',
                    'en' => 'A research paper exploring AI applications in Islamic education, including analysis of classical Arabic texts, automation of jurisprudential ruling extraction, and adaptive learning for students. It proposes a practical framework for integrating AI technologies into Azhari curricula.',
                    'fr' => 'Un article de recherche explorant les applications de l\'IA dans l\'education islamique, y compris l\'analyse de textes arabes classiques, l\'automatisation de l\'extraction de decisions juridiques et l\'apprentissage adaptatif pour les etudiants.',
                    'es' => 'Un articulo de investigacion que explora las aplicaciones de la IA en la educacion islamica, incluyendo el analisis de textos arabes clasicos, la automatizacion de la extraccion de decisiones juridicas y el aprendizaje adaptativo para estudiantes.',
                    'zh' => '一篇探索人工智能在伊斯兰教育中应用的研究论文，包括古典阿拉伯文本分析、法律裁决提取自动化和学生自适应学习。提出了将人工智能技术融入艾资哈尔课程的实用框架。',
                    'ru' => 'Научная статья, исследующая применение ИИ в исламском образовании, включая анализ классических арабских текстов, автоматизацию извлечения правовых решений и адаптивное обучение студентов.',
                    'ur' => 'ایک تحقیقی مقالہ جو اسلامی تعلیم میں مصنوعی ذہانت کے اطلاقات کی تلاش کرتا ہے، بشمول قدیم عربی متون کا تجزیہ، فقہی احکام کے استخراج کی خودکاری اور طلبہ کے لیے موافقتی تعلم۔',
                ],
                'abstract' => [
                    'ar' => 'يستكشف البحث إمكانية استخدام تقنيات الذكاء الاصطناعي في تطوير التعليم الأزهري وتحليل التراث الإسلامي.',
                    'en' => 'The research explores the potential of using AI technologies in developing Azhari education and analyzing Islamic heritage.',
                    'fr' => 'La recherche explore le potentiel de l\'utilisation des technologies d\'IA dans le developpement de l\'education azharie et l\'analyse du patrimoine islamique.',
                    'es' => 'La investigacion explora el potencial del uso de tecnologias de IA en el desarrollo de la educacion azhari y el analisis del patrimonio islamico.',
                    'zh' => '该研究探索利用人工智能技术发展艾资哈尔教育和分析伊斯兰遗产的潜力。',
                    'ru' => 'Исследование рассматривает потенциал использования технологий ИИ в развитии азхарского образования и анализе исламского наследия.',
                    'ur' => 'تحقیق ازہری تعلیم کی ترقی اور اسلامی ورثے کے تجزیے میں مصنوعی ذہانت ٹیکنالوجیز کے استعمال کے امکانات کا جائزہ لیتی ہے۔',
                ],
                'type' => 'research',
                'authors' => ['د. خالد محمد العتيبي', 'د. سارة أحمد الحسيني'],
                'subjects' => ['الذكاء الاصطناعي', 'التعليم الإسلامي', 'التكنولوجيا'],
                'publication_year' => 2025,
                'language' => 'ar',
                'page_count' => 35,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(2),
                'faculty_id' => $engineeringFaculty?->id,
            ],
            [
                'slug' => 'nanotechnology-water-treatment-desert',
                'title' => [
                    'ar' => 'تطبيقات النانو تكنولوجي في معالجة المياه بالمناطق الصحراوية',
                    'en' => 'Nanotechnology Applications in Water Treatment for Desert Regions',
                    'fr' => 'Applications de la nanotechnologie dans le traitement de l\'eau pour les regions desertiques',
                    'es' => 'Aplicaciones de la nanotecnologia en el tratamiento de agua para regiones deserticas',
                    'zh' => '纳米技术在沙漠地区水处理中的应用',
                    'ru' => 'Применение нанотехнологий в очистке воды для пустынных регионов',
                    'ur' => 'صحرائی علاقوں میں پانی کی صفائی میں نینو ٹیکنالوجی کے اطلاقات',
                ],
                'subtitle' => [
                    'ar' => 'بحث علمي محكّم',
                    'en' => 'Peer-Reviewed Research Paper',
                    'fr' => 'Article de recherche evalue par les pairs',
                    'es' => 'Articulo de investigacion revisado por pares',
                    'zh' => '同行评审研究论文',
                    'ru' => 'Рецензируемая научная статья',
                    'ur' => 'ہم مرتبہ جائزہ شدہ تحقیقی مقالہ',
                ],
                'description' => [
                    'ar' => 'بحث علمي يستعرض تطبيقات تقنية النانو في معالجة وتنقية المياه في المناطق الصحراوية. يقدم نتائج تجريبية واعدة لاستخدام جسيمات نانوية مبتكرة في إزالة الملوثات وتحلية المياه بتكلفة منخفضة.',
                    'en' => 'A research paper reviewing nanotechnology applications in water treatment and purification for desert regions. It presents promising experimental results for using innovative nanoparticles in pollutant removal and low-cost water desalination.',
                    'fr' => 'Un article de recherche examinant les applications de la nanotechnologie dans le traitement et la purification de l\'eau pour les regions desertiques. Il presente des resultats experimentaux prometteurs pour l\'utilisation de nanoparticules innovantes.',
                    'es' => 'Un articulo de investigacion que revisa las aplicaciones de la nanotecnologia en el tratamiento y purificacion de agua para regiones deserticas. Presenta resultados experimentales prometedores para el uso de nanoparticulas innovadoras.',
                    'zh' => '一篇综述纳米技术在沙漠地区水处理和净化中应用的研究论文。展示了使用创新纳米颗粒去除污染物和低成本海水淡化的有前景的实验结果。',
                    'ru' => 'Научная статья, рассматривающая применение нанотехнологий в очистке и обессоливании воды в пустынных регионах. Представлены многообещающие экспериментальные результаты использования инновационных наночастиц.',
                    'ur' => 'ایک تحقیقی مقالہ جو صحرائی علاقوں میں پانی کی صفائی اور تطہیر میں نینو ٹیکنالوجی کے اطلاقات کا جائزہ لیتا ہے۔ آلودگی دور کرنے اور کم لاگت سمندری پانی کی تحلیے میں جدید نینو ذرات کے استعمال کے امید افزا تجرباتی نتائج پیش کرتا ہے۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة تجريبية في استخدام تقنية النانو لمعالجة المياه في البيئات الصحراوية.',
                    'en' => 'An experimental study on using nanotechnology for water treatment in desert environments.',
                    'fr' => 'Une etude experimentale sur l\'utilisation de la nanotechnologie pour le traitement de l\'eau dans les environnements desertiques.',
                    'es' => 'Un estudio experimental sobre el uso de la nanotecnologia para el tratamiento del agua en entornos deserticos.',
                    'zh' => '关于在沙漠环境中使用纳米技术进行水处理的实验研究。',
                    'ru' => 'Экспериментальное исследование использования нанотехнологий для очистки воды в пустынных условиях.',
                    'ur' => 'صحرائی ماحول میں پانی کی صفائی کے لیے نینو ٹیکنالوجی کے استعمال پر تجرباتی مطالعہ۔',
                ],
                'type' => 'research',
                'authors' => ['د. مصطفى إبراهيم عبد الحميد', 'د. هالة محمد السيد'],
                'subjects' => ['النانو تكنولوجي', 'معالجة المياه', 'العلوم البيئية'],
                'publication_year' => 2025,
                'language' => 'ar',
                'page_count' => 22,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(1),
                'faculty_id' => $scienceFaculty?->id,
            ],

            // === JOURNAL ARTICLE (1) ===
            [
                'slug' => 'moderation-in-azhari-thought',
                'title' => [
                    'ar' => 'الوسطية في الفكر الأزهري: دراسة تاريخية تحليلية',
                    'en' => 'Moderation in Azhari Thought: A Historical Analytical Study',
                    'fr' => 'La moderation dans la pensee azharie : une etude historique analytique',
                    'es' => 'La moderacion en el pensamiento azhari: un estudio historico analitico',
                    'zh' => '艾资哈尔思想中的中正：历史分析研究',
                    'ru' => 'Умеренность в азхарской мысли: историко-аналитическое исследование',
                    'ur' => 'ازہری فکر میں وسطیت: ایک تاریخی تجزیاتی مطالعہ',
                ],
                'subtitle' => [
                    'ar' => 'مجلة الأزهر العالمية - العدد 47',
                    'en' => 'Al-Azhar International Journal - Issue 47',
                    'fr' => 'Revue internationale d\'Al-Azhar - Numero 47',
                    'es' => 'Revista internacional de Al-Azhar - Numero 47',
                    'zh' => '艾资哈尔国际期刊 - 第47期',
                    'ru' => 'Международный журнал Аль-Азхара - Выпуск 47',
                    'ur' => 'الازہر بین الاقوامی مجلہ - شمارہ 47',
                ],
                'description' => [
                    'ar' => 'مقال علمي منشور في مجلة الأزهر العالمية يتناول مفهوم الوسطية في الفكر الأزهري عبر التاريخ. يحلل كيف حافظ الأزهر على نهج الوسطية والاعتدال في مواجهة التيارات المتطرفة على مر العصور.',
                    'en' => 'A scholarly article in Al-Azhar International Journal examining the concept of moderation in Azhari thought throughout history. It analyzes how Al-Azhar maintained its moderate approach in facing extremist currents across the ages.',
                    'fr' => 'Un article scientifique dans la Revue internationale d\'Al-Azhar examinant le concept de moderation dans la pensee azharie a travers l\'histoire. Il analyse comment Al-Azhar a maintenu son approche moderee face aux courants extremistes.',
                    'es' => 'Un articulo academico en la Revista internacional de Al-Azhar que examina el concepto de moderacion en el pensamiento azhari a lo largo de la historia. Analiza como Al-Azhar mantuvo su enfoque moderado frente a las corrientes extremistas.',
                    'zh' => '发表在艾资哈尔国际期刊上的学术文章，审视艾资哈尔思想中贯穿历史的中正概念。分析了艾资哈尔如何在各个时代面对极端主义思潮时保持其温和立场。',
                    'ru' => 'Научная статья в Международном журнале Аль-Азхара, исследующая концепцию умеренности в азхарской мысли на протяжении истории. Анализирует, как Аль-Азхар сохранял умеренный подход перед лицом экстремистских течений.',
                    'ur' => 'الازہر بین الاقوامی مجلے میں شائع ہونے والا ایک علمی مقالہ جو تاریخ کے دوران ازہری فکر میں وسطیت کے تصور کا جائزہ لیتا ہے۔ تجزیہ کرتا ہے کہ الازہر نے مختلف ادوار میں انتہا پسند رجحانات کے مقابلے میں اپنے معتدل نقطہ نظر کو کیسے برقرار رکھا۔',
                ],
                'abstract' => [
                    'ar' => 'تحليل تاريخي لمنهج الوسطية في الفكر الأزهري ودوره في مواجهة التطرف.',
                    'en' => 'A historical analysis of the moderation approach in Azhari thought and its role in countering extremism.',
                    'fr' => 'Une analyse historique de l\'approche de moderation dans la pensee azharie et son role dans la lutte contre l\'extremisme.',
                    'es' => 'Un analisis historico del enfoque de moderacion en el pensamiento azhari y su papel en la lucha contra el extremismo.',
                    'zh' => '对艾资哈尔思想中中正方法的历史分析及其在反对极端主义中的作用。',
                    'ru' => 'Исторический анализ подхода умеренности в азхарской мысли и его роли в противодействии экстремизму.',
                    'ur' => 'ازہری فکر میں وسطیت کے منہج اور انتہا پسندی کے مقابلے میں اس کے کردار کا تاریخی تجزیہ۔',
                ],
                'type' => 'journal_article',
                'authors' => ['د. حسن محمد الشافعي'],
                'subjects' => ['الوسطية', 'الفكر الأزهري', 'التاريخ الإسلامي'],
                'publisher' => 'مجلة الأزهر العالمية',
                'publication_year' => 2025,
                'issn' => '1110-6344',
                'language' => 'ar',
                'page_count' => 18,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(1),
                'faculty_id' => $theologyFaculty?->id,
            ],

            // === NEW ITEMS (8) ===
            [
                'slug' => 'astronomical-treatises-qibla-direction',
                'title' => [
                    'ar' => 'رسائل فلكية لتحديد اتجاه القبلة',
                    'en' => 'Astronomical Treatises for Qibla Direction',
                    'fr' => 'Traites astronomiques pour la direction de la Qibla',
                    'es' => 'Tratados astronomicos para la direccion de la Qibla',
                    'zh' => '确定朝拜方向的天文论著',
                    'ru' => 'Астрономические трактаты для определения направления Киблы',
                    'ur' => 'قبلے کی سمت کے تعین کے لیے فلکیاتی رسائل',
                ],
                'subtitle' => [
                    'ar' => 'مخطوطات فلكية نادرة لتوجيه المساجد نحو مكة',
                    'en' => 'Rare astronomical manuscripts used to align mosques toward Mecca',
                    'fr' => 'Manuscrits astronomiques rares utilises pour orienter les mosquees vers La Mecque',
                    'es' => 'Manuscritos astronomicos raros utilizados para orientar las mezquitas hacia La Meca',
                    'zh' => '用于确定清真寺朝向麦加方向的珍贵天文手稿',
                    'ru' => 'Редкие астрономические рукописи для ориентации мечетей на Мекку',
                    'ur' => 'مساجد کو مکہ کی طرف سیدھ کرنے کے لیے استعمال ہونے والے نادر فلکیاتی مخطوطات',
                ],
                'description' => [
                    'ar' => 'مجموعة من المخطوطات الفلكية النادرة المحفوظة في مكتبة الأزهر، تتناول طرق تحديد اتجاه القبلة باستخدام حسابات فلكية دقيقة. استُخدمت هذه الرسائل لتوجيه المساجد في مختلف أنحاء العالم الإسلامي نحو مكة المكرمة.',
                    'en' => 'A collection of rare astronomical manuscripts preserved in the Al-Azhar Library, detailing methods for determining the Qibla direction using precise astronomical calculations. These treatises were used to align mosques toward Mecca across the Islamic world.',
                    'fr' => 'Une collection de manuscrits astronomiques rares conserves a la bibliotheque d\'Al-Azhar, detaillant les methodes de determination de la direction de la Qibla a l\'aide de calculs astronomiques precis. Ces traites etaient utilises pour orienter les mosquees vers La Mecque dans le monde islamique.',
                    'es' => 'Una coleccion de manuscritos astronomicos raros conservados en la biblioteca de Al-Azhar, que detallan metodos para determinar la direccion de la Qibla mediante calculos astronomicos precisos. Estos tratados se utilizaron para orientar las mezquitas hacia La Meca en todo el mundo islamico.',
                    'zh' => '艾资哈尔图书馆珍藏的一批珍贵天文手稿，详述了利用精确天文计算确定朝拜方向的方法。这些论著被用于在伊斯兰世界各地确定清真寺朝向麦加的方向。',
                    'ru' => 'Коллекция редких астрономических рукописей, хранящихся в библиотеке Аль-Азхара, описывающих методы определения направления Киблы с помощью точных астрономических расчётов. Эти трактаты использовались для ориентации мечетей на Мекку по всему исламскому миру.',
                    'ur' => 'الازہر لائبریری میں محفوظ نادر فلکیاتی مخطوطات کا مجموعہ جو دقیق فلکیاتی حسابات کے ذریعے قبلے کی سمت معلوم کرنے کے طریقے بیان کرتا ہے۔ یہ رسائل عالم اسلام میں مساجد کو مکہ مکرمہ کی طرف سیدھ کرنے کے لیے استعمال ہوتے تھے۔',
                ],
                'abstract' => [
                    'ar' => 'مخطوطات فلكية نادرة تتناول أساليب تحديد اتجاه القبلة بالحسابات الفلكية.',
                    'en' => 'Rare astronomical manuscripts detailing methods for determining Qibla direction through astronomical calculations.',
                    'fr' => 'Manuscrits astronomiques rares detaillant les methodes de determination de la direction de la Qibla par des calculs astronomiques.',
                    'es' => 'Manuscritos astronomicos raros que detallan metodos para determinar la direccion de la Qibla mediante calculos astronomicos.',
                    'zh' => '详述通过天文计算确定朝拜方向的珍贵天文手稿。',
                    'ru' => 'Редкие астрономические рукописи, описывающие методы определения направления Киблы.',
                    'ur' => 'فلکیاتی حسابات سے قبلے کی سمت معلوم کرنے کے طریقوں پر نادر فلکیاتی مخطوطات۔',
                ],
                'type' => 'manuscript',
                'authors' => ['علماء فلك مسلمون - مكتبة الأزهر'],
                'subjects' => ['الفلك الإسلامي', 'القبلة', 'المخطوطات العلمية'],
                'language' => 'ar',
                'era' => 'mamluk',
                'page_count' => 145,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(2),
                'faculty_id' => $scienceFaculty?->id,
            ],
            [
                'slug' => 'early-azhar-scholarly-debate-records',
                'title' => [
                    'ar' => 'سجلات المناظرات العلمية في الأزهر',
                    'en' => 'Early Al-Azhar Scholarly Debate Records',
                    'fr' => 'Archives des debats savants d\'Al-Azhar',
                    'es' => 'Registros de los debates academicos de Al-Azhar',
                    'zh' => '早期艾资哈尔学术辩论记录',
                    'ru' => 'Записи ранних учёных дебатов Аль-Азхара',
                    'ur' => 'الازہر کی ابتدائی علمی مناظرات کے ریکارڈ',
                ],
                'subtitle' => [
                    'ar' => 'وثائق المناظرات العلمية منذ العصر الفاطمي',
                    'en' => 'Records of scholarly disputations dating back to the Fatimid period',
                    'fr' => 'Archives des disputations savantes remontant a la periode fatimide',
                    'es' => 'Registros de disputas academicas que se remontan al periodo fatimi',
                    'zh' => '可追溯到法蒂玛时期的学术辩论记录',
                    'ru' => 'Записи учёных диспутов со времён Фатимидов',
                    'ur' => 'فاطمی دور سے چلی آنے والی علمی مباحثوں کے ریکارڈ',
                ],
                'description' => [
                    'ar' => 'مجموعة نادرة من سجلات المناظرات العلمية التي جرت في الجامع الأزهر منذ العصر الفاطمي. تُوثق هذه السجلات النقاشات الفقهية والكلامية والفلسفية بين كبار العلماء، وتكشف عن التقاليد العلمية الغنية للأزهر.',
                    'en' => 'A rare collection of records of scholarly disputations held at Al-Azhar dating back to the Fatimid period. These records document jurisprudential, theological, and philosophical debates among senior scholars, revealing Al-Azhar\'s rich scholarly traditions.',
                    'fr' => 'Une collection rare de registres des disputations savantes tenues a Al-Azhar depuis la periode fatimide. Ces archives documentent les debats juridiques, theologiques et philosophiques entre les grands savants.',
                    'es' => 'Una rara coleccion de registros de disputas academicas celebradas en Al-Azhar desde el periodo fatimi. Estos registros documentan los debates juridicos, teologicos y filosoficos entre los grandes eruditos.',
                    'zh' => '一批珍贵的艾资哈尔学术辩论记录，可追溯到法蒂玛时期。这些记录记载了高级学者之间的法学、神学和哲学辩论，揭示了艾资哈尔丰富的学术传统。',
                    'ru' => 'Редкая коллекция записей учёных диспутов в Аль-Азхаре со времён Фатимидов. Записи документируют юридические, богословские и философские дебаты среди старших учёных.',
                    'ur' => 'فاطمی دور سے جامع الازہر میں ہونے والی علمی مناظرات کے نادر ریکارڈ کا مجموعہ۔ یہ ریکارڈ بڑے علماء کے درمیان فقہی، کلامی اور فلسفیانہ مباحثوں کو محفوظ کرتے ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'سجلات توثق المناظرات العلمية في الأزهر منذ العصر الفاطمي بين كبار العلماء.',
                    'en' => 'Records documenting scholarly disputations at Al-Azhar since the Fatimid period among senior scholars.',
                    'fr' => 'Archives documentant les disputations savantes a Al-Azhar depuis la periode fatimide.',
                    'es' => 'Registros que documentan las disputas academicas en Al-Azhar desde el periodo fatimi.',
                    'zh' => '记录法蒂玛时期以来艾资哈尔高级学者间学术辩论的档案。',
                    'ru' => 'Записи, документирующие учёные диспуты в Аль-Азхаре со времён Фатимидов.',
                    'ur' => 'فاطمی دور سے الازہر میں بڑے علماء کے درمیان علمی مناظرات کی دستاویزات۔',
                ],
                'type' => 'manuscript',
                'authors' => ['علماء الأزهر - العصر الفاطمي'],
                'subjects' => ['المناظرات العلمية', 'تاريخ الأزهر', 'الفقه الإسلامي'],
                'language' => 'ar',
                'era' => 'fatimid',
                'page_count' => 320,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(3),
                'faculty_id' => $theologyFaculty?->id,
            ],
            [
                'slug' => 'maliki-jurisprudence-manuscript-collection',
                'title' => [
                    'ar' => 'مجموعة مخطوطات الفقه المالكي',
                    'en' => 'Maliki Jurisprudence Manuscript Collection',
                    'fr' => 'Collection de manuscrits de jurisprudence malekite',
                    'es' => 'Coleccion de manuscritos de jurisprudencia maliki',
                    'zh' => '马利基教法学手稿合集',
                    'ru' => 'Коллекция рукописей маликитской юриспруденции',
                    'ur' => 'مالکی فقہ کے مخطوطات کا مجموعہ',
                ],
                'subtitle' => [
                    'ar' => 'مخطوطات بارزة من المذهب المالكي في مكتبة الأزهر',
                    'en' => 'Notable manuscripts from the Maliki school housed in the Al-Azhar Library',
                    'fr' => 'Manuscrits remarquables de l\'ecole malekite conserves a la bibliotheque d\'Al-Azhar',
                    'es' => 'Manuscritos notables de la escuela maliki conservados en la biblioteca de Al-Azhar',
                    'zh' => '艾资哈尔图书馆珍藏的马利基学派重要手稿',
                    'ru' => 'Выдающиеся рукописи маликитской школы, хранящиеся в библиотеке Аль-Азхара',
                    'ur' => 'الازہر لائبریری میں محفوظ مالکی مسلک کے اہم مخطوطات',
                ],
                'description' => [
                    'ar' => 'مجموعة بارزة من مخطوطات الفقه المالكي المحفوظة في مكتبة الأزهر الشريف، تشمل شروحاً ومختصرات وحواشي على أمهات كتب المذهب المالكي. تعكس هذه المجموعة العناية الكبيرة التي أولاها الأزهر لتدريس ونشر الفقه المالكي عبر القرون.',
                    'en' => 'A notable collection of Maliki jurisprudence manuscripts housed in the Al-Azhar Library, including commentaries, abridgments, and marginalia on foundational Maliki texts. This collection reflects Al-Azhar\'s great attention to teaching and disseminating Maliki jurisprudence over centuries.',
                    'fr' => 'Une collection remarquable de manuscrits de jurisprudence malekite conserves a la bibliotheque d\'Al-Azhar, comprenant des commentaires, des abreges et des gloses sur les textes fondamentaux malekites.',
                    'es' => 'Una notable coleccion de manuscritos de jurisprudencia maliki conservados en la biblioteca de Al-Azhar, incluyendo comentarios, compendios y glosas sobre textos fundamentales malikies.',
                    'zh' => '艾资哈尔图书馆珍藏的马利基教法学手稿精品，包括对马利基学派基础文献的注释、缩编和旁注，反映了艾资哈尔数个世纪以来对马利基教法学教授和传播的重视。',
                    'ru' => 'Выдающаяся коллекция рукописей маликитской юриспруденции в библиотеке Аль-Азхара, включающая комментарии, сокращения и глоссы к основным маликитским текстам.',
                    'ur' => 'الازہر لائبریری میں محفوظ مالکی فقہ کے مخطوطات کا ایک اہم مجموعہ جس میں مالکی مسلک کی بنیادی کتابوں پر شروحات، مختصرات اور حواشی شامل ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'مجموعة مخطوطات الفقه المالكي في مكتبة الأزهر تشمل شروحاً ومختصرات على أمهات الكتب المالكية.',
                    'en' => 'Maliki jurisprudence manuscript collection at Al-Azhar Library including commentaries and abridgments on foundational Maliki texts.',
                    'fr' => 'Collection de manuscrits de jurisprudence malekite a la bibliotheque d\'Al-Azhar comprenant des commentaires et abreges.',
                    'es' => 'Coleccion de manuscritos de jurisprudencia maliki en la biblioteca de Al-Azhar con comentarios y compendios.',
                    'zh' => '艾资哈尔图书馆的马利基教法学手稿合集，包含对基础文献的注释和缩编。',
                    'ru' => 'Коллекция рукописей маликитской юриспруденции в библиотеке Аль-Азхара с комментариями и сокращениями.',
                    'ur' => 'الازہر لائبریری میں مالکی فقہ کے مخطوطات کا مجموعہ جس میں بنیادی مالکی کتابوں پر شروحات شامل ہیں۔',
                ],
                'type' => 'manuscript',
                'authors' => ['علماء المذهب المالكي'],
                'subjects' => ['الفقه المالكي', 'المخطوطات الإسلامية', 'الفقه الإسلامي'],
                'language' => 'ar',
                'era' => 'mamluk',
                'page_count' => 480,
                'access_level' => 'premium',
                'is_published' => true,
                'published_at' => now()->subMonths(2),
                'faculty_id' => $shariaFaculty?->id,
            ],
            [
                'slug' => 'document-on-human-fraternity-book',
                'title' => [
                    'ar' => 'وثيقة الأخوة الإنسانية',
                    'en' => 'Document on Human Fraternity',
                    'fr' => 'Document sur la Fraternite Humaine',
                    'es' => 'Documento sobre la Fraternidad Humana',
                    'zh' => '人类博爱文件',
                    'ru' => 'Документ о человеческом братстве',
                    'ur' => 'انسانی اخوت کی دستاویز',
                ],
                'subtitle' => [
                    'ar' => 'الوثيقة التاريخية الموقعة في أبوظبي 2019',
                    'en' => 'The historic document signed in Abu Dhabi, 2019',
                    'fr' => 'Le document historique signe a Abu Dhabi en 2019',
                    'es' => 'El documento historico firmado en Abu Dabi, 2019',
                    'zh' => '2019年在阿布扎比签署的历史性文件',
                    'ru' => 'Исторический документ, подписанный в Абу-Даби в 2019 году',
                    'ur' => '2019 میں ابوظبی میں دستخط شدہ تاریخی دستاویز',
                ],
                'description' => [
                    'ar' => 'الوثيقة التاريخية التي وقعها الإمام الأكبر أحمد الطيب شيخ الأزهر والبابا فرنسيس بابا الكنيسة الكاثوليكية في أبوظبي عام 2019. تدعو إلى السلام والتعايش والتسامح بين الأديان والشعوب، وأصبحت مرجعاً عالمياً للحوار بين الأديان.',
                    'en' => 'The historic document signed by Grand Imam Ahmed el-Tayeb, Sheikh of Al-Azhar, and Pope Francis, head of the Catholic Church, in Abu Dhabi in 2019. It calls for peace, coexistence, and tolerance among religions and peoples, and has become a global reference for interfaith dialogue.',
                    'fr' => 'Le document historique signe par le Grand Imam Ahmed el-Tayeb et le pape Francois a Abu Dhabi en 2019. Il appelle a la paix, a la coexistence et a la tolerance entre les religions et les peuples.',
                    'es' => 'El documento historico firmado por el Gran Imam Ahmed el-Tayeb y el papa Francisco en Abu Dabi en 2019. Llama a la paz, la coexistencia y la tolerancia entre religiones y pueblos.',
                    'zh' => '2019年大伊玛目艾哈迈德·泰耶布与教皇方济各在阿布扎比签署的历史性文件。呼吁宗教和民族间的和平、共存与包容，已成为全球宗教间对话的重要参考文件。',
                    'ru' => 'Исторический документ, подписанный Великим имамом Ахмедом ат-Тайибом и Папой Франциском в Абу-Даби в 2019 году. Призывает к миру, сосуществованию и терпимости между религиями и народами.',
                    'ur' => '2019 میں ابوظبی میں شیخ الازہر احمد الطیب اور پوپ فرانسس کی دستخط کردہ تاریخی دستاویز۔ مذاہب اور اقوام کے درمیان امن، بقائے باہمی اور رواداری کی دعوت دیتی ہے۔',
                ],
                'abstract' => [
                    'ar' => 'وثيقة تاريخية للحوار بين الأديان وقعها شيخ الأزهر والبابا فرنسيس في أبوظبي 2019.',
                    'en' => 'A historic interfaith dialogue document signed by the Grand Imam and Pope Francis in Abu Dhabi, 2019.',
                    'fr' => 'Un document historique de dialogue interreligieux signe par le Grand Imam et le pape Francois a Abu Dhabi en 2019.',
                    'es' => 'Un documento historico de dialogo interreligioso firmado por el Gran Imam y el papa Francisco en Abu Dabi, 2019.',
                    'zh' => '2019年大伊玛目与教皇方济各在阿布扎比签署的历史性宗教间对话文件。',
                    'ru' => 'Исторический документ межрелигиозного диалога, подписанный Великим имамом и Папой Франциском в 2019 году.',
                    'ur' => '2019 میں شیخ الازہر اور پوپ فرانسس کی ابوظبی میں دستخط کردہ بین المذاہب مکالمے کی تاریخی دستاویز۔',
                ],
                'type' => 'book',
                'authors' => ['الإمام الأكبر أحمد الطيب', 'البابا فرنسيس'],
                'subjects' => ['الحوار بين الأديان', 'الأخوة الإنسانية', 'السلام العالمي'],
                'publication_year' => 2019,
                'language' => 'ar',
                'page_count' => 48,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(4),
                'faculty_id' => $theologyFaculty?->id,
            ],
            [
                'slug' => 'al-azhar-magazine-archive',
                'title' => [
                    'ar' => 'أرشيف مجلة الأزهر',
                    'en' => 'Al-Azhar Magazine Archive (1930-2026)',
                    'fr' => 'Archives de la revue Al-Azhar (1930-2026)',
                    'es' => 'Archivo de la revista Al-Azhar (1930-2026)',
                    'zh' => '艾资哈尔杂志档案（1930-2026）',
                    'ru' => 'Архив журнала Аль-Азхар (1930-2026)',
                    'ur' => 'مجلہ الازہر کا آرکائیو (1930-2026)',
                ],
                'subtitle' => [
                    'ar' => 'أقدم مجلة علمية إسلامية صدرت بلا انقطاع',
                    'en' => 'The oldest continuously published Islamic scholarly journal',
                    'fr' => 'La plus ancienne revue savante islamique publiee sans interruption',
                    'es' => 'La revista academica islamica de publicacion continua mas antigua',
                    'zh' => '持续出版时间最长的伊斯兰学术期刊',
                    'ru' => 'Старейший непрерывно издаваемый исламский научный журнал',
                    'ur' => 'مسلسل شائع ہونے والا قدیم ترین اسلامی علمی مجلہ',
                ],
                'description' => [
                    'ar' => 'أرشيف رقمي شامل لمجلة الأزهر الشريف، أقدم مجلة علمية إسلامية لا تزال تصدر بلا انقطاع منذ عام 1930م. يضم الأرشيف آلاف المقالات في الفقه والتفسير واللغة العربية والقضايا المعاصرة لكبار علماء الأزهر.',
                    'en' => 'A comprehensive digital archive of Al-Azhar Magazine, the oldest continuously published Islamic scholarly journal since 1930. The archive contains thousands of articles on jurisprudence, Quranic exegesis, Arabic language, and contemporary issues by senior Al-Azhar scholars.',
                    'fr' => 'Archives numeriques completes de la revue Al-Azhar, la plus ancienne revue savante islamique publiee sans interruption depuis 1930. L\'archive contient des milliers d\'articles des grands savants d\'Al-Azhar.',
                    'es' => 'Archivo digital completo de la revista Al-Azhar, la revista academica islamica de publicacion continua mas antigua desde 1930. El archivo contiene miles de articulos de los grandes eruditos de Al-Azhar.',
                    'zh' => '艾资哈尔杂志的综合数字档案，这是自1930年以来持续出版时间最长的伊斯兰学术期刊。档案收录了艾资哈尔资深学者在教法、经注、阿拉伯语和当代议题方面的数千篇文章。',
                    'ru' => 'Полный цифровой архив журнала Аль-Азхар — старейшего непрерывно издаваемого исламского научного журнала с 1930 года. Архив содержит тысячи статей ведущих учёных Аль-Азхара.',
                    'ur' => 'مجلہ الازہر کا جامع ڈیجیٹل آرکائیو، 1930 سے مسلسل شائع ہونے والا قدیم ترین اسلامی علمی مجلہ۔ آرکائیو میں الازہر کے بڑے علماء کے فقہ، تفسیر، عربی زبان اور معاصر مسائل پر ہزاروں مضامین شامل ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'أرشيف رقمي لمجلة الأزهر العريقة الصادرة منذ 1930م يضم آلاف المقالات العلمية.',
                    'en' => 'Digital archive of the long-standing Al-Azhar Magazine published since 1930, containing thousands of scholarly articles.',
                    'fr' => 'Archives numeriques de la revue Al-Azhar publiee depuis 1930, contenant des milliers d\'articles savants.',
                    'es' => 'Archivo digital de la revista Al-Azhar publicada desde 1930, con miles de articulos academicos.',
                    'zh' => '自1930年出版的艾资哈尔杂志数字档案，收录数千篇学术文章。',
                    'ru' => 'Цифровой архив журнала Аль-Азхар, издающегося с 1930 года, с тысячами научных статей.',
                    'ur' => '1930 سے شائع ہونے والے مجلہ الازہر کا ڈیجیٹل آرکائیو جس میں ہزاروں علمی مقالات شامل ہیں۔',
                ],
                'type' => 'journal_article',
                'authors' => ['هيئة تحرير مجلة الأزهر'],
                'subjects' => ['الدراسات الإسلامية', 'الفقه', 'اللغة العربية'],
                'publisher' => 'مجمع البحوث الإسلامية',
                'publication_year' => 2026,
                'issn' => '1110-6344',
                'language' => 'ar',
                'page_count' => 96,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subWeeks(2),
                'faculty_id' => null,
            ],
            [
                'slug' => 'catalogue-arabic-manuscripts-azhar-library',
                'title' => [
                    'ar' => 'فهرس المخطوطات العربية في مكتبة الأزهر',
                    'en' => 'Catalogue of Arabic Manuscripts in Al-Azhar Library',
                    'fr' => 'Catalogue des manuscrits arabes de la bibliotheque d\'Al-Azhar',
                    'es' => 'Catalogo de manuscritos arabes en la biblioteca de Al-Azhar',
                    'zh' => '艾资哈尔图书馆阿拉伯文手稿目录',
                    'ru' => 'Каталог арабских рукописей библиотеки Аль-Азхара',
                    'ur' => 'الازہر لائبریری کے عربی مخطوطات کی فہرست',
                ],
                'subtitle' => [
                    'ar' => 'توثيق شامل لأكثر من 50,000 مخطوط في 7 ملايين صفحة',
                    'en' => 'Comprehensive catalogue documenting 50,000+ manuscripts across 7 million pages',
                    'fr' => 'Catalogue complet documentant plus de 50 000 manuscrits sur 7 millions de pages',
                    'es' => 'Catalogo completo que documenta mas de 50.000 manuscritos en 7 millones de paginas',
                    'zh' => '记录50,000多部手稿、共700万页的综合目录',
                    'ru' => 'Полный каталог, описывающий более 50 000 рукописей на 7 миллионах страниц',
                    'ur' => '7 ملین صفحات پر مشتمل 50,000 سے زائد مخطوطات کی جامع فہرست',
                ],
                'description' => [
                    'ar' => 'فهرس شامل يوثق المخطوطات العربية المحفوظة في مكتبة الأزهر الشريف والتي يزيد عددها عن 50,000 مخطوط في نحو 7 ملايين صفحة. يغطي الفهرس مخطوطات في علوم القرآن والحديث والفقه والتصوف واللغة والأدب والعلوم الطبيعية والفلك.',
                    'en' => 'A comprehensive catalogue documenting the Arabic manuscripts preserved in the Al-Azhar Library, numbering over 50,000 manuscripts across approximately 7 million pages. The catalogue covers manuscripts in Quranic sciences, hadith, jurisprudence, Sufism, language, literature, natural sciences, and astronomy.',
                    'fr' => 'Un catalogue complet documentant les manuscrits arabes conserves a la bibliotheque d\'Al-Azhar, soit plus de 50 000 manuscrits sur environ 7 millions de pages, couvrant les sciences coraniques, le hadith, la jurisprudence et les sciences naturelles.',
                    'es' => 'Un catalogo completo que documenta los manuscritos arabes conservados en la biblioteca de Al-Azhar, mas de 50.000 manuscritos en aproximadamente 7 millones de paginas, cubriendo ciencias coranicas, hadiz, jurisprudencia y ciencias naturales.',
                    'zh' => '全面记录艾资哈尔图书馆珍藏的阿拉伯文手稿目录，共50,000多部手稿约700万页，涵盖古兰经学、圣训学、教法学、苏菲学、语言文学和自然科学等领域。',
                    'ru' => 'Всеобъемлющий каталог арабских рукописей библиотеки Аль-Азхара — более 50 000 рукописей на примерно 7 миллионах страниц, охватывающих коранические науки, хадисоведение, юриспруденцию, суфизм и естественные науки.',
                    'ur' => 'الازہر لائبریری میں محفوظ عربی مخطوطات کی جامع فہرست جن کی تعداد 50,000 سے زائد ہے اور تقریباً 7 ملین صفحات پر مشتمل ہیں۔ فہرست میں علوم القرآن، حدیث، فقہ، تصوف، زبان، ادب اور سائنس کے مخطوطات شامل ہیں۔',
                ],
                'abstract' => [
                    'ar' => 'فهرس يوثق أكثر من 50,000 مخطوط عربي في مكتبة الأزهر تغطي شتى العلوم الإسلامية والطبيعية.',
                    'en' => 'A catalogue documenting over 50,000 Arabic manuscripts in the Al-Azhar Library covering diverse Islamic and natural sciences.',
                    'fr' => 'Un catalogue documentant plus de 50 000 manuscrits arabes couvrant diverses sciences islamiques et naturelles.',
                    'es' => 'Un catalogo que documenta mas de 50.000 manuscritos arabes que cubren diversas ciencias islamicas y naturales.',
                    'zh' => '记录艾资哈尔图书馆50,000多部阿拉伯文手稿的目录，涵盖伊斯兰和自然科学各领域。',
                    'ru' => 'Каталог более 50 000 арабских рукописей библиотеки Аль-Азхара по различным исламским и естественным наукам.',
                    'ur' => 'الازہر لائبریری کے 50,000 سے زائد عربی مخطوطات کی فہرست جو مختلف اسلامی اور سائنسی علوم کا احاطہ کرتی ہے۔',
                ],
                'type' => 'book',
                'authors' => ['إدارة المخطوطات بمكتبة الأزهر'],
                'subjects' => ['المخطوطات العربية', 'مكتبة الأزهر', 'الفهرسة'],
                'publisher' => 'مطبعة الأزهر',
                'publication_year' => 2020,
                'language' => 'ar',
                'page_count' => 1200,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(3),
                'faculty_id' => null,
            ],
            [
                'slug' => 'essentials-of-islam-el-tayeb',
                'title' => [
                    'ar' => 'أساسيات الإسلام - أحمد الطيب',
                    'en' => 'The Essentials of Islam by Ahmed el-Tayeb',
                    'fr' => 'Les fondements de l\'Islam par Ahmed el-Tayeb',
                    'es' => 'Los fundamentos del Islam por Ahmed el-Tayeb',
                    'zh' => '伊斯兰基础 - 艾哈迈德·泰耶布',
                    'ru' => 'Основы ислама — Ахмед ат-Тайиб',
                    'ur' => 'اسلام کی بنیادیں - احمد الطیب',
                ],
                'subtitle' => [
                    'ar' => 'نص تأسيسي في المبادئ الإسلامية لشيخ الأزهر',
                    'en' => 'A foundational text on Islamic principles by the Grand Imam',
                    'fr' => 'Un texte fondamental sur les principes islamiques par le Grand Imam',
                    'es' => 'Un texto fundamental sobre los principios islamicos por el Gran Imam',
                    'zh' => '大伊玛目关于伊斯兰原则的基础著作',
                    'ru' => 'Основополагающий текст о принципах ислама от Великого имама',
                    'ur' => 'شیخ الازہر کی اسلامی اصولوں پر بنیادی تصنیف',
                ],
                'description' => [
                    'ar' => 'كتاب تأسيسي للإمام الأكبر أحمد الطيب شيخ الأزهر يتناول أساسيات الإسلام ومبادئه الجوهرية بأسلوب واضح ومعاصر. يشرح أركان الإسلام والإيمان ومقاصد الشريعة ومنهج الأزهر الوسطي في فهم الدين.',
                    'en' => 'A foundational text by Grand Imam Ahmed el-Tayeb, Sheikh of Al-Azhar, covering the essentials of Islam and its core principles in a clear and contemporary style. It explains the pillars of Islam and faith, the objectives of Sharia, and Al-Azhar\'s moderate approach to understanding religion.',
                    'fr' => 'Un texte fondamental du Grand Imam Ahmed el-Tayeb couvrant les fondements de l\'Islam et ses principes fondamentaux dans un style clair et contemporain. Il explique les piliers de l\'Islam, les objectifs de la Charia et l\'approche moderee d\'Al-Azhar.',
                    'es' => 'Un texto fundamental del Gran Imam Ahmed el-Tayeb que cubre los fundamentos del Islam y sus principios basicos en un estilo claro y contemporaneo. Explica los pilares del Islam, los objetivos de la Sharia y el enfoque moderado de Al-Azhar.',
                    'zh' => '大伊玛目艾哈迈德·泰耶布以清晰现代的文风阐述伊斯兰教基本要义和核心原则的基础性著作。解释了伊斯兰五功、信仰六柱、教法目的和艾资哈尔的中正理解方法。',
                    'ru' => 'Основополагающий труд Великого имама Ахмеда ат-Тайиба, охватывающий основы ислама и его ключевые принципы в ясном современном стиле. Объясняет столпы ислама и веры, цели шариата и умеренный подход Аль-Азхара.',
                    'ur' => 'شیخ الازہر احمد الطیب کی بنیادی تصنیف جو واضح اور معاصر انداز میں اسلام کی بنیادیں اور بنیادی اصول بیان کرتی ہے۔ اسلام اور ایمان کے ارکان، شریعت کے مقاصد اور الازہر کا معتدل منہج بیان کیا گیا ہے۔',
                ],
                'abstract' => [
                    'ar' => 'كتاب لشيخ الأزهر يتناول أساسيات الإسلام وأركانه ومقاصد الشريعة بمنهج وسطي.',
                    'en' => 'A book by the Grand Imam covering Islamic essentials, pillars, and Sharia objectives with a moderate approach.',
                    'fr' => 'Un livre du Grand Imam couvrant les fondements de l\'Islam, ses piliers et les objectifs de la Charia avec une approche moderee.',
                    'es' => 'Un libro del Gran Imam que cubre los fundamentos del Islam, sus pilares y los objetivos de la Sharia con un enfoque moderado.',
                    'zh' => '大伊玛目关于伊斯兰基础、五功和教法目的的中正阐述。',
                    'ru' => 'Книга Великого имама об основах ислама, его столпах и целях шариата с умеренным подходом.',
                    'ur' => 'شیخ الازہر کی کتاب جو اسلام کی بنیادیں، ارکان اور شریعت کے مقاصد معتدل منہج سے بیان کرتی ہے۔',
                ],
                'type' => 'book',
                'authors' => ['الإمام الأكبر أحمد الطيب'],
                'subjects' => ['أصول الإسلام', 'العقيدة', 'الفكر الأزهري'],
                'publisher' => 'دار الشروق',
                'publication_year' => 2017,
                'language' => 'ar',
                'page_count' => 280,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(5),
                'faculty_id' => $theologyFaculty?->id,
            ],
            [
                'slug' => 'ethics-and-values-el-tayeb',
                'title' => [
                    'ar' => 'الأخلاق والقيم - أحمد الطيب',
                    'en' => 'Ethics and Values by Ahmed el-Tayeb',
                    'fr' => 'Ethique et valeurs par Ahmed el-Tayeb',
                    'es' => 'Etica y valores por Ahmed el-Tayeb',
                    'zh' => '伦理与价值观 - 艾哈迈德·泰耶布',
                    'ru' => 'Этика и ценности — Ахмед ат-Тайиб',
                    'ur' => 'اخلاق اور اقدار - احمد الطیب',
                ],
                'subtitle' => [
                    'ar' => 'استكشاف الإطار الأخلاقي الإسلامي',
                    'en' => 'Exploration of Islamic ethical framework by the Grand Imam',
                    'fr' => 'Exploration du cadre ethique islamique par le Grand Imam',
                    'es' => 'Exploracion del marco etico islamico por el Gran Imam',
                    'zh' => '大伊玛目对伊斯兰伦理框架的探讨',
                    'ru' => 'Исследование исламской этической системы Великим имамом',
                    'ur' => 'شیخ الازہر کی اسلامی اخلاقی نظام کی تحقیق',
                ],
                'description' => [
                    'ar' => 'كتاب للإمام الأكبر أحمد الطيب يستكشف الإطار الأخلاقي في الإسلام وقيمه الأساسية. يتناول منظومة الأخلاق الإسلامية من منظور أزهري وسطي، ويربط بين القيم الإسلامية والقيم الإنسانية العالمية في سياق الحوار الحضاري المعاصر.',
                    'en' => 'A book by Grand Imam Ahmed el-Tayeb exploring the Islamic ethical framework and its core values. It examines the Islamic moral system from Al-Azhar\'s moderate perspective, connecting Islamic values with universal human values in the context of contemporary civilizational dialogue.',
                    'fr' => 'Un livre du Grand Imam Ahmed el-Tayeb explorant le cadre ethique islamique et ses valeurs fondamentales. Il examine le systeme moral islamique dans la perspective moderee d\'Al-Azhar, reliant les valeurs islamiques aux valeurs humaines universelles.',
                    'es' => 'Un libro del Gran Imam Ahmed el-Tayeb que explora el marco etico islamico y sus valores fundamentales. Examina el sistema moral islamico desde la perspectiva moderada de Al-Azhar, conectando los valores islamicos con los valores humanos universales.',
                    'zh' => '大伊玛目艾哈迈德·泰耶布探讨伊斯兰伦理框架及其核心价值观的著作。从艾资哈尔中正视角审视伊斯兰道德体系，将伊斯兰价值观与当代文明对话中的人类普世价值观相联系。',
                    'ru' => 'Книга Великого имама Ахмеда ат-Тайиба, исследующая исламскую этическую систему и её основные ценности. Рассматривает исламскую нравственную систему с умеренной позиции Аль-Азхара, связывая исламские ценности с универсальными человеческими ценностями.',
                    'ur' => 'شیخ الازہر احمد الطیب کی کتاب جو اسلامی اخلاقی نظام اور بنیادی اقدار کا جائزہ لیتی ہے۔ الازہر کے معتدل نقطہ نظر سے اسلامی اخلاقی نظام کا مطالعہ کرتی ہے اور معاصر تہذیبی مکالمے میں اسلامی اقدار کو عالمگیر انسانی اقدار سے جوڑتی ہے۔',
                ],
                'abstract' => [
                    'ar' => 'دراسة للإطار الأخلاقي الإسلامي وعلاقته بالقيم الإنسانية العالمية من منظور أزهري وسطي.',
                    'en' => 'A study of the Islamic ethical framework and its relationship to universal human values from Al-Azhar\'s moderate perspective.',
                    'fr' => 'Une etude du cadre ethique islamique et de sa relation aux valeurs humaines universelles dans la perspective moderee d\'Al-Azhar.',
                    'es' => 'Un estudio del marco etico islamico y su relacion con los valores humanos universales desde la perspectiva moderada de Al-Azhar.',
                    'zh' => '从艾资哈尔中正视角研究伊斯兰伦理框架及其与人类普世价值的关系。',
                    'ru' => 'Исследование исламской этической системы и её связи с универсальными человеческими ценностями с позиции Аль-Азхара.',
                    'ur' => 'الازہر کے معتدل نقطہ نظر سے اسلامی اخلاقی نظام اور عالمگیر انسانی اقدار سے اس کے تعلق کا مطالعہ۔',
                ],
                'type' => 'book',
                'authors' => ['الإمام الأكبر أحمد الطيب'],
                'subjects' => ['الأخلاق الإسلامية', 'القيم', 'الحوار الحضاري'],
                'publisher' => 'دار الشروق',
                'publication_year' => 2018,
                'language' => 'ar',
                'page_count' => 320,
                'access_level' => 'free',
                'is_published' => true,
                'published_at' => now()->subMonths(5),
                'faculty_id' => $theologyFaculty?->id,
            ],
        ];

        foreach ($items as $data) {
            $item = new LibraryItem();
            $item->slug = $data['slug'];
            $item->title = $data['title'];
            $item->subtitle = $data['subtitle'];
            $item->description = $data['description'];
            $item->abstract = $data['abstract'];
            $item->type = $data['type'];
            $item->authors = $data['authors'];
            $item->subjects = $data['subjects'];
            $item->publisher = $data['publisher'] ?? null;
            $item->publication_year = $data['publication_year'] ?? null;
            $item->isbn = $data['isbn'] ?? null;
            $item->issn = $data['issn'] ?? null;
            $item->language = $data['language'];
            $item->era = $data['era'] ?? null;
            $item->page_count = $data['page_count'] ?? null;
            $item->access_level = $data['access_level'];
            $item->is_published = $data['is_published'];
            $item->published_at = $data['published_at'];
            $item->faculty_id = $data['faculty_id'];
            $item->save();
        }
    }
}
