<?php

namespace Database\Seeders;

use App\Models\NewsArticle;
use App\Models\NewsCategory;
use Illuminate\Database\Seeder;

class NewsArticleSeeder extends Seeder
{
    public function run(): void
    {
        $academic = NewsCategory::where('slug', 'academic')->first();
        $international = NewsCategory::where('slug', 'international')->first();
        $events = NewsCategory::where('slug', 'events')->first();
        $research = NewsCategory::where('slug', 'research')->first();

        $articles = [
            [
                'slug' => 'azhar-the-world-rankings-2025',
                'title' => [
                    'ar' => 'جامعة الأزهر تدخل تصنيفات THE العالمية 2025',
                    'en' => 'Al-Azhar University Enters THE World Rankings 2025',
                    'fr' => 'L\'Universite d\'Al-Azhar entre dans le classement mondial THE 2025',
                    'es' => 'La Universidad de Al-Azhar entra en las clasificaciones mundiales THE 2025',
                    'zh' => '艾资哈尔大学进入2025年THE世界大学排名',
                    'ru' => 'Университет Аль-Азхар входит в мировой рейтинг THE 2025',
                    'ur' => 'الازہر یونیورسٹی THE عالمی درجہ بندی 2025 میں شامل',
                ],
                'excerpt' => [
                    'ar' => 'حققت جامعة الأزهر تصنيفات متقدمة في تصنيفات تايمز للتعليم العالي 2025: الهندسة (501-600)، علوم الحياة (401-500)، العلوم الطبية (501-600).',
                    'en' => 'Al-Azhar University achieved notable rankings in THE World University Rankings 2025: Engineering (501-600), Life Sciences (401-500), Medical & Health Sciences (501-600).',
                    'fr' => 'Al-Azhar a obtenu des classements notables dans THE 2025: Ingenierie (501-600), Sciences de la vie (401-500).',
                    'es' => 'Al-Azhar logro clasificaciones notables en THE 2025: Ingenieria (501-600), Ciencias de la vida (401-500).',
                    'zh' => '艾资哈尔在THE 2025排名中取得显著成绩：工程(501-600)，生命科学(401-500)。',
                    'ru' => 'Аль-Азхар достиг заметных рейтингов в THE 2025: Инженерия (501-600), Науки о жизни (401-500).',
                    'ur' => 'الازہر نے THE 2025 میں قابل ذکر درجہ بندی حاصل کی: انجینئرنگ (501-600)، لائف سائنسز (401-500)۔',
                ],
                'content' => [
                    'ar' => 'حققت جامعة الأزهر إنجازاً أكاديمياً بارزاً بدخولها تصنيفات تايمز للتعليم العالي العالمية 2025 في عدة تخصصات. جاءت الجامعة في المرتبة 501-600 في الهندسة، و401-500 في علوم الحياة، و501-600 في العلوم الطبية والصحية، و601-800 في علوم الحاسب. كما أُدرجت ضمن أفضل 1000 جامعة عالمياً في تصنيف شنغهاي العالمي وتصنيف CWUR لعام 2024. يعكس هذا الإنجاز جهود الجامعة المتواصلة في تطوير البحث العلمي والارتقاء بالمستوى الأكاديمي.',
                    'en' => 'Al-Azhar University achieved a notable academic milestone by entering the Times Higher Education World Rankings 2025 in multiple disciplines. The university ranked 501-600 in Engineering, 401-500 in Life Sciences, 501-600 in Medical & Health Sciences, and 601-800 in Computer Science. It was also listed among the top 1,000 universities globally in the Shanghai Global Ranking and CWUR 2024 rankings. This reflects the university\'s continuous efforts in advancing scientific research and academic excellence.',
                    'fr' => 'L\'Universite d\'Al-Azhar a atteint une etape academique notable en entrant dans les classements mondiaux THE 2025 dans plusieurs disciplines.',
                    'es' => 'La Universidad de Al-Azhar alcanzo un hito academico notable al entrar en las clasificaciones mundiales THE 2025 en multiples disciplinas.',
                    'zh' => '艾资哈尔大学在THE 2025世界大学排名中取得了显著的学术里程碑。',
                    'ru' => 'Университет Аль-Азхар достиг заметного академического рубежа, войдя в мировой рейтинг THE 2025 по нескольким дисциплинам.',
                    'ur' => 'الازہر یونیورسٹی نے متعدد شعبوں میں THE عالمی درجہ بندی 2025 میں داخل ہو کر قابل ذکر اکیڈمک سنگ میل حاصل کیا۔',
                ],
                'category_id' => $academic?->id,
                'is_published' => true,
                'published_at' => '2025-01-15 10:00:00',
            ],
            [
                'slug' => 'muhammadiyah-cooperation-renewed',
                'title' => [
                    'ar' => 'تجديد اتفاقية التعاون مع المحمدية الإندونيسية',
                    'en' => 'Cooperation Agreement Renewed with Indonesian Muhammadiyah',
                    'fr' => 'Renouvellement de l\'accord de cooperation avec la Muhammadiyah indonesienne',
                    'es' => 'Renovacion del acuerdo de cooperacion con Muhammadiyah de Indonesia',
                    'zh' => '与印尼穆罕默迪亚续签合作协议',
                    'ru' => 'Обновление соглашения о сотрудничестве с индонезийской Мухаммадией',
                    'ur' => 'انڈونیشیائی محمدیہ کے ساتھ تعاون کے معاہدے کی تجدید',
                ],
                'excerpt' => [
                    'ar' => 'جددت جامعة الأزهر اتفاقية التعاون مع منظمة المحمدية، إحدى أكبر المنظمات الإسلامية في إندونيسيا.',
                    'en' => 'Al-Azhar University renewed its cooperation agreement with Muhammadiyah, one of Indonesia\'s largest Islamic organizations.',
                    'fr' => 'Al-Azhar a renouvele son accord avec la Muhammadiyah, l\'une des plus grandes organisations islamiques d\'Indonesie.',
                    'es' => 'Al-Azhar renovo su acuerdo con Muhammadiyah, una de las mayores organizaciones islamicas de Indonesia.',
                    'zh' => '艾资哈尔与印尼最大的伊斯兰组织之一穆罕默迪亚续签了合作协议。',
                    'ru' => 'Аль-Азхар обновил соглашение с Мухаммадией, одной из крупнейших исламских организаций Индонезии.',
                    'ur' => 'الازہر نے انڈونیشیا کی سب سے بڑی اسلامی تنظیموں میں سے ایک محمدیہ کے ساتھ معاہدے کی تجدید کی۔',
                ],
                'content' => [
                    'ar' => 'في إطار تعزيز العلاقات الأكاديمية الدولية، جددت جامعة الأزهر اتفاقية التعاون مع منظمة المحمدية الإندونيسية عام 2025م. تشمل الاتفاقية تبادل الطلاب والأساتذة والبرامج البحثية المشتركة وتطوير مناهج الدراسات الإسلامية. تُعد المحمدية من أكبر المنظمات الإسلامية في إندونيسيا ولها جامعات ومدارس في مختلف أنحاء البلاد.',
                    'en' => 'As part of strengthening international academic relations, Al-Azhar University renewed its cooperation agreement with Indonesia\'s Muhammadiyah organization in 2025. The agreement includes student and faculty exchange, joint research programs, and Islamic studies curriculum development. Muhammadiyah is one of Indonesia\'s largest Islamic organizations with universities and schools across the country.',
                    'fr' => 'L\'Universite d\'Al-Azhar a renouvele son accord de cooperation avec la Muhammadiyah indonesienne en 2025.',
                    'es' => 'La Universidad de Al-Azhar renovo su acuerdo de cooperacion con la Muhammadiyah indonesiana en 2025.',
                    'zh' => '作为加强国际学术关系的一部分，艾资哈尔大学于2025年与印尼穆罕默迪亚组织续签了合作协议。',
                    'ru' => 'В рамках укрепления международных академических связей Аль-Азхар обновил соглашение с Мухаммадией в 2025 году.',
                    'ur' => 'بین الاقوامی اکیڈمک تعلقات کو مضبوط بنانے کے تحت الازہر نے 2025 میں محمدیہ کے ساتھ معاہدے کی تجدید کی۔',
                ],
                'category_id' => $international?->id,
                'is_published' => true,
                'published_at' => '2025-02-20 09:00:00',
            ],
            [
                'slug' => 'english-resource-centre-upper-egypt',
                'title' => [
                    'ar' => 'افتتاح مركز موارد اللغة الإنجليزية لصعيد مصر',
                    'en' => 'English Language Resource Centre Inaugurated for Upper Egypt',
                    'fr' => 'Inauguration du Centre de Ressources en Anglais pour la Haute-Egypte',
                    'es' => 'Inauguracion del Centro de Recursos de Ingles para el Alto Egipto',
                    'zh' => '上埃及英语语言资源中心揭幕',
                    'ru' => 'Открыт Центр ресурсов английского языка для Верхнего Египта',
                    'ur' => 'بالائی مصر کے لیے انگریزی زبان ریسورس سینٹر کا افتتاح',
                ],
                'excerpt' => [
                    'ar' => 'افتتحت السفارة الأمريكية وجامعة الأزهر والجامعة الأمريكية بالقاهرة مركز موارد اللغة الإنجليزية لخدمة طلاب صعيد مصر.',
                    'en' => 'The U.S. Embassy, Al-Azhar University, and the American University in Cairo inaugurated an English Language Resource Centre Hub for Upper Egypt students.',
                    'fr' => 'L\'ambassade des Etats-Unis, Al-Azhar et l\'AUC ont inaugure un centre de ressources en anglais pour les etudiants de Haute-Egypte.',
                    'es' => 'La Embajada de EE.UU., Al-Azhar y la AUC inauguraron un centro de recursos de ingles para estudiantes del Alto Egipto.',
                    'zh' => '美国大使馆、艾资哈尔大学和开罗美国大学联合为上埃及学生开设了英语语言资源中心。',
                    'ru' => 'Посольство США, Аль-Азхар и АУК открыли Центр ресурсов английского языка для студентов Верхнего Египта.',
                    'ur' => 'امریکی سفارتخانے، الازہر اور AUC نے بالائی مصر کے طلباء کے لیے انگریزی زبان ریسورس سینٹر کا افتتاح کیا۔',
                ],
                'content' => [
                    'ar' => 'في مبادرة مشتركة، افتتحت السفارة الأمريكية بالقاهرة وجامعة الأزهر والجامعة الأمريكية بالقاهرة مركز موارد اللغة الإنجليزية لخدمة طلاب صعيد مصر عام 2025م. يهدف المركز إلى تعزيز قدرات الطلاب في اللغة الإنجليزية وتوفير موارد تعليمية حديثة وبرامج تدريبية متخصصة. يأتي هذا في إطار التعاون الدولي لتطوير التعليم في المناطق النائية.',
                    'en' => 'In a joint initiative, the U.S. Embassy in Cairo, Al-Azhar University, and the American University in Cairo inaugurated an English Language Resource Centre Hub for Upper Egypt in 2025. The centre aims to enhance students\' English language capabilities and provide modern educational resources and specialized training programs as part of international cooperation to develop education in remote areas.',
                    'fr' => 'Dans une initiative conjointe, le centre a ete inaugure pour ameliorer les capacites en anglais des etudiants de Haute-Egypte.',
                    'es' => 'En una iniciativa conjunta, se inauguro el centro para mejorar las capacidades en ingles de los estudiantes del Alto Egipto.',
                    'zh' => '作为联合倡议，该中心旨在增强上埃及学生的英语能力并提供现代教育资源。',
                    'ru' => 'В рамках совместной инициативы центр был открыт для повышения уровня английского языка студентов Верхнего Египта.',
                    'ur' => 'مشترکہ اقدام کے تحت بالائی مصر کے طلباء کی انگریزی صلاحیتوں کو بڑھانے کے لیے مرکز کا افتتاح کیا گیا۔',
                ],
                'category_id' => $international?->id,
                'is_published' => true,
                'published_at' => '2025-03-05 11:00:00',
            ],
            [
                'slug' => 'humanitarian-convoys-gaza',
                'title' => [
                    'ar' => 'الأزهر يرسل قوافل إنسانية لدعم أهل غزة',
                    'en' => 'Al-Azhar Sends Humanitarian Convoys to Support Gaza',
                    'fr' => 'Al-Azhar envoie des convois humanitaires pour soutenir Gaza',
                    'es' => 'Al-Azhar envia convoys humanitarios para apoyar a Gaza',
                    'zh' => '艾资哈尔向加沙派出人道主义车队',
                    'ru' => 'Аль-Азхар направляет гуманитарные конвои в поддержку Газы',
                    'ur' => 'الازہر نے غزہ کی حمایت میں انسانی امدادی قافلے بھیجے',
                ],
                'excerpt' => [
                    'ar' => 'أطلقت جامعة الأزهر قوافل إنسانية لدعم الشعب الفلسطيني في غزة، تتضمن مساعدات طبية وغذائية.',
                    'en' => 'Al-Azhar University launched humanitarian relief convoys to support the Palestinian people in Gaza, including medical and food aid.',
                    'fr' => 'L\'Universite d\'Al-Azhar a envoye des convois humanitaires pour soutenir le peuple palestinien a Gaza.',
                    'es' => 'La Universidad de Al-Azhar envio convoys humanitarios para apoyar al pueblo palestino en Gaza.',
                    'zh' => '艾资哈尔大学向加沙巴勒斯坦人民派出了人道主义救援车队。',
                    'ru' => 'Аль-Азхар направил гуманитарные конвои в поддержку палестинского народа в Газе.',
                    'ur' => 'الازہر نے غزہ میں فلسطینی عوام کی حمایت میں انسانی امدادی قافلے بھیجے۔',
                ],
                'content' => [
                    'ar' => 'أطلقت جامعة الأزهر قوافل إنسانية لدعم أهل غزة بفلسطين، شملت مستلزمات طبية وأدوية ومواد غذائية. أعلن الإمام الأكبر أحمد الطيب عن دعمه الكامل للشعب الفلسطيني ودعا المجتمع الدولي إلى وقف المعاناة الإنسانية. شارك طلاب وأساتذة الجامعة من مختلف الكليات في حملات التبرع والدعم.',
                    'en' => 'Al-Azhar University launched humanitarian convoys to support the people of Gaza, Palestine, including medical supplies, medicines, and food. Grand Imam Ahmed el-Tayeb declared full support for the Palestinian people and called on the international community to end the humanitarian suffering. Students and faculty from various colleges participated in donation and support campaigns.',
                    'fr' => 'L\'Universite d\'Al-Azhar a lance des convois humanitaires incluant fournitures medicales et nourriture pour Gaza.',
                    'es' => 'La Universidad de Al-Azhar lanzo convoys humanitarios incluyendo suministros medicos y alimentos para Gaza.',
                    'zh' => '艾资哈尔大学向加沙发送了包括医疗用品和食品在内的人道主义车队。',
                    'ru' => 'Аль-Азхар направил гуманитарные конвои с медикаментами и продовольствием для Газы.',
                    'ur' => 'الازہر نے غزہ کے لیے طبی سامان اور خوراک سمیت انسانی امدادی قافلے بھیجے۔',
                ],
                'category_id' => $events?->id,
                'is_published' => true,
                'published_at' => '2024-11-10 08:00:00',
            ],
            [
                'slug' => 'azhar-gaza-thesis-defense',
                'title' => [
                    'ar' => 'جامعة الأزهر بغزة تعقد أول مناقشة ماجستير',
                    'en' => 'Al-Azhar University-Gaza Holds First Master\'s Thesis Defense',
                    'fr' => 'L\'Universite Al-Azhar de Gaza tient sa premiere soutenance de master',
                    'es' => 'La Universidad Al-Azhar de Gaza celebra su primera defensa de tesis de maestria',
                    'zh' => '加沙艾资哈尔大学举行首次硕士论文答辩',
                    'ru' => 'Университет Аль-Азхар в Газе проводит первую защиту магистерской диссертации',
                    'ur' => 'الازہر یونیورسٹی غزہ نے پہلے ماسٹرز مقالے کا دفاع منعقد کیا',
                ],
                'excerpt' => [
                    'ar' => 'في إنجاز أكاديمي رغم الظروف الصعبة، عقدت جامعة الأزهر بغزة أول مناقشة رسالة ماجستير منذ بداية الحرب.',
                    'en' => 'In a remarkable academic achievement despite difficult circumstances, Al-Azhar University-Gaza held its first master\'s thesis defense since the onset of the regional war.',
                    'fr' => 'L\'universite a tenu sa premiere soutenance de master malgre les circonstances difficiles.',
                    'es' => 'La universidad celebro su primera defensa de tesis de maestria a pesar de las circunstancias dificiles.',
                    'zh' => '尽管困难重重，加沙艾资哈尔大学还是举行了战争以来首次硕士论文答辩。',
                    'ru' => 'Несмотря на трудные обстоятельства, университет провёл первую защиту магистерской диссертации с начала войны.',
                    'ur' => 'مشکل حالات کے باوجود جنگ شروع ہونے کے بعد پہلی بار ماسٹرز مقالے کا دفاع منعقد ہوا۔',
                ],
                'content' => [
                    'ar' => 'حققت جامعة الأزهر بغزة إنجازاً أكاديمياً استثنائياً بعقدها أول مناقشة رسالة ماجستير منذ اندلاع الحرب الإقليمية عام 2025م. يمثل هذا الحدث استمرارية أكاديمية ملهمة رغم الظروف القاسية، ويؤكد إصرار الطلاب والأساتذة على مواصلة مسيرتهم العلمية. أشاد المجتمع الأكاديمي الدولي بهذا الإنجاز.',
                    'en' => 'Al-Azhar University-Gaza achieved an exceptional academic milestone by holding its first master\'s thesis defense since the onset of the regional war in 2025, marking inspiring academic continuity despite harsh conditions and demonstrating students\' and faculty\'s determination to continue their scholarly journey. The international academic community praised this achievement.',
                    'fr' => 'L\'Universite d\'Al-Azhar de Gaza a realise un jalon academique exceptionnel malgre les conditions difficiles.',
                    'es' => 'La Universidad de Al-Azhar de Gaza logro un hito academico excepcional a pesar de las condiciones dificiles.',
                    'zh' => '加沙艾资哈尔大学在艰难条件下取得了杰出的学术里程碑。',
                    'ru' => 'Аль-Азхар в Газе достиг исключительного академического рубежа, несмотря на тяжёлые условия.',
                    'ur' => 'الازہر یونیورسٹی غزہ نے مشکل حالات کے باوجود غیر معمولی اکیڈمک سنگ میل حاصل کیا۔',
                ],
                'category_id' => $academic?->id,
                'is_published' => true,
                'published_at' => '2025-02-01 14:00:00',
            ],
            [
                'slug' => 'al-azhar-scholarship-program-2025',
                'title' => [
                    'ar' => 'برنامج المنح الدراسية للطلاب الدوليين 2024/2025',
                    'en' => 'Al-Azhar Scholarship Program for International Students 2024/2025',
                    'fr' => 'Programme de bourses Al-Azhar pour etudiants internationaux 2024/2025',
                    'es' => 'Programa de becas de Al-Azhar para estudiantes internacionales 2024/2025',
                    'zh' => '艾资哈尔2024/2025国际学生奖学金计划',
                    'ru' => 'Программа стипендий Аль-Азхара для иностранных студентов 2024/2025',
                    'ur' => 'الازہر بین الاقوامی طلباء کے لیے وظائف کا پروگرام 2024/2025',
                ],
                'excerpt' => [
                    'ar' => 'أعلنت جامعة الأزهر عن برنامج المنح الدراسية للطلاب الدوليين للعام الأكاديمي 2024/2025 بالتعاون مع حكومات عدة دول.',
                    'en' => 'Al-Azhar University announced its scholarship program for international students for the 2024/2025 academic year in partnership with several governments.',
                    'fr' => 'Al-Azhar a annonce son programme de bourses pour les etudiants internationaux en partenariat avec plusieurs gouvernements.',
                    'es' => 'Al-Azhar anuncio su programa de becas para estudiantes internacionales en asociacion con varios gobiernos.',
                    'zh' => '艾资哈尔大学宣布2024/2025学年国际学生奖学金计划。',
                    'ru' => 'Аль-Азхар объявил программу стипендий для иностранных студентов на 2024/2025 учебный год.',
                    'ur' => 'الازہر نے 2024/2025 کے لیے بین الاقوامی طلباء کے وظائف کے پروگرام کا اعلان کیا۔',
                ],
                'content' => [
                    'ar' => 'أعلنت جامعة الأزهر عن فتح باب التقديم لبرنامج المنح الدراسية للطلاب الدوليين للعام الأكاديمي 2024/2025. يستقبل الأزهر طلاباً من أكثر من 110 دولة حول العالم ويقدم لهم منحاً دراسية تشمل الرسوم الدراسية والسكن والإعاشة. تم التعاون مع حكومات عدة دول منها المالديف لتوفير المنح الحكومية. يخدم مركز تطوير تعليم الطلاب الوافدين أكثر من 40,000 طالب دولي.',
                    'en' => 'Al-Azhar University opened applications for its international student scholarship program for 2024/2025. Al-Azhar welcomes students from over 110 countries and provides scholarships covering tuition, housing, and living expenses. Government partnerships include countries like the Maldives. The Center for Development of International Students\' Education serves over 40,000 international students.',
                    'fr' => 'Al-Azhar accueille des etudiants de plus de 110 pays et offre des bourses couvrant frais de scolarite et hebergement.',
                    'es' => 'Al-Azhar acoge estudiantes de mas de 110 paises y ofrece becas que cubren matricula y alojamiento.',
                    'zh' => '艾资哈尔接纳来自110多个国家的学生，提供涵盖学费和住宿的奖学金。',
                    'ru' => 'Аль-Азхар принимает студентов из более чем 110 стран и предоставляет стипендии.',
                    'ur' => 'الازہر 110 سے زائد ممالک کے طلباء کا خیرمقدم کرتا ہے اور فیس اور رہائش کی اسکالرشپ فراہم کرتا ہے۔',
                ],
                'category_id' => $academic?->id,
                'is_published' => true,
                'published_at' => '2024-09-01 10:00:00',
            ],
            [
                'slug' => 'extremism-observatory-12-languages',
                'title' => [
                    'ar' => 'مرصد الأزهر يواصل مكافحة التطرف بـ12 لغة',
                    'en' => 'Al-Azhar Observatory Continues Combating Extremism in 12 Languages',
                    'fr' => 'L\'Observatoire d\'Al-Azhar poursuit la lutte contre l\'extremisme en 12 langues',
                    'es' => 'El Observatorio de Al-Azhar continua combatiendo el extremismo en 12 idiomas',
                    'zh' => '艾资哈尔观察站继续以12种语言打击极端主义',
                    'ru' => 'Обсерватория Аль-Азхара продолжает борьбу с экстремизмом на 12 языках',
                    'ur' => 'الازہر رصد گاہ 12 زبانوں میں انتہا پسندی کے خلاف جنگ جاری رکھے ہوئے ہے',
                ],
                'excerpt' => [
                    'ar' => 'يواصل مرصد الأزهر لمكافحة التطرف عمله بـ12 لغة لرصد الخطاب المتطرف والرد عليه بالحجة والدليل.',
                    'en' => 'The Al-Azhar Observatory for Combating Extremism continues its operations in 12 languages, monitoring and countering extremist discourse with evidence-based responses.',
                    'fr' => 'L\'Observatoire poursuit ses operations en 12 langues pour surveiller et contrer le discours extremiste.',
                    'es' => 'El Observatorio continua sus operaciones en 12 idiomas para monitorear y contrarrestar el discurso extremista.',
                    'zh' => '观察站继续以12种语言运作，监控和反击极端主义言论。',
                    'ru' => 'Обсерватория продолжает работу на 12 языках для мониторинга и противодействия экстремизму.',
                    'ur' => 'رصد گاہ 12 زبانوں میں انتہا پسندی کی نگرانی اور مقابلے کا کام جاری رکھے ہوئے ہے۔',
                ],
                'content' => [
                    'ar' => 'يواصل مرصد الأزهر لمكافحة التطرف عمله الدؤوب في رصد الخطاب المتطرف والرد عليه بـ12 لغة عالمية. أُنشئ المرصد بتوجيهات الإمام الأكبر أحمد الطيب ليكون أداة فاعلة في مواجهة الأفكار المتطرفة بالحجة والمنطق والدليل الشرعي. يصدر المرصد تقارير دورية وبيانات توضيحية ويتابع المحتوى على وسائل التواصل الاجتماعي.',
                    'en' => 'The Al-Azhar Observatory for Combating Extremism continues its work monitoring and countering extremist discourse in 12 world languages. Established under the directives of Grand Imam Ahmed el-Tayeb, it serves as an effective tool in confronting extremist ideas with rational argument and scriptural evidence. The observatory issues periodic reports and monitors social media content.',
                    'fr' => 'L\'Observatoire poursuit son travail en 12 langues mondiales pour combattre l\'extremisme avec des arguments rationnels.',
                    'es' => 'El Observatorio continua su trabajo en 12 idiomas mundiales para combatir el extremismo con argumentos racionales.',
                    'zh' => '观察站继续以12种世界语言监控和反击极端主义言论。',
                    'ru' => 'Обсерватория продолжает работу на 12 мировых языках для борьбы с экстремизмом.',
                    'ur' => 'رصد گاہ 12 عالمی زبانوں میں انتہا پسندی کی نگرانی اور عقلی دلائل سے مقابلے کا کام جاری رکھے ہوئے ہے۔',
                ],
                'category_id' => $research?->id,
                'is_published' => true,
                'published_at' => '2024-12-15 09:30:00',
            ],
            [
                'slug' => 'orthopedic-surgery-election',
                'title' => [
                    'ar' => 'انتخاب أساتذة الأزهر في مناصب دولية بجراحة العظام',
                    'en' => 'Al-Azhar Professors Elected to International Orthopedic Surgery Positions',
                    'fr' => 'Professeurs d\'Al-Azhar elus a des postes internationaux en chirurgie orthopedique',
                    'es' => 'Profesores de Al-Azhar elegidos para puestos internacionales en cirugia ortopedica',
                    'zh' => '艾资哈尔教授当选国际骨科手术职位',
                    'ru' => 'Профессора Аль-Азхара избраны на международные должности по ортопедической хирургии',
                    'ur' => 'الازہر کے پروفیسرز بین الاقوامی آرتھوپیڈک سرجری عہدوں پر منتخب',
                ],
                'excerpt' => [
                    'ar' => 'انتُخب الدكتور عبد الحكيم عبد الله رئيساً للجمعية المصرية لجراحة العظام والدكتور ياسر البطراوي رئيساً لمجموعة إدارة الكوارث.',
                    'en' => 'Dr. Abdel Hakim Abdullah was elected President of the Egyptian Society of Orthopedic Surgery, and Dr. Yasser El-Batrawy was elected Chair of the Disaster Management Group at the International Society of Orthopedic Surgery.',
                    'fr' => 'Le Dr Abdel Hakim Abdullah a ete elu president de la Societe egyptienne de chirurgie orthopedique.',
                    'es' => 'El Dr. Abdel Hakim Abdullah fue elegido presidente de la Sociedad Egipcia de Cirugia Ortopedica.',
                    'zh' => '阿卜杜勒·哈基姆博士当选埃及骨科外科学会主席。',
                    'ru' => 'Д-р Абдель Хаким Абдулла избран президентом Египетского общества ортопедической хирургии.',
                    'ur' => 'ڈاکٹر عبدالحکیم عبداللہ مصری آرتھوپیڈک سرجری سوسائٹی کے صدر منتخب ہوئے۔',
                ],
                'content' => [
                    'ar' => 'في إنجاز يعكس تميز خريجي جامعة الأزهر، انتُخب الدكتور عبد الحكيم عبد الله رئيساً للجمعية المصرية لجراحة العظام، كما انتُخب الدكتور ياسر البطراوي رئيساً لمجموعة إدارة الكوارث بالجمعية الدولية لجراحة العظام والكسور. يؤكد هذا الإنجاز مكانة جامعة الأزهر في المجالات الطبية الدولية.',
                    'en' => 'Reflecting Al-Azhar graduates\' distinction, Dr. Abdel Hakim Abdullah was elected President of the Egyptian Society of Orthopedic Surgery, while Dr. Yasser El-Batrawy was elected Chair of the Disaster Management Group at the International Society of Orthopedic Surgery and Traumatology. This achievement confirms Al-Azhar University\'s standing in international medical fields.',
                    'fr' => 'Cet accomplissement confirme la position d\'Al-Azhar dans les domaines medicaux internationaux.',
                    'es' => 'Este logro confirma la posicion de Al-Azhar en los campos medicos internacionales.',
                    'zh' => '这一成就证实了艾资哈尔大学在国际医学领域的地位。',
                    'ru' => 'Это достижение подтверждает позицию Аль-Азхара в международных медицинских областях.',
                    'ur' => 'یہ کامیابی بین الاقوامی طبی شعبوں میں الازہر کے مقام کی تصدیق کرتی ہے۔',
                ],
                'category_id' => $academic?->id,
                'is_published' => true,
                'published_at' => '2025-01-20 12:00:00',
            ],
            [
                'slug' => 'grand-imam-pope-tawadros-eid-call',
                'title' => [
                    'ar' => 'الإمام الأكبر يتلقى اتصالاً من البابا تواضروس للتهنئة بعيد الفطر',
                    'en' => 'Grand Imam Receives Call from Pope Tawadros for Eid al-Fitr',
                    'fr' => 'Le Grand Imam recoit un appel du Pape Tawadros pour l\'Aid al-Fitr',
                    'es' => 'El Gran Imam recibe una llamada del Papa Tawadros por el Eid al-Fitr',
                    'zh' => '大伊玛目接到塔瓦德罗斯教皇开斋节祝贺电话',
                    'ru' => 'Великий имам получил звонок от Папы Тавадроса по случаю Ид аль-Фитр',
                    'ur' => 'شیخ الازہر کو پوپ تواضروس کی عید الفطر کی مبارکباد کا فون',
                ],
                'excerpt' => [
                    'ar' => 'تلقى الإمام الأكبر شيخ الأزهر اتصالاً هاتفياً من البابا تواضروس الثاني بابا الإسكندرية وبطريرك الكرازة المرقسية للتهنئة بعيد الفطر المبارك، في مشهد يعكس الوئام بين الأديان في مصر.',
                    'en' => 'The Grand Imam received a phone call from Pope Tawadros II, head of the Coptic Orthodox Church, congratulating on Eid al-Fitr, reflecting interfaith harmony in Egypt.',
                    'fr' => 'Le Grand Imam a recu un appel du Pape Tawadros II pour le feliciter a l\'occasion de l\'Aid al-Fitr, refletant l\'harmonie interreligieuse en Egypte.',
                    'es' => 'El Gran Imam recibio una llamada del Papa Tawadros II felicitandole por el Eid al-Fitr, reflejando la armonia interreligiosa en Egipto.',
                    'zh' => '大伊玛目接到科普特东正教教皇塔瓦德罗斯二世的开斋节祝贺电话，体现了埃及的宗教间和谐。',
                    'ru' => 'Великий имам получил поздравительный звонок от Папы Тавадроса II по случаю Ид аль-Фитр, отражающий межконфессиональную гармонию в Египте.',
                    'ur' => 'شیخ الازہر نے قبطی آرتھوڈوکس چرچ کے سربراہ پوپ تواضروس ثانی سے عید الفطر کی مبارکباد کا فون وصول کیا جو مصر میں بین المذاہب ہم آہنگی کی عکاسی کرتا ہے۔',
                ],
                'content' => [
                    'ar' => 'تلقى فضيلة الإمام الأكبر الدكتور أحمد الطيب شيخ الأزهر الشريف اتصالاً هاتفياً من قداسة البابا تواضروس الثاني بابا الإسكندرية وبطريرك الكرازة المرقسية للتهنئة بمناسبة عيد الفطر المبارك 1447هـ. تبادل الطرفان التهاني والتمنيات بالسلام والاستقرار لمصر وشعبها. يأتي هذا الاتصال في إطار العلاقات الوطيدة بين الأزهر الشريف والكنيسة القبطية الأرثوذكسية التي تعكس روح التسامح والتعايش بين المسلمين والمسيحيين في مصر.',
                    'en' => 'Grand Imam Dr. Ahmed el-Tayeb received a phone call from His Holiness Pope Tawadros II, Pope of Alexandria and Patriarch of the See of St. Mark, congratulating him on the occasion of Eid al-Fitr 1447 AH. Both exchanged greetings and wishes for peace and stability for Egypt and its people. This call comes within the framework of the strong relationship between Al-Azhar and the Coptic Orthodox Church, reflecting the spirit of tolerance and coexistence between Muslims and Christians in Egypt.',
                    'fr' => 'Le Grand Imam a recu un appel du Pape Tawadros II a l\'occasion de l\'Aid al-Fitr, refletant les relations solides entre Al-Azhar et l\'Eglise copte orthodoxe.',
                    'es' => 'El Gran Imam recibio una llamada del Papa Tawadros II con motivo del Eid al-Fitr, reflejando las solidas relaciones entre Al-Azhar y la Iglesia Copta Ortodoxa.',
                    'zh' => '大伊玛目在开斋节之际接到塔瓦德罗斯二世教皇的电话，体现了艾资哈尔与科普特东正教会之间的深厚关系以及穆斯林与基督徒之间的共存精神。',
                    'ru' => 'Великий имам получил звонок от Папы Тавадроса II по случаю Ид аль-Фитр, что отражает крепкие отношения между Аль-Азхаром и Коптской православной церковью.',
                    'ur' => 'شیخ الازہر نے عید الفطر کے موقع پر پوپ تواضروس ثانی سے فون وصول کیا جو الازہر اور قبطی آرتھوڈوکس چرچ کے مضبوط تعلقات اور مسلمانوں اور مسیحیوں کے بقائے باہمی کی روح کو ظاہر کرتا ہے۔',
                ],
                'category_id' => $international?->id,
                'is_published' => true,
                'published_at' => '2026-03-15 09:00:00',
            ],
            [
                'slug' => 'azhar-condemns-iranian-aggression-gulf',
                'title' => [
                    'ar' => 'الأزهر يدين العدوان الإيراني على دول الخليج',
                    'en' => 'Al-Azhar Condemns Iranian Aggression on Gulf States',
                    'fr' => 'Al-Azhar condamne l\'agression iranienne contre les Etats du Golfe',
                    'es' => 'Al-Azhar condena la agresion irani contra los estados del Golfo',
                    'zh' => '艾资哈尔谴责伊朗对海湾国家的侵略',
                    'ru' => 'Аль-Азхар осуждает иранскую агрессию против стран Персидского залива',
                    'ur' => 'الازہر کی خلیجی ممالک پر ایرانی جارحیت کی مذمت',
                ],
                'excerpt' => [
                    'ar' => 'أصدر الأزهر الشريف بياناً يدين فيه الهجمات العسكرية الإيرانية غير المبررة على دول الخليج ويدعو إلى التهدئة الفورية.',
                    'en' => 'Al-Azhar issues statement condemning unjustified Iranian military attacks on Gulf countries and calling for immediate de-escalation.',
                    'fr' => 'Al-Azhar publie une declaration condamnant les attaques militaires iraniennes injustifiees contre les pays du Golfe et appelant a une desescalade immediate.',
                    'es' => 'Al-Azhar emite una declaracion condenando los ataques militares iranies injustificados contra los paises del Golfo y pidiendo una desescalada inmediata.',
                    'zh' => '艾资哈尔发表声明谴责伊朗对海湾国家的无理军事攻击，呼吁立即降级局势。',
                    'ru' => 'Аль-Азхар выпустил заявление с осуждением необоснованных военных атак Ирана на страны Залива и призывом к немедленной деэскалации.',
                    'ur' => 'الازہر نے خلیجی ممالک پر ایران کے غیر مبرر فوجی حملوں کی مذمت اور فوری تخفیف تناؤ کا مطالبہ کرتے ہوئے بیان جاری کیا۔',
                ],
                'content' => [
                    'ar' => 'أصدر الأزهر الشريف بياناً رسمياً يدين فيه بأشد العبارات الهجمات العسكرية الإيرانية على دول الخليج العربي. وأكد البيان أن هذه الهجمات تمثل عدواناً غير مبرر يهدد استقرار المنطقة وأمن شعوبها. دعا الأزهر جميع الأطراف إلى ضبط النفس والتهدئة الفورية واللجوء إلى الحوار والدبلوماسية لحل الخلافات، مؤكداً رفضه القاطع لأي شكل من أشكال العنف والعدوان.',
                    'en' => 'Al-Azhar issued an official statement strongly condemning Iranian military attacks on Arab Gulf states. The statement emphasized that these attacks constitute unjustified aggression threatening regional stability and the security of its peoples. Al-Azhar called on all parties to exercise restraint, pursue immediate de-escalation, and resort to dialogue and diplomacy to resolve disputes, reaffirming its categorical rejection of all forms of violence and aggression.',
                    'fr' => 'Al-Azhar a publie une declaration officielle condamnant fermement les attaques militaires iraniennes contre les Etats du Golfe et appelant au dialogue et a la diplomatie.',
                    'es' => 'Al-Azhar emitio una declaracion oficial condenando firmemente los ataques militares iranies contra los estados del Golfo y pidiendo dialogo y diplomacia.',
                    'zh' => '艾资哈尔发表官方声明，强烈谴责伊朗对阿拉伯海湾国家的军事攻击，呼吁各方克制并通过对话和外交解决争端。',
                    'ru' => 'Аль-Азхар выпустил официальное заявление с решительным осуждением иранских военных атак на страны Залива и призывом к диалогу и дипломатии.',
                    'ur' => 'الازہر نے سرکاری بیان جاری کرتے ہوئے خلیجی عرب ممالک پر ایرانی فوجی حملوں کی سخت مذمت کی اور تمام فریقین سے تحمل، فوری تخفیف تناؤ اور مکالمے کا مطالبہ کیا۔',
                ],
                'category_id' => $international?->id,
                'is_published' => true,
                'published_at' => '2026-03-10 08:00:00',
            ],
            [
                'slug' => 'ramadan-forum-zakat-al-fitr',
                'title' => [
                    'ar' => 'ملتقى رمضان يناقش دور زكاة الفطر في التكافل الاجتماعي',
                    'en' => 'Ramadan Forum Discusses Role of Zakat al-Fitr in Social Solidarity',
                    'fr' => 'Le forum du Ramadan discute du role de la Zakat al-Fitr dans la solidarite sociale',
                    'es' => 'El foro de Ramadan discute el papel del Zakat al-Fitr en la solidaridad social',
                    'zh' => '斋月论坛讨论开斋捐在社会团结中的作用',
                    'ru' => 'Форум Рамадана обсуждает роль Закят аль-Фитр в социальной солидарности',
                    'ur' => 'رمضان فورم میں زکاۃ الفطر کے سماجی یکجہتی میں کردار پر بحث',
                ],
                'excerpt' => [
                    'ar' => 'ناقش ملتقى الأزهر بعد صلاة التراويح دور زكاة الفطر في تحقيق التكافل الاجتماعي ودعم المحتاجين.',
                    'en' => 'The Al-Azhar post-Taraweeh forum discussed how Zakat al-Fitr achieves social solidarity and support for the needy.',
                    'fr' => 'Le forum d\'Al-Azhar apres les Taraweeh a discute de la maniere dont la Zakat al-Fitr realise la solidarite sociale.',
                    'es' => 'El foro de Al-Azhar despues de Taraweeh discutio como el Zakat al-Fitr logra la solidaridad social.',
                    'zh' => '艾资哈尔泰拉威祈祷后论坛讨论了开斋捐如何实现社会团结和帮助贫困者。',
                    'ru' => 'Форум Аль-Азхара после таравих обсудил, как Закят аль-Фитр способствует социальной солидарности.',
                    'ur' => 'الازہر کے تراویح کے بعد کے فورم میں زکاۃ الفطر کے ذریعے سماجی یکجہتی اور ضرورتمندوں کی مدد پر بحث ہوئی۔',
                ],
                'content' => [
                    'ar' => 'عقد الأزهر الشريف ملتقاه الرمضاني بعد صلاة التراويح في الجامع الأزهر الشريف، حيث ناقش العلماء والمشايخ دور زكاة الفطر في تحقيق التكافل الاجتماعي بين المسلمين. أوضح المتحدثون أن زكاة الفطر ليست مجرد فريضة شرعية بل هي وسيلة لإسعاد الفقراء والمحتاجين في يوم العيد وتعزيز روح التراحم والتعاون في المجتمع. كما تمت مناقشة أحكام زكاة الفطر ومقدارها ووقت إخراجها.',
                    'en' => 'Al-Azhar held its Ramadan forum after Taraweeh prayers at Al-Azhar Mosque, where scholars discussed the role of Zakat al-Fitr in achieving social solidarity among Muslims. Speakers explained that Zakat al-Fitr is not merely a religious obligation but a means to bring joy to the poor and needy on Eid day and to strengthen the spirit of compassion and cooperation in society. The forum also discussed the rulings, amount, and timing of Zakat al-Fitr.',
                    'fr' => 'Al-Azhar a tenu son forum du Ramadan a la mosquee Al-Azhar ou les erudits ont discute du role de la Zakat al-Fitr dans la solidarite sociale et le soutien aux pauvres.',
                    'es' => 'Al-Azhar celebro su foro de Ramadan en la mezquita de Al-Azhar donde los eruditos discutieron el papel del Zakat al-Fitr en la solidaridad social y el apoyo a los pobres.',
                    'zh' => '艾资哈尔在艾资哈尔清真寺举办了斋月论坛，学者们讨论了开斋捐在穆斯林社会团结中的作用及其法律规定。',
                    'ru' => 'Аль-Азхар провёл рамаданский форум в мечети Аль-Азхар, где учёные обсудили роль Закят аль-Фитр в социальной солидарности и поддержке нуждающихся.',
                    'ur' => 'الازہر نے جامع الازہر میں رمضان فورم منعقد کیا جہاں علماء نے مسلمانوں میں سماجی یکجہتی میں زکاۃ الفطر کے کردار اور اس کے احکام پر بحث کی۔',
                ],
                'category_id' => $events?->id,
                'is_published' => true,
                'published_at' => '2026-03-18 22:00:00',
            ],
            [
                'slug' => 'ten-new-faculties-2025-2026',
                'title' => [
                    'ar' => 'إنشاء 10 كليات جديدة للعام الأكاديمي 2025-2026',
                    'en' => '10 New Faculties Added for Academic Year 2025-2026',
                    'fr' => '10 nouvelles facultes ajoutees pour l\'annee academique 2025-2026',
                    'es' => '10 nuevas facultades anadidas para el ano academico 2025-2026',
                    'zh' => '2025-2026学年新增10个学院',
                    'ru' => '10 новых факультетов открыты на 2025-2026 учебный год',
                    'ur' => 'تعلیمی سال 2025-2026 کے لیے 10 نئی فیکلٹیاں قائم',
                ],
                'excerpt' => [
                    'ar' => 'أنشأت جامعة الأزهر 10 كليات جديدة تشمل الذكاء الاصطناعي والطب البيطري والهندسة الزراعية في عدة محافظات.',
                    'en' => 'Al-Azhar University establishes 10 new faculties including AI, Veterinary Medicine, and Agricultural Engineering across multiple governorates.',
                    'fr' => 'L\'Universite d\'Al-Azhar cree 10 nouvelles facultes dont l\'IA, la medecine veterinaire et le genie agricole dans plusieurs gouvernorats.',
                    'es' => 'La Universidad de Al-Azhar establece 10 nuevas facultades incluyendo IA, Medicina Veterinaria e Ingenieria Agricola en multiples gobernaciones.',
                    'zh' => '艾资哈尔大学在多个省份新设10个学院，包括人工智能、兽医学和农业工程。',
                    'ru' => 'Университет Аль-Азхар открывает 10 новых факультетов, включая ИИ, ветеринарию и сельскохозяйственную инженерию.',
                    'ur' => 'الازہر یونیورسٹی نے متعدد صوبوں میں AI، ویٹرنری میڈیسن اور زرعی انجینئرنگ سمیت 10 نئی فیکلٹیاں قائم کیں۔',
                ],
                'content' => [
                    'ar' => 'أعلنت جامعة الأزهر عن إنشاء 10 كليات جديدة للعام الأكاديمي 2025-2026 في إطار خطة التوسع والتطوير. تشمل الكليات الجديدة كلية الذكاء الاصطناعي وكلية الطب البيطري وكلية الهندسة الزراعية، وتتوزع على عدة محافظات مصرية لتلبية احتياجات سوق العمل وتوفير تعليم متميز للطلاب. يأتي هذا التوسع ضمن رؤية الجامعة لتطوير برامجها الأكاديمية ومواكبة التطورات العلمية الحديثة.',
                    'en' => 'Al-Azhar University announced the establishment of 10 new faculties for the 2025-2026 academic year as part of its expansion and development plan. The new faculties include AI, Veterinary Medicine, and Agricultural Engineering, distributed across multiple Egyptian governorates to meet labor market needs and provide distinguished education. This expansion aligns with the university\'s vision to develop academic programs and keep pace with modern scientific developments.',
                    'fr' => 'L\'Universite d\'Al-Azhar a annonce la creation de 10 nouvelles facultes pour 2025-2026, incluant l\'IA et la medecine veterinaire, dans le cadre de son plan d\'expansion.',
                    'es' => 'La Universidad de Al-Azhar anuncio la creacion de 10 nuevas facultades para 2025-2026, incluyendo IA y medicina veterinaria, como parte de su plan de expansion.',
                    'zh' => '艾资哈尔大学宣布在2025-2026学年设立10个新学院，包括人工智能和兽医学，作为其扩展计划的一部分。',
                    'ru' => 'Университет Аль-Азхар объявил о создании 10 новых факультетов на 2025-2026 год, включая ИИ и ветеринарию, в рамках плана расширения.',
                    'ur' => 'الازہر یونیورسٹی نے 2025-2026 کے لیے AI اور ویٹرنری میڈیسن سمیت 10 نئی فیکلٹیوں کے قیام کا اعلان کیا جو توسیعی منصوبے کا حصہ ہے۔',
                ],
                'category_id' => $academic?->id,
                'is_published' => true,
                'published_at' => '2026-01-10 10:00:00',
            ],
            [
                'slug' => 'students-lead-taraweeh-azhar-mosque',
                'title' => [
                    'ar' => 'طلاب الأزهر يؤمون صلاة التراويح في الجامع الأزهر',
                    'en' => 'Al-Azhar Students Lead Taraweeh Prayers at Al-Azhar Mosque',
                    'fr' => 'Les etudiants d\'Al-Azhar dirigent les prieres de Taraweeh a la mosquee Al-Azhar',
                    'es' => 'Estudiantes de Al-Azhar dirigen las oraciones de Taraweeh en la mezquita de Al-Azhar',
                    'zh' => '艾资哈尔学生在艾资哈尔清真寺带领泰拉威祈祷',
                    'ru' => 'Студенты Аль-Азхара ведут молитвы Таравих в мечети Аль-Азхар',
                    'ur' => 'الازہر کے طلباء نے جامع الازہر میں تراویح کی نماز کی امامت کی',
                ],
                'excerpt' => [
                    'ar' => 'أمّ طلاب موهوبون من الأزهر صلاة التراويح والتهجد في الجامع الأزهر الشريف خلال شهر رمضان 2026م.',
                    'en' => 'Talented Al-Azhar students lead Taraweeh and Tahajjud prayers at the historic Al-Azhar Mosque during Ramadan 2026.',
                    'fr' => 'Des etudiants talentueux d\'Al-Azhar dirigent les prieres de Taraweeh et Tahajjud a la mosquee historique d\'Al-Azhar pendant le Ramadan 2026.',
                    'es' => 'Estudiantes talentosos de Al-Azhar dirigen las oraciones de Taraweeh y Tahajjud en la historica mezquita de Al-Azhar durante el Ramadan 2026.',
                    'zh' => '才华横溢的艾资哈尔学生在2026年斋月期间在历史悠久的艾资哈尔清真寺带领泰拉威和夜间祈祷。',
                    'ru' => 'Талантливые студенты Аль-Азхара ведут молитвы Таравих и Тахаджуд в исторической мечети Аль-Азхар во время Рамадана 2026.',
                    'ur' => 'الازہر کے باصلاحیت طلباء نے رمضان 2026 میں تاریخی جامع الازہر میں تراویح اور تہجد کی نماز کی امامت کی۔',
                ],
                'content' => [
                    'ar' => 'في مشهد روحاني مهيب، أمّ طلاب موهوبون من جامعة الأزهر صلاة التراويح والتهجد في الجامع الأزهر الشريف خلال شهر رمضان المبارك 1447هـ/2026م. تميز الطلاب بأصواتهم العذبة وإتقانهم لأحكام التجويد. يأتي ذلك في إطار حرص الأزهر على إبراز مواهب طلابه ودورهم في إحياء الشعائر الدينية في أعرق مؤسسة إسلامية في العالم.',
                    'en' => 'In a spiritually uplifting scene, talented Al-Azhar University students led Taraweeh and Tahajjud prayers at the historic Al-Azhar Mosque during Ramadan 1447 AH/2026. The students distinguished themselves with their beautiful voices and mastery of Quran recitation rules. This reflects Al-Azhar\'s commitment to showcasing its students\' talents and their role in reviving religious practices at the world\'s oldest Islamic institution.',
                    'fr' => 'Des etudiants talentueux ont dirige les prieres de Taraweeh a la mosquee Al-Azhar, demontrant la maitrise de la recitation coranique et le role d\'Al-Azhar dans la formation des talents.',
                    'es' => 'Estudiantes talentosos dirigieron las oraciones de Taraweeh en la mezquita de Al-Azhar, demostrando el dominio de la recitacion coranica y el papel de Al-Azhar en la formacion de talentos.',
                    'zh' => '才华横溢的学生在艾资哈尔清真寺带领泰拉威祈祷，展示了古兰经诵读的精湛技艺以及艾资哈尔在人才培养中的作用。',
                    'ru' => 'Талантливые студенты провели молитвы Таравих в мечети Аль-Азхар, продемонстрировав мастерство чтения Корана и роль Аль-Азхара в подготовке талантов.',
                    'ur' => 'باصلاحیت طلباء نے جامع الازہر میں تراویح کی نماز کی امامت کی، قرآنی تلاوت میں مہارت اور الازہر کے صلاحیتوں کی تربیت میں کردار کو ظاہر کیا۔',
                ],
                'category_id' => $events?->id,
                'is_published' => true,
                'published_at' => '2026-03-05 21:00:00',
            ],
            [
                'slug' => 'human-fraternity-document-fifth-anniversary',
                'title' => [
                    'ar' => 'وثيقة الأخوة الإنسانية تحتفل بالذكرى الخامسة',
                    'en' => 'Document on Human Fraternity Marks Fifth Anniversary',
                    'fr' => 'Le Document sur la Fraternite Humaine celebre son cinquieme anniversaire',
                    'es' => 'El Documento sobre la Fraternidad Humana celebra su quinto aniversario',
                    'zh' => '人类博爱文件迎来五周年纪念',
                    'ru' => 'Документ о человеческом братстве отмечает пятую годовщину',
                    'ur' => 'انسانی اخوت کی دستاویز کی پانچویں سالگرہ',
                ],
                'excerpt' => [
                    'ar' => 'احتفلت وثيقة الأخوة الإنسانية التاريخية الموقعة من الإمام الأكبر والبابا فرنسيس في أبوظبي بذكراها الخامسة مع الاحتفال باليوم الدولي للأخوة الإنسانية في 4 فبراير.',
                    'en' => 'The landmark Document on Human Fraternity signed by Grand Imam and Pope Francis in Abu Dhabi celebrates its fifth anniversary, with the UN International Day of Human Fraternity on February 4.',
                    'fr' => 'Le Document historique sur la Fraternite Humaine signe par le Grand Imam et le Pape Francois a Abu Dhabi celebre son cinquieme anniversaire.',
                    'es' => 'El historico Documento sobre la Fraternidad Humana firmado por el Gran Imam y el Papa Francisco en Abu Dabi celebra su quinto aniversario.',
                    'zh' => '大伊玛目和教皇方济各在阿布扎比签署的具有里程碑意义的人类博爱文件迎来五周年纪念。',
                    'ru' => 'Исторический Документ о человеческом братстве, подписанный Великим имамом и Папой Франциском в Абу-Даби, отмечает пятую годовщину.',
                    'ur' => 'شیخ الازہر اور پوپ فرانسس کے ابوظبی میں دستخط شدہ تاریخی انسانی اخوت کی دستاویز کی پانچویں سالگرہ۔',
                ],
                'content' => [
                    'ar' => 'احتفل العالم بالذكرى الخامسة لوثيقة الأخوة الإنسانية التاريخية التي وقعها الإمام الأكبر الدكتور أحمد الطيب شيخ الأزهر الشريف وقداسة البابا فرنسيس بابا الكنيسة الكاثوليكية في أبوظبي عام 2019م. وقد أعلنت الأمم المتحدة يوم 4 فبراير يوماً دولياً للأخوة الإنسانية تقديراً لهذه الوثيقة التي تدعو إلى السلام والتعايش والحوار بين الأديان والثقافات. أقيمت فعاليات واحتفالات في عدة دول بهذه المناسبة.',
                    'en' => 'The world celebrated the fifth anniversary of the historic Document on Human Fraternity signed by Grand Imam Dr. Ahmed el-Tayeb and His Holiness Pope Francis in Abu Dhabi in 2019. The United Nations declared February 4 as the International Day of Human Fraternity in recognition of this document, which calls for peace, coexistence, and interfaith and intercultural dialogue. Events and celebrations were held in multiple countries to mark the occasion.',
                    'fr' => 'Le monde a celebre le cinquieme anniversaire du Document sur la Fraternite Humaine, avec le 4 fevrier declare Journee internationale par l\'ONU.',
                    'es' => 'El mundo celebro el quinto aniversario del Documento sobre la Fraternidad Humana, con el 4 de febrero declarado Dia Internacional por la ONU.',
                    'zh' => '全球庆祝人类博爱文件签署五周年，联合国将2月4日定为国际人类博爱日。',
                    'ru' => 'Мир отметил пятую годовщину Документа о братстве, а ООН объявила 4 февраля Международным днём человеческого братства.',
                    'ur' => 'دنیا نے انسانی اخوت کی دستاویز کی پانچویں سالگرہ منائی، اقوام متحدہ نے 4 فروری کو بین الاقوامی یوم انسانی اخوت قرار دیا۔',
                ],
                'category_id' => $international?->id,
                'is_published' => true,
                'published_at' => '2026-02-04 10:00:00',
            ],
            [
                'slug' => 'azhar-magazine-special-eid-edition',
                'title' => [
                    'ar' => 'مجمع البحوث الإسلامية يصدر عدداً خاصاً من مجلة الأزهر بمناسبة العيد',
                    'en' => 'Islamic Research Academy Publishes Special Eid Edition of Al-Azhar Magazine',
                    'fr' => 'L\'Academie de Recherches Islamiques publie une edition speciale de l\'Aid du Magazine Al-Azhar',
                    'es' => 'La Academia de Investigacion Islamica publica una edicion especial del Eid de la Revista Al-Azhar',
                    'zh' => '伊斯兰研究院出版艾资哈尔杂志开斋节特刊',
                    'ru' => 'Академия исламских исследований выпускает специальный праздничный номер журнала «Аль-Азхар»',
                    'ur' => 'مجمع البحوث الاسلامیہ نے مجلہ الازہر کا عید خصوصی شمارہ جاری کیا',
                ],
                'excerpt' => [
                    'ar' => 'أصدر مجمع البحوث الإسلامية عدد شوال الخاص من مجلة الأزهر متضمناً ملفاً خاصاً عن عادات عيد الفطر وتعاليمه الإسلامية.',
                    'en' => 'Special Shawwal issue of Al-Azhar Magazine released with a dedicated file on Eid al-Fitr traditions and Islamic teachings.',
                    'fr' => 'Le numero special de Chawwal du Magazine Al-Azhar est publie avec un dossier consacre aux traditions de l\'Aid al-Fitr.',
                    'es' => 'El numero especial de Shawwal de la Revista Al-Azhar se publica con un expediente dedicado a las tradiciones del Eid al-Fitr.',
                    'zh' => '艾资哈尔杂志肖瓦尔月特刊发行，专题介绍开斋节传统和伊斯兰教导。',
                    'ru' => 'Специальный номер журнала за месяц Шавваль вышел с разделом о традициях Ид аль-Фитр.',
                    'ur' => 'مجلہ الازہر کا شوال خصوصی شمارہ عید الفطر کی روایات اور اسلامی تعلیمات پر خاص فائل کے ساتھ جاری کیا گیا۔',
                ],
                'content' => [
                    'ar' => 'أصدر مجمع البحوث الإسلامية بالأزهر الشريف عدد شهر شوال 1447هـ من مجلة الأزهر الشهرية العلمية. تضمن العدد ملفاً خاصاً عن عيد الفطر المبارك يشمل آداب العيد وأحكامه وعاداته في البلدان الإسلامية المختلفة. كما تضمن العدد أبحاثاً ومقالات علمية في الفقه والتفسير والحديث واللغة العربية. تصدر مجلة الأزهر منذ عام 1930م وتُعد من أعرق المجلات العلمية الإسلامية.',
                    'en' => 'The Islamic Research Academy published the Shawwal 1447 AH issue of Al-Azhar Magazine, the monthly scholarly journal. The issue featured a special file on Eid al-Fitr including its etiquette, rulings, and traditions across different Islamic countries. It also included scholarly research and articles on jurisprudence, Quran interpretation, Hadith, and Arabic language. Al-Azhar Magazine has been published since 1930 and is one of the oldest Islamic scholarly journals.',
                    'fr' => 'L\'Academie a publie le numero de Chawwal avec un dossier special sur l\'Aid al-Fitr et des recherches en jurisprudence islamique. La revue est publiee depuis 1930.',
                    'es' => 'La Academia publico el numero de Shawwal con un expediente especial sobre el Eid al-Fitr e investigaciones en jurisprudencia islamica. La revista se publica desde 1930.',
                    'zh' => '伊斯兰研究院出版了肖瓦尔月刊，包含开斋节专题和伊斯兰法学研究。该杂志自1930年以来持续出版。',
                    'ru' => 'Академия выпустила номер за Шавваль со специальным разделом об Ид аль-Фитр и научными статьями по исламской юриспруденции. Журнал издаётся с 1930 года.',
                    'ur' => 'مجمع البحوث نے مجلہ الازہر کا شوال کا شمارہ جاری کیا جس میں عید الفطر پر خصوصی فائل اور فقہ و تفسیر کی تحقیقات شامل ہیں۔ مجلہ 1930 سے شائع ہو رہا ہے۔',
                ],
                'category_id' => $research?->id,
                'is_published' => true,
                'published_at' => '2026-03-20 11:00:00',
            ],
        ];

        foreach ($articles as $data) {
            NewsArticle::create($data);
        }
    }
}
