<?php

namespace Database\Seeders;

use App\Models\Person;
use Illuminate\Database\Seeder;

class PersonSeeder extends Seeder
{
    public function run(): void
    {
        $people = [
            // Current Leadership
            [
                'slug' => 'ahmed-el-tayeb',
                'name' => [
                    'ar' => 'الإمام الأكبر أحمد الطيب',
                    'en' => 'Grand Imam Ahmed el-Tayeb',
                    'fr' => 'Grand Imam Ahmed el-Tayeb',
                    'es' => 'Gran Imam Ahmed el-Tayeb',
                    'zh' => '大伊玛目艾哈迈德·泰耶布',
                    'ru' => 'Великий имам Ахмед ат-Тайиб',
                    'ur' => 'شیخ الازہر احمد الطیب',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الشريف',
                    'en' => 'Grand Imam of Al-Azhar',
                    'fr' => 'Grand Imam d\'Al-Azhar',
                    'es' => 'Gran Imam de Al-Azhar',
                    'zh' => '艾资哈尔大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара',
                    'ur' => 'شیخ الازہر الشریف',
                ],
                'bio' => [
                    'ar' => 'الإمام الأكبر أحمد محمد أحمد الطيب، وُلد في 6 يناير 1946 بالقرنة، الأقصر. حصل على بكالوريوس أصول الدين (1969) بامتياز، وماجستير في العقيدة والفلسفة (1971)، ودكتوراه في الفلسفة الإسلامية (1977). درس في جامعة باريس (1977-1978) ويجيد الفرنسية. تدرج من مدرس مساعد إلى أستاذ بالأزهر (1988)، ثم عميداً لعدة كليات. شغل منصب مفتي مصر (2002-2003) ورئيس جامعة الأزهر (2003-2010). عُيّن شيخاً للأزهر في 19 مارس 2010. يرأس مجلس حكماء المسلمين منذ 2014. وقّع وثيقة الأخوة الإنسانية مع البابا فرنسيس في أبوظبي عام 2019. قام بأكثر من 34 زيارة دولية في 21 دولة.',
                    'en' => 'Grand Imam Ahmed Mohamed Ahmed el-Tayeb was born January 6, 1946 in Qurna, Luxor. He earned his B.A. in Theology (1969, with distinction), M.A. in Creed and Philosophy (1971), and Ph.D. in Islamic Philosophy (1977). He studied at the University of Paris (1977-78) and is fluent in French. He rose from teaching assistant to Professor at Al-Azhar (1988), then Dean of several faculties. He served as Grand Mufti of Egypt (2002-2003) and President of Al-Azhar University (2003-2010). Appointed Grand Imam on March 19, 2010. He chairs the Muslim Council of Elders since 2014 and signed the Document on Human Fraternity with Pope Francis in Abu Dhabi in 2019. He has made 34+ international visits across 21 countries.',
                    'fr' => 'Le Grand Imam Ahmed el-Tayeb, ne le 6 janvier 1946 a Qurna, Louxor. Docteur en philosophie islamique, il a ete nomme Grand Imam le 19 mars 2010. Il preside le Conseil des sages musulmans et a signe le Document sur la Fraternite Humaine avec le pape Francois en 2019.',
                    'es' => 'El Gran Imam Ahmed el-Tayeb, nacido el 6 de enero de 1946 en Qurna, Luxor. Doctor en filosofia islamica, fue nombrado Gran Imam el 19 de marzo de 2010. Preside el Consejo de Sabios Musulmanes y firmo el Documento sobre la Fraternidad Humana con el papa Francisco en 2019.',
                    'zh' => '大伊玛目艾哈迈德·泰耶布1946年1月6日出生于卢克索。伊斯兰哲学博士，2010年3月19日就任大伊玛目。主持穆斯林长老委员会，2019年与教皇方济各签署《人类博爱文件》。',
                    'ru' => 'Великий имам Ахмед ат-Тайиб родился 6 января 1946 года в Курне, Луксор. Доктор исламской философии, назначен Великим имамом 19 марта 2010 года. Возглавляет Мусульманский совет старейшин и подписал Документ о братстве с Папой Франциском в 2019 году.',
                    'ur' => 'شیخ الازہر احمد الطیب 6 جنوری 1946 کو قرنہ، الاقصر میں پیدا ہوئے۔ اسلامی فلسفے میں ڈاکٹریٹ۔ 19 مارچ 2010 کو شیخ الازہر مقرر ہوئے۔ مجلس حکماء المسلمین کے سربراہ ہیں اور 2019 میں پوپ فرانسس کے ساتھ انسانی اخوت کی دستاویز پر دستخط کیے۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 1,
            ],
            [
                'slug' => 'salama-daoud',
                'name' => [
                    'ar' => 'أ.د. سلامة داود',
                    'en' => 'Prof. Dr. Salama Daoud',
                    'fr' => 'Prof. Dr. Salama Daoud',
                    'es' => 'Prof. Dr. Salama Daoud',
                    'zh' => '萨拉马·达乌德教授',
                    'ru' => 'Проф. д-р Салама Дауд',
                    'ur' => 'پروفیسر ڈاکٹر سلامۃ داؤد',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر بالإنابة',
                    'en' => 'Acting President of Al-Azhar University',
                    'fr' => 'President par interim de l\'Universite d\'Al-Azhar',
                    'es' => 'Presidente interino de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学代理校长',
                    'ru' => 'Исполняющий обязанности ректора университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے قائم مقام صدر',
                ],
                'bio' => [
                    'ar' => 'تولى الدكتور سلامة داود إدارة شؤون جامعة الأزهر بعد وفاة الرئيس السابق الأستاذ الدكتور محمد حسين المحرصاوي في مارس 2025م. يعمل على استكمال مسيرة التطوير والتحول الرقمي في الجامعة وتعزيز مكانتها الدولية.',
                    'en' => 'Dr. Salama Daoud was assigned to manage Al-Azhar University affairs after the passing of former President Prof. Dr. Muhammad Husayn al-Mahrasawi in March 2025. He works to continue the university\'s development, digital transformation, and international standing.',
                    'fr' => 'Le Dr. Salama Daoud gere les affaires de l\'universite apres le deces du president al-Mahrasawi en mars 2025.',
                    'es' => 'El Dr. Salama Daoud gestiona los asuntos de la universidad tras el fallecimiento del presidente al-Mahrasawi en marzo de 2025.',
                    'zh' => '萨拉马·达乌德博士在前校长马赫拉萨维于2025年3月逝世后管理大学事务。',
                    'ru' => 'Д-р Салама Дауд управляет делами университета после кончины ректора аль-Махрасави в марте 2025 года.',
                    'ur' => 'ڈاکٹر سلامۃ داؤد مارچ 2025 میں سابق صدر ڈاکٹر محمد حسین المحرصاوی کی وفات کے بعد یونیورسٹی کے معاملات چلا رہے ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 2,
            ],
            [
                'slug' => 'youssef-amer',
                'name' => [
                    'ar' => 'أ.د. يوسف عامر',
                    'en' => 'Prof. Youssef Amer',
                    'fr' => 'Prof. Youssef Amer',
                    'es' => 'Prof. Youssef Amer',
                    'zh' => '优素福·阿米尔教授',
                    'ru' => 'Проф. Юсуф Амер',
                    'ur' => 'پروفیسر یوسف عامر',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة لشؤون التعليم والطلاب',
                    'en' => 'Vice President for Education and Student Affairs',
                    'fr' => 'Vice-president pour l\'Education et les Affaires Etudiantes',
                    'es' => 'Vicepresidente de Educacion y Asuntos Estudiantiles',
                    'zh' => '教育与学生事务副校长',
                    'ru' => 'Вице-президент по образованию и делам студентов',
                    'ur' => 'نائب صدر برائے تعلیم و طلبہ امور',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور يوسف عامر نيابة رئيس جامعة الأزهر لشؤون التعليم والطلاب. يشرف على العملية التعليمية وشؤون الطلاب في جميع كليات الجامعة.',
                    'en' => 'Prof. Youssef Amer serves as Vice President for Education and Student Affairs at Al-Azhar University, overseeing the educational process and student affairs across all faculties.',
                    'fr' => 'Le Prof. Youssef Amer est vice-president charge de l\'education et des affaires etudiantes.',
                    'es' => 'El Prof. Youssef Amer es vicepresidente encargado de educacion y asuntos estudiantiles.',
                    'zh' => '优素福·阿米尔教授担任教育与学生事务副校长。',
                    'ru' => 'Проф. Юсуф Амер — вице-президент по образованию и делам студентов.',
                    'ur' => 'پروفیسر یوسف عامر تعلیم و طلبہ امور کے نائب صدر ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 3,
            ],
            [
                'slug' => 'mahmoud-sedeek',
                'name' => [
                    'ar' => 'أ.د. محمود صديق',
                    'en' => 'Prof. Mahmoud Sedeek',
                    'fr' => 'Prof. Mahmoud Sedeek',
                    'es' => 'Prof. Mahmoud Sedeek',
                    'zh' => '马哈茂德·赛迪克教授',
                    'ru' => 'Проф. Махмуд Сиддик',
                    'ur' => 'پروفیسر محمود صدیق',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة للدراسات العليا والبحوث',
                    'en' => 'Vice President for Graduate Studies and Research',
                    'fr' => 'Vice-president pour les Etudes Superieures et la Recherche',
                    'es' => 'Vicepresidente de Estudios de Posgrado e Investigacion',
                    'zh' => '研究生与科研副校长',
                    'ru' => 'Вице-президент по аспирантуре и исследованиям',
                    'ur' => 'نائب صدر برائے اعلیٰ تعلیم و تحقیق',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور محمود صديق نيابة رئيس جامعة الأزهر للدراسات العليا والبحوث. يشرف على برامج الماجستير والدكتوراه والبحث العلمي والشراكات البحثية الدولية.',
                    'en' => 'Prof. Mahmoud Sedeek serves as Vice President for Graduate Studies and Research, overseeing Master\'s and PhD programs, scientific research, and international research partnerships.',
                    'fr' => 'Le Prof. Mahmoud Sedeek est vice-president charge des etudes superieures et de la recherche.',
                    'es' => 'El Prof. Mahmoud Sedeek es vicepresidente encargado de estudios de posgrado e investigacion.',
                    'zh' => '马哈茂德·赛迪克教授担任研究生与科研副校长。',
                    'ru' => 'Проф. Махмуд Сиддик — вице-президент по аспирантуре и исследованиям.',
                    'ur' => 'پروفیسر محمود صدیق اعلیٰ تعلیم و تحقیق کے نائب صدر ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 4,
            ],
            [
                'slug' => 'mohamed-fekry',
                'name' => [
                    'ar' => 'أ.د. محمد فكري',
                    'en' => 'Prof. Mohamed Fekry',
                    'fr' => 'Prof. Mohamed Fekry',
                    'es' => 'Prof. Mohamed Fekry',
                    'zh' => '穆罕默德·费克里教授',
                    'ru' => 'Проф. Мухаммад Фикри',
                    'ur' => 'پروفیسر محمد فکری',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة لفرع البنات',
                    'en' => 'Vice President for the Girls\' Branch',
                    'fr' => 'Vice-president pour la Branche des Filles',
                    'es' => 'Vicepresidente de la Rama Femenina',
                    'zh' => '女子分校副校长',
                    'ru' => 'Вице-президент по женскому отделению',
                    'ur' => 'نائب صدر برائے بنات شعبہ',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور محمد فكري نيابة رئيس جامعة الأزهر لفرع البنات. يشرف على أكثر من 30 كلية للبنات في مختلف المحافظات المصرية.',
                    'en' => 'Prof. Mohamed Fekry serves as Vice President for the Girls\' Branch, overseeing over 30 girls\' faculties across various Egyptian governorates.',
                    'fr' => 'Le Prof. Mohamed Fekry est vice-president charge de la branche des filles, supervisant plus de 30 facultes.',
                    'es' => 'El Prof. Mohamed Fekry es vicepresidente de la rama femenina, supervisando mas de 30 facultades.',
                    'zh' => '穆罕默德·费克里教授担任女子分校副校长，监管30多个女子学院。',
                    'ru' => 'Проф. Мухаммад Фикри — вице-президент по женскому отделению, курирующий более 30 женских факультетов.',
                    'ur' => 'پروفیسر محمد فکری بنات شعبے کے نائب صدر ہیں اور 30 سے زائد بنات کی فیکلٹیوں کی نگرانی کرتے ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 5,
            ],
            // Historical Grand Sheikhs
            [
                'slug' => 'muhammad-al-kharashi',
                'name' => [
                    'ar' => 'الشيخ محمد الخراشي',
                    'en' => 'Sheikh Muhammad al-Kharashi',
                    'fr' => 'Cheikh Muhammad al-Kharashi',
                    'es' => 'Jeque Muhammad al-Kharashi',
                    'zh' => '谢赫穆罕默德·哈拉希',
                    'ru' => 'Шейх Мухаммад аль-Хараши',
                    'ur' => 'شیخ محمد الخراشی',
                ],
                'title' => [
                    'ar' => 'أول شيخ رسمي للأزهر',
                    'en' => 'First Official Grand Imam of Al-Azhar',
                    'fr' => 'Premier Grand Imam officiel d\'Al-Azhar',
                    'es' => 'Primer Gran Imam oficial de Al-Azhar',
                    'zh' => '首位正式艾资哈尔大伊玛目',
                    'ru' => 'Первый официальный Великий имам Аль-Азхара',
                    'ur' => 'الازہر کے پہلے باضابطہ شیخ',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد الخراشي (ت. 1690م) هو أول شيخ رسمي يتولى منصب شيخ الأزهر الشريف. كان على المذهب المالكي وعُرف بعلمه الواسع وورعه. وضع أسس نظام المشيخة الرسمي الذي استمر حتى اليوم.',
                    'en' => 'Sheikh Muhammad al-Kharashi (d. 1690) was the first official Grand Imam of Al-Azhar. A Maliki scholar known for his vast knowledge and piety, he established the formal system of the Grand Imamate that continues to this day.',
                    'fr' => 'Le cheikh al-Kharashi (mort en 1690) fut le premier Grand Imam officiel d\'Al-Azhar, erudit malekite connu pour son savoir et sa piete.',
                    'es' => 'El jeque al-Kharashi (fallecido en 1690) fue el primer Gran Imam oficial de Al-Azhar, erudito maliki conocido por su sabiduria y piedad.',
                    'zh' => '谢赫哈拉希（卒于1690年）是首位正式的大伊玛目，马利基学派学者，以博学和虔诚著称。',
                    'ru' => 'Шейх аль-Хараши (ум. 1690) — первый официальный Великий имам, маликитский учёный.',
                    'ur' => 'شیخ محمد الخراشی (وفات 1690) الازہر کے پہلے باضابطہ شیخ الازہر تھے۔ مالکی مسلک کے عالم تھے۔',
                ],
                'era' => 'ottoman',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 6,
            ],
            [
                'slug' => 'muhammad-abduh',
                'name' => [
                    'ar' => 'الإمام محمد عبده',
                    'en' => 'Imam Muhammad Abduh',
                    'fr' => 'Imam Muhammad Abduh',
                    'es' => 'Imam Muhammad Abduh',
                    'zh' => '伊玛目穆罕默德·阿卜杜赫',
                    'ru' => 'Имам Мухаммад Абдух',
                    'ur' => 'امام محمد عبدہ',
                ],
                'title' => [
                    'ar' => 'مفتي مصر ورائد الإصلاح',
                    'en' => 'Grand Mufti of Egypt & Pioneer of Reform',
                    'fr' => 'Grand Mufti d\'Egypte et pionnier de la reforme',
                    'es' => 'Gran Mufti de Egipto y pionero de la reforma',
                    'zh' => '埃及大穆夫提与改革先驱',
                    'ru' => 'Великий муфтий Египта и пионер реформ',
                    'ur' => 'مصر کے مفتی اعظم اور اصلاح کے رہنما',
                ],
                'bio' => [
                    'ar' => 'الإمام محمد عبده (1849-1905م) أحد أبرز رواد الإصلاح في العالم الإسلامي الحديث. وُلد في محافظة البحيرة بمصر وتعلم في الأزهر على يد جمال الدين الأفغاني. تولى منصب مفتي الديار المصرية عام 1899م وقاد حركة إصلاحية شاملة في الأزهر شملت تطوير المناهج وإدخال العلوم الحديثة. دعا إلى الاجتهاد والتجديد مع الحفاظ على الثوابت.',
                    'en' => 'Imam Muhammad Abduh (1849-1905) was one of the most prominent reformers in the modern Islamic world. Born in Beheira, Egypt, he studied at Al-Azhar under Jamal al-Din al-Afghani. He became Grand Mufti of Egypt in 1899 and led comprehensive reforms at Al-Azhar, developing curricula and introducing modern sciences. He advocated for ijtihad and renewal while preserving fundamentals.',
                    'fr' => 'L\'imam Muhammad Abduh (1849-1905) fut un eminent reformateur islamique. Mufti d\'Egypte en 1899, il a mene des reformes completes a Al-Azhar.',
                    'es' => 'El imam Muhammad Abduh (1849-1905) fue un eminente reformador islamico. Mufti de Egipto en 1899, lidero reformas integrales en Al-Azhar.',
                    'zh' => '伊玛目穆罕默德·阿卜杜赫（1849-1905）是现代伊斯兰世界最杰出的改革家之一。1899年成为埃及大穆夫提，领导了艾资哈尔的全面改革。',
                    'ru' => 'Имам Мухаммад Абдух (1849-1905) — выдающийся реформатор исламского мира. Великий муфтий Египта с 1899 года, провёл комплексные реформы в Аль-Азхаре.',
                    'ur' => 'امام محمد عبدہ (1849-1905) جدید اسلامی دنیا کے نامور مصلحین میں سے ایک تھے۔ 1899 میں مصر کے مفتی اعظم بنے اور الازہر میں جامع اصلاحات کیں۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 7,
            ],
            [
                'slug' => 'mahmoud-shaltout',
                'name' => [
                    'ar' => 'الشيخ محمود شلتوت',
                    'en' => 'Sheikh Mahmoud Shaltout',
                    'fr' => 'Cheikh Mahmoud Shaltout',
                    'es' => 'Jeque Mahmoud Shaltout',
                    'zh' => '谢赫马哈茂德·沙尔图特',
                    'ru' => 'Шейх Махмуд Шальтут',
                    'ur' => 'شیخ محمود شلتوت',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر - قائد التحول الكبير',
                    'en' => 'Grand Imam - Leader of the Great Transformation',
                    'fr' => 'Grand Imam - Leader de la grande transformation',
                    'es' => 'Gran Imam - Lider de la gran transformacion',
                    'zh' => '大伊玛目 - 伟大转型的领导者',
                    'ru' => 'Великий имам — лидер великой трансформации',
                    'ur' => 'شیخ الازہر - عظیم تبدیلی کے رہنما',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمود شلتوت (1893-1963م) شيخ الأزهر الذي قاد مرحلة التحول الكبرى. تولى المشيخة عام 1958م. عُرف بفكره المستنير ودعوته إلى التقريب بين المذاهب الإسلامية. أصدر فتواه الشهيرة بجواز التعبد بالمذهب الجعفري. ساهم في صياغة قانون 103 لسنة 1961م.',
                    'en' => 'Sheikh Mahmoud Shaltout (1893-1963) led Al-Azhar\'s major transformation as Grand Imam from 1958. Known for his enlightened thought and call for rapprochement between Islamic schools, he issued his famous fatwa permitting worship according to the Ja\'fari school and contributed to drafting Law 103 of 1961.',
                    'fr' => 'Le cheikh Shaltout (1893-1963) a dirige la grande transformation d\'Al-Azhar. Il a contribue a la loi 103 de 1961.',
                    'es' => 'El jeque Shaltout (1893-1963) lidero la gran transformacion de Al-Azhar. Contribuyo a la Ley 103 de 1961.',
                    'zh' => '谢赫沙尔图特（1893-1963）领导了艾资哈尔的重大转型。参与起草1961年第103号法令。',
                    'ru' => 'Шейх Шальтут (1893-1963) возглавил великую трансформацию Аль-Азхара. Содействовал принятию Закона 103.',
                    'ur' => 'شیخ شلتوت (1893-1963) نے شیخ الازہر کی حیثیت سے الازہر کی عظیم تبدیلی کی قیادت کی۔ 1961 کے قانون 103 کی تشکیل میں حصہ لیا۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 8,
            ],
            [
                'slug' => 'al-maraghi',
                'name' => [
                    'ar' => 'الشيخ محمد مصطفى المراغي',
                    'en' => 'Sheikh Muhammad Mustafa al-Maraghi',
                    'fr' => 'Cheikh Muhammad Mustafa al-Maraghi',
                    'es' => 'Jeque Muhammad Mustafa al-Maraghi',
                    'zh' => '谢赫穆罕默德·穆斯塔法·马拉吉',
                    'ru' => 'Шейх Мухаммад Мустафа аль-Мараги',
                    'ur' => 'شیخ محمد مصطفیٰ المراغی',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر - المجدد',
                    'en' => 'Grand Imam - The Reformer',
                    'fr' => 'Grand Imam - Le reformateur',
                    'es' => 'Gran Imam - El reformador',
                    'zh' => '大伊玛目 - 改革者',
                    'ru' => 'Великий имам — реформатор',
                    'ur' => 'شیخ الازہر - مجدد',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد مصطفى المراغي (1881-1945م) تولى مشيخة الأزهر مرتين (1928-1929 و1935-1945). كان من أبرز المجددين في تاريخ الأزهر الحديث. عمل على إصلاح نظام التعليم الأزهري وتطوير المناهج وفتح باب الاجتهاد.',
                    'en' => 'Sheikh Muhammad Mustafa al-Maraghi (1881-1945) served as Grand Imam twice (1928-1929 and 1935-1945). He was among the most prominent reformers in modern Al-Azhar history, working to reform the educational system and open the door to ijtihad.',
                    'fr' => 'Le cheikh al-Maraghi (1881-1945) a servi comme Grand Imam deux fois et fut un reformateur eminent de l\'Azhar moderne.',
                    'es' => 'El jeque al-Maraghi (1881-1945) sirvio como Gran Imam dos veces y fue un reformador eminente del Azhar moderno.',
                    'zh' => '谢赫马拉吉（1881-1945）两次担任大伊玛目，是现代艾资哈尔最杰出的改革家之一。',
                    'ru' => 'Шейх аль-Мараги (1881-1945) дважды занимал пост Великого имама и был выдающимся реформатором.',
                    'ur' => 'شیخ المراغی (1881-1945) نے دو بار شیخ الازہر کا منصب سنبھالا اور جدید الازہر کے نامور مصلحین میں سے تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 9,
            ],
            [
                'slug' => 'abdel-halim-mahmoud',
                'name' => [
                    'ar' => 'الشيخ عبد الحليم محمود',
                    'en' => 'Sheikh Abdel Halim Mahmoud',
                    'fr' => 'Cheikh Abdel Halim Mahmoud',
                    'es' => 'Jeque Abdel Halim Mahmoud',
                    'zh' => '谢赫阿卜杜勒·哈利姆·马哈茂德',
                    'ru' => 'Шейх Абдель Халим Махмуд',
                    'ur' => 'شیخ عبدالحلیم محمود',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر',
                    'en' => 'Grand Imam of Al-Azhar',
                    'fr' => 'Grand Imam d\'Al-Azhar',
                    'es' => 'Gran Imam de Al-Azhar',
                    'zh' => '艾资哈尔大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара',
                    'ur' => 'شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ عبد الحليم محمود (1910-1978م) تولى مشيخة الأزهر من 1973 إلى 1978م. عُرف بتصوفه وعمقه الروحي وعلمه الغزير. حصل على الدكتوراه من جامعة السوربون بفرنسا. جمع بين الثقافتين العربية والغربية.',
                    'en' => 'Sheikh Abdel Halim Mahmoud (1910-1978) served as Grand Imam from 1973 to 1978. Known for his Sufism, spiritual depth, and vast knowledge, he earned his doctorate from the Sorbonne in France, combining Arab and Western cultures.',
                    'fr' => 'Le cheikh Abdel Halim Mahmoud (1910-1978) a ete Grand Imam de 1973 a 1978, docteur de la Sorbonne.',
                    'es' => 'El jeque Abdel Halim Mahmoud (1910-1978) fue Gran Imam de 1973 a 1978, doctor por la Sorbona.',
                    'zh' => '谢赫阿卜杜勒·哈利姆（1910-1978）1973至1978年任大伊玛目，索邦大学博士。',
                    'ru' => 'Шейх Абдель Халим Махмуд (1910-1978) был Великим имамом с 1973 по 1978 год, доктор Сорбонны.',
                    'ur' => 'شیخ عبدالحلیم محمود (1910-1978) 1973 سے 1978 تک شیخ الازہر رہے۔ سوربون فرانس سے ڈاکٹریٹ حاصل کی۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 10,
            ],
            // Notable Alumni
            [
                'slug' => 'taha-hussein',
                'name' => [
                    'ar' => 'طه حسين',
                    'en' => 'Taha Hussein',
                    'fr' => 'Taha Hussein',
                    'es' => 'Taha Hussein',
                    'zh' => '塔哈·侯赛因',
                    'ru' => 'Таха Хусейн',
                    'ur' => 'طٰہ حسین',
                ],
                'title' => [
                    'ar' => 'عميد الأدب العربي',
                    'en' => 'Dean of Arabic Literature',
                    'fr' => 'Doyen de la litterature arabe',
                    'es' => 'Decano de la literatura arabe',
                    'zh' => '阿拉伯文学泰斗',
                    'ru' => 'Декан арабской литературы',
                    'ur' => 'عربی ادب کے سربراہ',
                ],
                'bio' => [
                    'ar' => 'طه حسين (1889-1973م) الملقب بعميد الأدب العربي، درس في الأزهر ثم حصل على الدكتوراه من جامعة السوربون. رُشح لجائزة نوبل 21 مرة. من أبرز خريجي الأزهر وأحد أعظم الأدباء العرب في العصر الحديث.',
                    'en' => 'Taha Hussein (1889-1973), known as the "Dean of Arabic Literature," studied at Al-Azhar then earned his doctorate from the Sorbonne. He was nominated for the Nobel Prize 21 times and is one of Al-Azhar\'s most distinguished alumni and one of the greatest modern Arab writers.',
                    'fr' => 'Taha Hussein (1889-1973), "Doyen de la litterature arabe", a etudie a Al-Azhar puis a la Sorbonne. Nomine 21 fois au prix Nobel.',
                    'es' => 'Taha Hussein (1889-1973), "Decano de la literatura arabe", estudio en Al-Azhar y luego en la Sorbona. Nominado 21 veces al Nobel.',
                    'zh' => '塔哈·侯赛因（1889-1973），被誉为"阿拉伯文学泰斗"，曾在艾资哈尔学习，后获索邦大学博士学位。21次获诺贝尔奖提名。',
                    'ru' => 'Таха Хусейн (1889-1973), «декан арабской литературы», учился в Аль-Азхаре, затем в Сорбонне. 21 раз номинирован на Нобелевскую премию.',
                    'ur' => 'طٰہ حسین (1889-1973) عربی ادب کے سربراہ کے نام سے مشہور ہیں۔ الازہر میں پڑھے، پھر سوربون سے ڈاکٹریٹ۔ 21 بار نوبل انعام کے لیے نامزد۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 11,
            ],
            [
                'slug' => 'ibn-khaldun',
                'name' => [
                    'ar' => 'ابن خلدون',
                    'en' => 'Ibn Khaldun',
                    'fr' => 'Ibn Khaldoun',
                    'es' => 'Ibn Jaldun',
                    'zh' => '伊本·赫勒敦',
                    'ru' => 'Ибн Хальдун',
                    'ur' => 'ابن خلدون',
                ],
                'title' => [
                    'ar' => 'مؤسس علم الاجتماع',
                    'en' => 'Founder of Sociology',
                    'fr' => 'Fondateur de la sociologie',
                    'es' => 'Fundador de la sociologia',
                    'zh' => '社会学创始人',
                    'ru' => 'Основатель социологии',
                    'ur' => 'سماجیات کے بانی',
                ],
                'bio' => [
                    'ar' => 'عبد الرحمن بن محمد بن خلدون (1332-1406م) هو العالم والمؤرخ والفيلسوف العربي الشهير، مؤسس علم العمران البشري. وُلد في تونس ورحل إلى مصر حيث عُيّن قاضياً للقضاة المالكية ودرّس في الأزهر. ألّف كتابه الشهير "المقدمة" الذي يُعد من أهم المؤلفات في تاريخ الفكر الإنساني.',
                    'en' => 'Abd al-Rahman ibn Muhammad ibn Khaldun (1332-1406) was the renowned Arab scholar, historian, and philosopher, founder of the science of civilization (sociology). Born in Tunisia, he traveled to Egypt where he was appointed Maliki Chief Judge and taught at Al-Azhar. He authored the famous "Muqaddimah," one of the most important works in human intellectual history.',
                    'fr' => 'Ibn Khaldoun (1332-1406), fondateur de la sociologie, a enseigne a Al-Azhar et ecrit la celebre "Muqaddimah".',
                    'es' => 'Ibn Jaldun (1332-1406), fundador de la sociologia, enseno en Al-Azhar y escribio la celebre "Muqaddimah".',
                    'zh' => '伊本·赫勒敦（1332-1406），社会学创始人，在艾资哈尔教学并撰写了著名的《穆卡迪玛》。',
                    'ru' => 'Ибн Хальдун (1332-1406) — основатель социологии, преподавал в Аль-Азхаре и написал знаменитую «Мукаддиму».',
                    'ur' => 'ابن خلدون (1332-1406) عظیم عالم، مؤرخ اور فلسفی، سماجیات کے بانی۔ مصر میں قاضی القضاۃ مقرر ہوئے اور الازہر میں تدریس کی۔ مشہور "مقدمہ" کے مصنف۔',
                ],
                'era' => 'mamluk',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 12,
            ],
            [
                'slug' => 'saad-zaghloul',
                'name' => [
                    'ar' => 'سعد زغلول',
                    'en' => 'Saad Zaghloul',
                    'fr' => 'Saad Zaghloul',
                    'es' => 'Saad Zaghloul',
                    'zh' => '萨阿德·扎格卢尔',
                    'ru' => 'Саад Заглул',
                    'ur' => 'سعد زغلول',
                ],
                'title' => [
                    'ar' => 'زعيم الحركة الوطنية المصرية',
                    'en' => 'Leader of the Egyptian Nationalist Movement',
                    'fr' => 'Leader du mouvement nationaliste egyptien',
                    'es' => 'Lider del movimiento nacionalista egipcio',
                    'zh' => '埃及民族运动领袖',
                    'ru' => 'Лидер египетского национального движения',
                    'ur' => 'مصری قومی تحریک کے رہنما',
                ],
                'bio' => [
                    'ar' => 'سعد زغلول (1859-1927م) زعيم وطني مصري ومؤسس حزب الوفد. درس في الأزهر وتتلمذ على يد الإمام محمد عبده. قاد ثورة 1919 ضد الاحتلال البريطاني وأصبح رئيساً لوزراء مصر. يُعد من أبرز خريجي الأزهر في المجال السياسي.',
                    'en' => 'Saad Zaghloul (1859-1927) was an Egyptian nationalist leader and founder of the Wafd Party. He studied at Al-Azhar under Muhammad Abduh, led the 1919 Revolution against British occupation, and became Prime Minister of Egypt. He is among Al-Azhar\'s most prominent alumni in politics.',
                    'fr' => 'Saad Zaghloul (1859-1927), leader nationaliste egyptien et fondateur du parti Wafd, a etudie a Al-Azhar.',
                    'es' => 'Saad Zaghloul (1859-1927), lider nacionalista egipcio y fundador del partido Wafd, estudio en Al-Azhar.',
                    'zh' => '萨阿德·扎格卢尔（1859-1927），埃及民族运动领袖，华夫脱党创始人，曾在艾资哈尔学习。',
                    'ru' => 'Саад Заглул (1859-1927) — лидер египетского национального движения, основатель партии Вафд, учился в Аль-Азхаре.',
                    'ur' => 'سعد زغلول (1859-1927) مصری قومی رہنما اور وفد پارٹی کے بانی تھے۔ الازہر میں محمد عبدہ سے پڑھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 13,
            ],
            [
                'slug' => 'muhammad-metwalli-sha-rawi',
                'name' => [
                    'ar' => 'الشيخ محمد متولي الشعراوي',
                    'en' => 'Sheikh Muhammad Metwalli al-Sha\'rawi',
                    'fr' => 'Cheikh Muhammad Metwalli al-Sha\'rawi',
                    'es' => 'Jeque Muhammad Metwalli al-Sha\'rawi',
                    'zh' => '谢赫穆罕默德·麦特瓦利·沙阿拉维',
                    'ru' => 'Шейх Мухаммад Метвалли аш-Шаарави',
                    'ur' => 'شیخ محمد متولی الشعراوی',
                ],
                'title' => [
                    'ar' => 'إمام الدعاة',
                    'en' => 'Imam of Preachers',
                    'fr' => 'Imam des predicateurs',
                    'es' => 'Imam de los predicadores',
                    'zh' => '传教士之伊玛目',
                    'ru' => 'Имам проповедников',
                    'ur' => 'امام الدعاۃ',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد متولي الشعراوي (1911-1998م) خريج الأزهر وأشهر داعية إسلامي في مصر. شغل منصب وزير الأوقاف. اشتهر بتفسيره المبسط للقرآن الكريم عبر التلفزيون، وأثّر في ملايين المسلمين حول العالم بأسلوبه السهل الممتنع.',
                    'en' => 'Sheikh Muhammad Metwalli al-Sha\'rawi (1911-1998) was an Al-Azhar graduate and Egypt\'s most popular Islamic preacher. He served as Minister of Endowments and became famous for his accessible television Quran commentary, influencing millions of Muslims worldwide.',
                    'fr' => 'Le cheikh al-Sha\'rawi (1911-1998), diplome d\'Al-Azhar, fut le predicateur islamique le plus populaire d\'Egypte.',
                    'es' => 'El jeque al-Sha\'rawi (1911-1998), graduado de Al-Azhar, fue el predicador islamico mas popular de Egipto.',
                    'zh' => '谢赫沙阿拉维（1911-1998），艾资哈尔毕业生，埃及最受欢迎的伊斯兰传教士。',
                    'ru' => 'Шейх аш-Шаарави (1911-1998) — самый популярный исламский проповедник Египта, выпускник Аль-Азхара.',
                    'ur' => 'شیخ الشعراوی (1911-1998) الازہر کے فارغ التحصیل اور مصر کے مقبول ترین اسلامی داعی تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 14,
            ],
        ];

        foreach ($people as $data) {
            Person::create($data);
        }
    }
}
