<?php

namespace Database\Seeders;

use App\Models\Person;
use Illuminate\Database\Seeder;

class PersonSeeder extends Seeder
{
    public function run(): void
    {
        $people = [
            // Current Leadership
            [
                'slug' => 'ahmed-el-tayeb',
                'name' => [
                    'ar' => 'الإمام الأكبر أحمد الطيب',
                    'en' => 'Grand Imam Ahmed el-Tayeb',
                    'fr' => 'Grand Imam Ahmed el-Tayeb',
                    'es' => 'Gran Imam Ahmed el-Tayeb',
                    'zh' => '大伊玛目艾哈迈德·泰耶布',
                    'ru' => 'Великий имам Ахмед ат-Тайиб',
                    'ur' => 'شیخ الازہر احمد الطیب',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الشريف',
                    'en' => 'Grand Imam of Al-Azhar',
                    'fr' => 'Grand Imam d\'Al-Azhar',
                    'es' => 'Gran Imam de Al-Azhar',
                    'zh' => '艾资哈尔大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара',
                    'ur' => 'شیخ الازہر الشریف',
                ],
                'bio' => [
                    'ar' => 'الإمام الأكبر أحمد محمد أحمد الطيب، وُلد في 6 يناير 1946 بالقرنة، الأقصر. حصل على بكالوريوس أصول الدين (1969) بامتياز، وماجستير في العقيدة والفلسفة (1971)، ودكتوراه في الفلسفة الإسلامية (1977). درس في جامعة باريس (1977-1978) ويجيد الفرنسية. تدرج من مدرس مساعد إلى أستاذ بالأزهر (1988)، ثم عميداً لعدة كليات. شغل منصب مفتي مصر (2002-2003) ورئيس جامعة الأزهر (2003-2010). عُيّن شيخاً للأزهر في 19 مارس 2010. يرأس مجلس حكماء المسلمين منذ 2014. وقّع وثيقة الأخوة الإنسانية مع البابا فرنسيس في أبوظبي عام 2019. قام بأكثر من 34 زيارة دولية في 21 دولة.',
                    'en' => 'Grand Imam Ahmed Mohamed Ahmed el-Tayeb was born January 6, 1946 in Qurna, Luxor. He earned his B.A. in Theology (1969, with distinction), M.A. in Creed and Philosophy (1971), and Ph.D. in Islamic Philosophy (1977). He studied at the University of Paris (1977-78) and is fluent in French. He rose from teaching assistant to Professor at Al-Azhar (1988), then Dean of several faculties. He served as Grand Mufti of Egypt (2002-2003) and President of Al-Azhar University (2003-2010). Appointed Grand Imam on March 19, 2010. He chairs the Muslim Council of Elders since 2014 and signed the Document on Human Fraternity with Pope Francis in Abu Dhabi in 2019. He has made 34+ international visits across 21 countries.',
                    'fr' => 'Le Grand Imam Ahmed el-Tayeb, ne le 6 janvier 1946 a Qurna, Louxor. Docteur en philosophie islamique, il a ete nomme Grand Imam le 19 mars 2010. Il preside le Conseil des sages musulmans et a signe le Document sur la Fraternite Humaine avec le pape Francois en 2019.',
                    'es' => 'El Gran Imam Ahmed el-Tayeb, nacido el 6 de enero de 1946 en Qurna, Luxor. Doctor en filosofia islamica, fue nombrado Gran Imam el 19 de marzo de 2010. Preside el Consejo de Sabios Musulmanes y firmo el Documento sobre la Fraternidad Humana con el papa Francisco en 2019.',
                    'zh' => '大伊玛目艾哈迈德·泰耶布1946年1月6日出生于卢克索。伊斯兰哲学博士，2010年3月19日就任大伊玛目。主持穆斯林长老委员会，2019年与教皇方济各签署《人类博爱文件》。',
                    'ru' => 'Великий имам Ахмед ат-Тайиб родился 6 января 1946 года в Курне, Луксор. Доктор исламской философии, назначен Великим имамом 19 марта 2010 года. Возглавляет Мусульманский совет старейшин и подписал Документ о братстве с Папой Франциском в 2019 году.',
                    'ur' => 'شیخ الازہر احمد الطیب 6 جنوری 1946 کو قرنہ، الاقصر میں پیدا ہوئے۔ اسلامی فلسفے میں ڈاکٹریٹ۔ 19 مارچ 2010 کو شیخ الازہر مقرر ہوئے۔ مجلس حکماء المسلمین کے سربراہ ہیں اور 2019 میں پوپ فرانسس کے ساتھ انسانی اخوت کی دستاویز پر دستخط کیے۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 1,
            ],
            [
                'slug' => 'salama-daoud',
                'name' => [
                    'ar' => 'أ.د. سلامة داود',
                    'en' => 'Prof. Dr. Salama Daoud',
                    'fr' => 'Prof. Dr. Salama Daoud',
                    'es' => 'Prof. Dr. Salama Daoud',
                    'zh' => '萨拉马·达乌德教授',
                    'ru' => 'Проф. д-р Салама Дауд',
                    'ur' => 'پروفیسر ڈاکٹر سلامۃ داؤد',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر بالإنابة',
                    'en' => 'Acting President of Al-Azhar University',
                    'fr' => 'President par interim de l\'Universite d\'Al-Azhar',
                    'es' => 'Presidente interino de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学代理校长',
                    'ru' => 'Исполняющий обязанности ректора университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے قائم مقام صدر',
                ],
                'bio' => [
                    'ar' => 'تولى الدكتور سلامة داود إدارة شؤون جامعة الأزهر بعد وفاة الرئيس السابق الأستاذ الدكتور محمد حسين المحرصاوي في مارس 2025م. يعمل على استكمال مسيرة التطوير والتحول الرقمي في الجامعة وتعزيز مكانتها الدولية.',
                    'en' => 'Dr. Salama Daoud was assigned to manage Al-Azhar University affairs after the passing of former President Prof. Dr. Muhammad Husayn al-Mahrasawi in March 2025. He works to continue the university\'s development, digital transformation, and international standing.',
                    'fr' => 'Le Dr. Salama Daoud gere les affaires de l\'universite apres le deces du president al-Mahrasawi en mars 2025.',
                    'es' => 'El Dr. Salama Daoud gestiona los asuntos de la universidad tras el fallecimiento del presidente al-Mahrasawi en marzo de 2025.',
                    'zh' => '萨拉马·达乌德博士在前校长马赫拉萨维于2025年3月逝世后管理大学事务。',
                    'ru' => 'Д-р Салама Дауд управляет делами университета после кончины ректора аль-Махрасави в марте 2025 года.',
                    'ur' => 'ڈاکٹر سلامۃ داؤد مارچ 2025 میں سابق صدر ڈاکٹر محمد حسین المحرصاوی کی وفات کے بعد یونیورسٹی کے معاملات چلا رہے ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 2,
            ],
            [
                'slug' => 'youssef-amer',
                'name' => [
                    'ar' => 'أ.د. يوسف عامر',
                    'en' => 'Prof. Youssef Amer',
                    'fr' => 'Prof. Youssef Amer',
                    'es' => 'Prof. Youssef Amer',
                    'zh' => '优素福·阿米尔教授',
                    'ru' => 'Проф. Юсуф Амер',
                    'ur' => 'پروفیسر یوسف عامر',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة لشؤون التعليم والطلاب',
                    'en' => 'Vice President for Education and Student Affairs',
                    'fr' => 'Vice-president pour l\'Education et les Affaires Etudiantes',
                    'es' => 'Vicepresidente de Educacion y Asuntos Estudiantiles',
                    'zh' => '教育与学生事务副校长',
                    'ru' => 'Вице-президент по образованию и делам студентов',
                    'ur' => 'نائب صدر برائے تعلیم و طلبہ امور',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور يوسف عامر نيابة رئيس جامعة الأزهر لشؤون التعليم والطلاب. يشرف على العملية التعليمية وشؤون الطلاب في جميع كليات الجامعة.',
                    'en' => 'Prof. Youssef Amer serves as Vice President for Education and Student Affairs at Al-Azhar University, overseeing the educational process and student affairs across all faculties.',
                    'fr' => 'Le Prof. Youssef Amer est vice-president charge de l\'education et des affaires etudiantes.',
                    'es' => 'El Prof. Youssef Amer es vicepresidente encargado de educacion y asuntos estudiantiles.',
                    'zh' => '优素福·阿米尔教授担任教育与学生事务副校长。',
                    'ru' => 'Проф. Юсуф Амер — вице-президент по образованию и делам студентов.',
                    'ur' => 'پروفیسر یوسف عامر تعلیم و طلبہ امور کے نائب صدر ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 3,
            ],
            [
                'slug' => 'mahmoud-sedeek',
                'name' => [
                    'ar' => 'أ.د. محمود صديق',
                    'en' => 'Prof. Mahmoud Sedeek',
                    'fr' => 'Prof. Mahmoud Sedeek',
                    'es' => 'Prof. Mahmoud Sedeek',
                    'zh' => '马哈茂德·赛迪克教授',
                    'ru' => 'Проф. Махмуд Сиддик',
                    'ur' => 'پروفیسر محمود صدیق',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة للدراسات العليا والبحوث',
                    'en' => 'Vice President for Graduate Studies and Research',
                    'fr' => 'Vice-president pour les Etudes Superieures et la Recherche',
                    'es' => 'Vicepresidente de Estudios de Posgrado e Investigacion',
                    'zh' => '研究生与科研副校长',
                    'ru' => 'Вице-президент по аспирантуре и исследованиям',
                    'ur' => 'نائب صدر برائے اعلیٰ تعلیم و تحقیق',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور محمود صديق نيابة رئيس جامعة الأزهر للدراسات العليا والبحوث. يشرف على برامج الماجستير والدكتوراه والبحث العلمي والشراكات البحثية الدولية.',
                    'en' => 'Prof. Mahmoud Sedeek serves as Vice President for Graduate Studies and Research, overseeing Master\'s and PhD programs, scientific research, and international research partnerships.',
                    'fr' => 'Le Prof. Mahmoud Sedeek est vice-president charge des etudes superieures et de la recherche.',
                    'es' => 'El Prof. Mahmoud Sedeek es vicepresidente encargado de estudios de posgrado e investigacion.',
                    'zh' => '马哈茂德·赛迪克教授担任研究生与科研副校长。',
                    'ru' => 'Проф. Махмуд Сиддик — вице-президент по аспирантуре и исследованиям.',
                    'ur' => 'پروفیسر محمود صدیق اعلیٰ تعلیم و تحقیق کے نائب صدر ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 4,
            ],
            [
                'slug' => 'mohamed-fekry',
                'name' => [
                    'ar' => 'أ.د. محمد فكري',
                    'en' => 'Prof. Mohamed Fekry',
                    'fr' => 'Prof. Mohamed Fekry',
                    'es' => 'Prof. Mohamed Fekry',
                    'zh' => '穆罕默德·费克里教授',
                    'ru' => 'Проф. Мухаммад Фикри',
                    'ur' => 'پروفیسر محمد فکری',
                ],
                'title' => [
                    'ar' => 'نائب رئيس الجامعة لفرع البنات',
                    'en' => 'Vice President for the Girls\' Branch',
                    'fr' => 'Vice-president pour la Branche des Filles',
                    'es' => 'Vicepresidente de la Rama Femenina',
                    'zh' => '女子分校副校长',
                    'ru' => 'Вице-президент по женскому отделению',
                    'ur' => 'نائب صدر برائے بنات شعبہ',
                ],
                'bio' => [
                    'ar' => 'يتولى الأستاذ الدكتور محمد فكري نيابة رئيس جامعة الأزهر لفرع البنات. يشرف على أكثر من 30 كلية للبنات في مختلف المحافظات المصرية.',
                    'en' => 'Prof. Mohamed Fekry serves as Vice President for the Girls\' Branch, overseeing over 30 girls\' faculties across various Egyptian governorates.',
                    'fr' => 'Le Prof. Mohamed Fekry est vice-president charge de la branche des filles, supervisant plus de 30 facultes.',
                    'es' => 'El Prof. Mohamed Fekry es vicepresidente de la rama femenina, supervisando mas de 30 facultades.',
                    'zh' => '穆罕默德·费克里教授担任女子分校副校长，监管30多个女子学院。',
                    'ru' => 'Проф. Мухаммад Фикри — вице-президент по женскому отделению, курирующий более 30 женских факультетов.',
                    'ur' => 'پروفیسر محمد فکری بنات شعبے کے نائب صدر ہیں اور 30 سے زائد بنات کی فیکلٹیوں کی نگرانی کرتے ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => false,
                'is_current_leadership' => true,
                'order' => 5,
            ],
            // Historical Grand Sheikhs
            [
                'slug' => 'muhammad-al-kharashi',
                'name' => [
                    'ar' => 'الشيخ محمد الخراشي',
                    'en' => 'Sheikh Muhammad al-Kharashi',
                    'fr' => 'Cheikh Muhammad al-Kharashi',
                    'es' => 'Jeque Muhammad al-Kharashi',
                    'zh' => '谢赫穆罕默德·哈拉希',
                    'ru' => 'Шейх Мухаммад аль-Хараши',
                    'ur' => 'شیخ محمد الخراشی',
                ],
                'title' => [
                    'ar' => 'أول شيخ رسمي للأزهر',
                    'en' => 'First Official Grand Imam of Al-Azhar',
                    'fr' => 'Premier Grand Imam officiel d\'Al-Azhar',
                    'es' => 'Primer Gran Imam oficial de Al-Azhar',
                    'zh' => '首位正式艾资哈尔大伊玛目',
                    'ru' => 'Первый официальный Великий имам Аль-Азхара',
                    'ur' => 'الازہر کے پہلے باضابطہ شیخ',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد الخراشي (ت. 1690م) هو أول شيخ رسمي يتولى منصب شيخ الأزهر الشريف. كان على المذهب المالكي وعُرف بعلمه الواسع وورعه. وضع أسس نظام المشيخة الرسمي الذي استمر حتى اليوم.',
                    'en' => 'Sheikh Muhammad al-Kharashi (d. 1690) was the first official Grand Imam of Al-Azhar. A Maliki scholar known for his vast knowledge and piety, he established the formal system of the Grand Imamate that continues to this day.',
                    'fr' => 'Le cheikh al-Kharashi (mort en 1690) fut le premier Grand Imam officiel d\'Al-Azhar, erudit malekite connu pour son savoir et sa piete.',
                    'es' => 'El jeque al-Kharashi (fallecido en 1690) fue el primer Gran Imam oficial de Al-Azhar, erudito maliki conocido por su sabiduria y piedad.',
                    'zh' => '谢赫哈拉希（卒于1690年）是首位正式的大伊玛目，马利基学派学者，以博学和虔诚著称。',
                    'ru' => 'Шейх аль-Хараши (ум. 1690) — первый официальный Великий имам, маликитский учёный.',
                    'ur' => 'شیخ محمد الخراشی (وفات 1690) الازہر کے پہلے باضابطہ شیخ الازہر تھے۔ مالکی مسلک کے عالم تھے۔',
                ],
                'era' => 'ottoman',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 6,
            ],
            [
                'slug' => 'muhammad-abduh',
                'name' => [
                    'ar' => 'الإمام محمد عبده',
                    'en' => 'Imam Muhammad Abduh',
                    'fr' => 'Imam Muhammad Abduh',
                    'es' => 'Imam Muhammad Abduh',
                    'zh' => '伊玛目穆罕默德·阿卜杜赫',
                    'ru' => 'Имам Мухаммад Абдух',
                    'ur' => 'امام محمد عبدہ',
                ],
                'title' => [
                    'ar' => 'مفتي مصر ورائد الإصلاح',
                    'en' => 'Grand Mufti of Egypt & Pioneer of Reform',
                    'fr' => 'Grand Mufti d\'Egypte et pionnier de la reforme',
                    'es' => 'Gran Mufti de Egipto y pionero de la reforma',
                    'zh' => '埃及大穆夫提与改革先驱',
                    'ru' => 'Великий муфтий Египта и пионер реформ',
                    'ur' => 'مصر کے مفتی اعظم اور اصلاح کے رہنما',
                ],
                'bio' => [
                    'ar' => 'الإمام محمد عبده (1849-1905م) أحد أبرز رواد الإصلاح في العالم الإسلامي الحديث. وُلد في محافظة البحيرة بمصر وتعلم في الأزهر على يد جمال الدين الأفغاني. تولى منصب مفتي الديار المصرية عام 1899م وقاد حركة إصلاحية شاملة في الأزهر شملت تطوير المناهج وإدخال العلوم الحديثة. دعا إلى الاجتهاد والتجديد مع الحفاظ على الثوابت.',
                    'en' => 'Imam Muhammad Abduh (1849-1905) was one of the most prominent reformers in the modern Islamic world. Born in Beheira, Egypt, he studied at Al-Azhar under Jamal al-Din al-Afghani. He became Grand Mufti of Egypt in 1899 and led comprehensive reforms at Al-Azhar, developing curricula and introducing modern sciences. He advocated for ijtihad and renewal while preserving fundamentals.',
                    'fr' => 'L\'imam Muhammad Abduh (1849-1905) fut un eminent reformateur islamique. Mufti d\'Egypte en 1899, il a mene des reformes completes a Al-Azhar.',
                    'es' => 'El imam Muhammad Abduh (1849-1905) fue un eminente reformador islamico. Mufti de Egipto en 1899, lidero reformas integrales en Al-Azhar.',
                    'zh' => '伊玛目穆罕默德·阿卜杜赫（1849-1905）是现代伊斯兰世界最杰出的改革家之一。1899年成为埃及大穆夫提，领导了艾资哈尔的全面改革。',
                    'ru' => 'Имам Мухаммад Абдух (1849-1905) — выдающийся реформатор исламского мира. Великий муфтий Египта с 1899 года, провёл комплексные реформы в Аль-Азхаре.',
                    'ur' => 'امام محمد عبدہ (1849-1905) جدید اسلامی دنیا کے نامور مصلحین میں سے ایک تھے۔ 1899 میں مصر کے مفتی اعظم بنے اور الازہر میں جامع اصلاحات کیں۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 7,
            ],
            [
                'slug' => 'mahmoud-shaltout',
                'name' => [
                    'ar' => 'الشيخ محمود شلتوت',
                    'en' => 'Sheikh Mahmoud Shaltout',
                    'fr' => 'Cheikh Mahmoud Shaltout',
                    'es' => 'Jeque Mahmoud Shaltout',
                    'zh' => '谢赫马哈茂德·沙尔图特',
                    'ru' => 'Шейх Махмуд Шальтут',
                    'ur' => 'شیخ محمود شلتوت',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر - قائد التحول الكبير',
                    'en' => 'Grand Imam - Leader of the Great Transformation',
                    'fr' => 'Grand Imam - Leader de la grande transformation',
                    'es' => 'Gran Imam - Lider de la gran transformacion',
                    'zh' => '大伊玛目 - 伟大转型的领导者',
                    'ru' => 'Великий имам — лидер великой трансформации',
                    'ur' => 'شیخ الازہر - عظیم تبدیلی کے رہنما',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمود شلتوت (1893-1963م) شيخ الأزهر الذي قاد مرحلة التحول الكبرى. تولى المشيخة عام 1958م. عُرف بفكره المستنير ودعوته إلى التقريب بين المذاهب الإسلامية. أصدر فتواه الشهيرة بجواز التعبد بالمذهب الجعفري. ساهم في صياغة قانون 103 لسنة 1961م.',
                    'en' => 'Sheikh Mahmoud Shaltout (1893-1963) led Al-Azhar\'s major transformation as Grand Imam from 1958. Known for his enlightened thought and call for rapprochement between Islamic schools, he issued his famous fatwa permitting worship according to the Ja\'fari school and contributed to drafting Law 103 of 1961.',
                    'fr' => 'Le cheikh Shaltout (1893-1963) a dirige la grande transformation d\'Al-Azhar. Il a contribue a la loi 103 de 1961.',
                    'es' => 'El jeque Shaltout (1893-1963) lidero la gran transformacion de Al-Azhar. Contribuyo a la Ley 103 de 1961.',
                    'zh' => '谢赫沙尔图特（1893-1963）领导了艾资哈尔的重大转型。参与起草1961年第103号法令。',
                    'ru' => 'Шейх Шальтут (1893-1963) возглавил великую трансформацию Аль-Азхара. Содействовал принятию Закона 103.',
                    'ur' => 'شیخ شلتوت (1893-1963) نے شیخ الازہر کی حیثیت سے الازہر کی عظیم تبدیلی کی قیادت کی۔ 1961 کے قانون 103 کی تشکیل میں حصہ لیا۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 8,
            ],
            [
                'slug' => 'al-maraghi',
                'name' => [
                    'ar' => 'الشيخ محمد مصطفى المراغي',
                    'en' => 'Sheikh Muhammad Mustafa al-Maraghi',
                    'fr' => 'Cheikh Muhammad Mustafa al-Maraghi',
                    'es' => 'Jeque Muhammad Mustafa al-Maraghi',
                    'zh' => '谢赫穆罕默德·穆斯塔法·马拉吉',
                    'ru' => 'Шейх Мухаммад Мустафа аль-Мараги',
                    'ur' => 'شیخ محمد مصطفیٰ المراغی',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر - المجدد',
                    'en' => 'Grand Imam - The Reformer',
                    'fr' => 'Grand Imam - Le reformateur',
                    'es' => 'Gran Imam - El reformador',
                    'zh' => '大伊玛目 - 改革者',
                    'ru' => 'Великий имам — реформатор',
                    'ur' => 'شیخ الازہر - مجدد',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد مصطفى المراغي (1881-1945م) تولى مشيخة الأزهر مرتين (1928-1929 و1935-1945). كان من أبرز المجددين في تاريخ الأزهر الحديث. عمل على إصلاح نظام التعليم الأزهري وتطوير المناهج وفتح باب الاجتهاد.',
                    'en' => 'Sheikh Muhammad Mustafa al-Maraghi (1881-1945) served as Grand Imam twice (1928-1929 and 1935-1945). He was among the most prominent reformers in modern Al-Azhar history, working to reform the educational system and open the door to ijtihad.',
                    'fr' => 'Le cheikh al-Maraghi (1881-1945) a servi comme Grand Imam deux fois et fut un reformateur eminent de l\'Azhar moderne.',
                    'es' => 'El jeque al-Maraghi (1881-1945) sirvio como Gran Imam dos veces y fue un reformador eminente del Azhar moderno.',
                    'zh' => '谢赫马拉吉（1881-1945）两次担任大伊玛目，是现代艾资哈尔最杰出的改革家之一。',
                    'ru' => 'Шейх аль-Мараги (1881-1945) дважды занимал пост Великого имама и был выдающимся реформатором.',
                    'ur' => 'شیخ المراغی (1881-1945) نے دو بار شیخ الازہر کا منصب سنبھالا اور جدید الازہر کے نامور مصلحین میں سے تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 9,
            ],
            [
                'slug' => 'abdel-halim-mahmoud',
                'name' => [
                    'ar' => 'الشيخ عبد الحليم محمود',
                    'en' => 'Sheikh Abdel Halim Mahmoud',
                    'fr' => 'Cheikh Abdel Halim Mahmoud',
                    'es' => 'Jeque Abdel Halim Mahmoud',
                    'zh' => '谢赫阿卜杜勒·哈利姆·马哈茂德',
                    'ru' => 'Шейх Абдель Халим Махмуд',
                    'ur' => 'شیخ عبدالحلیم محمود',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر',
                    'en' => 'Grand Imam of Al-Azhar',
                    'fr' => 'Grand Imam d\'Al-Azhar',
                    'es' => 'Gran Imam de Al-Azhar',
                    'zh' => '艾资哈尔大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара',
                    'ur' => 'شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ عبد الحليم محمود (1910-1978م) تولى مشيخة الأزهر من 1973 إلى 1978م. عُرف بتصوفه وعمقه الروحي وعلمه الغزير. حصل على الدكتوراه من جامعة السوربون بفرنسا. جمع بين الثقافتين العربية والغربية.',
                    'en' => 'Sheikh Abdel Halim Mahmoud (1910-1978) served as Grand Imam from 1973 to 1978. Known for his Sufism, spiritual depth, and vast knowledge, he earned his doctorate from the Sorbonne in France, combining Arab and Western cultures.',
                    'fr' => 'Le cheikh Abdel Halim Mahmoud (1910-1978) a ete Grand Imam de 1973 a 1978, docteur de la Sorbonne.',
                    'es' => 'El jeque Abdel Halim Mahmoud (1910-1978) fue Gran Imam de 1973 a 1978, doctor por la Sorbona.',
                    'zh' => '谢赫阿卜杜勒·哈利姆（1910-1978）1973至1978年任大伊玛目，索邦大学博士。',
                    'ru' => 'Шейх Абдель Халим Махмуд (1910-1978) был Великим имамом с 1973 по 1978 год, доктор Сорбонны.',
                    'ur' => 'شیخ عبدالحلیم محمود (1910-1978) 1973 سے 1978 تک شیخ الازہر رہے۔ سوربون فرانس سے ڈاکٹریٹ حاصل کی۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 10,
            ],
            // Notable Alumni
            [
                'slug' => 'taha-hussein',
                'name' => [
                    'ar' => 'طه حسين',
                    'en' => 'Taha Hussein',
                    'fr' => 'Taha Hussein',
                    'es' => 'Taha Hussein',
                    'zh' => '塔哈·侯赛因',
                    'ru' => 'Таха Хусейн',
                    'ur' => 'طٰہ حسین',
                ],
                'title' => [
                    'ar' => 'عميد الأدب العربي',
                    'en' => 'Dean of Arabic Literature',
                    'fr' => 'Doyen de la litterature arabe',
                    'es' => 'Decano de la literatura arabe',
                    'zh' => '阿拉伯文学泰斗',
                    'ru' => 'Декан арабской литературы',
                    'ur' => 'عربی ادب کے سربراہ',
                ],
                'bio' => [
                    'ar' => 'طه حسين (1889-1973م) الملقب بعميد الأدب العربي، درس في الأزهر ثم حصل على الدكتوراه من جامعة السوربون. رُشح لجائزة نوبل 21 مرة. من أبرز خريجي الأزهر وأحد أعظم الأدباء العرب في العصر الحديث.',
                    'en' => 'Taha Hussein (1889-1973), known as the "Dean of Arabic Literature," studied at Al-Azhar then earned his doctorate from the Sorbonne. He was nominated for the Nobel Prize 21 times and is one of Al-Azhar\'s most distinguished alumni and one of the greatest modern Arab writers.',
                    'fr' => 'Taha Hussein (1889-1973), "Doyen de la litterature arabe", a etudie a Al-Azhar puis a la Sorbonne. Nomine 21 fois au prix Nobel.',
                    'es' => 'Taha Hussein (1889-1973), "Decano de la literatura arabe", estudio en Al-Azhar y luego en la Sorbona. Nominado 21 veces al Nobel.',
                    'zh' => '塔哈·侯赛因（1889-1973），被誉为"阿拉伯文学泰斗"，曾在艾资哈尔学习，后获索邦大学博士学位。21次获诺贝尔奖提名。',
                    'ru' => 'Таха Хусейн (1889-1973), «декан арабской литературы», учился в Аль-Азхаре, затем в Сорбонне. 21 раз номинирован на Нобелевскую премию.',
                    'ur' => 'طٰہ حسین (1889-1973) عربی ادب کے سربراہ کے نام سے مشہور ہیں۔ الازہر میں پڑھے، پھر سوربون سے ڈاکٹریٹ۔ 21 بار نوبل انعام کے لیے نامزد۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 11,
            ],
            [
                'slug' => 'ibn-khaldun',
                'name' => [
                    'ar' => 'ابن خلدون',
                    'en' => 'Ibn Khaldun',
                    'fr' => 'Ibn Khaldoun',
                    'es' => 'Ibn Jaldun',
                    'zh' => '伊本·赫勒敦',
                    'ru' => 'Ибн Хальдун',
                    'ur' => 'ابن خلدون',
                ],
                'title' => [
                    'ar' => 'مؤسس علم الاجتماع',
                    'en' => 'Founder of Sociology',
                    'fr' => 'Fondateur de la sociologie',
                    'es' => 'Fundador de la sociologia',
                    'zh' => '社会学创始人',
                    'ru' => 'Основатель социологии',
                    'ur' => 'سماجیات کے بانی',
                ],
                'bio' => [
                    'ar' => 'عبد الرحمن بن محمد بن خلدون (1332-1406م) هو العالم والمؤرخ والفيلسوف العربي الشهير، مؤسس علم العمران البشري. وُلد في تونس ورحل إلى مصر حيث عُيّن قاضياً للقضاة المالكية ودرّس في الأزهر. ألّف كتابه الشهير "المقدمة" الذي يُعد من أهم المؤلفات في تاريخ الفكر الإنساني.',
                    'en' => 'Abd al-Rahman ibn Muhammad ibn Khaldun (1332-1406) was the renowned Arab scholar, historian, and philosopher, founder of the science of civilization (sociology). Born in Tunisia, he traveled to Egypt where he was appointed Maliki Chief Judge and taught at Al-Azhar. He authored the famous "Muqaddimah," one of the most important works in human intellectual history.',
                    'fr' => 'Ibn Khaldoun (1332-1406), fondateur de la sociologie, a enseigne a Al-Azhar et ecrit la celebre "Muqaddimah".',
                    'es' => 'Ibn Jaldun (1332-1406), fundador de la sociologia, enseno en Al-Azhar y escribio la celebre "Muqaddimah".',
                    'zh' => '伊本·赫勒敦（1332-1406），社会学创始人，在艾资哈尔教学并撰写了著名的《穆卡迪玛》。',
                    'ru' => 'Ибн Хальдун (1332-1406) — основатель социологии, преподавал в Аль-Азхаре и написал знаменитую «Мукаддиму».',
                    'ur' => 'ابن خلدون (1332-1406) عظیم عالم، مؤرخ اور فلسفی، سماجیات کے بانی۔ مصر میں قاضی القضاۃ مقرر ہوئے اور الازہر میں تدریس کی۔ مشہور "مقدمہ" کے مصنف۔',
                ],
                'era' => 'mamluk',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 12,
            ],
            [
                'slug' => 'saad-zaghloul',
                'name' => [
                    'ar' => 'سعد زغلول',
                    'en' => 'Saad Zaghloul',
                    'fr' => 'Saad Zaghloul',
                    'es' => 'Saad Zaghloul',
                    'zh' => '萨阿德·扎格卢尔',
                    'ru' => 'Саад Заглул',
                    'ur' => 'سعد زغلول',
                ],
                'title' => [
                    'ar' => 'زعيم الحركة الوطنية المصرية',
                    'en' => 'Leader of the Egyptian Nationalist Movement',
                    'fr' => 'Leader du mouvement nationaliste egyptien',
                    'es' => 'Lider del movimiento nacionalista egipcio',
                    'zh' => '埃及民族运动领袖',
                    'ru' => 'Лидер египетского национального движения',
                    'ur' => 'مصری قومی تحریک کے رہنما',
                ],
                'bio' => [
                    'ar' => 'سعد زغلول (1859-1927م) زعيم وطني مصري ومؤسس حزب الوفد. درس في الأزهر وتتلمذ على يد الإمام محمد عبده. قاد ثورة 1919 ضد الاحتلال البريطاني وأصبح رئيساً لوزراء مصر. يُعد من أبرز خريجي الأزهر في المجال السياسي.',
                    'en' => 'Saad Zaghloul (1859-1927) was an Egyptian nationalist leader and founder of the Wafd Party. He studied at Al-Azhar under Muhammad Abduh, led the 1919 Revolution against British occupation, and became Prime Minister of Egypt. He is among Al-Azhar\'s most prominent alumni in politics.',
                    'fr' => 'Saad Zaghloul (1859-1927), leader nationaliste egyptien et fondateur du parti Wafd, a etudie a Al-Azhar.',
                    'es' => 'Saad Zaghloul (1859-1927), lider nacionalista egipcio y fundador del partido Wafd, estudio en Al-Azhar.',
                    'zh' => '萨阿德·扎格卢尔（1859-1927），埃及民族运动领袖，华夫脱党创始人，曾在艾资哈尔学习。',
                    'ru' => 'Саад Заглул (1859-1927) — лидер египетского национального движения, основатель партии Вафд, учился в Аль-Азхаре.',
                    'ur' => 'سعد زغلول (1859-1927) مصری قومی رہنما اور وفد پارٹی کے بانی تھے۔ الازہر میں محمد عبدہ سے پڑھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 13,
            ],
            [
                'slug' => 'muhammad-metwalli-sha-rawi',
                'name' => [
                    'ar' => 'الشيخ محمد متولي الشعراوي',
                    'en' => 'Sheikh Muhammad Metwalli al-Sha\'rawi',
                    'fr' => 'Cheikh Muhammad Metwalli al-Sha\'rawi',
                    'es' => 'Jeque Muhammad Metwalli al-Sha\'rawi',
                    'zh' => '谢赫穆罕默德·麦特瓦利·沙阿拉维',
                    'ru' => 'Шейх Мухаммад Метвалли аш-Шаарави',
                    'ur' => 'شیخ محمد متولی الشعراوی',
                ],
                'title' => [
                    'ar' => 'إمام الدعاة',
                    'en' => 'Imam of Preachers',
                    'fr' => 'Imam des predicateurs',
                    'es' => 'Imam de los predicadores',
                    'zh' => '传教士之伊玛目',
                    'ru' => 'Имам проповедников',
                    'ur' => 'امام الدعاۃ',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد متولي الشعراوي (1911-1998م) خريج الأزهر وأشهر داعية إسلامي في مصر. شغل منصب وزير الأوقاف. اشتهر بتفسيره المبسط للقرآن الكريم عبر التلفزيون، وأثّر في ملايين المسلمين حول العالم بأسلوبه السهل الممتنع.',
                    'en' => 'Sheikh Muhammad Metwalli al-Sha\'rawi (1911-1998) was an Al-Azhar graduate and Egypt\'s most popular Islamic preacher. He served as Minister of Endowments and became famous for his accessible television Quran commentary, influencing millions of Muslims worldwide.',
                    'fr' => 'Le cheikh al-Sha\'rawi (1911-1998), diplome d\'Al-Azhar, fut le predicateur islamique le plus populaire d\'Egypte.',
                    'es' => 'El jeque al-Sha\'rawi (1911-1998), graduado de Al-Azhar, fue el predicador islamico mas popular de Egipto.',
                    'zh' => '谢赫沙阿拉维（1911-1998），艾资哈尔毕业生，埃及最受欢迎的伊斯兰传教士。',
                    'ru' => 'Шейх аш-Шаарави (1911-1998) — самый популярный исламский проповедник Египта, выпускник Аль-Азхара.',
                    'ur' => 'شیخ الشعراوی (1911-1998) الازہر کے فارغ التحصیل اور مصر کے مقبول ترین اسلامی داعی تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 14,
            ],
            // More Historical Grand Imams
            [
                'slug' => 'abdullah-al-sharqawi',
                'name' => [
                    'ar' => 'الشيخ عبد الله الشرقاوي',
                    'en' => 'Sheikh Abdullah al-Sharqawi',
                    'fr' => 'Cheikh Abdullah al-Sharqawi',
                    'es' => 'Jeque Abdullah al-Sharqawi',
                    'zh' => '谢赫阿卜杜拉·沙尔卡维',
                    'ru' => 'Шейх Абдуллах аш-Шаркави',
                    'ur' => 'شیخ عبداللہ الشرقاوی',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الحادي عشر',
                    'en' => 'Grand Imam #11 of Al-Azhar',
                    'fr' => 'Grand Imam n°11 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 11 de Al-Azhar',
                    'zh' => '艾资哈尔第11任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №11',
                    'ur' => 'الازہر کے گیارہویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ عبد الله الشرقاوي (ت. 1812م) تولى مشيخة الأزهر من 1793 إلى 1812م. كان عالماً شافعياً بارزاً لعب دوراً محورياً خلال فترة الاحتلال الفرنسي لمصر. دافع عن مصالح الشعب المصري وكان عضواً في الديوان الذي أنشأه الفرنسيون.',
                    'en' => 'Sheikh Abdullah al-Sharqawi (d. 1812) served as Grand Imam of Al-Azhar from 1793 to 1812. A prominent Shafi\'i scholar, he played a pivotal role during the French occupation of Egypt, defending the interests of the Egyptian people and serving on the council established by the French.',
                    'fr' => 'Le cheikh Abdullah al-Sharqawi (mort en 1812) fut Grand Imam de 1793 a 1812. Erudit chafeite, il joua un role cle pendant l\'occupation francaise de l\'Egypte.',
                    'es' => 'El jeque Abdullah al-Sharqawi (fallecido en 1812) fue Gran Imam de 1793 a 1812. Erudito shafi\'i, desempeno un papel clave durante la ocupacion francesa de Egipto.',
                    'zh' => '谢赫阿卜杜拉·沙尔卡维（卒于1812年）于1793至1812年担任大伊玛目。沙菲仪学派学者，在法国占领埃及期间发挥了关键作用。',
                    'ru' => 'Шейх Абдуллах аш-Шаркави (ум. 1812) был Великим имамом с 1793 по 1812 год. Шафиитский учёный, сыгравший ключевую роль во время французской оккупации Египта.',
                    'ur' => 'شیخ عبداللہ الشرقاوی (وفات 1812) 1793 سے 1812 تک شیخ الازہر رہے۔ شافعی مسلک کے عالم تھے اور فرانسیسی قبضے کے دوران اہم کردار ادا کیا۔',
                ],
                'era' => 'ottoman',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 15,
            ],
            [
                'slug' => 'hassan-al-attar',
                'name' => [
                    'ar' => 'الشيخ حسن العطار',
                    'en' => 'Sheikh Hassan al-Attar',
                    'fr' => 'Cheikh Hassan al-Attar',
                    'es' => 'Jeque Hassan al-Attar',
                    'zh' => '谢赫哈桑·阿塔尔',
                    'ru' => 'Шейх Хасан аль-Аттар',
                    'ur' => 'شیخ حسن العطار',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الخامس عشر',
                    'en' => 'Grand Imam #15 of Al-Azhar',
                    'fr' => 'Grand Imam n°15 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 15 de Al-Azhar',
                    'zh' => '艾资哈尔第15任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №15',
                    'ur' => 'الازہر کے پندرہویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ حسن العطار (1766-1835م) تولى مشيخة الأزهر من 1830 إلى 1834م. كان رائداً في إصلاح التعليم الحديث وأستاذاً لرفاعة الطهطاوي. تميز بانفتاحه على العلوم الحديثة ودعوته لتطوير مناهج الأزهر.',
                    'en' => 'Sheikh Hassan al-Attar (1766-1835) served as Grand Imam from 1830 to 1834. He was a pioneer of modern education reform and the mentor of Rifa\'a al-Tahtawi. He was distinguished by his openness to modern sciences and his call to develop Al-Azhar\'s curricula.',
                    'fr' => 'Le cheikh Hassan al-Attar (1766-1835) fut Grand Imam de 1830 a 1834. Pionnier de la reforme educative moderne et mentor de Rifa\'a al-Tahtawi.',
                    'es' => 'El jeque Hassan al-Attar (1766-1835) fue Gran Imam de 1830 a 1834. Pionero de la reforma educativa moderna y mentor de Rifa\'a al-Tahtawi.',
                    'zh' => '谢赫哈桑·阿塔尔（1766-1835）于1830至1834年任大伊玛目。现代教育改革先驱，里法阿·塔赫塔维的导师。',
                    'ru' => 'Шейх Хасан аль-Аттар (1766-1835) был Великим имамом с 1830 по 1834 год. Пионер реформы современного образования и наставник Рифаа ат-Тахтави.',
                    'ur' => 'شیخ حسن العطار (1766-1835) 1830 سے 1834 تک شیخ الازہر رہے۔ جدید تعلیمی اصلاحات کے رہنما اور رفاعۃ الطہطاوی کے استاد تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 16,
            ],
            [
                'slug' => 'ibrahim-al-bajuri',
                'name' => [
                    'ar' => 'الشيخ إبراهيم الباجوري',
                    'en' => 'Sheikh Ibrahim al-Bajuri',
                    'fr' => 'Cheikh Ibrahim al-Bajuri',
                    'es' => 'Jeque Ibrahim al-Bajuri',
                    'zh' => '谢赫易卜拉欣·巴朱里',
                    'ru' => 'Шейх Ибрахим аль-Баджури',
                    'ur' => 'شیخ ابراہیم الباجوری',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الثامن عشر',
                    'en' => 'Grand Imam #18 of Al-Azhar',
                    'fr' => 'Grand Imam n°18 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 18 de Al-Azhar',
                    'zh' => '艾资哈尔第18任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №18',
                    'ur' => 'الازہر کے اٹھارہویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ إبراهيم الباجوري (1784-1860م) تولى مشيخة الأزهر من 1847 إلى 1860م. كان فقيهاً شافعياً عظيماً اشتهر بحاشيته الشهيرة على متن السنوسية في علم التوحيد. ترك إرثاً علمياً كبيراً في الفقه والعقيدة.',
                    'en' => 'Sheikh Ibrahim al-Bajuri (1784-1860) served as Grand Imam from 1847 to 1860. A great Shafi\'i jurist, he was famous for his celebrated commentary on al-Sanusi\'s text in theology. He left a significant scholarly legacy in jurisprudence and creed.',
                    'fr' => 'Le cheikh Ibrahim al-Bajuri (1784-1860) fut Grand Imam de 1847 a 1860. Grand juriste chafeite, celebre pour son commentaire sur al-Sanusi en theologie.',
                    'es' => 'El jeque Ibrahim al-Bajuri (1784-1860) fue Gran Imam de 1847 a 1860. Gran jurista shafi\'i, famoso por su comentario sobre al-Sanusi en teologia.',
                    'zh' => '谢赫易卜拉欣·巴朱里（1784-1860）于1847至1860年任大伊玛目。沙菲仪学派伟大法学家，以其对赛努西神学著作的著名注释闻名。',
                    'ru' => 'Шейх Ибрахим аль-Баджури (1784-1860) был Великим имамом с 1847 по 1860 год. Великий шафиитский правовед, известный своим комментарием на текст ас-Сануси по теологии.',
                    'ur' => 'شیخ ابراہیم الباجوری (1784-1860) 1847 سے 1860 تک شیخ الازہر رہے۔ عظیم شافعی فقیہ، علم التوحید میں سنوسی کی شرح کے لیے مشہور تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 17,
            ],
            [
                'slug' => 'hassouna-al-nawawi',
                'name' => [
                    'ar' => 'الشيخ حسونة النواوي',
                    'en' => 'Sheikh Hassouna al-Nawawi',
                    'fr' => 'Cheikh Hassouna al-Nawawi',
                    'es' => 'Jeque Hassouna al-Nawawi',
                    'zh' => '谢赫哈苏纳·纳瓦维',
                    'ru' => 'Шейх Хассуна ан-Навави',
                    'ur' => 'شیخ حسونۃ النواوی',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر الرابع والعشرون',
                    'en' => 'Grand Imam #24 of Al-Azhar',
                    'fr' => 'Grand Imam n°24 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 24 de Al-Azhar',
                    'zh' => '艾资哈尔第24任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №24',
                    'ur' => 'الازہر کے چوبیسویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ حسونة النواوي (1839-1925م) تولى مشيخة الأزهر من 1896 إلى 1900م. يُعد أول من حمل لقب "الإمام الأكبر" رسمياً في تاريخ الأزهر. قاد جهود تنظيم إدارة الأزهر ووضع أسس المؤسسية الحديثة.',
                    'en' => 'Sheikh Hassouna al-Nawawi (1839-1925) served as Grand Imam from 1896 to 1900. He was the first to officially hold the title of "Grand Imam" in Al-Azhar\'s history. He led efforts to organize Al-Azhar\'s administration and laid the foundations of modern institutionalization.',
                    'fr' => 'Le cheikh Hassouna al-Nawawi (1839-1925) fut Grand Imam de 1896 a 1900. Premier a porter officiellement le titre de « Grand Imam » dans l\'histoire d\'Al-Azhar.',
                    'es' => 'El jeque Hassouna al-Nawawi (1839-1925) fue Gran Imam de 1896 a 1900. Primero en ostentar oficialmente el titulo de «Gran Imam» en la historia de Al-Azhar.',
                    'zh' => '谢赫哈苏纳·纳瓦维（1839-1925）于1896至1900年任大伊玛目。他是艾资哈尔历史上首位正式拥有"大伊玛目"头衔的人。',
                    'ru' => 'Шейх Хассуна ан-Навави (1839-1925) был Великим имамом с 1896 по 1900 год. Первый, кто официально получил титул «Великий имам» в истории Аль-Азхара.',
                    'ur' => 'شیخ حسونۃ النواوی (1839-1925) 1896 سے 1900 تک شیخ الازہر رہے۔ الازہر کی تاریخ میں باضابطہ طور پر "الإمام الأکبر" کا لقب حاصل کرنے والے پہلے شخص تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 18,
            ],
            [
                'slug' => 'selim-al-bishri',
                'name' => [
                    'ar' => 'الشيخ سليم البشري',
                    'en' => 'Sheikh Selim al-Bishri',
                    'fr' => 'Cheikh Selim al-Bishri',
                    'es' => 'Jeque Selim al-Bishri',
                    'zh' => '谢赫赛利姆·比什里',
                    'ru' => 'Шейх Салим аль-Бишри',
                    'ur' => 'شیخ سلیم البشری',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر (تولى مرتين)',
                    'en' => 'Grand Imam #26/30 of Al-Azhar (served twice)',
                    'fr' => 'Grand Imam n°26/30 d\'Al-Azhar (deux mandats)',
                    'es' => 'Gran Imam n.° 26/30 de Al-Azhar (dos mandatos)',
                    'zh' => '艾资哈尔第26/30任大伊玛目（两次任职）',
                    'ru' => 'Великий имам Аль-Азхара №26/30 (два срока)',
                    'ur' => 'شیخ الازہر نمبر 26/30 (دو مرتبہ)',
                ],
                'bio' => [
                    'ar' => 'الشيخ سليم البشري (1832-1916م) تولى مشيخة الأزهر مرتين: الأولى من 1900 إلى 1904م، والثانية من 1909 إلى 1916م. أعاد هيكلة نظام التعليم الأزهري وأدخل إصلاحات جوهرية على المناهج الدراسية.',
                    'en' => 'Sheikh Selim al-Bishri (1832-1916) served as Grand Imam twice: first from 1900 to 1904, and second from 1909 to 1916. He restructured Al-Azhar\'s educational system and introduced fundamental reforms to the curricula.',
                    'fr' => 'Le cheikh Selim al-Bishri (1832-1916) fut Grand Imam a deux reprises (1900-1904 et 1909-1916). Il restructura le systeme educatif d\'Al-Azhar.',
                    'es' => 'El jeque Selim al-Bishri (1832-1916) fue Gran Imam en dos ocasiones (1900-1904 y 1909-1916). Reestructuro el sistema educativo de Al-Azhar.',
                    'zh' => '谢赫赛利姆·比什里（1832-1916）两次担任大伊玛目（1900-1904年和1909-1916年）。他重组了艾资哈尔的教育体系。',
                    'ru' => 'Шейх Салим аль-Бишри (1832-1916) дважды занимал пост Великого имама (1900-1904 и 1909-1916). Реструктуризировал систему образования Аль-Азхара.',
                    'ur' => 'شیخ سلیم البشری (1832-1916) نے دو مرتبہ شیخ الازہر کا منصب سنبھالا (1900-1904 اور 1909-1916)۔ الازہر کے تعلیمی نظام کی تنظیم نو کی۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 19,
            ],
            [
                'slug' => 'muhammad-sayyid-tantawy',
                'name' => [
                    'ar' => 'الشيخ محمد سيد طنطاوي',
                    'en' => 'Sheikh Muhammad Sayyid Tantawy',
                    'fr' => 'Cheikh Muhammad Sayyid Tantawi',
                    'es' => 'Jeque Muhammad Sayyid Tantawi',
                    'zh' => '谢赫穆罕默德·赛义德·坦塔维',
                    'ru' => 'Шейх Мухаммад Сайид Тантави',
                    'ur' => 'شیخ محمد سید طنطاوی',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر السابع والأربعون',
                    'en' => 'Grand Imam #47 of Al-Azhar',
                    'fr' => 'Grand Imam n°47 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 47 de Al-Azhar',
                    'zh' => '艾资哈尔第47任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №47',
                    'ur' => 'الازہر کے سینتالیسویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمد سيد طنطاوي (1928-2010م) تولى مشيخة الأزهر من 1996 إلى 2010م. حصل على الدكتوراه في التفسير وعلوم القرآن. شغل منصب مفتي الديار المصرية قبل توليه المشيخة. عُرف بتوجهه التحديثي وانفتاحه على الحوار مع مختلف الديانات والثقافات.',
                    'en' => 'Sheikh Muhammad Sayyid Tantawy (1928-2010) served as Grand Imam from 1996 to 2010. He held a PhD in Tafsir (Quranic exegesis) and served as Grand Mufti of Egypt before becoming Grand Imam. Known for his modernizing approach and openness to interfaith and intercultural dialogue.',
                    'fr' => 'Le cheikh Tantawi (1928-2010) fut Grand Imam de 1996 a 2010. Docteur en exegese coranique, il fut auparavant Grand Mufti d\'Egypte. Connu pour son approche modernisatrice.',
                    'es' => 'El jeque Tantawi (1928-2010) fue Gran Imam de 1996 a 2010. Doctor en exegesis coranica, fue previamente Gran Mufti de Egipto. Conocido por su enfoque modernizador.',
                    'zh' => '谢赫坦塔维（1928-2010）于1996至2010年任大伊玛目。古兰经注释学博士，此前曾任埃及大穆夫提。以现代化路线和开放对话著称。',
                    'ru' => 'Шейх Тантави (1928-2010) был Великим имамом с 1996 по 2010 год. Доктор тафсира, ранее Великий муфтий Египта. Известен модернизаторским подходом.',
                    'ur' => 'شیخ طنطاوی (1928-2010) 1996 سے 2010 تک شیخ الازہر رہے۔ تفسیر میں ڈاکٹریٹ حاصل تھی۔ اس سے قبل مفتی اعظم مصر رہے۔ جدت پسندی اور بین المذاہب مکالمے کے لیے مشہور تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 20,
            ],
            [
                'slug' => 'gad-al-haq-ali-gad-al-haq',
                'name' => [
                    'ar' => 'الشيخ جاد الحق علي جاد الحق',
                    'en' => 'Sheikh Gad al-Haq Ali Gad al-Haq',
                    'fr' => 'Cheikh Gad al-Haq Ali Gad al-Haq',
                    'es' => 'Jeque Gad al-Haq Ali Gad al-Haq',
                    'zh' => '谢赫贾德·哈克·阿里·贾德·哈克',
                    'ru' => 'Шейх Гад аль-Хакк Али Гад аль-Хакк',
                    'ur' => 'شیخ جاد الحق علی جاد الحق',
                ],
                'title' => [
                    'ar' => 'شيخ الأزهر السادس والأربعون',
                    'en' => 'Grand Imam #46 of Al-Azhar',
                    'fr' => 'Grand Imam n°46 d\'Al-Azhar',
                    'es' => 'Gran Imam n.° 46 de Al-Azhar',
                    'zh' => '艾资哈尔第46任大伊玛目',
                    'ru' => 'Великий имам Аль-Азхара №46',
                    'ur' => 'الازہر کے چھیالیسویں شیخ الازہر',
                ],
                'bio' => [
                    'ar' => 'الشيخ جاد الحق علي جاد الحق (1917-1996م) تولى مشيخة الأزهر من 1982 إلى 1996م. دافع بقوة عن استقلالية الأزهر عن الدولة وتصدى لمحاولات تهميش دوره. كان من أبرز المدافعين عن هوية الأزهر واستقلاله الفكري والمؤسسي.',
                    'en' => 'Sheikh Gad al-Haq Ali Gad al-Haq (1917-1996) served as Grand Imam from 1982 to 1996. He staunchly defended Al-Azhar\'s independence from the state and resisted attempts to marginalize its role. He was among the most prominent defenders of Al-Azhar\'s identity and its intellectual and institutional independence.',
                    'fr' => 'Le cheikh Gad al-Haq (1917-1996) fut Grand Imam de 1982 a 1996. Ardent defenseur de l\'independance d\'Al-Azhar vis-a-vis de l\'Etat.',
                    'es' => 'El jeque Gad al-Haq (1917-1996) fue Gran Imam de 1982 a 1996. Ferviente defensor de la independencia de Al-Azhar frente al Estado.',
                    'zh' => '谢赫贾德·哈克（1917-1996）于1982至1996年任大伊玛目。坚定捍卫艾资哈尔独立于国家的地位。',
                    'ru' => 'Шейх Гад аль-Хакк (1917-1996) был Великим имамом с 1982 по 1996 год. Стойко защищал независимость Аль-Азхара от государства.',
                    'ur' => 'شیخ جاد الحق (1917-1996) 1982 سے 1996 تک شیخ الازہر رہے۔ ریاست سے الازہر کی آزادی کے زبردست محافظ تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 21,
            ],
            // University Presidents
            [
                'slug' => 'muhammad-al-bahi',
                'name' => [
                    'ar' => 'الدكتور محمد البهي',
                    'en' => 'Dr. Muhammad al-Bahi',
                    'fr' => 'Dr. Muhammad al-Bahi',
                    'es' => 'Dr. Muhammad al-Bahi',
                    'zh' => '穆罕默德·巴希博士',
                    'ru' => 'Д-р Мухаммад аль-Бахи',
                    'ur' => 'ڈاکٹر محمد البہی',
                ],
                'title' => [
                    'ar' => 'أول رئيس لجامعة الأزهر',
                    'en' => 'First President of Al-Azhar University',
                    'fr' => 'Premier president de l\'Universite d\'Al-Azhar',
                    'es' => 'Primer presidente de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学首任校长',
                    'ru' => 'Первый ректор университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے پہلے صدر',
                ],
                'bio' => [
                    'ar' => 'الدكتور محمد البهي (1905-1982م) كان أول رئيس لجامعة الأزهر بعد صدور قانون 103 لسنة 1961م الذي أعاد تنظيم الأزهر. تولى الرئاسة من 1961 إلى 1964م وأسس الهيكل الجامعي الحديث للأزهر بإضافة الكليات العلمية والعملية.',
                    'en' => 'Dr. Muhammad al-Bahi (1905-1982) was the first president of Al-Azhar University after Law 103 of 1961 reorganized Al-Azhar. He served from 1961 to 1964 and established the modern university structure by adding scientific and practical faculties.',
                    'fr' => 'Le Dr. Muhammad al-Bahi (1905-1982) fut le premier president de l\'Universite d\'Al-Azhar (1961-1964), etablissant la structure universitaire moderne.',
                    'es' => 'El Dr. Muhammad al-Bahi (1905-1982) fue el primer presidente de la Universidad de Al-Azhar (1961-1964), estableciendo la estructura universitaria moderna.',
                    'zh' => '穆罕默德·巴希博士（1905-1982）是艾资哈尔大学首任校长（1961-1964），建立了现代大学架构。',
                    'ru' => 'Д-р Мухаммад аль-Бахи (1905-1982) — первый ректор университета Аль-Азхар (1961-1964), создавший современную университетскую структуру.',
                    'ur' => 'ڈاکٹر محمد البہی (1905-1982) 1961 کے قانون 103 کے بعد الازہر یونیورسٹی کے پہلے صدر تھے (1961-1964)۔ جدید یونیورسٹی ڈھانچہ قائم کیا۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 22,
            ],
            [
                'slug' => 'ahmad-hassan-al-baquri',
                'name' => [
                    'ar' => 'الشيخ أحمد حسن الباقوري',
                    'en' => 'Sheikh Ahmad Hassan al-Baquri',
                    'fr' => 'Cheikh Ahmad Hassan al-Baquri',
                    'es' => 'Jeque Ahmad Hassan al-Baquri',
                    'zh' => '谢赫艾哈迈德·哈桑·巴库里',
                    'ru' => 'Шейх Ахмад Хасан аль-Бакури',
                    'ur' => 'شیخ احمد حسن الباقوری',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر',
                    'en' => 'President of Al-Azhar University',
                    'fr' => 'President de l\'Universite d\'Al-Azhar',
                    'es' => 'Presidente de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学校长',
                    'ru' => 'Ректор университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے صدر',
                ],
                'bio' => [
                    'ar' => 'الشيخ أحمد حسن الباقوري (1907-1985م) تولى رئاسة جامعة الأزهر من 1964 إلى 1969م. شغل سابقاً منصب وزير الأوقاف في عهد الرئيس جمال عبد الناصر. ساهم في تطوير الجامعة وتوسيع نشاطها الأكاديمي.',
                    'en' => 'Sheikh Ahmad Hassan al-Baquri (1907-1985) served as President of Al-Azhar University from 1964 to 1969. He formerly held the position of Minister of Endowments under President Gamal Abdel Nasser. He contributed to developing the university and expanding its academic activities.',
                    'fr' => 'Le cheikh al-Baquri (1907-1985) fut president de l\'Universite d\'Al-Azhar de 1964 a 1969, ancien ministre des Waqfs.',
                    'es' => 'El jeque al-Baquri (1907-1985) fue presidente de la Universidad de Al-Azhar de 1964 a 1969, exministro de Waqfs.',
                    'zh' => '谢赫巴库里（1907-1985）于1964至1969年任艾资哈尔大学校长，曾任宗教基金部长。',
                    'ru' => 'Шейх аль-Бакури (1907-1985) был ректором с 1964 по 1969 год, ранее — министр вакуфов.',
                    'ur' => 'شیخ احمد حسن الباقوری (1907-1985) 1964 سے 1969 تک الازہر یونیورسٹی کے صدر رہے۔ اس سے قبل وزیر اوقاف تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 23,
            ],
            [
                'slug' => 'ahmad-omar-hashim',
                'name' => [
                    'ar' => 'الدكتور أحمد عمر هاشم',
                    'en' => 'Dr. Ahmad Omar Hashim',
                    'fr' => 'Dr. Ahmad Omar Hashim',
                    'es' => 'Dr. Ahmad Omar Hashim',
                    'zh' => '艾哈迈德·奥马尔·哈希姆博士',
                    'ru' => 'Д-р Ахмад Умар Хашим',
                    'ur' => 'ڈاکٹر احمد عمر ہاشم',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر الأسبق',
                    'en' => 'Former President of Al-Azhar University',
                    'fr' => 'Ancien president de l\'Universite d\'Al-Azhar',
                    'es' => 'Expresidente de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学前校长',
                    'ru' => 'Бывший ректор университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے سابق صدر',
                ],
                'bio' => [
                    'ar' => 'الدكتور أحمد عمر هاشم (مواليد 1941م) تولى رئاسة جامعة الأزهر من 1995 إلى 2003م. عالم إسلامي بارز وداعية تلفزيوني مشهور. ساهم في تعزيز الحضور الإعلامي للأزهر وتطوير العلاقات الدولية للجامعة.',
                    'en' => 'Dr. Ahmad Omar Hashim (born 1941) served as President of Al-Azhar University from 1995 to 2003. A prominent Islamic scholar and well-known TV preacher, he contributed to strengthening Al-Azhar\'s media presence and developing the university\'s international relations.',
                    'fr' => 'Le Dr. Ahmad Omar Hashim (ne en 1941) fut president de l\'Universite d\'Al-Azhar de 1995 a 2003. Eminent erudit et predicateur televise.',
                    'es' => 'El Dr. Ahmad Omar Hashim (nacido en 1941) fue presidente de la Universidad de Al-Azhar de 1995 a 2003. Eminente erudito y predicador televisivo.',
                    'zh' => '艾哈迈德·奥马尔·哈希姆博士（1941年生）于1995至2003年任艾资哈尔大学校长。著名伊斯兰学者和电视布道者。',
                    'ru' => 'Д-р Ахмад Умар Хашим (род. 1941) был ректором с 1995 по 2003 год. Известный исламский учёный и телепроповедник.',
                    'ur' => 'ڈاکٹر احمد عمر ہاشم (پیدائش 1941) 1995 سے 2003 تک الازہر یونیورسٹی کے صدر رہے۔ نامور اسلامی عالم اور مشہور ٹیلی ویژن مبلغ ہیں۔',
                ],
                'era' => 'contemporary',
                'is_historical' => false,
                'is_current_leadership' => false,
                'order' => 24,
            ],
            [
                'slug' => 'osama-al-abd',
                'name' => [
                    'ar' => 'الدكتور أسامة العبد',
                    'en' => 'Dr. Osama al-Abd',
                    'fr' => 'Dr. Osama al-Abd',
                    'es' => 'Dr. Osama al-Abd',
                    'zh' => '乌萨马·阿布德博士',
                    'ru' => 'Д-р Усама аль-Абд',
                    'ur' => 'ڈاکٹر اسامۃ العبد',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر الأسبق',
                    'en' => 'Former President of Al-Azhar University',
                    'fr' => 'Ancien president de l\'Universite d\'Al-Azhar',
                    'es' => 'Expresidente de la Universidad de Al-Azhar',
                    'zh' => '艾资哈尔大学前校长',
                    'ru' => 'Бывший ректор университета Аль-Азхар',
                    'ur' => 'الازہر یونیورسٹی کے سابق صدر',
                ],
                'bio' => [
                    'ar' => 'الدكتور أسامة العبد تولى رئاسة جامعة الأزهر من 2011 إلى 2014م. دعا إلى تحديث الجامعة وتعزيز دورها في المجتمع المصري خلال فترة التحولات السياسية التي شهدتها مصر بعد ثورة 2011.',
                    'en' => 'Dr. Osama al-Abd served as President of Al-Azhar University from 2011 to 2014. He advocated for modernizing the university and strengthening its role in Egyptian society during the political transformations following the 2011 revolution.',
                    'fr' => 'Le Dr. Osama al-Abd fut president de l\'Universite d\'Al-Azhar de 2011 a 2014, defenseur de la modernisation universitaire.',
                    'es' => 'El Dr. Osama al-Abd fue presidente de la Universidad de Al-Azhar de 2011 a 2014, defensor de la modernizacion universitaria.',
                    'zh' => '乌萨马·阿布德博士于2011至2014年任艾资哈尔大学校长，倡导大学现代化。',
                    'ru' => 'Д-р Усама аль-Абд был ректором с 2011 по 2014 год, выступал за модернизацию университета.',
                    'ur' => 'ڈاکٹر اسامۃ العبد 2011 سے 2014 تک الازہر یونیورسٹی کے صدر رہے۔ یونیورسٹی کی جدید کاری کے حامی تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 25,
            ],
            [
                'slug' => 'muhammad-al-mahrasawi',
                'name' => [
                    'ar' => 'الدكتور محمد المحرصاوي',
                    'en' => 'Dr. Muhammad al-Mahrasawi',
                    'fr' => 'Dr. Muhammad al-Mahrasawi',
                    'es' => 'Dr. Muhammad al-Mahrasawi',
                    'zh' => '穆罕默德·马赫拉萨维博士',
                    'ru' => 'Д-р Мухаммад аль-Махрасави',
                    'ur' => 'ڈاکٹر محمد المحرصاوی',
                ],
                'title' => [
                    'ar' => 'رئيس جامعة الأزهر الراحل',
                    'en' => 'Late President of Al-Azhar University',
                    'fr' => 'Feu le president de l\'Universite d\'Al-Azhar',
                    'es' => 'Difunto presidente de la Universidad de Al-Azhar',
                    'zh' => '已故艾资哈尔大学校长',
                    'ru' => 'Покойный ректор университета Аль-Азхар',
                    'ur' => 'مرحوم صدر الازہر یونیورسٹی',
                ],
                'bio' => [
                    'ar' => 'الدكتور محمد حسين المحرصاوي (1962-2025م) تولى رئاسة جامعة الأزهر من 2017 إلى 2022م. تخرج من كلية اللغة العربية عام 1985م. توفي في 27 مارس 2025م. عمل على تحديث الجامعة وتطوير بنيتها التحتية والأكاديمية.',
                    'en' => 'Dr. Muhammad Husayn al-Mahrasawi (1962-2025) served as President of Al-Azhar University from 2017 to 2022. He graduated from the Faculty of Arabic Languages in 1985 and passed away on March 27, 2025. He worked on modernizing the university and developing its infrastructure and academic programs.',
                    'fr' => 'Le Dr. al-Mahrasawi (1962-2025) fut president de l\'Universite d\'Al-Azhar de 2017 a 2022. Diplome de la Faculte de langue arabe (1985), decede le 27 mars 2025.',
                    'es' => 'El Dr. al-Mahrasawi (1962-2025) fue presidente de la Universidad de Al-Azhar de 2017 a 2022. Graduado de la Facultad de Lengua Arabe (1985), fallecio el 27 de marzo de 2025.',
                    'zh' => '马赫拉萨维博士（1962-2025）于2017至2022年任艾资哈尔大学校长。1985年毕业于阿拉伯语学院，2025年3月27日逝世。',
                    'ru' => 'Д-р аль-Махрасави (1962-2025) был ректором с 2017 по 2022 год. Выпускник факультета арабского языка (1985), скончался 27 марта 2025 года.',
                    'ur' => 'ڈاکٹر المحرصاوی (1962-2025) 2017 سے 2022 تک الازہر یونیورسٹی کے صدر رہے۔ 1985 میں کلیۃ اللغۃ العربیۃ سے فارغ التحصیل ہوئے۔ 27 مارچ 2025 کو وفات پائی۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 26,
            ],
            // More Notable Alumni
            [
                'slug' => 'ahmad-urabi',
                'name' => [
                    'ar' => 'أحمد عرابي',
                    'en' => 'Ahmad Urabi',
                    'fr' => 'Ahmad Urabi',
                    'es' => 'Ahmad Urabi',
                    'zh' => '艾哈迈德·乌拉比',
                    'ru' => 'Ахмад Ураби',
                    'ur' => 'احمد عرابی',
                ],
                'title' => [
                    'ar' => 'قائد أول ثورة وطنية مصرية',
                    'en' => 'Leader of the First Egyptian National Revolution',
                    'fr' => 'Leader de la premiere revolution nationale egyptienne',
                    'es' => 'Lider de la primera revolucion nacional egipcia',
                    'zh' => '埃及首次民族革命领导者',
                    'ru' => 'Лидер первой египетской национальной революции',
                    'ur' => 'مصر کی پہلی قومی انقلاب کے رہنما',
                ],
                'bio' => [
                    'ar' => 'أحمد عرابي (1841-1911م) ضابط عسكري مصري وزعيم وطني. قاد الثورة العرابية عام 1882م ضد الاحتلال البريطاني والتدخل الأجنبي في شؤون مصر. درس في الأزهر قبل التحاقه بالجيش. يُعد رمزاً للمقاومة الوطنية المصرية.',
                    'en' => 'Ahmad Urabi (1841-1911) was an Egyptian military officer and national leader. He led the Urabi Revolution of 1882 against British occupation and foreign interference in Egyptian affairs. He studied at Al-Azhar before joining the military. He is regarded as a symbol of Egyptian national resistance.',
                    'fr' => 'Ahmad Urabi (1841-1911), officier militaire egyptien, mena la revolution de 1882 contre l\'occupation britannique. Il etudia a Al-Azhar.',
                    'es' => 'Ahmad Urabi (1841-1911), oficial militar egipcio, lidero la revolucion de 1882 contra la ocupacion britanica. Estudio en Al-Azhar.',
                    'zh' => '艾哈迈德·乌拉比（1841-1911），埃及军官和民族领袖，领导了1882年反对英国占领的乌拉比革命。曾在艾资哈尔学习。',
                    'ru' => 'Ахмад Ураби (1841-1911) — египетский военный и национальный лидер, возглавивший революцию 1882 года против британской оккупации. Учился в Аль-Азхаре.',
                    'ur' => 'احمد عرابی (1841-1911) مصری فوجی افسر اور قومی رہنما تھے۔ 1882 میں برطانوی قبضے کے خلاف عرابی انقلاب کی قیادت کی۔ الازہر میں تعلیم حاصل کی۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 27,
            ],
            [
                'slug' => 'houari-boumediene',
                'name' => [
                    'ar' => 'هواري بومدين',
                    'en' => 'Houari Boumediene',
                    'fr' => 'Houari Boumediene',
                    'es' => 'Houari Boumediene',
                    'zh' => '胡阿里·布迈丁',
                    'ru' => 'Хуари Бумедьен',
                    'ur' => 'ہواری بومدین',
                ],
                'title' => [
                    'ar' => 'رئيس الجزائر',
                    'en' => 'President of Algeria',
                    'fr' => 'President de l\'Algerie',
                    'es' => 'Presidente de Argelia',
                    'zh' => '阿尔及利亚总统',
                    'ru' => 'Президент Алжира',
                    'ur' => 'صدر الجزائر',
                ],
                'bio' => [
                    'ar' => 'هواري بومدين (1932-1978م) رئيس الجزائر من 1965 إلى 1978م. درس في الأزهر في القاهرة. قاد حركة التصنيع والتحديث في الجزائر وكان من أبرز قادة حركة عدم الانحياز. يُعد من أبرز خريجي الأزهر في المجال السياسي الدولي.',
                    'en' => 'Houari Boumediene (1932-1978) was President of Algeria from 1965 to 1978. He studied at Al-Azhar in Cairo. He led Algeria\'s industrialization and modernization and was a leading figure in the Non-Aligned Movement. He is among Al-Azhar\'s most prominent alumni in international politics.',
                    'fr' => 'Houari Boumediene (1932-1978), president de l\'Algerie de 1965 a 1978, etudia a Al-Azhar au Caire. Leader du Mouvement des non-alignes.',
                    'es' => 'Houari Boumediene (1932-1978), presidente de Argelia de 1965 a 1978, estudio en Al-Azhar en El Cairo. Lider del Movimiento de Paises No Alineados.',
                    'zh' => '胡阿里·布迈丁（1932-1978），1965至1978年任阿尔及利亚总统。曾在开罗艾资哈尔学习。不结盟运动领导人。',
                    'ru' => 'Хуари Бумедьен (1932-1978) — президент Алжира с 1965 по 1978 год. Учился в Аль-Азхаре в Каире. Лидер Движения неприсоединения.',
                    'ur' => 'ہواری بومدین (1932-1978) 1965 سے 1978 تک الجزائر کے صدر رہے۔ قاہرہ میں الازہر میں تعلیم حاصل کی۔ عدم وابستگی تحریک کے اہم رہنما تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 28,
            ],
            [
                'slug' => 'abdurrahman-wahid',
                'name' => [
                    'ar' => 'عبد الرحمن وحيد',
                    'en' => 'Abdurrahman Wahid',
                    'fr' => 'Abdurrahman Wahid',
                    'es' => 'Abdurrahman Wahid',
                    'zh' => '阿卜杜拉赫曼·瓦希德',
                    'ru' => 'Абдуррахман Вахид',
                    'ur' => 'عبدالرحمٰن وحید',
                ],
                'title' => [
                    'ar' => 'الرئيس الرابع لإندونيسيا',
                    'en' => '4th President of Indonesia',
                    'fr' => '4e president de l\'Indonesie',
                    'es' => '4.° presidente de Indonesia',
                    'zh' => '印度尼西亚第四任总统',
                    'ru' => '4-й президент Индонезии',
                    'ur' => 'انڈونیشیا کے چوتھے صدر',
                ],
                'bio' => [
                    'ar' => 'عبد الرحمن وحيد (1940-2009م) المعروف بـ"جوس دور"، الرئيس الرابع لإندونيسيا (1999-2001). درس في الأزهر بالقاهرة. كان رئيساً لمنظمة نهضة العلماء أكبر منظمة إسلامية في العالم. عُرف بدفاعه عن التعددية والديمقراطية.',
                    'en' => 'Abdurrahman Wahid (1940-2009), known as "Gus Dur," was the 4th President of Indonesia (1999-2001). He studied at Al-Azhar in Cairo. He chaired Nahdlatul Ulama, the world\'s largest Islamic organization. He was known for his defense of pluralism and democracy.',
                    'fr' => 'Abdurrahman Wahid (1940-2009), dit « Gus Dur », fut le 4e president de l\'Indonesie (1999-2001). Il etudia a Al-Azhar au Caire.',
                    'es' => 'Abdurrahman Wahid (1940-2009), conocido como "Gus Dur", fue el 4.° presidente de Indonesia (1999-2001). Estudio en Al-Azhar en El Cairo.',
                    'zh' => '阿卜杜拉赫曼·瓦希德（1940-2009），被称为"古斯杜尔"，印度尼西亚第四任总统（1999-2001）。曾在开罗艾资哈尔学习。',
                    'ru' => 'Абдуррахман Вахид (1940-2009), известный как «Гус Дур», — 4-й президент Индонезии (1999-2001). Учился в Аль-Азхаре в Каире.',
                    'ur' => 'عبدالرحمٰن وحید (1940-2009) جنہیں "گس دور" کہا جاتا ہے، انڈونیشیا کے چوتھے صدر تھے (1999-2001)۔ قاہرہ میں الازہر میں تعلیم حاصل کی۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 29,
            ],
            [
                'slug' => 'rifaa-al-tahtawi',
                'name' => [
                    'ar' => 'رفاعة الطهطاوي',
                    'en' => 'Rifa\'a al-Tahtawi',
                    'fr' => 'Rifa\'a al-Tahtawi',
                    'es' => 'Rifa\'a al-Tahtawi',
                    'zh' => '里法阿·塔赫塔维',
                    'ru' => 'Рифаа ат-Тахтави',
                    'ur' => 'رفاعۃ الطہطاوی',
                ],
                'title' => [
                    'ar' => 'رائد التحديث المصري',
                    'en' => 'Pioneer of Egyptian Modernization',
                    'fr' => 'Pionnier de la modernisation egyptienne',
                    'es' => 'Pionero de la modernizacion egipcia',
                    'zh' => '埃及现代化先驱',
                    'ru' => 'Пионер египетской модернизации',
                    'ur' => 'مصری جدید کاری کے رہنما',
                ],
                'bio' => [
                    'ar' => 'رفاعة رافع الطهطاوي (1801-1873م) رائد التحديث في مصر ومن أبرز خريجي الأزهر. تتلمذ على الشيخ حسن العطار. أُرسل إماماً للبعثة العلمية إلى باريس عام 1826م. ألّف كتاب "تخليص الإبريز في تلخيص باريز". أسس مدرسة الألسن وترجم عشرات الكتب الأوروبية إلى العربية.',
                    'en' => 'Rifa\'a Rafi\' al-Tahtawi (1801-1873) was a pioneer of Egyptian modernization and one of Al-Azhar\'s most distinguished graduates. A student of Sheikh Hassan al-Attar, he was sent as imam of the educational mission to Paris in 1826. He authored "Takhlis al-Ibriz" and founded the School of Languages, translating dozens of European books into Arabic.',
                    'fr' => 'Rifa\'a al-Tahtawi (1801-1873), pionnier de la modernisation egyptienne, diplome d\'Al-Azhar. Envoy a Paris en 1826, il fonda l\'Ecole des Langues.',
                    'es' => 'Rifa\'a al-Tahtawi (1801-1873), pionero de la modernizacion egipcia, graduado de Al-Azhar. Enviado a Paris en 1826, fundo la Escuela de Lenguas.',
                    'zh' => '里法阿·塔赫塔维（1801-1873），埃及现代化先驱，艾资哈尔杰出毕业生。1826年被派往巴黎，创立语言学校，将大量欧洲书籍翻译成阿拉伯文。',
                    'ru' => 'Рифаа ат-Тахтави (1801-1873) — пионер модернизации Египта, выпускник Аль-Азхара. Отправлен в Париж в 1826 году, основал Школу языков.',
                    'ur' => 'رفاعۃ الطہطاوی (1801-1873) مصری جدید کاری کے رہنما اور الازہر کے ممتاز فارغ التحصیل تھے۔ 1826 میں پیرس بھیجے گئے۔ مدرسۃ الالسن کے بانی اور درجنوں یورپی کتب کے مترجم تھے۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 30,
            ],
            [
                'slug' => 'ibn-hajar-al-asqalani',
                'name' => [
                    'ar' => 'ابن حجر العسقلاني',
                    'en' => 'Ibn Hajar al-Asqalani',
                    'fr' => 'Ibn Hajar al-Asqalani',
                    'es' => 'Ibn Hajar al-Asqalani',
                    'zh' => '伊本·哈吉尔·阿斯卡拉尼',
                    'ru' => 'Ибн Хаджар аль-Аскалани',
                    'ur' => 'ابن حجر العسقلانی',
                ],
                'title' => [
                    'ar' => 'أمير المؤمنين في الحديث',
                    'en' => 'Preeminent Hadith Scholar',
                    'fr' => 'Eminent erudit du hadith',
                    'es' => 'Eminente erudito del hadiz',
                    'zh' => '圣训学泰斗',
                    'ru' => 'Выдающийся хадисовед',
                    'ur' => 'امیر المؤمنین فی الحدیث',
                ],
                'bio' => [
                    'ar' => 'أحمد بن علي بن حجر العسقلاني (1372-1449م) من أعظم علماء الحديث النبوي في التاريخ الإسلامي. درّس في الأزهر وتولى قضاء مصر. اشتهر بكتابه "فتح الباري شرح صحيح البخاري" الذي يُعد أعظم شرح لصحيح البخاري. ألّف أكثر من 150 مؤلفاً.',
                    'en' => 'Ahmad ibn Ali ibn Hajar al-Asqalani (1372-1449) was one of the greatest hadith scholars in Islamic history. He taught at Al-Azhar and served as Chief Judge of Egypt. He is famous for "Fath al-Bari," the greatest commentary on Sahih al-Bukhari. He authored over 150 works.',
                    'fr' => 'Ibn Hajar al-Asqalani (1372-1449), l\'un des plus grands specialistes du hadith. Enseigna a Al-Azhar, auteur du celebre « Fath al-Bari ».',
                    'es' => 'Ibn Hajar al-Asqalani (1372-1449), uno de los mayores especialistas en hadiz. Enseno en Al-Azhar, autor del celebre "Fath al-Bari".',
                    'zh' => '伊本·哈吉尔·阿斯卡拉尼（1372-1449），伊斯兰历史上最伟大的圣训学家之一。在艾资哈尔教学，著有《法特赫·巴里》等150多部著作。',
                    'ru' => 'Ибн Хаджар аль-Аскалани (1372-1449) — один из величайших хадисоведов в истории ислама. Преподавал в Аль-Азхаре, автор «Фатх аль-Бари».',
                    'ur' => 'ابن حجر العسقلانی (1372-1449) اسلامی تاریخ کے عظیم ترین محدثین میں سے تھے۔ الازہر میں تدریس کی۔ فتح الباری شرح صحیح البخاری کے مصنف۔ 150 سے زائد تصانیف لکھیں۔',
                ],
                'era' => 'medieval',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 31,
            ],
            [
                'slug' => 'al-suyuti',
                'name' => [
                    'ar' => 'جلال الدين السيوطي',
                    'en' => 'Jalal al-Din al-Suyuti',
                    'fr' => 'Jalal al-Din al-Suyuti',
                    'es' => 'Jalal al-Din al-Suyuti',
                    'zh' => '贾拉鲁丁·苏尤提',
                    'ru' => 'Джалал ад-Дин ас-Суюти',
                    'ur' => 'جلال الدین السیوطی',
                ],
                'title' => [
                    'ar' => 'العالم الموسوعي',
                    'en' => 'The Prolific Polymath',
                    'fr' => 'Le polymathe prolifique',
                    'es' => 'El erudito polifacetico',
                    'zh' => '博学多产的学者',
                    'ru' => 'Плодовитый полимат',
                    'ur' => 'موسوعی عالم',
                ],
                'bio' => [
                    'ar' => 'جلال الدين عبد الرحمن السيوطي (1445-1505م) عالم موسوعي مصري ومن أغزر المؤلفين في التاريخ الإسلامي. درّس في الأزهر وألّف أكثر من 500 مؤلف في التفسير والحديث واللغة والتاريخ والفقه. من أشهر كتبه "الإتقان في علوم القرآن" و"الدر المنثور".',
                    'en' => 'Jalal al-Din al-Suyuti (1445-1505) was an Egyptian polymath and one of the most prolific authors in Islamic history. He taught at Al-Azhar and authored over 500 works in tafsir, hadith, linguistics, history, and jurisprudence. His most famous works include "Al-Itqan fi Ulum al-Quran" and "Al-Durr al-Manthur."',
                    'fr' => 'Al-Suyuti (1445-1505), polymathe egyptien, enseigna a Al-Azhar et ecrivit plus de 500 ouvrages en sciences islamiques.',
                    'es' => 'Al-Suyuti (1445-1505), erudito egipcio, enseno en Al-Azhar y escribio mas de 500 obras en ciencias islamicas.',
                    'zh' => '苏尤提（1445-1505），埃及博学家，在艾资哈尔教学，著有500多部伊斯兰学科著作。',
                    'ru' => 'Ас-Суюти (1445-1505) — египетский полимат, преподавал в Аль-Азхаре, автор более 500 трудов по исламским наукам.',
                    'ur' => 'جلال الدین السیوطی (1445-1505) مصری موسوعی عالم اور اسلامی تاریخ کے سب سے زیادہ لکھنے والے مصنفین میں سے تھے۔ الازہر میں تدریس کی اور 500 سے زائد تصانیف لکھیں۔',
                ],
                'era' => 'medieval',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 32,
            ],
            [
                'slug' => 'yusuf-al-qaradawi',
                'name' => [
                    'ar' => 'الشيخ يوسف القرضاوي',
                    'en' => 'Sheikh Yusuf al-Qaradawi',
                    'fr' => 'Cheikh Yusuf al-Qaradawi',
                    'es' => 'Jeque Yusuf al-Qaradawi',
                    'zh' => '谢赫优素福·卡拉达维',
                    'ru' => 'Шейх Юсуф аль-Карадави',
                    'ur' => 'شیخ یوسف القرضاوی',
                ],
                'title' => [
                    'ar' => 'رئيس الاتحاد العالمي لعلماء المسلمين',
                    'en' => 'Chairman of the International Union of Muslim Scholars',
                    'fr' => 'President de l\'Union internationale des savants musulmans',
                    'es' => 'Presidente de la Union Internacional de Eruditos Musulmanes',
                    'zh' => '国际穆斯林学者联盟主席',
                    'ru' => 'Председатель Международного союза мусульманских учёных',
                    'ur' => 'بین الاقوامی اتحاد علمائے مسلمین کے سربراہ',
                ],
                'bio' => [
                    'ar' => 'الشيخ يوسف القرضاوي (1926-2022م) من أبرز العلماء المسلمين المعاصرين. تخرج من الأزهر وحصل على الدكتوراه منه. أسس ورأس الاتحاد العالمي لعلماء المسلمين. ألّف أكثر من 120 كتاباً وكان له تأثير واسع في الفكر الإسلامي المعاصر.',
                    'en' => 'Sheikh Yusuf al-Qaradawi (1926-2022) was one of the most prominent contemporary Muslim scholars. He graduated from Al-Azhar and obtained his doctorate there. He founded and chaired the International Union of Muslim Scholars. He authored over 120 books and had a wide influence on contemporary Islamic thought.',
                    'fr' => 'Le cheikh al-Qaradawi (1926-2022), diplome d\'Al-Azhar, fondateur de l\'Union internationale des savants musulmans. Auteur de plus de 120 ouvrages.',
                    'es' => 'El jeque al-Qaradawi (1926-2022), graduado de Al-Azhar, fundador de la Union Internacional de Eruditos Musulmanes. Autor de mas de 120 libros.',
                    'zh' => '谢赫卡拉达维（1926-2022），艾资哈尔毕业生，国际穆斯林学者联盟创始人兼主席。著有120多部著作。',
                    'ru' => 'Шейх аль-Карадави (1926-2022), выпускник Аль-Азхара, основатель Международного союза мусульманских учёных. Автор более 120 книг.',
                    'ur' => 'شیخ یوسف القرضاوی (1926-2022) معاصر مسلم علماء میں سب سے نمایاں تھے۔ الازہر سے فارغ التحصیل اور ڈاکٹریٹ حاصل کی۔ بین الاقوامی اتحاد علمائے مسلمین کے بانی۔ 120 سے زائد کتب کے مصنف۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 33,
            ],
            [
                'slug' => 'mahmoud-khalil-al-hussary',
                'name' => [
                    'ar' => 'الشيخ محمود خليل الحصري',
                    'en' => 'Sheikh Mahmoud Khalil al-Hussary',
                    'fr' => 'Cheikh Mahmoud Khalil al-Hussary',
                    'es' => 'Jeque Mahmoud Khalil al-Hussary',
                    'zh' => '谢赫马哈茂德·哈利勒·侯萨里',
                    'ru' => 'Шейх Махмуд Халиль аль-Хусари',
                    'ur' => 'شیخ محمود خلیل الحصری',
                ],
                'title' => [
                    'ar' => 'من أشهر قراء القرآن الكريم',
                    'en' => 'One of the Most Famous Quran Reciters',
                    'fr' => 'L\'un des plus celebres recitateurs du Coran',
                    'es' => 'Uno de los recitadores del Coran mas famosos',
                    'zh' => '最著名的古兰经诵读家之一',
                    'ru' => 'Один из самых знаменитых чтецов Корана',
                    'ur' => 'قرآن کریم کے مشہور ترین قراء میں سے ایک',
                ],
                'bio' => [
                    'ar' => 'الشيخ محمود خليل الحصري (1917-1980م) من أشهر قراء القرآن الكريم في العالم الإسلامي. تخرج من الأزهر وأتقن القراءات العشر. أول من سجّل المصحف المرتل كاملاً بالقراءات المتعددة. حصل على لقب "صوت مكة" وأثّر في أجيال من القراء.',
                    'en' => 'Sheikh Mahmoud Khalil al-Hussary (1917-1980) was one of the most famous Quran reciters in the Islamic world. He graduated from Al-Azhar and mastered the ten Quranic readings. He was the first to record the complete Quran in multiple readings. He earned the title "Voice of Mecca" and influenced generations of reciters.',
                    'fr' => 'Le cheikh al-Hussary (1917-1980), diplome d\'Al-Azhar, l\'un des plus celebres recitateurs du Coran. Premier a enregistrer le Coran complet en lectures multiples.',
                    'es' => 'El jeque al-Hussary (1917-1980), graduado de Al-Azhar, uno de los recitadores del Coran mas famosos. Primero en grabar el Coran completo en lecturas multiples.',
                    'zh' => '谢赫侯萨里（1917-1980），艾资哈尔毕业生，伊斯兰世界最著名的古兰经诵读家之一。首位以多种诵读方式录制完整古兰经的人。',
                    'ru' => 'Шейх аль-Хусари (1917-1980), выпускник Аль-Азхара, один из самых известных чтецов Корана. Первый, кто записал полный Коран в нескольких чтениях.',
                    'ur' => 'شیخ محمود خلیل الحصری (1917-1980) اسلامی دنیا کے مشہور ترین قراء قرآن میں سے تھے۔ الازہر سے فارغ التحصیل۔ متعدد قراءات میں مکمل قرآن ریکارڈ کرنے والے پہلے شخص تھے۔',
                ],
                'era' => 'contemporary',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 34,
            ],
            [
                'slug' => 'abu-al-qasim-al-shabbi',
                'name' => [
                    'ar' => 'أبو القاسم الشابي',
                    'en' => 'Abu al-Qasim al-Shabbi',
                    'fr' => 'Abou al-Qasim al-Chabbi',
                    'es' => 'Abu al-Qasim al-Shabbi',
                    'zh' => '阿布·卡西姆·沙比',
                    'ru' => 'Абу аль-Касим аш-Шабби',
                    'ur' => 'ابو القاسم الشابی',
                ],
                'title' => [
                    'ar' => 'شاعر تونس القومي',
                    'en' => 'Tunisian National Poet',
                    'fr' => 'Poete national tunisien',
                    'es' => 'Poeta nacional tunecino',
                    'zh' => '突尼斯民族诗人',
                    'ru' => 'Национальный поэт Туниса',
                    'ur' => 'تیونس کے قومی شاعر',
                ],
                'bio' => [
                    'ar' => 'أبو القاسم الشابي (1909-1934م) شاعر تونسي يُعد من أبرز الشعراء العرب في العصر الحديث. درس في جامع الزيتونة ثم في الأزهر. اشتهر بقصيدته "إرادة الحياة" التي أصبحت رمزاً للنضال العربي. توفي في سن مبكرة لكنه ترك إرثاً شعرياً خالداً.',
                    'en' => 'Abu al-Qasim al-Shabbi (1909-1934) was a Tunisian poet considered one of the most prominent Arab poets of the modern era. He studied at the Zaytuna Mosque and then at Al-Azhar. He is famous for his poem "The Will to Live," which became a symbol of Arab struggle. He died young but left an immortal poetic legacy.',
                    'fr' => 'Abou al-Qasim al-Chabbi (1909-1934), poete tunisien, etudia a Al-Azhar. Celebre pour son poeme « La Volonte de vivre », symbole de la lutte arabe.',
                    'es' => 'Abu al-Qasim al-Shabbi (1909-1934), poeta tunecino, estudio en Al-Azhar. Famoso por su poema "La voluntad de vivir", simbolo de la lucha arabe.',
                    'zh' => '阿布·卡西姆·沙比（1909-1934），突尼斯诗人，曾在艾资哈尔学习。以诗作《生命的意志》闻名，成为阿拉伯斗争的象征。',
                    'ru' => 'Абу аль-Касим аш-Шабби (1909-1934) — тунисский поэт, учился в Аль-Азхаре. Знаменит поэмой «Воля к жизни», ставшей символом арабской борьбы.',
                    'ur' => 'ابو القاسم الشابی (1909-1934) تیونسی شاعر، الازہر میں تعلیم حاصل کی۔ نظم "ارادۃ الحیاۃ" کے لیے مشہور جو عرب جدوجہد کی علامت بن گئی۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 35,
            ],
            [
                'slug' => 'ahmad-amin',
                'name' => [
                    'ar' => 'أحمد أمين',
                    'en' => 'Ahmad Amin',
                    'fr' => 'Ahmad Amin',
                    'es' => 'Ahmad Amin',
                    'zh' => '艾哈迈德·阿明',
                    'ru' => 'Ахмад Амин',
                    'ur' => 'احمد امین',
                ],
                'title' => [
                    'ar' => 'مؤرخ وأديب',
                    'en' => 'Historian and Writer',
                    'fr' => 'Historien et ecrivain',
                    'es' => 'Historiador y escritor',
                    'zh' => '历史学家与作家',
                    'ru' => 'Историк и писатель',
                    'ur' => 'مؤرخ اور ادیب',
                ],
                'bio' => [
                    'ar' => 'أحمد أمين (1886-1954م) مؤرخ ومفكر وأديب مصري. تخرج من الأزهر ثم درّس في الجامعة المصرية. اشتهر بثلاثيته التاريخية "فجر الإسلام" و"ضحى الإسلام" و"ظهر الإسلام" التي أرّخت للحضارة الإسلامية. كان عضواً في مجمع اللغة العربية.',
                    'en' => 'Ahmad Amin (1886-1954) was an Egyptian historian, thinker, and writer. He graduated from Al-Azhar and taught at the Egyptian University. He is famous for his historical trilogy "Dawn of Islam," "Morning of Islam," and "Noon of Islam," which chronicled Islamic civilization. He was a member of the Arabic Language Academy.',
                    'fr' => 'Ahmad Amin (1886-1954), historien et ecrivain egyptien, diplome d\'Al-Azhar. Auteur de la trilogie « Aube de l\'Islam », « Matin de l\'Islam » et « Midi de l\'Islam ».',
                    'es' => 'Ahmad Amin (1886-1954), historiador y escritor egipcio, graduado de Al-Azhar. Autor de la trilogia "Amanecer del Islam", "Manana del Islam" y "Mediodia del Islam".',
                    'zh' => '艾哈迈德·阿明（1886-1954），埃及历史学家和作家，艾资哈尔毕业生。以历史三部曲《伊斯兰黎明》《伊斯兰上午》《伊斯兰正午》闻名。',
                    'ru' => 'Ахмад Амин (1886-1954) — египетский историк и писатель, выпускник Аль-Азхара. Автор трилогии «Заря ислама», «Утро ислама» и «Полдень ислама».',
                    'ur' => 'احمد امین (1886-1954) مصری مؤرخ، مفکر اور ادیب تھے۔ الازہر سے فارغ التحصیل۔ "فجر الاسلام"، "ضحی الاسلام" اور "ظہر الاسلام" کی تاریخی سہ گانہ کے لیے مشہور ہیں۔',
                ],
                'era' => 'modern',
                'is_historical' => true,
                'is_current_leadership' => false,
                'order' => 36,
            ],
        ];

        foreach ($people as $data) {
            Person::create($data);
        }
    }
}
