<?php

namespace Database\Seeders;

use App\Models\Faculty;
use App\Models\ResearchPublication;
use Illuminate\Database\Seeder;

class ResearchPublicationSeeder extends Seeder
{
    public function run(): void
    {
        $faculties = Faculty::all()->keyBy('slug');

        $publications = [
            [
                'title' => [
                    'ar' => 'مقاصد الشريعة الإسلامية وتطبيقاتها المعاصرة',
                    'en' => 'Objectives of Islamic Sharia and Their Contemporary Applications',
                    'fr' => 'Objectifs de la Charia islamique et leurs applications contemporaines',
                    'es' => 'Objetivos de la Sharia islámica y sus aplicaciones contemporáneas',
                    'zh' => '伊斯兰教法的目标及其当代应用',
                    'ru' => 'Цели исламского шариата и их современное применение',
                    'ur' => 'اسلامی شریعت کے مقاصد اور ان کے معاصر اطلاقات',
                ],
                'abstract' => [
                    'ar' => 'تتناول هذه الدراسة مقاصد الشريعة الإسلامية الخمسة وتطبيقاتها في القضايا المعاصرة، مع التركيز على حفظ النفس والمال والعقل والنسل والدين في سياق التحديات الحديثة.',
                    'en' => 'This study examines the five objectives of Islamic Sharia and their applications in contemporary issues, focusing on the preservation of life, wealth, intellect, lineage, and religion in the context of modern challenges.',
                    'fr' => 'Cette étude examine les cinq objectifs de la Charia islamique et leurs applications dans les questions contemporaines.',
                    'es' => 'Este estudio examina los cinco objetivos de la Sharia islámica y sus aplicaciones en cuestiones contemporáneas.',
                    'zh' => '本研究探讨了伊斯兰教法的五个目标及其在当代问题中的应用。',
                    'ru' => 'Данное исследование рассматривает пять целей исламского шариата и их применение в современных вопросах.',
                    'ur' => 'یہ مطالعہ اسلامی شریعت کے پانچ مقاصد اور معاصر مسائل میں ان کے اطلاقات کا جائزہ لیتا ہے۔',
                ],
                'authors' => ['د. أحمد محمد الطيب', 'د. عبد الله المنصور'],
                'journal_name' => ['ar' => 'مجلة الأزهر للدراسات الإسلامية', 'en' => 'Al-Azhar Journal of Islamic Studies'],
                'publication_date' => '2025-06-15',
                'doi' => '10.1234/azhar.2025.001',
                'citation_count' => 45,
                'research_area' => 'islamic_studies',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-sharia-and-law',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'تأثير النانو تكنولوجيا في علاج الأورام السرطانية',
                    'en' => 'Impact of Nanotechnology on Cancer Tumor Treatment',
                    'fr' => 'Impact de la nanotechnologie sur le traitement des tumeurs cancéreuses',
                    'es' => 'Impacto de la nanotecnología en el tratamiento de tumores cancerosos',
                    'zh' => '纳米技术对癌症肿瘤治疗的影响',
                    'ru' => 'Влияние нанотехнологий на лечение раковых опухолей',
                    'ur' => 'کینسر کے ٹیومر کے علاج پر نینو ٹیکنالوجی کا اثر',
                ],
                'abstract' => [
                    'ar' => 'يستعرض هذا البحث أحدث التطورات في استخدام تقنية النانو لتوصيل الأدوية المضادة للسرطان بشكل مستهدف، مما يقلل من الآثار الجانبية ويزيد من فعالية العلاج.',
                    'en' => 'This research reviews the latest developments in using nanotechnology for targeted delivery of anti-cancer drugs, reducing side effects and increasing treatment efficacy.',
                    'fr' => 'Cette recherche passe en revue les derniers développements de la nanotechnologie pour la livraison ciblée de médicaments anticancéreux.',
                    'es' => 'Esta investigación revisa los últimos desarrollos en nanotecnología para la entrega dirigida de medicamentos anticancerosos.',
                    'zh' => '本研究综述了利用纳米技术靶向递送抗癌药物的最新进展。',
                    'ru' => 'Данное исследование обзирает последние разработки в области нанотехнологий для целевой доставки противораковых препаратов.',
                    'ur' => 'یہ تحقیق کینسر مخالف ادویات کی ہدفی ترسیل کے لیے نینو ٹیکنالوجی کے استعمال میں تازہ ترین پیشرفت کا جائزہ لیتی ہے۔',
                ],
                'authors' => ['د. فاطمة الزهراء حسن', 'د. محمد عبد الرحمن'],
                'journal_name' => ['ar' => 'المجلة المصرية للطب النانوي', 'en' => 'Egyptian Journal of Nanomedicine'],
                'publication_date' => '2025-09-20',
                'doi' => '10.1234/azhar.2025.002',
                'citation_count' => 78,
                'research_area' => 'medicine',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-medicine',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'الطاقة الشمسية المركزة وتطبيقاتها في المناطق الصحراوية',
                    'en' => 'Concentrated Solar Power and Its Applications in Desert Regions',
                    'fr' => 'Énergie solaire concentrée et ses applications dans les régions désertiques',
                    'es' => 'Energía solar concentrada y sus aplicaciones en regiones desérticas',
                    'zh' => '聚光太阳能及其在沙漠地区的应用',
                    'ru' => 'Концентрированная солнечная энергия и её применение в пустынных регионах',
                    'ur' => 'مرتکز شمسی توانائی اور صحرائی علاقوں میں اس کے استعمالات',
                ],
                'abstract' => [
                    'ar' => 'تدرس هذه الورقة كفاءة أنظمة الطاقة الشمسية المركزة في البيئات الصحراوية المصرية، مع تقديم نماذج محاكاة لتحسين الأداء وخفض التكاليف.',
                    'en' => 'This paper studies the efficiency of concentrated solar power systems in Egyptian desert environments, presenting simulation models to optimize performance and reduce costs.',
                    'fr' => 'Cet article étudie l\'efficacité des systèmes d\'énergie solaire concentrée dans les environnements désertiques égyptiens.',
                    'es' => 'Este artículo estudia la eficiencia de los sistemas de energía solar concentrada en entornos desérticos egipcios.',
                    'zh' => '本文研究了埃及沙漠环境中聚光太阳能系统的效率。',
                    'ru' => 'Данная работа изучает эффективность систем концентрированной солнечной энергии в пустынных условиях Египта.',
                    'ur' => 'یہ مقالہ مصری صحرائی ماحول میں مرتکز شمسی توانائی کے نظاموں کی کارکردگی کا مطالعہ کرتا ہے۔',
                ],
                'authors' => ['د. خالد إبراهيم', 'د. سارة أحمد النجار'],
                'journal_name' => ['ar' => 'مجلة الهندسة والتكنولوجيا', 'en' => 'Journal of Engineering and Technology'],
                'publication_date' => '2025-03-10',
                'doi' => '10.1234/azhar.2025.003',
                'citation_count' => 32,
                'research_area' => 'engineering',
                'publication_type' => 'conference_paper',
                'faculty_slug' => 'faculty-of-engineering',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'التفسير الموضوعي لآيات الأحكام في القرآن الكريم',
                    'en' => 'Thematic Interpretation of Legal Verses in the Holy Quran',
                    'fr' => 'Interprétation thématique des versets juridiques du Saint Coran',
                    'es' => 'Interpretación temática de los versículos legales del Sagrado Corán',
                    'zh' => '《古兰经》法律经文的主题解释',
                    'ru' => 'Тематическое толкование правовых аятов Священного Корана',
                    'ur' => 'قرآن کریم کی احکام کی آیات کی موضوعی تفسیر',
                ],
                'abstract' => [
                    'ar' => 'يقدم هذا الكتاب دراسة موضوعية شاملة لآيات الأحكام في القرآن الكريم، مع ربطها بالاجتهادات الفقهية المعاصرة والقضايا المستجدة.',
                    'en' => 'This book presents a comprehensive thematic study of legal verses in the Holy Quran, linking them to contemporary jurisprudential reasoning and emerging issues.',
                    'fr' => 'Ce livre présente une étude thématique complète des versets juridiques du Saint Coran.',
                    'es' => 'Este libro presenta un estudio temático completo de los versículos legales del Sagrado Corán.',
                    'zh' => '本书对《古兰经》中的法律经文进行了全面的主题研究。',
                    'ru' => 'Эта книга представляет всестороннее тематическое исследование правовых аятов Священного Корана.',
                    'ur' => 'یہ کتاب قرآن کریم کی احکام کی آیات کا ایک جامع موضوعی مطالعہ پیش کرتی ہے۔',
                ],
                'authors' => ['أ.د. محمود عبد الحليم'],
                'journal_name' => ['ar' => 'دار النشر الأزهرية', 'en' => 'Al-Azhar Publishing House'],
                'publication_date' => '2024-11-01',
                'doi' => '10.1234/azhar.2024.004',
                'citation_count' => 120,
                'research_area' => 'islamic_studies',
                'publication_type' => 'book',
                'faculty_slug' => 'faculty-of-theology',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'تطوير لقاح جديد لمقاومة فيروسات الجهاز التنفسي',
                    'en' => 'Development of a Novel Vaccine Against Respiratory Viruses',
                    'fr' => 'Développement d\'un nouveau vaccin contre les virus respiratoires',
                    'es' => 'Desarrollo de una nueva vacuna contra virus respiratorios',
                    'zh' => '新型呼吸道病毒疫苗的开发',
                    'ru' => 'Разработка новой вакцины против респираторных вирусов',
                    'ur' => 'سانس کے وائرسوں کے خلاف نئی ویکسین کی تیاری',
                ],
                'abstract' => [
                    'ar' => 'يعرض هذا البحث نتائج التجارب السريرية للقاح جديد طوره فريق بحثي من كلية الطب بجامعة الأزهر لمواجهة فيروسات الجهاز التنفسي الموسمية.',
                    'en' => 'This research presents clinical trial results for a novel vaccine developed by a research team from Al-Azhar University Faculty of Medicine to combat seasonal respiratory viruses.',
                    'fr' => 'Cette recherche présente les résultats d\'essais cliniques pour un nouveau vaccin développé par l\'Université Al-Azhar.',
                    'es' => 'Esta investigación presenta resultados de ensayos clínicos para una nueva vacuna desarrollada por la Universidad Al-Azhar.',
                    'zh' => '本研究展示了艾资哈尔大学医学院研究团队开发的新型疫苗的临床试验结果。',
                    'ru' => 'Данное исследование представляет результаты клинических испытаний новой вакцины, разработанной Университетом Аль-Азхар.',
                    'ur' => 'یہ تحقیق الازہر یونیورسٹی کی طبی ٹیم کی تیار کردہ نئی ویکسین کے کلینیکل ٹرائل کے نتائج پیش کرتی ہے۔',
                ],
                'authors' => ['د. عمرو حسين', 'د. نهى سالم', 'د. أحمد فؤاد'],
                'journal_name' => ['ar' => 'المجلة الدولية للعلوم الطبية', 'en' => 'International Journal of Medical Sciences'],
                'publication_date' => '2025-12-05',
                'doi' => '10.1234/azhar.2025.005',
                'citation_count' => 95,
                'research_area' => 'medicine',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-medicine',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'دور الذكاء الاصطناعي في تحسين التعليم الجامعي',
                    'en' => 'The Role of Artificial Intelligence in Improving University Education',
                    'fr' => 'Le rôle de l\'intelligence artificielle dans l\'amélioration de l\'enseignement universitaire',
                    'es' => 'El papel de la inteligencia artificial en la mejora de la educación universitaria',
                    'zh' => '人工智能在改善大学教育中的作用',
                    'ru' => 'Роль искусственного интеллекта в улучшении университетского образования',
                    'ur' => 'جامعی تعلیم کی بہتری میں مصنوعی ذہانت کا کردار',
                ],
                'abstract' => [
                    'ar' => 'تستكشف هذه الدراسة إمكانيات استخدام تقنيات الذكاء الاصطناعي في تطوير المناهج الدراسية وأساليب التدريس في الجامعات المصرية.',
                    'en' => 'This study explores the potential of using AI technologies to develop curricula and teaching methods in Egyptian universities.',
                    'fr' => 'Cette étude explore le potentiel de l\'IA pour développer les programmes et méthodes d\'enseignement.',
                    'es' => 'Este estudio explora el potencial de la IA para desarrollar currículos y métodos de enseñanza.',
                    'zh' => '本研究探讨了利用人工智能技术发展埃及大学课程和教学方法的潜力。',
                    'ru' => 'Данное исследование изучает потенциал ИИ для развития учебных программ и методов преподавания.',
                    'ur' => 'یہ مطالعہ مصری جامعات میں نصاب اور تدریسی طریقوں کی ترقی میں AI ٹیکنالوجیز کے استعمال کی صلاحیت کو دریافت کرتا ہے۔',
                ],
                'authors' => ['د. هاني محمود', 'د. رانيا عبد الفتاح'],
                'journal_name' => ['ar' => 'مجلة تكنولوجيا التعليم', 'en' => 'Journal of Educational Technology'],
                'publication_date' => '2025-08-18',
                'doi' => '10.1234/azhar.2025.006',
                'citation_count' => 55,
                'research_area' => 'education',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-education',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'الأحكام الفقهية للمعاملات المالية الإلكترونية',
                    'en' => 'Jurisprudential Rulings on Electronic Financial Transactions',
                    'fr' => 'Jurisprudence des transactions financières électroniques',
                    'es' => 'Jurisprudencia de las transacciones financieras electrónicas',
                    'zh' => '电子金融交易的法学裁决',
                    'ru' => 'Юриспруденция электронных финансовых операций',
                    'ur' => 'الیکٹرانک مالی لین دین کے فقہی احکام',
                ],
                'abstract' => [
                    'ar' => 'يبحث هذا العمل في الأحكام الشرعية المتعلقة بالعملات الرقمية والتجارة الإلكترونية والتمويل عبر الإنترنت من منظور الفقه الإسلامي.',
                    'en' => 'This work examines Islamic jurisprudential rulings on digital currencies, e-commerce, and online financing from an Islamic law perspective.',
                    'fr' => 'Ce travail examine les règles de la jurisprudence islamique sur les monnaies numériques et le commerce électronique.',
                    'es' => 'Este trabajo examina las reglas de la jurisprudencia islámica sobre monedas digitales y comercio electrónico.',
                    'zh' => '本文从伊斯兰法学角度审视数字货币、电子商务和网络融资的法学裁决。',
                    'ru' => 'Данная работа рассматривает исламские юридические решения о цифровых валютах и электронной коммерции.',
                    'ur' => 'یہ کام ڈیجیٹل کرنسیوں، ای کامرس اور آن لائن فنانسنگ پر اسلامی فقہی احکام کا جائزہ لیتا ہے۔',
                ],
                'authors' => ['أ.د. عبد الرحمن الشافعي'],
                'journal_name' => ['ar' => 'مجلة الفقه والقانون', 'en' => 'Journal of Jurisprudence and Law'],
                'publication_date' => '2025-04-22',
                'doi' => '10.1234/azhar.2025.007',
                'citation_count' => 67,
                'research_area' => 'law',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-sharia-and-law',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'تحسين إنتاجية القمح في الأراضي الملحية باستخدام تقنيات حيوية',
                    'en' => 'Improving Wheat Productivity in Saline Soils Using Biotechnology',
                    'fr' => 'Amélioration de la productivité du blé dans les sols salins par la biotechnologie',
                    'es' => 'Mejora de la productividad del trigo en suelos salinos mediante biotecnología',
                    'zh' => '利用生物技术提高盐碱地小麦产量',
                    'ru' => 'Повышение продуктивности пшеницы на засоленных почвах с использованием биотехнологий',
                    'ur' => 'بائیو ٹیکنالوجی کے ذریعے نمکین مٹی میں گندم کی پیداوار میں بہتری',
                ],
                'abstract' => [
                    'ar' => 'تقدم هذه الدراسة نتائج تجارب ميدانية لتحسين إنتاجية القمح في الأراضي الملحية بدلتا النيل باستخدام سلالات بكتيرية محسنة وراثياً.',
                    'en' => 'This study presents field trial results for improving wheat productivity in saline soils of the Nile Delta using genetically enhanced bacterial strains.',
                    'fr' => 'Cette étude présente les résultats d\'essais sur le terrain pour améliorer la productivité du blé dans les sols salins du delta du Nil.',
                    'es' => 'Este estudio presenta resultados de pruebas de campo para mejorar la productividad del trigo en suelos salinos del delta del Nilo.',
                    'zh' => '本研究展示了利用基因增强细菌菌株改善尼罗河三角洲盐碱地小麦产量的田间试验结果。',
                    'ru' => 'Данное исследование представляет результаты полевых испытаний по повышению продуктивности пшеницы на засоленных почвах дельты Нила.',
                    'ur' => 'یہ مطالعہ جینیاتی طور پر بہتر بیکٹیریل سٹرینز کے ذریعے دریائے نیل کے ڈیلٹا کی نمکین مٹی میں گندم کی پیداوار بہتر بنانے کے میدانی تجربات پیش کرتا ہے۔',
                ],
                'authors' => ['د. مصطفى كامل', 'د. سمية عبد الهادي'],
                'journal_name' => ['ar' => 'مجلة العلوم الزراعية', 'en' => 'Journal of Agricultural Sciences'],
                'publication_date' => '2025-07-14',
                'doi' => '10.1234/azhar.2025.008',
                'citation_count' => 28,
                'research_area' => 'agriculture',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-agriculture',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'الأدب العربي في العصر العباسي: دراسة تحليلية نقدية',
                    'en' => 'Arabic Literature in the Abbasid Era: A Critical Analytical Study',
                    'fr' => 'La littérature arabe à l\'époque abbasside : une étude analytique critique',
                    'es' => 'La literatura árabe en la era abasí: un estudio analítico crítico',
                    'zh' => '阿拔斯时代的阿拉伯文学：批判性分析研究',
                    'ru' => 'Арабская литература эпохи Аббасидов: критическое аналитическое исследование',
                    'ur' => 'عباسی دور میں عربی ادب: ایک تنقیدی تجزیاتی مطالعہ',
                ],
                'abstract' => [
                    'ar' => 'يتناول هذا البحث تطور الأدب العربي في العصر العباسي، مع التركيز على التجديد في الشعر والنثر وتأثير الثقافات الأخرى.',
                    'en' => 'This research examines the development of Arabic literature during the Abbasid era, focusing on innovation in poetry and prose and the influence of other cultures.',
                    'fr' => 'Cette recherche examine le développement de la littérature arabe pendant l\'ère abbasside.',
                    'es' => 'Esta investigación examina el desarrollo de la literatura árabe durante la era abasí.',
                    'zh' => '本研究考察了阿拔斯时代阿拉伯文学的发展。',
                    'ru' => 'Данное исследование рассматривает развитие арабской литературы в эпоху Аббасидов.',
                    'ur' => 'یہ تحقیق عباسی دور میں عربی ادب کی ترقی کا جائزہ لیتی ہے۔',
                ],
                'authors' => ['أ.د. حسن عبد الباقي', 'د. ليلى محمد'],
                'journal_name' => ['ar' => 'مجلة اللغة العربية وآدابها', 'en' => 'Journal of Arabic Language and Literature'],
                'publication_date' => '2024-12-20',
                'doi' => '10.1234/azhar.2024.009',
                'citation_count' => 38,
                'research_area' => 'humanities',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-arabic-language',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'تصميم مبانٍ ذكية مستدامة في المناخ الحار الجاف',
                    'en' => 'Designing Sustainable Smart Buildings in Hot Arid Climates',
                    'fr' => 'Conception de bâtiments intelligents durables dans les climats chauds et arides',
                    'es' => 'Diseño de edificios inteligentes sostenibles en climas cálidos y áridos',
                    'zh' => '炎热干旱气候下可持续智能建筑设计',
                    'ru' => 'Проектирование устойчивых умных зданий в жарком засушливом климате',
                    'ur' => 'گرم خشک آب و ہوا میں پائیدار سمارٹ عمارتوں کا ڈیزائن',
                ],
                'abstract' => [
                    'ar' => 'يقدم هذا البحث إطاراً تصميمياً لمبانٍ ذكية مستدامة تتكيف مع المناخ المصري الحار، باستخدام تقنيات إنترنت الأشياء والطاقة المتجددة.',
                    'en' => 'This research presents a design framework for sustainable smart buildings adapted to Egypt\'s hot climate, using IoT technologies and renewable energy.',
                    'fr' => 'Cette recherche présente un cadre de conception pour des bâtiments intelligents durables adaptés au climat chaud de l\'Égypte.',
                    'es' => 'Esta investigación presenta un marco de diseño para edificios inteligentes sostenibles adaptados al clima cálido de Egipto.',
                    'zh' => '本研究提出了适应埃及炎热气候的可持续智能建筑设计框架。',
                    'ru' => 'Данное исследование представляет проектную основу для устойчивых умных зданий, адаптированных к жаркому климату Египта.',
                    'ur' => 'یہ تحقیق مصر کی گرم آب و ہوا کے مطابق پائیدار سمارٹ عمارتوں کے لیے ڈیزائن فریم ورک پیش کرتی ہے۔',
                ],
                'authors' => ['د. طارق النجار', 'م. أسماء وهبة'],
                'journal_name' => ['ar' => 'مجلة العمارة والتخطيط', 'en' => 'Journal of Architecture and Planning'],
                'publication_date' => '2025-05-30',
                'doi' => '10.1234/azhar.2025.010',
                'citation_count' => 41,
                'research_area' => 'engineering',
                'publication_type' => 'conference_paper',
                'faculty_slug' => 'faculty-of-engineering',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'أثر التعليم عن بُعد على التحصيل الدراسي في المرحلة الجامعية',
                    'en' => 'Impact of Distance Learning on Academic Achievement at University Level',
                    'fr' => 'Impact de l\'enseignement à distance sur la réussite académique au niveau universitaire',
                    'es' => 'Impacto del aprendizaje a distancia en el rendimiento académico universitario',
                    'zh' => '远程教育对大学阶段学业成就的影响',
                    'ru' => 'Влияние дистанционного обучения на академическую успеваемость в университете',
                    'ur' => 'جامعی سطح پر تعلیمی کارکردگی پر فاصلاتی تعلیم کا اثر',
                ],
                'abstract' => [
                    'ar' => 'تحلل هذه الأطروحة تأثير التعليم عن بُعد على مستوى التحصيل الدراسي لطلاب جامعة الأزهر خلال فترة جائحة كوفيد-19 وما بعدها.',
                    'en' => 'This thesis analyzes the impact of distance learning on academic achievement among Al-Azhar University students during and after the COVID-19 pandemic.',
                    'fr' => 'Cette thèse analyse l\'impact de l\'enseignement à distance sur la réussite académique des étudiants d\'Al-Azhar.',
                    'es' => 'Esta tesis analiza el impacto del aprendizaje a distancia en el rendimiento académico de los estudiantes de Al-Azhar.',
                    'zh' => '本论文分析了远程教育对艾资哈尔大学学生学业成就的影响。',
                    'ru' => 'Данная диссертация анализирует влияние дистанционного обучения на успеваемость студентов Аль-Азхар.',
                    'ur' => 'یہ مقالہ الازہر یونیورسٹی کے طلبا کی تعلیمی کارکردگی پر فاصلاتی تعلیم کے اثرات کا تجزیہ کرتا ہے۔',
                ],
                'authors' => ['د. منى السيد إبراهيم'],
                'journal_name' => ['ar' => 'رسالة دكتوراه - كلية التربية', 'en' => 'PhD Thesis - Faculty of Education'],
                'publication_date' => '2025-02-15',
                'doi' => '10.1234/azhar.2025.011',
                'citation_count' => 19,
                'research_area' => 'education',
                'publication_type' => 'thesis',
                'faculty_slug' => 'faculty-of-education',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'الخلايا الجذعية وتطبيقاتها في علاج أمراض القلب',
                    'en' => 'Stem Cells and Their Applications in Cardiac Disease Treatment',
                    'fr' => 'Cellules souches et leurs applications dans le traitement des maladies cardiaques',
                    'es' => 'Células madre y sus aplicaciones en el tratamiento de enfermedades cardíacas',
                    'zh' => '干细胞及其在心脏病治疗中的应用',
                    'ru' => 'Стволовые клетки и их применение в лечении сердечных заболеваний',
                    'ur' => 'اسٹیم سیلز اور دل کی بیماریوں کے علاج میں ان کے استعمالات',
                ],
                'abstract' => [
                    'ar' => 'يستعرض هذا التقرير أحدث الأبحاث في مجال استخدام الخلايا الجذعية لعلاج أمراض القلب المزمنة، مع عرض نتائج من مستشفيات جامعة الأزهر.',
                    'en' => 'This report reviews the latest research on using stem cells to treat chronic cardiac diseases, presenting results from Al-Azhar University hospitals.',
                    'fr' => 'Ce rapport passe en revue les dernières recherches sur l\'utilisation des cellules souches pour traiter les maladies cardiaques chroniques.',
                    'es' => 'Este informe revisa las últimas investigaciones sobre el uso de células madre para tratar enfermedades cardíacas crónicas.',
                    'zh' => '本报告综述了利用干细胞治疗慢性心脏病的最新研究。',
                    'ru' => 'Данный отчёт обзирает последние исследования использования стволовых клеток для лечения хронических заболеваний сердца.',
                    'ur' => 'یہ رپورٹ دائمی دل کی بیماریوں کے علاج کے لیے اسٹیم سیلز کے استعمال پر تازہ ترین تحقیق کا جائزہ لیتی ہے۔',
                ],
                'authors' => ['د. يوسف الشريف', 'د. هدى عبد الله', 'د. إيمان حسن'],
                'journal_name' => ['ar' => 'تقرير مستشفيات الأزهر الجامعية', 'en' => 'Al-Azhar University Hospitals Report'],
                'publication_date' => '2025-10-08',
                'doi' => '10.1234/azhar.2025.012',
                'citation_count' => 52,
                'research_area' => 'medicine',
                'publication_type' => 'report',
                'faculty_slug' => 'faculty-of-medicine',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'منهج الإمام الغزالي في التربية الروحية',
                    'en' => 'Imam Al-Ghazali\'s Methodology in Spiritual Education',
                    'fr' => 'La méthodologie de l\'Imam Al-Ghazali en éducation spirituelle',
                    'es' => 'La metodología del Imam Al-Ghazali en la educación espiritual',
                    'zh' => '伊玛目安萨里的精神教育方法论',
                    'ru' => 'Методология имама Аль-Газали в духовном воспитании',
                    'ur' => 'امام غزالی کا روحانی تربیت کا منہج',
                ],
                'abstract' => [
                    'ar' => 'تدرس هذه الورقة منهج الإمام أبي حامد الغزالي في التربية الروحية كما عرضه في كتابه إحياء علوم الدين، مع مقارنة بالمناهج التربوية الحديثة.',
                    'en' => 'This paper studies Imam Abu Hamid Al-Ghazali\'s methodology in spiritual education as presented in his book Ihya Ulum al-Din, compared with modern educational approaches.',
                    'fr' => 'Cet article étudie la méthodologie d\'Al-Ghazali en éducation spirituelle telle que présentée dans son livre Ihya Ulum al-Din.',
                    'es' => 'Este artículo estudia la metodología de Al-Ghazali en la educación espiritual según su libro Ihya Ulum al-Din.',
                    'zh' => '本文研究了安萨里在其著作《宗教科学的复兴》中提出的精神教育方法论。',
                    'ru' => 'Данная работа изучает методологию Аль-Газали в духовном воспитании, представленную в его книге «Ихья улум ад-дин».',
                    'ur' => 'یہ مقالہ امام غزالی کے روحانی تربیت کے منہج کا مطالعہ کرتا ہے جیسا کہ ان کی کتاب احیاء علوم الدین میں بیان کیا گیا ہے۔',
                ],
                'authors' => ['د. عائشة محمد البنا'],
                'journal_name' => ['ar' => 'مجلة الدراسات الإسلامية والعربية', 'en' => 'Journal of Islamic and Arabic Studies'],
                'publication_date' => '2025-01-10',
                'doi' => '10.1234/azhar.2025.013',
                'citation_count' => 73,
                'research_area' => 'islamic_studies',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-theology',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'تطبيقات الحوسبة السحابية في إدارة البيانات الجامعية',
                    'en' => 'Cloud Computing Applications in University Data Management',
                    'fr' => 'Applications du cloud computing dans la gestion des données universitaires',
                    'es' => 'Aplicaciones de computación en la nube en la gestión de datos universitarios',
                    'zh' => '云计算在大学数据管理中的应用',
                    'ru' => 'Применение облачных вычислений в управлении университетскими данными',
                    'ur' => 'جامعی ڈیٹا مینجمنٹ میں کلاؤڈ کمپیوٹنگ کے استعمالات',
                ],
                'abstract' => [
                    'ar' => 'يقترح هذا البحث نموذجاً لاستخدام الحوسبة السحابية في إدارة بيانات الطلاب والموظفين في جامعة الأزهر بشكل آمن وفعال.',
                    'en' => 'This research proposes a model for using cloud computing to manage student and staff data at Al-Azhar University securely and efficiently.',
                    'fr' => 'Cette recherche propose un modèle d\'utilisation du cloud computing pour gérer les données des étudiants et du personnel.',
                    'es' => 'Esta investigación propone un modelo de computación en la nube para gestionar datos de estudiantes y personal.',
                    'zh' => '本研究提出了一个利用云计算安全高效管理艾资哈尔大学学生和员工数据的模型。',
                    'ru' => 'Данное исследование предлагает модель использования облачных вычислений для управления данными студентов и сотрудников.',
                    'ur' => 'یہ تحقیق الازہر یونیورسٹی میں طلبا اور عملے کے ڈیٹا کو محفوظ اور مؤثر طریقے سے منظم کرنے کے لیے کلاؤڈ کمپیوٹنگ کا ماڈل تجویز کرتی ہے۔',
                ],
                'authors' => ['د. أيمن صالح', 'م. نورهان خالد'],
                'journal_name' => ['ar' => 'مجلة علوم الحاسب', 'en' => 'Journal of Computer Science'],
                'publication_date' => '2025-11-25',
                'doi' => '10.1234/azhar.2025.014',
                'citation_count' => 15,
                'research_area' => 'science',
                'publication_type' => 'conference_paper',
                'faculty_slug' => 'faculty-of-science',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'حقوق المرأة في الفقه الإسلامي: دراسة مقارنة',
                    'en' => 'Women\'s Rights in Islamic Jurisprudence: A Comparative Study',
                    'fr' => 'Les droits des femmes dans la jurisprudence islamique : une étude comparative',
                    'es' => 'Los derechos de la mujer en la jurisprudencia islámica: un estudio comparativo',
                    'zh' => '伊斯兰法学中的女性权利：比较研究',
                    'ru' => 'Права женщин в исламской юриспруденции: сравнительное исследование',
                    'ur' => 'اسلامی فقہ میں خواتین کے حقوق: ایک تقابلی مطالعہ',
                ],
                'abstract' => [
                    'ar' => 'تقارن هذه الدراسة بين المذاهب الفقهية الأربعة في مسائل حقوق المرأة، مع عرض الاجتهادات المعاصرة التي تراعي مقاصد الشريعة.',
                    'en' => 'This study compares the four schools of Islamic jurisprudence on women\'s rights issues, presenting contemporary interpretations that consider Sharia objectives.',
                    'fr' => 'Cette étude compare les quatre écoles de jurisprudence islamique sur les questions des droits des femmes.',
                    'es' => 'Este estudio compara las cuatro escuelas de jurisprudencia islámica sobre cuestiones de derechos de la mujer.',
                    'zh' => '本研究比较了伊斯兰法学四大学派在女性权利问题上的观点。',
                    'ru' => 'Данное исследование сравнивает четыре школы исламской юриспруденции по вопросам прав женщин.',
                    'ur' => 'یہ مطالعہ خواتین کے حقوق کے معاملات پر اسلامی فقہ کے چار مکاتب فکر کا تقابل کرتا ہے۔',
                ],
                'authors' => ['د. زينب عبد الله الحسيني', 'د. أمل فتحي'],
                'journal_name' => ['ar' => 'مجلة الدراسات القانونية والشرعية', 'en' => 'Journal of Legal and Sharia Studies'],
                'publication_date' => '2025-06-01',
                'doi' => '10.1234/azhar.2025.015',
                'citation_count' => 84,
                'research_area' => 'law',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-sharia-and-law',
                'is_featured' => true,
            ],
            [
                'title' => [
                    'ar' => 'مقاومة المضادات الحيوية: تحديات وحلول من منظور صيدلاني',
                    'en' => 'Antibiotic Resistance: Challenges and Solutions from a Pharmaceutical Perspective',
                    'fr' => 'Résistance aux antibiotiques : défis et solutions d\'un point de vue pharmaceutique',
                    'es' => 'Resistencia a los antibióticos: desafíos y soluciones desde una perspectiva farmacéutica',
                    'zh' => '抗生素耐药性：药学视角下的挑战与解决方案',
                    'ru' => 'Устойчивость к антибиотикам: проблемы и решения с фармацевтической точки зрения',
                    'ur' => 'اینٹی بائیوٹک مزاحمت: فارماسیوٹیکل نقطہ نظر سے چیلنجز اور حل',
                ],
                'abstract' => [
                    'ar' => 'يدرس هذا البحث ظاهرة مقاومة البكتيريا للمضادات الحيوية ويقترح استراتيجيات صيدلانية جديدة لمواجهة هذا التحدي العالمي.',
                    'en' => 'This research studies the phenomenon of bacterial antibiotic resistance and proposes new pharmaceutical strategies to address this global challenge.',
                    'fr' => 'Cette recherche étudie la résistance bactérienne aux antibiotiques et propose de nouvelles stratégies pharmaceutiques.',
                    'es' => 'Esta investigación estudia la resistencia bacteriana a los antibióticos y propone nuevas estrategias farmacéuticas.',
                    'zh' => '本研究探讨了细菌抗生素耐药现象，并提出了应对这一全球挑战的新药学策略。',
                    'ru' => 'Данное исследование изучает феномен бактериальной устойчивости к антибиотикам и предлагает новые фармацевтические стратегии.',
                    'ur' => 'یہ تحقیق بیکٹیریل اینٹی بائیوٹک مزاحمت کے رجحان کا مطالعہ کرتی ہے اور نئی فارماسیوٹیکل حکمت عملی تجویز کرتی ہے۔',
                ],
                'authors' => ['د. نادية حسين', 'د. محمد سعيد'],
                'journal_name' => ['ar' => 'المجلة المصرية للعلوم الصيدلانية', 'en' => 'Egyptian Journal of Pharmaceutical Sciences'],
                'publication_date' => '2025-09-12',
                'doi' => '10.1234/azhar.2025.016',
                'citation_count' => 61,
                'research_area' => 'science',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-science',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'التنمية المستدامة في ضوء القرآن والسنة',
                    'en' => 'Sustainable Development in Light of the Quran and Sunnah',
                    'fr' => 'Le développement durable à la lumière du Coran et de la Sunna',
                    'es' => 'El desarrollo sostenible a la luz del Corán y la Sunnah',
                    'zh' => '从古兰经和圣训看可持续发展',
                    'ru' => 'Устойчивое развитие в свете Корана и Сунны',
                    'ur' => 'قرآن اور سنت کی روشنی میں پائیدار ترقی',
                ],
                'abstract' => [
                    'ar' => 'يبحث هذا العمل في المبادئ الإسلامية المتعلقة بالتنمية المستدامة والحفاظ على البيئة كما وردت في القرآن الكريم والأحاديث النبوية الشريفة.',
                    'en' => 'This work examines Islamic principles related to sustainable development and environmental conservation as mentioned in the Holy Quran and Prophetic traditions.',
                    'fr' => 'Ce travail examine les principes islamiques liés au développement durable et à la conservation de l\'environnement.',
                    'es' => 'Este trabajo examina los principios islámicos relacionados con el desarrollo sostenible y la conservación ambiental.',
                    'zh' => '本文探讨了古兰经和先知传统中关于可持续发展和环境保护的伊斯兰原则。',
                    'ru' => 'Данная работа исследует исламские принципы устойчивого развития и охраны окружающей среды.',
                    'ur' => 'یہ کام قرآن کریم اور احادیث نبوی میں بیان کردہ پائیدار ترقی اور ماحولیاتی تحفظ سے متعلق اسلامی اصولوں کا جائزہ لیتا ہے۔',
                ],
                'authors' => ['أ.د. سعيد عبد اللطيف فودة'],
                'journal_name' => ['ar' => 'مجلة البحوث الإسلامية', 'en' => 'Journal of Islamic Research'],
                'publication_date' => '2024-08-20',
                'doi' => '10.1234/azhar.2024.017',
                'citation_count' => 92,
                'research_area' => 'islamic_studies',
                'publication_type' => 'book',
                'faculty_slug' => 'faculty-of-theology',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'تأثير التغيرات المناخية على الإنتاج الحيواني في مصر',
                    'en' => 'Impact of Climate Change on Animal Production in Egypt',
                    'fr' => 'Impact du changement climatique sur la production animale en Égypte',
                    'es' => 'Impacto del cambio climático en la producción animal en Egipto',
                    'zh' => '气候变化对埃及畜牧业的影响',
                    'ru' => 'Влияние изменения климата на животноводство в Египте',
                    'ur' => 'مصر میں حیوانی پیداوار پر موسمیاتی تبدیلیوں کا اثر',
                ],
                'abstract' => [
                    'ar' => 'تحلل هذه الدراسة تأثير ارتفاع درجات الحرارة والتغيرات المناخية على إنتاجية الماشية والدواجن في المزارع المصرية وتقترح حلولاً تكيفية.',
                    'en' => 'This study analyzes the impact of rising temperatures and climate change on livestock and poultry productivity in Egyptian farms, proposing adaptive solutions.',
                    'fr' => 'Cette étude analyse l\'impact de la hausse des températures sur la productivité de l\'élevage en Égypte.',
                    'es' => 'Este estudio analiza el impacto del aumento de las temperaturas en la productividad ganadera en Egipto.',
                    'zh' => '本研究分析了气温升高和气候变化对埃及农场畜禽生产力的影响。',
                    'ru' => 'Данное исследование анализирует влияние повышения температуры на продуктивность животноводства в Египте.',
                    'ur' => 'یہ مطالعہ مصری فارموں میں مویشیوں اور مرغیوں کی پیداوار پر درجہ حرارت میں اضافے کے اثرات کا تجزیہ کرتا ہے۔',
                ],
                'authors' => ['د. عبد العزيز محمد', 'د. سامية حسن عوض'],
                'journal_name' => ['ar' => 'مجلة الإنتاج الحيواني', 'en' => 'Journal of Animal Production'],
                'publication_date' => '2025-04-05',
                'doi' => '10.1234/azhar.2025.018',
                'citation_count' => 23,
                'research_area' => 'agriculture',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-agriculture',
                'is_featured' => false,
            ],
            [
                'title' => [
                    'ar' => 'تطوير خوارزميات التعلم العميق لتشخيص أمراض العيون',
                    'en' => 'Developing Deep Learning Algorithms for Diagnosing Eye Diseases',
                    'fr' => 'Développement d\'algorithmes d\'apprentissage profond pour le diagnostic des maladies oculaires',
                    'es' => 'Desarrollo de algoritmos de aprendizaje profundo para diagnosticar enfermedades oculares',
                    'zh' => '开发用于诊断眼科疾病的深度学习算法',
                    'ru' => 'Разработка алгоритмов глубокого обучения для диагностики глазных заболеваний',
                    'ur' => 'آنکھوں کی بیماریوں کی تشخیص کے لیے ڈیپ لرننگ الگورتھم کی تیاری',
                ],
                'abstract' => [
                    'ar' => 'يقدم هذا البحث نموذج ذكاء اصطناعي يعتمد على التعلم العميق لتشخيص أمراض شبكية العين من صور قاع العين بدقة تصل إلى 96%.',
                    'en' => 'This research presents an AI model based on deep learning to diagnose retinal diseases from fundus images with accuracy up to 96%.',
                    'fr' => 'Cette recherche présente un modèle d\'IA basé sur l\'apprentissage profond pour diagnostiquer les maladies rétiniennes.',
                    'es' => 'Esta investigación presenta un modelo de IA basado en aprendizaje profundo para diagnosticar enfermedades retinianas.',
                    'zh' => '本研究提出了一个基于深度学习的AI模型，用于从眼底图像诊断视网膜疾病，准确率高达96%。',
                    'ru' => 'Данное исследование представляет модель ИИ на основе глубокого обучения для диагностики заболеваний сетчатки.',
                    'ur' => 'یہ تحقیق ریٹینل بیماریوں کی تشخیص کے لیے ڈیپ لرننگ پر مبنی AI ماڈل پیش کرتی ہے جس کی درستگی 96 فیصد تک ہے۔',
                ],
                'authors' => ['د. أحمد مجدي', 'د. رضا علي', 'م. كريم حسام'],
                'journal_name' => ['ar' => 'مجلة الذكاء الاصطناعي في الطب', 'en' => 'Journal of AI in Medicine'],
                'publication_date' => '2026-01-15',
                'doi' => '10.1234/azhar.2026.019',
                'citation_count' => 8,
                'research_area' => 'medicine',
                'publication_type' => 'journal_article',
                'faculty_slug' => 'faculty-of-medicine',
                'is_featured' => true,
            ],
        ];

        foreach ($publications as $data) {
            $facultySlug = $data['faculty_slug'] ?? null;
            unset($data['faculty_slug']);

            $data['faculty_id'] = $facultySlug ? ($faculties[$facultySlug]->id ?? null) : null;

            ResearchPublication::create($data);
        }
    }
}
