// Mock data for development - matches API response structures

export const mockTimelineEras = [
  {
    id: 1,
    slug: 'fatimid',
    name_ar: 'العصر الفاطمي',
    name_en: 'The Fatimid Era',
    year_start: 970,
    year_end: 1171,
    description_ar: 'تأسس الجامع الأزهر عام 970م بأمر من الخليفة المعز لدين الله الفاطمي، وسرعان ما أصبح مركزاً للعلم والمعرفة في العالم الإسلامي.',
    description_en: 'Al-Azhar Mosque was founded in 970 CE by the Fatimid Caliph Al-Mu\'izz li-Din Allah, quickly becoming a center of learning and knowledge in the Islamic world.',
    color: '#c9a84c',
    events: [
      {
        id: 1,
        year: 970,
        title_ar: 'وضع حجر الأساس',
        title_en: 'Foundation Stone Laid',
        description_ar: 'بدأ بناء الجامع الأزهر بأمر من القائد جوهر الصقلي نيابة عن الخليفة المعز لدين الله.',
        description_en: 'Construction of Al-Azhar Mosque began under the command of General Jawhar al-Siqilli on behalf of Caliph Al-Mu\'izz.',
      },
      {
        id: 2,
        year: 972,
        title_ar: 'أول حلقة علم',
        title_en: 'First Circle of Knowledge',
        description_ar: 'انعقدت أول حلقة علمية في الجامع الأزهر، مما جعله أقدم جامعة في العالم تمنح درجات علمية.',
        description_en: 'The first scholarly circle convened at Al-Azhar, making it the oldest degree-granting university in the world.',
      },
      {
        id: 3,
        year: 988,
        title_ar: 'إنشاء المكتبة',
        title_en: 'Library Established',
        description_ar: 'أُنشئت مكتبة الأزهر التي ضمت آلاف المخطوطات في مختلف العلوم.',
        description_en: 'The Al-Azhar Library was established, housing thousands of manuscripts across various sciences.',
      },
      {
        id: 4,
        year: 1009,
        title_ar: 'توسعة الخليفة الحاكم',
        title_en: 'Caliph Al-Hakim\'s Expansion',
        description_ar: 'قام الخليفة الحاكم بأمر الله بتوسعة كبيرة للجامع وزيادة أوقافه.',
        description_en: 'Caliph Al-Hakim bi-Amr Allah carried out a major expansion of the mosque and increased its endowments.',
      },
    ],
  },
  {
    id: 2,
    slug: 'mamluk',
    name_ar: 'عصر المماليك',
    name_en: 'The Mamluk Era',
    year_start: 1250,
    year_end: 1517,
    description_ar: 'في عهد المماليك، شهد الأزهر نهضة علمية كبرى وأصبح المرجع الأول للعلوم الإسلامية في العالم.',
    description_en: 'Under the Mamluks, Al-Azhar witnessed a great scholarly renaissance and became the foremost reference for Islamic sciences worldwide.',
    color: '#1a6b6b',
    events: [
      {
        id: 5,
        year: 1266,
        title_ar: 'تعيين أول شيخ للأزهر',
        title_en: 'First Sheikh of Al-Azhar',
        description_ar: 'تم تعيين أول شيخ رسمي للجامع الأزهر، مما أسس لنظام إداري مستقل.',
        description_en: 'The first official Sheikh of Al-Azhar was appointed, establishing an independent administrative system.',
      },
      {
        id: 6,
        year: 1340,
        title_ar: 'إنشاء المدارس الملحقة',
        title_en: 'Annexed Schools Established',
        description_ar: 'أُنشئت عدة مدارس ملحقة بالأزهر لتدريس مختلف المذاهب الفقهية.',
        description_en: 'Several schools were annexed to Al-Azhar to teach various jurisprudential schools of thought.',
      },
      {
        id: 7,
        year: 1468,
        title_ar: 'توسعة السلطان قايتباي',
        title_en: 'Sultan Qaytbay\'s Expansion',
        description_ar: 'أمر السلطان قايتباي بتوسعة كبيرة شملت بناء المئذنة الشهيرة.',
        description_en: 'Sultan Qaytbay ordered a major expansion including the construction of the famous minaret.',
      },
    ],
  },
  {
    id: 3,
    slug: 'ottoman',
    name_ar: 'العصر العثماني',
    name_en: 'The Ottoman Era',
    year_start: 1517,
    year_end: 1798,
    description_ar: 'حافظ الأزهر على مكانته العلمية والروحية خلال الحكم العثماني، وأصبح صوت الأمة في مواجهة التحديات.',
    description_en: 'Al-Azhar maintained its scholarly and spiritual status during Ottoman rule, becoming the voice of the nation in facing challenges.',
    color: '#c44569',
    events: [
      {
        id: 8,
        year: 1517,
        title_ar: 'الأزهر تحت الحكم العثماني',
        title_en: 'Al-Azhar Under Ottoman Rule',
        description_ar: 'انتقل الحكم إلى العثمانيين لكن الأزهر حافظ على استقلاليته العلمية.',
        description_en: 'Rule transferred to the Ottomans, but Al-Azhar maintained its scholarly independence.',
      },
      {
        id: 9,
        year: 1575,
        title_ar: 'تجديد المنهج التعليمي',
        title_en: 'Curriculum Renewal',
        description_ar: 'تم تجديد المناهج التعليمية لتشمل علوماً جديدة إلى جانب العلوم الشرعية.',
        description_en: 'Educational curricula were renewed to include new sciences alongside religious sciences.',
      },
      {
        id: 10,
        year: 1798,
        title_ar: 'مقاومة الحملة الفرنسية',
        title_en: 'Resistance to French Campaign',
        description_ar: 'لعب الأزهر دوراً محورياً في مقاومة الحملة الفرنسية على مصر.',
        description_en: 'Al-Azhar played a pivotal role in resisting the French campaign in Egypt.',
      },
    ],
  },
  {
    id: 4,
    slug: 'modern',
    name_ar: 'العصر الحديث',
    name_en: 'The Modern Era',
    year_start: 1872,
    year_end: 2025,
    description_ar: 'شهد العصر الحديث تحول الأزهر إلى جامعة عصرية شاملة مع الحفاظ على هويته العلمية والروحية.',
    description_en: 'The modern era saw Al-Azhar transform into a comprehensive modern university while preserving its scholarly and spiritual identity.',
    color: '#0d4f4f',
    events: [
      {
        id: 11,
        year: 1872,
        title_ar: 'أول نظام تعليمي حديث',
        title_en: 'First Modern Educational System',
        description_ar: 'تم إدخال أول نظام تعليمي حديث بإصلاحات الشيخ محمد عبده.',
        description_en: 'The first modern educational system was introduced through Sheikh Muhammad Abduh\'s reforms.',
      },
      {
        id: 12,
        year: 1930,
        title_ar: 'تأسيس كليات جديدة',
        title_en: 'New Faculties Founded',
        description_ar: 'تم تأسيس كليات أصول الدين والشريعة واللغة العربية.',
        description_en: 'Faculties of Theology, Sharia, and Arabic Language were founded.',
      },
      {
        id: 13,
        year: 1961,
        title_ar: 'قانون تطوير الأزهر',
        title_en: 'Al-Azhar Development Law',
        description_ar: 'صدر القانون رقم 103 لسنة 1961 الذي حوّل الأزهر إلى جامعة شاملة تضم كليات علمية وعملية.',
        description_en: 'Law No. 103 of 1961 was issued, transforming Al-Azhar into a comprehensive university with scientific and practical faculties.',
      },
      {
        id: 14,
        year: 2010,
        title_ar: 'التحول الرقمي',
        title_en: 'Digital Transformation',
        description_ar: 'بدأ مشروع التحول الرقمي الشامل للأزهر شاملاً رقمنة المخطوطات وإنشاء منصات تعليمية إلكترونية.',
        description_en: 'A comprehensive digital transformation project began, including digitizing manuscripts and creating e-learning platforms.',
      },
    ],
  },
];

export const mockFaculties = [
  {
    id: 1,
    slug: 'faculty-of-theology',
    name_ar: 'كلية أصول الدين',
    name_en: 'Faculty of Theology',
    type: 'faculty',
    established_year: 1930,
    description_ar: 'واحدة من أقدم كليات الأزهر، تُعنى بدراسة العقيدة والفلسفة الإسلامية والتفسير والحديث.',
    description_en: 'One of the oldest Al-Azhar faculties, focusing on Islamic theology, philosophy, Quran interpretation, and Hadith.',
    departments_count: 5,
    dean_name_ar: 'أ.د. محمد أحمد',
    dean_name_en: 'Prof. Muhammad Ahmad',
  },
  {
    id: 2,
    slug: 'faculty-of-sharia',
    name_ar: 'كلية الشريعة والقانون',
    name_en: 'Faculty of Sharia and Law',
    type: 'faculty',
    established_year: 1930,
    description_ar: 'تُعنى بدراسة الفقه الإسلامي والقانون المقارن والاقتصاد الإسلامي.',
    description_en: 'Focuses on Islamic jurisprudence, comparative law, and Islamic economics.',
    departments_count: 4,
    dean_name_ar: 'أ.د. أحمد علي',
    dean_name_en: 'Prof. Ahmad Ali',
  },
  {
    id: 3,
    slug: 'faculty-of-arabic',
    name_ar: 'كلية اللغة العربية',
    name_en: 'Faculty of Arabic Language',
    type: 'faculty',
    established_year: 1930,
    description_ar: 'تُعنى بدراسة اللغة العربية وآدابها والبلاغة والنقد الأدبي.',
    description_en: 'Focuses on Arabic language and literature, rhetoric, and literary criticism.',
    departments_count: 6,
    dean_name_ar: 'أ.د. عبدالله محمود',
    dean_name_en: 'Prof. Abdullah Mahmoud',
  },
  {
    id: 4,
    slug: 'faculty-of-medicine',
    name_ar: 'كلية الطب',
    name_en: 'Faculty of Medicine',
    type: 'faculty',
    established_year: 1961,
    description_ar: 'كلية طبية متكاملة تجمع بين التعليم الطبي الحديث والقيم الأزهرية.',
    description_en: 'A comprehensive medical faculty combining modern medical education with Azhari values.',
    departments_count: 12,
    dean_name_ar: 'أ.د. حسن إبراهيم',
    dean_name_en: 'Prof. Hassan Ibrahim',
  },
  {
    id: 5,
    slug: 'faculty-of-engineering',
    name_ar: 'كلية الهندسة',
    name_en: 'Faculty of Engineering',
    type: 'faculty',
    established_year: 1961,
    description_ar: 'تقدم برامج هندسية متنوعة مع التركيز على الابتكار والتطبيقات العملية.',
    description_en: 'Offers diverse engineering programs with emphasis on innovation and practical applications.',
    departments_count: 8,
    dean_name_ar: 'أ.د. محمود سعيد',
    dean_name_en: 'Prof. Mahmoud Said',
  },
  {
    id: 6,
    slug: 'faculty-of-science',
    name_ar: 'كلية العلوم',
    name_en: 'Faculty of Science',
    type: 'faculty',
    established_year: 1961,
    description_ar: 'تُعنى بالعلوم الأساسية والتطبيقية مع مراكز بحثية متقدمة.',
    description_en: 'Focuses on basic and applied sciences with advanced research centers.',
    departments_count: 7,
    dean_name_ar: 'أ.د. طارق حسين',
    dean_name_en: 'Prof. Tarek Hussein',
  },
  {
    id: 7,
    slug: 'islamic-research-academy',
    name_ar: 'مجمع البحوث الإسلامية',
    name_en: 'Islamic Research Academy',
    type: 'institute',
    established_year: 1961,
    description_ar: 'يضم نخبة من العلماء المسلمين من مختلف أنحاء العالم لدراسة القضايا الإسلامية المعاصرة.',
    description_en: 'Comprises elite Muslim scholars from around the world to study contemporary Islamic issues.',
    departments_count: 3,
    dean_name_ar: 'أ.د. عمر عبدالرحمن',
    dean_name_en: 'Prof. Omar Abdulrahman',
  },
  {
    id: 8,
    slug: 'azhar-university-hospital',
    name_ar: 'مستشفى الأزهر الجامعي',
    name_en: 'Al-Azhar University Hospital',
    type: 'hospital',
    established_year: 1975,
    description_ar: 'مستشفى تعليمي متكامل يخدم المجتمع ويوفر التدريب العملي لطلاب الطب.',
    description_en: 'A comprehensive teaching hospital serving the community and providing practical training for medical students.',
    departments_count: 15,
    dean_name_ar: 'أ.د. سمير كامل',
    dean_name_en: 'Prof. Samir Kamel',
  },
  {
    id: 9,
    slug: 'center-for-islamic-studies',
    name_ar: 'مركز الدراسات الإسلامية',
    name_en: 'Center for Islamic Studies',
    type: 'center',
    established_year: 1985,
    description_ar: 'مركز بحثي متخصص في الدراسات الإسلامية المعاصرة وحوار الحضارات.',
    description_en: 'A research center specializing in contemporary Islamic studies and interfaith dialogue.',
    departments_count: 2,
    dean_name_ar: 'أ.د. يوسف القرضاوي',
    dean_name_en: 'Prof. Yusuf Al-Qaradawi',
  },
];

export const mockLibraryItems = [
  {
    id: 1,
    slug: 'sahih-al-bukhari-manuscript',
    title_ar: 'صحيح البخاري - نسخة مخطوطة نادرة',
    title_en: 'Sahih Al-Bukhari - Rare Manuscript Copy',
    type: 'manuscript',
    author_ar: 'الإمام محمد بن إسماعيل البخاري',
    author_en: 'Imam Muhammad ibn Ismail al-Bukhari',
    year: 1215,
    language: 'ar',
    description_ar: 'نسخة مخطوطة نادرة من صحيح البخاري تعود للقرن الثالث عشر الميلادي، محفوظة في مكتبة الأزهر.',
    description_en: 'A rare manuscript copy of Sahih Al-Bukhari dating back to the 13th century, preserved in the Al-Azhar Library.',
    pages: 450,
    access_level: 'open',
    views: 12500,
    downloads: 3200,
    cover_color: '#c9a84c',
  },
  {
    id: 2,
    slug: 'al-muwatta-imam-malik',
    title_ar: 'موطأ الإمام مالك',
    title_en: 'Al-Muwatta by Imam Malik',
    type: 'manuscript',
    author_ar: 'الإمام مالك بن أنس',
    author_en: 'Imam Malik ibn Anas',
    year: 1300,
    language: 'ar',
    description_ar: 'مخطوطة قديمة لموطأ الإمام مالك، أحد أقدم كتب الحديث في الإسلام.',
    description_en: 'An ancient manuscript of Al-Muwatta by Imam Malik, one of the oldest books of Hadith in Islam.',
    pages: 320,
    access_level: 'restricted',
    views: 8900,
    downloads: 1500,
    cover_color: '#0d4f4f',
  },
  {
    id: 3,
    slug: 'modern-islamic-thought',
    title_ar: 'الفكر الإسلامي المعاصر: رؤية أزهرية',
    title_en: 'Contemporary Islamic Thought: An Azhari Vision',
    type: 'book',
    author_ar: 'أ.د. أحمد الطيب',
    author_en: 'Prof. Ahmad Al-Tayyeb',
    year: 2018,
    language: 'ar',
    description_ar: 'كتاب يستعرض رؤية الأزهر للفكر الإسلامي المعاصر وقضايا التجديد.',
    description_en: 'A book presenting Al-Azhar\'s vision of contemporary Islamic thought and issues of renewal.',
    pages: 280,
    access_level: 'open',
    views: 5600,
    downloads: 2800,
    cover_color: '#1a6b6b',
  },
  {
    id: 4,
    slug: 'islamic-architecture-cairo',
    title_ar: 'العمارة الإسلامية في القاهرة',
    title_en: 'Islamic Architecture in Cairo',
    type: 'research',
    author_ar: 'د. سارة محمود',
    author_en: 'Dr. Sarah Mahmoud',
    year: 2022,
    language: 'ar',
    description_ar: 'بحث معماري شامل عن تطور العمارة الإسلامية في القاهرة عبر العصور.',
    description_en: 'A comprehensive architectural research on the evolution of Islamic architecture in Cairo through the ages.',
    pages: 95,
    access_level: 'open',
    views: 3400,
    downloads: 1200,
    cover_color: '#c44569',
  },
  {
    id: 5,
    slug: 'quranic-sciences-methodology',
    title_ar: 'مناهج العلوم القرآنية',
    title_en: 'Quranic Sciences Methodology',
    type: 'thesis',
    author_ar: 'محمد عبدالعزيز',
    author_en: 'Muhammad Abdulaziz',
    year: 2021,
    language: 'ar',
    description_ar: 'رسالة دكتوراه في مناهج العلوم القرآنية وتطورها عبر العصور.',
    description_en: 'A doctoral thesis on the methodology of Quranic sciences and their development through the ages.',
    pages: 350,
    access_level: 'open',
    views: 2100,
    downloads: 890,
    cover_color: '#8b6914',
  },
  {
    id: 6,
    slug: 'azhar-journal-vol-42',
    title_ar: 'مجلة الأزهر - المجلد 42',
    title_en: 'Al-Azhar Journal - Volume 42',
    type: 'journal',
    author_ar: 'هيئة التحرير',
    author_en: 'Editorial Board',
    year: 2023,
    language: 'ar',
    description_ar: 'العدد الأخير من مجلة الأزهر العلمية المحكمة.',
    description_en: 'The latest issue of the peer-reviewed Al-Azhar Scientific Journal.',
    pages: 180,
    access_level: 'open',
    views: 4500,
    downloads: 2100,
    cover_color: '#155a5a',
  },
  {
    id: 7,
    slug: 'tafsir-al-azhar',
    title_ar: 'تفسير الأزهر',
    title_en: 'Tafsir Al-Azhar',
    type: 'manuscript',
    author_ar: 'متعدد',
    author_en: 'Multiple Authors',
    year: 1150,
    language: 'ar',
    description_ar: 'مجموعة من التفاسير القرآنية المجمّعة من علماء الأزهر عبر القرون.',
    description_en: 'A collection of Quranic interpretations compiled from Al-Azhar scholars across centuries.',
    pages: 600,
    access_level: 'restricted',
    views: 7800,
    downloads: 900,
    cover_color: '#c9a84c',
  },
  {
    id: 8,
    slug: 'arabic-grammar-comprehensive',
    title_ar: 'النحو العربي الشامل',
    title_en: 'Comprehensive Arabic Grammar',
    type: 'book',
    author_ar: 'أ.د. عبدالله محمود',
    author_en: 'Prof. Abdullah Mahmoud',
    year: 2020,
    language: 'ar',
    description_ar: 'مرجع شامل في النحو العربي لطلاب الجامعات والباحثين.',
    description_en: 'A comprehensive reference in Arabic grammar for university students and researchers.',
    pages: 420,
    access_level: 'open',
    views: 6700,
    downloads: 3400,
    cover_color: '#0d4f4f',
  },
];

export const mockNews = [
  {
    id: 1,
    slug: 'grand-imam-interfaith-conference',
    title_ar: 'فضيلة الإمام الأكبر يفتتح مؤتمر الحوار بين الأديان',
    title_en: 'Grand Imam Opens Interfaith Dialogue Conference',
    category_ar: 'مؤتمرات',
    category_en: 'Conferences',
    excerpt_ar: 'افتتح فضيلة الإمام الأكبر شيخ الأزهر المؤتمر الدولي للحوار بين الأديان بمشاركة ممثلين من أكثر من 50 دولة.',
    excerpt_en: 'The Grand Imam of Al-Azhar opened the International Interfaith Dialogue Conference with representatives from over 50 countries.',
    date: '2026-03-15',
    image: null,
    featured: true,
  },
  {
    id: 2,
    slug: 'digital-library-launch',
    title_ar: 'إطلاق المكتبة الرقمية الجديدة',
    title_en: 'Launch of the New Digital Library',
    category_ar: 'تكنولوجيا',
    category_en: 'Technology',
    excerpt_ar: 'أعلنت جامعة الأزهر عن إطلاق منصة المكتبة الرقمية الجديدة التي تتيح الوصول لأكثر من 100,000 مخطوطة وكتاب.',
    excerpt_en: 'Al-Azhar University announced the launch of the new digital library platform providing access to over 100,000 manuscripts and books.',
    date: '2026-03-10',
    image: null,
    featured: false,
  },
  {
    id: 3,
    slug: 'international-students-graduation',
    title_ar: 'تخريج 5000 طالب دولي من 80 دولة',
    title_en: 'Graduation of 5,000 International Students from 80 Countries',
    category_ar: 'أكاديمي',
    category_en: 'Academic',
    excerpt_ar: 'احتفلت جامعة الأزهر بتخريج دفعة جديدة من الطلاب الدوليين القادمين من 80 دولة حول العالم.',
    excerpt_en: 'Al-Azhar University celebrated the graduation of a new cohort of international students from 80 countries worldwide.',
    date: '2026-03-05',
    image: null,
    featured: false,
  },
  {
    id: 4,
    slug: 'research-collaboration-agreement',
    title_ar: 'اتفاقية تعاون بحثي مع جامعة أكسفورد',
    title_en: 'Research Collaboration Agreement with Oxford University',
    category_ar: 'تعاون دولي',
    category_en: 'International Cooperation',
    excerpt_ar: 'وقّعت جامعة الأزهر اتفاقية تعاون بحثي مشترك مع جامعة أكسفورد في مجال دراسات المخطوطات.',
    excerpt_en: 'Al-Azhar University signed a joint research collaboration agreement with Oxford University in the field of manuscript studies.',
    date: '2026-02-28',
    image: null,
    featured: false,
  },
  {
    id: 5,
    slug: 'new-medical-complex',
    title_ar: 'افتتاح المجمع الطبي الجديد',
    title_en: 'Opening of New Medical Complex',
    category_ar: 'مرافق',
    category_en: 'Facilities',
    excerpt_ar: 'افتتح رئيس الجامعة المجمع الطبي الجديد المجهز بأحدث التقنيات الطبية.',
    excerpt_en: 'The University President opened the new medical complex equipped with the latest medical technologies.',
    date: '2026-02-20',
    image: null,
    featured: false,
  },
  {
    id: 6,
    slug: 'manuscript-digitization-milestone',
    title_ar: 'رقمنة 50,000 مخطوطة تاريخية',
    title_en: 'Digitization of 50,000 Historical Manuscripts',
    category_ar: 'تراث',
    category_en: 'Heritage',
    excerpt_ar: 'أعلن مركز التراث عن إتمام رقمنة 50,000 مخطوطة تاريخية نادرة من مكتبة الأزهر.',
    excerpt_en: 'The Heritage Center announced the completion of digitizing 50,000 rare historical manuscripts from the Al-Azhar Library.',
    date: '2026-02-15',
    image: null,
    featured: false,
  },
];

export const mockPeople = [
  {
    id: 1,
    slug: 'grand-imam',
    name_ar: 'أ.د. أحمد الطيب',
    name_en: 'Prof. Ahmad Al-Tayyeb',
    title_ar: 'شيخ الأزهر الشريف',
    title_en: 'Grand Imam of Al-Azhar',
    role: 'president',
    bio_ar: 'شيخ الأزهر الشريف ورئيس مجلس حكماء المسلمين، يقود مسيرة التجديد والتحديث في أعرق مؤسسة إسلامية.',
    bio_en: 'Grand Imam of Al-Azhar and Chairman of the Muslim Council of Elders, leading the march of renewal and modernization in the oldest Islamic institution.',
    initials: 'أط',
  },
  {
    id: 2,
    slug: 'university-president',
    name_ar: 'أ.د. سلامة داود',
    name_en: 'Prof. Salama Dawood',
    title_ar: 'رئيس جامعة الأزهر',
    title_en: 'President of Al-Azhar University',
    role: 'president',
    bio_ar: 'يشرف على إدارة الجامعة وتطوير برامجها الأكاديمية والبحثية.',
    bio_en: 'Oversees university administration and development of academic and research programs.',
    initials: 'سد',
  },
  {
    id: 3,
    slug: 'vp-academic',
    name_ar: 'أ.د. عبدالحليم منصور',
    name_en: 'Prof. Abdel Halim Mansour',
    title_ar: 'نائب رئيس الجامعة للشؤون الأكاديمية',
    title_en: 'Vice President for Academic Affairs',
    role: 'vice_president',
    bio_ar: 'مسؤول عن تطوير العملية التعليمية والمناهج الدراسية.',
    bio_en: 'Responsible for developing the educational process and curricula.',
    initials: 'عم',
  },
  {
    id: 4,
    slug: 'vp-research',
    name_ar: 'أ.د. أحمد حسني',
    name_en: 'Prof. Ahmad Hosny',
    title_ar: 'نائب رئيس الجامعة للدراسات العليا والبحوث',
    title_en: 'Vice President for Graduate Studies and Research',
    role: 'vice_president',
    bio_ar: 'يشرف على برامج الدراسات العليا ومراكز البحث العلمي.',
    bio_en: 'Oversees graduate programs and scientific research centers.',
    initials: 'أح',
  },
  {
    id: 5,
    slug: 'vp-community',
    name_ar: 'أ.د. يوسف عامر',
    name_en: 'Prof. Youssef Amer',
    title_ar: 'نائب رئيس الجامعة لخدمة المجتمع',
    title_en: 'Vice President for Community Service',
    role: 'vice_president',
    bio_ar: 'مسؤول عن برامج خدمة المجتمع والتواصل الخارجي.',
    bio_en: 'Responsible for community service programs and external outreach.',
    initials: 'يع',
  },
];

export const mockEvents = [
  {
    id: 1,
    slug: 'annual-quran-competition',
    title_ar: 'المسابقة السنوية لحفظ القرآن الكريم',
    title_en: 'Annual Quran Memorization Competition',
    description_ar: 'المسابقة السنوية الدولية لحفظ القرآن الكريم بمشاركة طلاب من أكثر من 50 دولة.',
    description_en: 'The annual international Quran memorization competition with students from over 50 countries.',
    date: '2026-04-15',
    end_date: '2026-04-20',
    location_ar: 'قاعة المؤتمرات الكبرى',
    location_en: 'Grand Conference Hall',
    category: 'academic',
    status: 'upcoming',
  },
  {
    id: 2,
    slug: 'islamic-art-exhibition',
    title_ar: 'معرض الفن الإسلامي المعاصر',
    title_en: 'Contemporary Islamic Art Exhibition',
    description_ar: 'معرض يستعرض أعمال فنية إسلامية معاصرة من فنانين من مختلف أنحاء العالم.',
    description_en: 'An exhibition showcasing contemporary Islamic artworks from artists around the world.',
    date: '2026-05-01',
    end_date: '2026-05-10',
    location_ar: 'متحف الأزهر',
    location_en: 'Al-Azhar Museum',
    category: 'cultural',
    status: 'upcoming',
  },
  {
    id: 3,
    slug: 'research-symposium-2026',
    title_ar: 'ملتقى البحث العلمي 2026',
    title_en: 'Research Symposium 2026',
    description_ar: 'ملتقى سنوي يجمع الباحثين من مختلف كليات الجامعة لعرض أحدث الأبحاث.',
    description_en: 'An annual symposium bringing together researchers from various university faculties to present the latest research.',
    date: '2026-06-10',
    end_date: '2026-06-12',
    location_ar: 'مركز المؤتمرات',
    location_en: 'Conference Center',
    category: 'academic',
    status: 'upcoming',
  },
  {
    id: 4,
    slug: 'interfaith-dialogue-week',
    title_ar: 'أسبوع الحوار بين الأديان',
    title_en: 'Interfaith Dialogue Week',
    description_ar: 'فعاليات متنوعة تهدف لتعزيز الحوار والتفاهم بين أتباع الأديان المختلفة.',
    description_en: 'Various events aimed at promoting dialogue and understanding between followers of different religions.',
    date: '2026-03-01',
    end_date: '2026-03-07',
    location_ar: 'مقر الأزهر',
    location_en: 'Al-Azhar Headquarters',
    category: 'cultural',
    status: 'past',
  },
  {
    id: 5,
    slug: 'manuscript-preservation-workshop',
    title_ar: 'ورشة عمل حفظ المخطوطات',
    title_en: 'Manuscript Preservation Workshop',
    description_ar: 'ورشة عمل تدريبية حول أحدث تقنيات حفظ وترميم المخطوطات التاريخية.',
    description_en: 'A training workshop on the latest techniques for preserving and restoring historical manuscripts.',
    date: '2026-02-15',
    end_date: '2026-02-17',
    location_ar: 'مكتبة الأزهر',
    location_en: 'Al-Azhar Library',
    category: 'academic',
    status: 'past',
  },
];

export const mockRecords = [
  {
    id: 1,
    title_ar: 'أكثر جسم طلابي تنوعاً',
    title_en: 'Most Diverse Student Body',
    description_ar: 'يدرس في جامعة الأزهر طلاب من أكثر من 100 دولة، مما يجعلها من أكثر الجامعات تنوعاً في العالم.',
    description_en: 'Al-Azhar University hosts students from over 100 countries, making it one of the most diverse universities in the world.',
    stat: '100+',
    stat_label_ar: 'دولة',
    stat_label_en: 'Countries',
    icon: 'globe',
  },
  {
    id: 2,
    title_ar: 'أقدم جامعة تمنح درجات علمية',
    title_en: 'Oldest Degree-Granting University',
    description_ar: 'منذ عام 972م، يمنح الأزهر درجات علمية بشكل متواصل لأكثر من ألف عام.',
    description_en: 'Since 972 CE, Al-Azhar has been continuously granting degrees for over a thousand years.',
    stat: '1054',
    stat_label_ar: 'عام',
    stat_label_en: 'Years',
    icon: 'award',
  },
  {
    id: 3,
    title_ar: 'أكبر أرشيف مخطوطات',
    title_en: 'Largest Manuscript Archive',
    description_ar: 'تضم مكتبة الأزهر أكثر من 100,000 مخطوطة نادرة تعود لقرون متعددة.',
    description_en: 'The Al-Azhar Library houses over 100,000 rare manuscripts dating back several centuries.',
    stat: '100K+',
    stat_label_ar: 'مخطوطة',
    stat_label_en: 'Manuscripts',
    icon: 'scroll',
  },
  {
    id: 4,
    title_ar: 'أول متحف جامعي رقمي',
    title_en: 'First Digital University Museum',
    description_ar: 'أطلقت جامعة الأزهر أول متحف رقمي جامعي في المنطقة يعرض تاريخ ألف عام.',
    description_en: 'Al-Azhar University launched the first digital university museum in the region showcasing a thousand years of history.',
    stat: '#1',
    stat_label_ar: 'رقمي',
    stat_label_en: 'Digital',
    icon: 'monitor',
  },
  {
    id: 5,
    title_ar: 'أكبر شبكة خريجين إسلامية',
    title_en: 'Largest Islamic Alumni Network',
    description_ar: 'يفخر الأزهر بشبكة خريجين تضم أكثر من مليون خريج في مختلف أنحاء العالم.',
    description_en: 'Al-Azhar boasts an alumni network of over one million graduates across the globe.',
    stat: '1M+',
    stat_label_ar: 'خريج',
    stat_label_en: 'Alumni',
    icon: 'users',
  },
];
